balena-os/meta-balena

- CHANGELOG.md
- meta-resin-common/recipes-support/resin-supervisor/resin-supervisor-disk.bb
Instead of doing "docker images [repository_name]" and then grep for what we are
interested in, we should just do a "docker images" and search through that output.
The issue we are trying to fix is that on different build Operating Systems, "docker images"
will prepend the string "docker.io" to this command's output so our current way we grep will
just return nothing.
fixes #14 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/15)
> resin-supervisor-disk: Fix repository grep

- meta-resin-common/classes/image_types_resin.bbclass
@floion @telphan
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/32)
> image_types_resin: mkfs.vfat expects -C file not to exist

- CHANGELOG.md
- meta-resin-common/recipes-core/images/resin-image-flasher.bb
- meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
> resin flasher - Move sdcard image to the flasher rootfs instead of the boot partition

- meta-resin-common/recipes-go/resin-provisioner/resin-provisioner_1.0.1.bb
Binary to use is now called `resin-provision`. Dependencies are vendored, so no need to make this package depend on them.
Connects to #123
> Update resin-provisioner to 1.0.1

- meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
as not fatal.
Now that we use "set -e" in this script, we have to ignore resin-device-progress
failures as non-fatal which can happen if at first try of progress reporting the
device has not yet been registered.
> resin-init-flasher: Treat resin-device-progress failures

- meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
We need to allow do_patch to be able to take place as we patch the sources
from another location and this setting from here will prevent any patching
to take place.
> kernel-modules-headers.bb: Allow do_patch

- meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
We use let to calculate the ratio of the provisioning progress. This will
error expectedly on first calculation(s) because "let" exits with an error if
arithmetic expression used is evaluated to 0. This happens when provisioning
progress is less than 1%.
> resin-init-flasher: Don't error on "let" errors

- meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
We need to make sure we unmount only when we have the directory mounted
> resin-init-flasher: Ensure correct umount

- meta-resin-common/recipes-containers/docker/docker/docker.service
We need to forcefully remove the file as at first boot this file will not
be available and the docker.service will fail to start because this ExecStartPre
will fail to non-forcefully remove a non-existent file.
> docker.service: Fix key.json check

- meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
TRANSLATED_TARGET_ARCH now uses a regex to match all x86 types.
Connects to #152
> kernel-modules-headers.bb: Change the TRANSLATED_TARGET_ARCH to match all x86 machine types

- meta-resin-common/recipes-core/images/resin-image.bb
If we generate the fingerprints as a post rootfs, other functions might
change the rootfs in different ways (for example zap passwd). In this
case the fingerprints will depend on the order of this function and if
it is not the last one might include bad hashes. Moving this generation
before image create we ensure that all the other postrootfs functions
were finalized.
@floion @telphan
> resin-image: Generate fingerprints just before image creation

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
connects to #192
[Changelog](https://github.com/resin-io/resin-supervisor/blob/master/CHANGELOG.md):
* Add endpoints for docker-compose up and down [Pablo]
> Bump resin-supervisor to v1.12.0

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
connects  to #195 
[Changelog](https://github.com/resin-io/resin-supervisor/blob/master/CHANGELOG.md):
* Fix preloaded apps by passing appId to extendEnvVars
> Bump resin-supervisor to v1.12.1

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker/docker/0001-bucket-correct-broken-unaligned-load-store-in-armv5.patch
- meta-resin-common/recipes-containers/docker/docker_git.bb
Applies fix to boltdb to resolve issue with unaligned 64-bit access on armv5 platforms.
Idempotent for non-armv5 devices.
Fixes issue #227. See that issue (+ its links) for more details.
> docker: boltdb: correct broken unaligned load/store in armv5

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker/docker/0002-Inherit-StopSignal-from-Dockerfile.patch
- meta-resin-common/recipes-containers/docker/docker_git.bb
fixes #270 
connects to resin-io-library/base-images#77
> docker: fix STOPSIGNAL handling when set in a Dockerfile

- meta-resin-common/recipes-support/resin-btrfs/resin-btrfs-balance/resin-btrfs-balance
We now use btrfs in mixed mode. In this mode, data and metadata are combined into
the same blocks and btrfs balance needs also the -musage filter to function correctly.
> resin-btrfs-balance: Fix btrfs balance options for mixed mode

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
connects to #278 
Depends on resin-io/resin-ui#23 (which has yet to be deployed to production)
> Update supervisor to v2.1.0

- meta-resin-common/recipes-containers/docker/docker/0003-Safer-file-io-for-configuration-files.patch
- meta-resin-common/recipes-containers/docker/docker/0004-Set-permission-on-atomic-file-write.patch
- meta-resin-common/recipes-containers/docker/docker/0005-Update-layer-store-to-sync-transaction-files-before-.patch
- meta-resin-common/recipes-containers/docker/docker_git.bb
This set of patches make sure that changes in the layer store are synced
to disk before updating the metadata of docker.
connects to docker/docker#25523
fixes resin-io/hq#274
> docker: backport transactional layer store fixes

- CHANGELOG.md
- meta-resin-common/recipes-connectivity/openvpn/openvpn/resin.conf
This prevents conflict with user applications using tun0
Connects to #282 
This requires https://github.com/resin-io/resin-supervisor/issues/247 to be deployed before being deployed to HOSTOS
> resin.conf: Change the TUN device used by OpenVPN to resin-vpn 

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/update-resin-supervisor
If the supervisor version requested is already downloaded then there is no need
to stop the supervisor that may be already running, docker pull the already existing
supervisor version and then restart supervisor.
Fixes #286
> update-resin-supervisor: Don't download already downloaded supervisor

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
> docker-resin-supervisor-disk: Update supervisor to v2.2.0

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
> docker-resin-supervisor-disk: Update supervisor to v2.3.0

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
connects to #344 
Depends on resin-io/resin-api#50
> docker-resin-supervisor-disk: Update supervisor to v2.5.0

- CHANGELOG.md
- meta-resin-common/recipes-connectivity/avahi/avahi_%.bbappend
- meta-resin-common/recipes-core/dropbear/dropbear_%.bbappend
- meta-resin-common/recipes-core/dropbear/files/ssh.service
- meta-resin-common/recipes-core/packagegroups/packagegroup-resin-connectivity.bb
Connects to #317 
Avahi daemon on the device advertise the following services:
```
+ wlp4s0 IPv4 raspberrypi3 [b8:27:eb:a5:7d:b0]              Workstation          local
+ wlp4s0 IPv4 raspberrypi3                                  SSH Remote Terminal  local
= wlp4s0 IPv4 raspberrypi3 [b8:27:eb:a5:7d:b0]              Workstation          local
hostname = [raspberrypi3.local]
address = [192.168.1.167]
port = [9]
txt = []
= wlp4s0 IPv4 raspberrypi3                                  SSH Remote Terminal  local
hostname = [raspberrypi3.local]
address = [192.168.1.167]
port = [22222]
txt = []
```
Example of ssh-ing on a device:
```
andrei@resin ~ $ ssh -p 22222 root@raspberrypi3.local
The authenticity of host '[raspberrypi3.local]:22222 ([192.168.1.167]:22222)' can't be established.
RSA key …
```
> Install and configure avahi

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
Use of grep and tr is error prone when parsing a .json file. Instead we use
the command line json processor to get the required info.
> docker-resin-supervisor-disk.bb: Use jq to parse supervisor version

- meta-resin-common/recipes-connectivity/networkmanager/networkmanager_%.bbappend
It looks like "PACKAGECONFIG +=" does not actually append but rather just
sets the PACKAGECONFIG variable to these values.
> networkmanager_%.bbappend: Fix appending to PACKAGECONFIG

- CHANGELOG.md
- meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
The latest update of the script fixes the isue with binaries in `scripts/` being built for the host arch rather than the target arch which makes the headers useless for building on target arch or emulated target arch.
> Update module headers

- meta-resin-common/recipes-connectivity/avahi/avahi_%.bbappend
- meta-resin-common/recipes-connectivity/avahi/files/avahi-daemon.conf
We need to make sure the hostname is set before having avahi
start advertising.
> avahi_%.bbappend: Add dependency on resin-hostname.service

- meta-resin-common/recipes-core/dropbear/dropbear_%.bbappend
- meta-resin-common/recipes-core/dropbear/files/dropbearkey.conf
We need /etc/dropbear/ bind mounted to our read-write location when
dropbear will attempt to write the host key there.
Fixes #387
> dropbear_%.bbappend: Add Require and After on etc-dropbear.mount

- meta-resin-common/recipes-connectivity/networkmanager/files/resin-sample
Adding "hidden=true" for being able to connect to hidden SSIDs too.
> networkmanager: Add hidden setting to sample config file

- meta-resin-common/recipes-connectivity/modemmanager/files/0001-Revert-iface-modem-the-Command-method-is-only-allowe.patch
- meta-resin-common/recipes-connectivity/modemmanager/files/ModemManager.conf.systemd
- meta-resin-common/recipes-connectivity/modemmanager/modemmanager_%.bbappend
Patch ModemManager to support the Modem.Command() dbus function without
needing to run the daemon in debug mode.
fixes #391
> modemmanager: enable Modem.Command() dbus call

- meta-resin-common/recipes-connectivity/networkmanager/files/NetworkManager.conf
NetworkManager tries to configure the virtual ethernet devices created
by docker otherwise.
> nm: ignore bridge, tun, and veth type devices

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
> docker-resin-supervisor-disk: Update supervisor to 2.6.2

- meta-resin-common/recipes-core/ucl/ucl_1.03.bb
configure error on gcc6
This commit fixes(by using the ISO C90 standard) the following ucl configure error on gcc6:
| checking for vsnprintf... yes
| checking whether your compiler passes the ACC conformance test... FAILED
| configure:
| configure: Your compiler failed the ACC conformance test - for details see
| configure: `config.log'. Please check that log file and consider sending
| configure: a patch or bug-report to <markus@oberhumer.com>.
| configure: Thanks for your support.
| configure:
| configure: error: ACC conformance test failed. Stop.
| NOTE: The following config.log files may provide further information.
> ucl_1.03.bb: Fix ACC conformance test

- meta-resin-common/classes/kernel-resin.bbclass
This commit fixes the following error:
Exception: TypeError: getVar() takes at least 3 arguments (2 given)
> kernel-resin.bbclass: Fix getVar() invocation

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
connect https://github.com/resin-os/meta-resin/pull/426
> docker-resin-supervisor-disk: Update supervisor to 2.6.3

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
Also PRd to master, but this version also has fixes that are relevant to 1.X.
> docker-resin-supervisor-disk: Update supervisor to v2.7.0

- meta-resin-common/recipes-core/dropbear/dropbear_%.bbappend
This includes a bashism fix too.
> dropbear: Only disabled builds should not include authorized_keys

- meta-resin-common/recipes-core/upx/files/fix_indentation_for_gcc6.patch
- meta-resin-common/recipes-core/upx/upx_3.91.bb
This fixes the following compile crash on gcc6:
| p_vmlinx.cpp: In static member function 'static int PackVmlinuxBase<TElfClass>::compare_Phdr(const void*, const void*)':
| p_vmlinx.cpp:100:5: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
|      if (a->p_paddr > b->p_paddr) return  1;
|      ^~
| p_vmlinx.cpp:101:34: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
|                                   return  0;
|                                   ^~~~~~
> upx_3.91.bb: Fix indentation error on gcc6

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
> docker-resin-supervisor-disk: Update supervisor to v2.7.1

- CHANGELOG.md
- meta-resin-common/recipes-support/resin-hostname/resin-hostname/resin-hostname
If the string is shorter than 7 characters, use what's provided.
connect https://github.com/resin-os/resinos/issues/101
> resin-hostname: use just the first 7 characters of the uuid for the hostname

- meta-resin-common/classes/host-update-resin.bbclass
Point to deploy directory when referring to the rootfs tar archive. Newer poky
versions (>= krogoth) error out complaining the archive is not found. Specifying
here the full path fixes this problem.
> host-update-resin.bbclass: Explicitly reference rootfs tar archive

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker/docker/0009-graph-aufs-durably-write-layer-on-disk-before-return.patch
- meta-resin-common/recipes-containers/docker/docker/0010-pkg-ioutils-sync-parent-directory-too.patch
- meta-resin-common/recipes-containers/docker/docker_git.bb
Before this patch a power failure or system crash right after a
`docker pull` would result in a corrupted /var/lib/docker
> docker: fix durable writing of image layers to disk

- CHANGELOG.md
- meta-resin-common/recipes-connectivity/connman/resin-connman-conf/main.conf
Connects to https://github.com/resin-os/resinos/issues/123
This PR is 1.X specific as 2.X doesn't use connman anymore. NM masks devices by type.
> Fix tun rename

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
> [1.X] docker-resin-supervisor-disk: Update supervisor to v2.8.3

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
> docker-resin-supervisor-disk: Update supervisor to v2.8.3

- meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
Revert a previous commit, support only 1.x releases.
> Revert "resinhup/run-resinhup.sh: Switch to aufs instead of btrfs"

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
> [1.X] docker-resin-supervisor-disk: Update supervisor to v2.9.0

- meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
- scripts/resinhup/run-resinhup-ssh.sh
…holding message
When migrating to docker, calculating the hash of all the images can take a
while (minutes) while user waits for the device to reboot. Let's have a holding
message in the meanwhile.
> Tweaks for resinhup

- meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher/temp-conf.service
All .services by default depend on basic.target. This is unneeded for
this simple service, and created a dependency cycle.
> resin-mounts-flasher: don't make temp-conf.service depend on defaults

- meta-resin-common/classes/kernel-resin.bbclass
dictionary view object to a list
This fixes the following error:
*** 0417:    for key, value in reversed(aufsdict.items()) :
0418:        if key.split('+')[0] is kernelversion:
0419:            aufsbranch = key
0420:            break
0421:
Exception: TypeError: argument to reversed() must be a sequence
> kernel-resin.bbclass: Convert iterable

- meta-resin-common/recipes-containers/docker-disk/docker-utils.inc
Python 3 reveals these warnings:
WARNING: docker-custom-disk.bb: <string>:12: ResourceWarning: unclosed
<socket.socket fd=28, family=AddressFamily.AF_INET, type=2049, proto=6,
laddr=('138.201.202.11', 55360), raddr=('52.207.178.113', 80)>
WARNING: docker-resin-supervisor-disk.bb: <string>:12: ResourceWarning:
unclosed <socket.socket fd=32, family=AddressFamily.AF_INET, type=2049,
proto=6, laddr=('138.201.202.11', 43862), raddr=('52.73.159.23', 80)>
> docker-utils.inc: Fix unclosed socket warnings for the 1.X branch

- meta-resin-common/recipes-containers/docker-disk/docker-utils.inc
Python 3 reveals these warnings:
WARNING: docker-custom-disk.bb: <string>:12: ResourceWarning: unclosed
<socket.socket fd=28, family=AddressFamily.AF_INET, type=2049, proto=6,
laddr=('138.201.202.11', 55360), raddr=('52.207.178.113', 80)>
WARNING: docker-resin-supervisor-disk.bb: <string>:12: ResourceWarning:
unclosed <socket.socket fd=32, family=AddressFamily.AF_INET, type=2049,
proto=6, laddr=('138.201.202.11', 43862), raddr=('52.73.159.23', 80)>
> docker-utils.inc: Fix unclosed socket warnings for the master branch

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/resin-supervisor.service
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/start-resin-supervisor
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/update-resin-supervisor
Instead, we add a start-resin-supervisor script that checks
whether the existing container's image matches the one specified
in supervisor.conf, and just starts that container in that case.
It falls back to the docker run command that creates and starts
the supervisor container.
We also add the container removal in the update-resin-supervisor script,
after stopping the resin-supervisor service.
Connects to #184
Also connects to #280 as it should make the issue appear way less often.
> [1.X] Do not remove the supervisor container before every start

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/resin-supervisor.service
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/start-resin-supervisor
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/update-resin-supervisor
[Untested, this is my first attempt]
Instead, we add a start-resin-supervisor script that checks
whether the existing container's image matches the one specified
in supervisor.conf, and just starts that container in that case.
It falls back to the docker run command that creates and starts
the supervisor container.
We also add the container removal in the update-resin-supervisor script,
after stopping the resin-supervisor service.
Closes #184 
Also connects to #280 as it should make the issue appear way less often.
> [master] Do not remove the supervisor container before every start

- CHANGELOG.md
- meta-resin-common/classes/image_types_resin.bbclass
- meta-resin-common/recipes-connectivity/dnsmasq/dnsmasq_%.bbappend
- meta-resin-common/recipes-connectivity/dnsmasq/files/systemd-dnsmasq.conf
- meta-resin-common/recipes-core/systemd/systemd_%.bbappend
Fixes https://github.com/resin-os/resinos/issues/196
Connected to https://github.com/resin-os/resinos/issues/113 because now the yocto depends on ext4 for live images.
> Switch to ext4 for rootfs

- CHANGELOG.md
- meta-resin-common/classes/host-update-resin.bbclass
and undeclared variable
If entering the if branch where IMGDEPLOYDIR is not declared
then expect IMAGE_NAME_SUFFIX is not declared either.
> host-update-resin.bbclass: Fix missing quoting

- CHANGELOG.md
- meta-resin-common/recipes-core/images/resin-image.bb
- meta-resin-common/recipes-core/packagegroups/packagegroup-resin-debugtools.bb
Connects to https://github.com/resin-os/resinos/issues/174
> Add mkfs.ext4 to resin-image

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
When switching from jethro to morty, the architecture for the rpi3
changes from "armv7a" to "armv7ve", which is armv7a + virtualization.
> docker-resin-supervisor-disk: add armv7ve support

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
Closes #589 
(Jenkins build will fail until the supervisor is built)
> docker-resin-supervisor-disk: Update supervisor to v4.0.0

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
Connects to #589 
(Jenkins build will fail until the supervisor is built)
> [1.X] docker-resin-supervisor-disk: Update supervisor to v4.0.0

- CHANGELOG.md
- meta-resin-common/recipes-support/resinhup/resinhup.bb
resinhup: install e2label
The e2label utility is provided by the e2fsprogs-tune2fs package.
This utility is a prerequisite to switching the root partition for Intel
based boards (grub.cfg).
Also sort list.
> Ship with e2fsprogs-tune2fs

- CHANGELOG.md
- meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
This PR cherry picks the changes from:
https://github.com/resin-os/meta-resin/pull/614
This allows us to build with Jenkins and adds a changelog.
> Avoid writing to /root when running nohup

- CHANGELOG.md
- meta-resin-common/recipes-core/systemd/systemd/coredump.conf
- meta-resin-common/recipes-core/systemd/systemd_%.bbappend
- meta-resin-common/recipes-support/resin-mounts/resin-mounts.bb
- meta-resin-common/recipes-support/resin-mounts/resin-mounts/var-lib-systemd.mount
This is the PR from Jon, but with a comment fixed, coredumps disabled altogether and changelog entries.
connect https://github.com/resin-os/meta-resin/pull/650
> Systemd persistence

- CHANGELOG.md
- meta-resin-common/recipes-support/resinhup/resinhup.bb
In order to update to resinOS 2.x we need to be able to manipulate ext2/3/4 filesystems.
> Include e2fsprogs utilities for resinhup

- CHANGELOG.md
- meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
Update to the most recent resinhup tag which allows running on staging devices.
> Update resinhup to v1.1.2

- CHANGELOG.md
- meta-resin-common/classes/kernel-resin.bbclass
- meta-resin-morty/recipes-connectivity/libmbim/files/0001-avoid-iconv.patch
- meta-resin-morty/recipes-connectivity/libmbim/libmbim_%.bbappend
Because iconv is not being used conversion from utf-8 to utf-16le had issues
Signed-off-by: Joshua Benjamin <joshuabnjmn@gmail.com>
> libmbim: fix conversion issue in libmbim

- README.md
Our current release versioning scheme needs the revision to be added
to a meta-resin version using the plus character (+) instead of the
dot character (.)
> README.md: Adapt to the correct release versioning scheme

- CHANGELOG.md
- meta-resin-common/recipes-connectivity/networkmanager/files/NetworkManager.conf
NetworkManager will attempt to connect to a network 4 times by default before bailing out. This is unsuitable for resin device that can be deployed in flaky networks.
Setting `autoconnect-retries-default` to 0 will cause NM to never stop trying to connect.
https://developer.gnome.org/NetworkManager/unstable/nm-settings.html#nm-settings.property.connection.autoconnect-retries
> networkmanager: set reconnection attempts to infinity

- CHANGELOG.md
- meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
Basically automatic application of https://github.com/resin-os/resin-beaglebone/blob/1.X/layers/meta-resin-beaglebone/recipes-core/fix-mmc-bbb/files/fix-mmc-bbb.conf
> resinhup: apply BeagleBone memory fixes for affected resinOS releases before update

- CHANGELOG.md
- meta-resin-common/classes/image-resin.bbclass
By default docker creates a symlink for /etc/mtab that is slightly different to what systemd is expecting, causing systemd to try and rewrite the symlink on boot. This causes resinhup-ed 2.x images to error on boot due to a read-only root filesystem.
> Add a quirk for mtab

- CHANGELOG.md
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/start-resin-supervisor
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/update-resin-supervisor
This change is an attempt to implement Andrei's suggestion for simplifying 1.x to 2.x upgrades. When we upgrade to 2.x the docker containers are wiped out (we switched from btrfs to aufs) so there is no supervisor available to run. Using the tag specified in the supervisor.conf directly allows us to fall back to downloading the container.
> Use specified version of supervisor when starting

- CHANGELOG.md
- meta-resin-common/recipes-core/packagegroups/packagegroup-resin.bb
Add dosfstools for fsck.vfat which allows repairing some corrupt FAT filesystems. This is a backport of the change already on master to 1.X.
> Add dosfstools for FAT fsck

- CHANGELOG.md
Last PR was including a wrong change entry (ipk).
The second last PR included an entry without name (supervisor update).
> CHANGELOG.md: fixes

- CHANGELOG.md
- meta-resin-common/classes/kernel-resin.bbclass
- meta-resin-common/recipes-connectivity/redsocks/redsocks_0.5.bb
- meta-resin-common/recipes-connectivity/resin-proxy-config/resin-proxy-config.bb
- meta-resin-common/recipes-connectivity/resin-proxy-config/resin-proxy-config/redsocks.service
- meta-resin-common/recipes-connectivity/resin-proxy-config/resin-proxy-config/resin-proxy-config
- meta-resin-common/recipes-connectivity/resin-proxy-config/resin-proxy-config/resin-proxy-config.service
- meta-resin-common/recipes-core/packagegroups/packagegroup-resin-connectivity.bb
- meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
This PR adds a recipe for [redsocks](http://darkk.net.ru/redsocks/), which allows transparent redirection to SOCKS and HTTP proxies.
It introduces a `resin-proxy-config` service, which looks for redsocks.conf inside a system-proxy folder in the boot partition. The service creates the corresponding iptables rules and starts redsocks, only if the configuration file is found (otherwise it just exists).
Users wanting a device to connect behind a proxy would have to add a `redsocks.conf` file at the `/mnt/boot/system-proxy/`, specifying whatever proxy configuration they need but ensuring that:
* `daemon = off` is set, so that redsocks doesn't fork (because the service type is `simple`)
* `local_port = 12345` is set, so that the iptables rules and redsocks' port match.
(I left the port shown in …
> Add support for transparent proxy redirection

- versionist.conf.js
Currently we only use two lines for the file header and we use heading, not
sub-deading, for version lines.
Changelog-entry: Use current changelog format with versionist
> versionist: Make it work with current format

- meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
When migrating the splash directory don't copy the directoy but the content of
it. As well make sure the destination directory is created.
Changelog-entry: Fix splash image migration in flasher images
> resin-init-flasher: Fix splash image migration

- meta-resin-common/classes/resin-sanity.bbclass
Add systemd as a required distro feature.
> resin-sanity.bbclass: Require systemd

- README.md
Changelog-entry: Document Change-type and Changelog-entry git commit footers
> README.md: Add info about Change-type and Changelog-entry

- README.md
- meta-resin-common/recipes-connectivity/resin-ntp-config/resin-ntp-config.bb
- meta-resin-common/recipes-connectivity/resin-ntp-config/resin-ntp-config/resin-ntp-config
- meta-resin-common/recipes-connectivity/resin-ntp-config/resin-ntp-config/resin-ntp-config.service
- meta-resin-common/recipes-core/systemd/systemd_%.bbappend
- meta-resin-common/recipes-support/resin-mounts/resin-mounts.bb
- meta-resin-common/recipes-support/resin-mounts/resin-mounts/etc-systemd-timesyncd.conf.mount
- meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars
Read a list of NTP servers from config.json if available and configure systemd-timesyncd to use them, otherwise use the defaults. This uses a new service rather than resin-net-config due to boot time ordering issues.
> Add support for customizing NTP server list

- meta-resin-common/recipes-containers/docker-disk/files/entry.sh
We use a specific tag when starting supervisor and latest tag was a relic from
an old implementation. Right now it's not needed anymore.
Changelog-entry: Remove latest supervisor tag as it is not used anymore
> docker-disk: Don't set latest tag

- README.md
- meta-resin-common/recipes-connectivity/dnsmasq/files/dnsmasq.conf.systemd
- meta-resin-common/recipes-connectivity/resin-net-config/resin-net-config/resin-net-config
- meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars
Add support for a new config.json key "dnsServers" that contains a space separated list of DNS servers to use in preference to the DHCP-provided and defaults.
> Add support for configuring DNS servers

- meta-resin-common/recipes-support/resin-state-reset/resin-state-reset/resin-state-reset
We mark that the state partition was initialized using a file called
remove_me_to_reset . If this file ends up on the disk but some data written by
the state doesn't, next boot will get corrupted.
Example. The reset creates supervisor.conf file in state partition and other
files and then writes remove_me_to_reset. Immediately afterwards the board
loses power. At next boot we can end up in a state where remove_me_to_reset
ended up on disk while the supervisor.conf didn't which will break the board.
Changelog-entry: Make sure resin-state-reset doesn't end up in an inconsistent state
Fixes https://github.com/resin-os/meta-resin/issues/676
> resin-state-reset: Make sure data is on disk before marking it done

- CHANGELOG.md
- meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
- scripts/resinhup/run-resinhup-ssh.sh
A number of small fixes to resinhup scripts, while working on other parts.
* get the API endpoint, instead of hardcode (which should be wrong when using current script on staging, for example)
* fix a bug when only supervisor update was requested, but still needed to pass hostOS version for the script
* fix the sections that are marked as errors by shellcheck (haven't touched the "warnings" yet, these are some minimum changes needed)
Happy to hear any comments!
> Resinhup fixes

- meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand
This script is very simple and set -e can misinterpret some of the
informative error codes from e2fsck as fatal errors. Remove set -e
as it doesn't buy us any reliability in this simple script.
> resin-filesystem-expand: Remove set -e

- meta-resin-common/recipes-connectivity/socat/socat_%.bbappend
We no longer include socat in our base images so this is no
longer needed.
> socat: Remove bbappend

- meta-resin-common/recipes-connectivity/dhcp/dhcp_%.bbappend
> dhcp_%.bbappend: Add forward space needed when doing SRC_URI_append

- meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars
It's quite common to have unset variables and it seems like it
would be better to warn in the places where the variables are
needed rather than here.
> resin-vars: Remove warning print for unset variables

- CHANGELOG.md
- meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
- scripts/resinhup/run-resinhup-ssh.sh
With a new flag, one can tell the resinhup script to fetch the target update's supervisor version, and if it's newer than the current one running on the device, update it alongside the resinOS update.
This will enable self-service resinHUP to also do supervisor updates non-interactively.
(Updated version of #711)
> resinhup: new flag to set supervisor to the target release's default version

- CHANGELOG.md
- meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
will add Changelog and thus finish PR when #761 is merged as that is more important to include.
> resinhup: bump default resinhup container to v1.2.1 (Alpine)

- meta-resin-common/recipes-containers/docker/docker/docker.conf.systemd
- meta-resin-common/recipes-containers/docker/docker/docker.service
We change the default subnet of docker to avoid conflicts with the local
network which will cause one of the two conflicting networks to become
unroutable. Docker attempts to find an unused subnet on startup but this is not
enough to avoid coflicts in the case of resin because the network might not
have come up when docker starts (e.g slow wifi/DHCP) or might change after it
has come up (e.g resin wifi connect). Furthermore, even if the subnet
automatically selected by docker is not directly accessible from the host, it
might be through the default gateway. So no matter what we do there is a
possibility to shadow a useful subnet.
This change attempts to minimise the chances of this happening by reducing the
size of the subnet to /24 instead of /16 and also moving it to a fairly
uncommon …
> docker: set bridge subnet to 10.114.101.1/24

- meta-resin-common/recipes-support/resin-device-progress/resin-device-progress/resin-device-progress
1) There needs to be a space befor the last "]", and because of that `resin-device-progress` actually does not work since the last changes in 2.0.7.
Also refactoring that line according to shellcheck advice, https://github.com/koalaman/shellcheck/wiki/SC2166
2) A variable substitution was faulty, due to a missing `$` the variable's name was substituted instead of its value, resulting in Unauthorized API calls.
> resin-device-progress: fix typo that broke script

- meta-resin-common/classes/image-resin.bbclass
Set deviceType in config.json so unmanaged images don't have
an unknown/empty type.
Changelog-entry: Set deviceType in config.json
> image-resin.bbclass: Set deviceType in config.json

- meta-resin-common/recipes-connectivity/openvpn/openvpn/prepare-openvpn
- meta-resin-common/recipes-connectivity/openvpn/openvpn/prepare-openvpn.service
- meta-resin-common/recipes-support/resin-vars/resin-vars.bb
- meta-resin-common/recipes-support/resin-vars/resin-vars/config-json.path
- meta-resin-common/recipes-support/resin-vars/resin-vars/config-json.service
This PR is related to the key switching from #656, and allows us to use a dedicated provisioning key in order to register and get the device api key for #656.  Without this PR it is necessary to use a user-api-key as otherwise the prepare-vpn service will try to use the provisioning key (which will fail), and it will not switch to using the device key (which will work) until the device is rebooted, this PR will make the VPN switch to using the correct key as soon as it is available
> prepare-openvpn: Switch to watching for config.json changes in order to update the VPN config

- meta-resin-common/recipes-connectivity/openvpn/openvpn/resin.conf
- meta-resin-common/recipes-connectivity/openvpn/openvpn_%.bbappend
OpenVPN should not run as root user, drop privileges to special openvpn user.
Connects-To: #798
Changelog-entry: openvpn: Run OpenVPN service as openvpn user
Signed-off-by: Andreas Fitzek <andreas@resin.io>
---- Autogenerated Waffleboard Connection: Connects to #798
> Don't run OpenVPN as root

- meta-resin-common/recipes-connectivity/openvpn/openvpn/prepare-openvpn
Use correct variable referencing in default parameter substitution
Changelog-entry: Fix variable referencing in default variable substitution inside prepare-openvpn script
> openvpn: Fix prepare-openvpn script

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/start-resin-supervisor
In the previous implementation, if docker start exited with non-zero (for instance, when
stopping the supervisor service), the right hand side of the `||` expression would start
running, removing the supervisor container, which is something we want to avoid and is unnecessary.
Changelog-entry: Avoid removing the supervisor container when the supervisor exits
> Avoid removing the supervisor container when the supervisor exits

- meta-resin-common/recipes-core/packagegroups/packagegroup-resin.inc
Only install systemd-analyze if we are building a development
image.
Changelog-entry: Only install systemd-analyze in development images
> packagegroup-resin: Make systemd-analyze dev only

- meta-resin-common/recipes-connectivity/networkmanager/networkmanager_1.8.2.bb
Changelog-Entry: Update NetworkManager to 1.8.2
> networkmanager: Bump to 1.8.2

- meta-resin-common/classes/resin-sanity.bbclass
- meta-resin-common/recipes-core/images/resin-image-flasher.bb
- meta-resin-common/recipes-core/images/resin-image.bb
With Yocto Pyro having this check in resin-sanity.bbclass was
causing problems, so move it.
@floion could you check if that fixes the issue for you? Thanks
> resin-sanity.bbclass: Move systemd check to image recipes

- meta-resin-common/recipes-containers/docker/docker_git.bb
- meta-resin-pyro/README.md
- meta-resin-pyro/conf/layer.conf
- meta-resin-pyro/recipes-containers/docker/docker_git.bbappend
A few minor changes to the Docker recipe to reflect changes in Yocto Pyro. We now use the built-in Go recipes and libdevmapper has been split out of lvm2.
> Add support for building Docker with Pyro

- meta-resin-common/recipes-connectivity/usb-modeswitch/usb-modeswitch_2.2.5.bb
- meta-resin-common/recipes-core/images/resin-image.bb
- meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
- meta-resin-jethro/recipes-devtools/jq/jq/Support-without-oniguruma.patch
- meta-resin-jethro/recipes-devtools/jq/jq_1.5.bb
- meta-resin-krogoth/recipes-devtools/jq/jq/Support-without-oniguruma.patch
- meta-resin-krogoth/recipes-devtools/jq/jq_1.5.bbappend
Yocto Pyro is much stricter on which host tools can be run from recipes. Add some missing dependencies to fix building with Pyro.
> Fix host tool dependency issues for Pyro

- meta-resin-common/recipes-devtools/mtools/mtools/initialize-direntry.patch
- meta-resin-common/recipes-devtools/mtools/mtools_4.0.18.bbappend
mtools uninitialized data when creating directories which can
potentially cause filesystem corruption.
https://lists.gnu.org/archive/html/info-mtools/2014-08/msg00000.html
Changelog-entry: Patch mtools directory creation
> mtools: Add patch to fix mtools directory creation

- meta-resin-common/classes/kernel-resin.bbclass
Disable a number of filesystem and block related options in
order to reduce the size of the image. On Raspberry Pi 3 this
saves around 4MB of image size.
Changelog-entry: Disable rarely used kernel configs for size
> kernel-resin.bbclass: Add config options to reduce size

- meta-resin-pyro/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
Include firmwares in the Pyro version of the OS.
Changelog-entry: Include connectivity firmwares in Pyro
> meta-resin-pyro: Add packagegroup-resin-connectivity

- meta-resin-common/recipes-containers/docker/docker_git.bb
docker was accidentally commited to be compiled statically which breaks
journald logging
> docker: dynamically link docker

- meta-resin-common/recipes-containers/docker-disk/docker-disk.inc
We force the use of the host's docker instead of the yocto built native docker.
This way we avoid version mismatches
Changelog-entry: Force use of host's docker daemon for the docker-disk recipe
> docker-disk.inc: Use host docker

- CHANGELOG.md
- meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
The previous version matched e.g. the Raspberry Pi's `/dev/mmcblk0p2` root partition, but it fails on e.g. some Intel NUC's `/dev/sda2` partition name. Adjust the matching that both are found correctly.
Related: https://github.com/resin-os/resinhup/issues/82 (sorry, first I though it's an issue in the Python part, hence filed it there)
> resinhup: query the partition number looser for root partition.

- meta-resin-common/conf/distro/include/resin-os.inc
- meta-resin-common/recipes-containers/tini/tini_0.14.0.bb
Enable Yocto security flags such as stack protector, fortify and
Position Independent Executables.
Changelog-entry: Enable Yocto security flags on all builds
> resin-os.inc: Add security flags

- CHANGELOG.md
- meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
- scripts/resinhup/run-resinhup-ssh.sh
Two changes in this PR:
* make supervisor update default behaviour (no flag needed), and update the flags to be able to disable this behaviour, and handle supervisor tag setting properly
* allow resinhup updater container to be cached like it is already possible for the other containers that are used in the update process (supervisor and resinOS)
> 1.x resinhup improvements

- meta-resin-morty/recipes-support/gnutls/gnutls.inc
- meta-resin-morty/recipes-support/gnutls/gnutls/0001-configure.ac-fix-sed-command.patch
- meta-resin-morty/recipes-support/gnutls/gnutls/arm_eabi.patch
- meta-resin-morty/recipes-support/gnutls/gnutls/correct_rpl_gettimeofday_signature.patch
- meta-resin-morty/recipes-support/gnutls/gnutls/use-pkg-config-to-locate-zlib.patch
- meta-resin-morty/recipes-support/gnutls/gnutls_3.5.9.bb
- meta-resin-morty/recipes-support/gnutls/libtasn1/0001-stdint.m4-reintroduce-GNULIB_OVERRIDES_WINT_T-check.patch
- meta-resin-morty/recipes-support/gnutls/libtasn1/dont-depend-on-help2man.patch
- meta-resin-morty/recipes-support/gnutls/libtasn1_4.10.bb
gnutls: Update to 3.5.9 in morty
The NetworkManager loads the gnutls library which calls on initialisation getrandom(). This call blocks until the entropy level is high enough in the system to initialise the random number pool, see #831. This delays the start of the NetworkManager, and in our case until the timeout of 1.5 minutes is reached. There is no need for gnutls to call getrandom() during initialisation because at this stage no en- or decryption operation is called. In gnutls 3.5.9 and newer, this issue is fixed. Unfortunately, this version isn't part of morty, yet. Therefore, if you update to NetworkManager 1.8, then you should also update the gnutls library.
Changelog-entry: Update gnutls to 3.5.9 in morty because of blocking NetworkManager
Signed-off-by: …
> NetworkManager Blocks Until Timeout During Startup // Fixed with gnutls 3.5.9

- meta-resin-common/classes/kernel-resin.bbclass
Enable stack protection in the kernel by default. This requires
gcc 4.9 and kernel 3.14.
Changelog-entry: Enable kernel stack protection
> kernel-resin.bbclass: Enable strong stack protector

- meta-resin-common/recipes-containers/docker/docker_git.bb
Inherit from the Go class rather than depending on it as this breaks
the Pyro build.
Changelog-entry: Switch docker to inherit from Go class
> docker: Switch to inheriting from go.bbclass

- meta-resin-common/classes/kernel-resin.bbclass
Enable the zram kernelmodule by default. This provides an
in-memory compressed swap device which can alleviate problems
with memory pressure on memory constrained devices and is enabled
by default on Chromebooks.
Changelog-entry: Enable zram kernel module by default
> kernel-resin: Enable zram

- meta-resin-common/recipes-connectivity/bluez5/bluez5_%.bbappend
- meta-resin-common/recipes-connectivity/bluez5/files/10-local-bt-hci-up.rules
There are boards which boot with hci0 brought down. By adding this rule
we make sure bluetooth is functional once the board has booted.
Changelog-entry: Make sure hci0 bluetooth interface is activated once booted
> bluez5.bbappend: Add udev rule to bring hci0 up

- meta-resin-common/classes/image-resin.bbclass
- meta-resin-common/recipes-support/resin-device-register/resin-device-register/resin-device-register
Pass the -S flag to jq to sort the keys in config.json. This
makes the output reproducible and easier for humans to read.
This fixes the kernel rebuild issue for me.
Changelog-entry: Sort config.json keys
> config.json: Sort keys when processing with jq

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/update-resin-supervisor
Same issue as in the `resin-device-progress` script, fixed in https://github.com/resin-os/meta-resin/pull/791
This basically makes update-resin-supervisor unable to pull a supervisor based on API response, as the API call is done incorrectly using the device API key.
> update-resin-supervisor: device API key is substituted incorrectly

- meta-resin-common/recipes-containers/docker/docker_git.bb
If pkgconfig is not part of the recipe sysroot then the docker
build scripts will just plough ahead and get things wrong.
Changelog-entry: Ensure docker links with systemd in pyro
> docker: Inherit pkgconfig

- meta-resin-pyro/classes/goarch.bbclass
The upstream version of this calss incorrectly identified the
arm1176 (original Raspberry Pi core) as an armv7 which led to
illegal instructions being generated.
Changelog-entry: Add a fixed goarch.bbclass for pyro
> goarch.bbclass: Add a fixed goarch.bbclass for pyro

- meta-resin-common/recipes-containers/mkfs-hostapp-native/files/mkfs.hostapp-ext4
We use a yocto's PATH to pass it in the container for it to have access to the
sysroot paths. Since pyro, yocto has per recipe sysroots so a recipe will not
have access to a shared sysroot. In the same time, yocto's path excludes host
paths to avoid host contamination but pasing this path in the container will
make the container not able to find executables in the docker images based on
PATH. This patch makes sure that the PATH passed to the container contains
entries to host paths too.
> mkfs.hostapp-ext4: Make sure PATH contains entries to container's paths

- meta-resin-common/recipes-connectivity/modemmanager/files/0001-helpers-new-parser-for-AT-IFC.patch
- meta-resin-common/recipes-connectivity/modemmanager/files/0002-broadband-modem-query-supported-flow-control-modes-b.patch
- meta-resin-common/recipes-connectivity/modemmanager/files/0003-wavecom-ignore-custom-flow-control-handling.patch
- meta-resin-common/recipes-connectivity/modemmanager/files/0004-telit-ignore-custom-flow-control-handling.patch
- meta-resin-common/recipes-connectivity/modemmanager/files/0005-port-serial-new-internal-method-to-run-tcsetattr.patch
- meta-resin-common/recipes-connectivity/modemmanager/files/0006-port-serial-new-method-to-explicitly-set-flow-contro.patch
- meta-resin-common/recipes-connectivity/modemmanager/files/0007-port-serial-remove-all-default-flow-control-settings.patch
- meta-resin-common/recipes-connectivity/modemmanager/files/0008-broadband-bearer-once-connected-set-flow-control-set.patch
- meta-resin-common/recipes-connectivity/modemmanager/modemmanager_%.bbappend
Backport a number of patches from upstream master that enable
setting flow control for RS232 modems.
Changelog-entry: Backport ModemManager flow control patches
> modemmanager: Backport flow control patches

- meta-resin-common/recipes-devtools/dosfstools/dosfstools/0001-src-check.c-Fix-up-mtools-created-bad-dir-entries.patch
- meta-resin-common/recipes-devtools/dosfstools/dosfstools_%.bbappend
The boot partition contains some directory entries with bad flags
that were created by mtools. Fix fsck so it clears the flags rather
than destroying the system-connections directory.
Changelog-entry: Fix fsck of boot partition with dosfstools
> dosfstools: Add patch to fix fsck of boot partition

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/start-resin-supervisor
The previous logic did not take into account what happens if there is no resin-supervisor image nor container on the device, and could end up in a state that the device cannot automatically recover
itself from a missing supervisor image. This happened for example for resinHUP 1.x->2.x, when after the update it was necessary for the device to start up without any images or containers.
Add logic to handle the missing image case by running the update-resin-supervisor service when no image exists.
Also added comments so that the logic is documented.
> docker-resin-supervisor-disk: allow supervisor start when no supervisor image present

- meta-resin-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
A board specific layer should choose between 99-resin-grub
and 99-resin-uboot accordingly.
Changelog-entry: Support grub boards with hostapp-update-hooks
> hostapp-update-hooks: Support grub

- meta-resin-common/recipes-connectivity/libqmi/libqmi_1.18.0.bb
Changelog-entry: Update libqmi to version 1.18.0
> libqmi: Update to version 1.18.0

- meta-resin-common/classes/kernel-resin.bbclass
The kernel option CONFIG_NETFILTER_XT_MATCH_OWNER also needs CONFIG_NETFILTER_ADVANCED
Changelog-entry: Add required kernel config dependency for being able to use redsocks
> kernel-resin.bbclass: Add required dependency for redsocks

- meta-resin-common/recipes-support/hostapp-update-hooks/files/0-bootfiles
When copying boot files from the OS we update to, we were using the list of
files from the current OS. This is wrong because the version we update to might
come with new files or might have removed files.
Change-log-entry: When updating to a new host os use bootfiles list from the next OS
> hostapp-update-hooks: Use boot files list from the 'next' OS

- meta-resin-common/classes/image-resin.bbclass
We have a bunch of calls to the realtime binary in this class so let's also
depend on coreutils-native which provides this binary.
Change-log-entry: Add dependency to coreutils-native on build time
> image-resin.bbclass: Add build time dependency on coreutils-native

- meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
after giving resin-device-register a chance to run
We should do our best to ensure we copy the config.json from the flasher over
to the internal media after the resin-device-register script was executed and
hopefully registered the board.
Changelog-entry: Do our best to ensure we copy to internal media the config.json after resin-device-register was able to register the board
> resin-init-flasher: Copy config.json to internal media

- meta-resin-common/recipes-connectivity/networkmanager/networkmanager_%.bbappend
- meta-resin-common/recipes-connectivity/networkmanager/networkmanager_1.10.0.bb
Also, disabled ovs support (Open vSwitch) as we do not use it and it would
have brought an extra dependency in the rootfs (Jansson).
Changelog-entry: Update NetworkManager to version 1.10.0
> networkmanager: Update to version 1.10.0

- meta-resin-common/recipes-support/resin-init/resin-init-flasher.bb
Since commit 7a39577e0a36427e82efeab9a57b609f2c0e7c38
(resin-init-flasher: Detect the drive we are running from and ignore it)
we also need to have the flasher rootfs contain the lsblk binary.
Changelog-entry: Add the lsblk binary to the flasher rootfs
> resin-init-flasher.bb: Add runtime dependency on util-linux-lsblk

- meta-resin-common/recipes-support/hostapp-update-hooks/files/0-bootfiles
Changelog-entry: Fix 0-bootfiles when running hooks
> hostapp-update-hook: Fix 0-bootfiles when running hooks

- meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update
Because as part of a host OS update we need to update the bootloader also,
for some boards we need to be able to write the bootloader directly to a
specific /dev entry. Hence we need the update container be able to have access
to /dev of the host.
Changelog-entry: Run the update container as privileged
> hostapp-update: Run the update container as privileged

- meta-resin-common/recipes-containers/balena/balena/balena.conf.systemd
- meta-resin-common/recipes-containers/balena/balena/balena.service
- meta-resin-common/recipes-containers/balena/balena_git.bb
As well run the daemon with experimental flag to enable restarting
unhealthy containers.
Changelog-entry: Update balena cu include healthcheck support
> balena: Update to version with healthcheck support

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/start-resin-supervisor
/mnt/root/var/lib/docker as DOCKER_ROOT until the supervisor handles this instead
Changelog-Entry: Pass /mnt/root/var/lib/docker as DOCKER_ROOT to the supervisor
> docker-resin-supervisor-disk: Have the start-resin-supervisor script use

- meta-resin-common/classes/kernel-resin.bbclass
With this, we can make sure balena is able to manage memory/swap limiting per
container.
Changelog-entry: Activate memory/swap cgroups in kernel
> kernel-resin.bbclass: Activate memory/swap cgroups

- meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update
When updating from a system that does not have hostapp-update-hooks or not capable of rollback, have a flag that allows the script to skip that step on failed hooks run, as it should be safer from the system's point of view. Try to fix any issues manually instead of automatically which in those circumstances has the potential to make things worse.
Connects-to: #939
Changelog-entry: Make hostapp-update-hooks rollback on failure optional
Signed-off-by: Gergely Imreh <imrehg@gmail.com>
---- Autogenerated Waffleboard Connection: Connects to #939
> hostapp-update: make hostapp-update-hooks rollback on failure optional

- meta-resin-common/recipes-core/packagegroups/packagegroup-resin.bb
This script is a dependency of resinOS updates. It was removed by mistake
when you dropped resinhup dummy script from resin-image. It used to be a
dependency of the removed package. Without this dependency this tool was
removed from the image.
Changelog-entry: Bring back resin-device-progress in resin-image
> packagegroup-resin: Install resin-device-progress

- meta-resin-common/recipes-connectivity/networkmanager/files/NetworkManager.conf
Let network manager manage bridge devices that are not managed by balena. In
this way users will be able to create bridge interface through network manager.
> NetworkManager: Allow managing "non-balena" bridge interfaces

- meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update
Some hooks use blkid which needs to be able to resolve labels for the mounts
on fs labels. In order to make this tool work in the container we bind mount
/dev which will make fs labels resolve to the block devices.
> hostapp-update: Bind mount /dev from host so we can resolv labels

- meta-resin-common/recipes-core/systemd/systemd/0001-resolved-fix-loop-on-packets-with-pseudo-dns-types-229.patch
- meta-resin-common/recipes-core/systemd/systemd/0001-resolved-fix-loop-on-packets-with-pseudo-dns-types.patch
- meta-resin-common/recipes-core/systemd/systemd_%.bbappend
Fixes: https://github.com/resin-os/meta-resin/issues/916
> systemd: Backport patch to fix Remote DOS of systemd-resolve service

- meta-resin-common/recipes-core/healthdog/healthdog.inc
New meta-rust version don't set RUNPATH anymore and the current fix was patching it only when the RUNPATH was set.
This patch is based on https://github.com/meta-rust/meta-rust/commit/463622c0c6828e7fb970f46f9bf0dcf156345373 which is only available for recipes which use the rust-bin bbclass. Healthdog uses cargo so the fix is not available for it. Furthermore, the fix is only available on master (not on pyro, the branch we are working on).
Fixes https://github.com/resin-os/meta-resin/issues/955
> healthdog: Fix RPATH on newer meta-rust

- meta-resin-common/recipes-core/coreutils/coreutils_%.bbappend
> coreutils: Set uptime to use procfs for accurate uptime

- meta-resin-common/recipes-containers/mkfs-hostapp-native/mkfs-hostapp-native.bb
When using machine specific variables the parser will consider it only
available target recipes. This change forces this native recipe to use the
definition of BALENA_STORAGE when a machine specific definition is available.
Changelog-entry: Fix BALENA_STORAGE when machine specific definition is used
> mkfs-hostapp-native: Use BALENA_STORAGE even if it's machine specific

- .github/PULL_REQUEST_TEMPLATE.md
Creating a template, so that the requirements for good PRs can be codified, instead of the PR submitters warned after the PR was already submitted.
Adding items that I know of at the moment.
> housekeeping: adding PR template

- meta-resin-common/recipes-core/systemd/systemd/0002-core-Avoid-empty-directory-warning-when-we-are-bind-.patch
- meta-resin-common/recipes-core/systemd/systemd_%.bbappend
Fixes #893
Changelog-entry: Avoid mount warnings when using systemd mount units on files
---
> systemd: Add patch to suppress warnings when mounting files

- meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
When compiling this package, the tool uses the kernel source directory
STAGING_KERNEL_DIR along with the deploy dir (which includes artifacts from
building the kernel). We already depend on do_deploy for kernel but when building
from sstate, the STAGING_KERNEL_DIR is not populated. Make sure that is
populated when compiling kernel-modules-headers by adding an explicit
dependency to kernel:do_patch.
Changelog-entry: Fix kernel-modules-headers when building from sstate
--- …
> kernel-modules-headers: Compile depends on do_patch

- meta-resin-common/recipes-connectivity/openvpn/openvpn/openvpn-resin.service
Openvpn already deploys a tmpfiles configuration for systemd to handle the run directory. No need for this service StartPre anymore.
Fixes #167
Changelog-entry: Let systemd handle openvpn run directory
--- …
> openvpn: Let systemd handle the run directory

- meta-resin-common/recipes-core/ucl/ucl_1.03.bb
configure error for ucl-native too
This extends the fix from commit 88cffcce8cd93c909af31454d8fe7577fbf96ab2
to ucl-native too.
This commit fixes(by using the ISO C90 standard) the following ucl-native configure error on gcc6:
| checking whether your compiler passes the ACC conformance test... FAILED
| configure:
| configure: Your compiler failed the ACC conformance test - for details see
| configure: `config.log'. Please check that log file and consider sending
| configure: a patch or bug-report to <markus@oberhumer.com>.
| configure: Thanks for your support.
| configure:
| configure: error: ACC conformance test failed. Stop.
Changelog-entry: Fix ucl-native ACC conformance test configure error on gcc6
---
- When submitting …
> ucl: Fix gcc6 ACC conformance test for ucl-native

- meta-resin-common/classes/image-resin.bbclass
We use jq in image-resin.bbclass for building our image so we need
to have the proper dependency on jq-native.
Changelog-entry: Make image-resin.bbclass depend on jq-native at buildtime
--- …
> image-resin.bbclass: Depend on jq-native

- meta-resin-common/recipes-core/dropbear/dropbear_%.bbappend
use_atomic_key_generation_in_all_cases for version
2017.75 or newer.
Starting with dropbear version 2017.75 this patch is included
so no need to apply this backported patch to these dropbear versions.
Changelog-entry: Do not apply the use_atomic_key_generation_in_all_cases patch for dropbear 2017.75 or newer
--- …
> dropbear_%.bbappend: conditionally apply backported patch

- meta-resin-common/recipes-connectivity/modemmanager/modemmanager_1.7.990.bb
When compiling with Poky Rocko we need to explictily add a build-time
dependency to libxslt-native.
Changelog-entry: Make ModemManager depend on libxslt-native at build-time for Poky Rocko
--- …
> modemmanager_1.7.990.bb: Add dependency to libxslt-native

- meta-resin-common/recipes-containers/balena/balena_git.bb
The go.bbclass from Poky Rocko requires the GO_IMPORT variable to be defined.
We also adapt for the changes this brings in: the source files get moved to
${S}/src/import rather than just in ${S}.
Changelog-entry: Prepare the balena recipe for Poky Rocko
--- …
> balena_git.bb: Prepare for go.bbclass changes from Poky Rocko

- meta-resin-rocko/recipes-go/resin-provisioner/resin-provisioner_1.0.4.bbappend
This commit fixes the following error when using Poky Rocko:
| build/tmp/work/core2-64-poky-linux/resin-provisioner/1.0.4-r0/go-tmp/go-link-534922009/go.o:(.data.rel.ro+0x403700): undefined reference to `main.init'
| build/tmp/work/core2-64-poky-linux/resin-provisioner/1.0.4-r0/go-tmp/go-link-534922009/go.o:(.data.rel.ro+0x403708): undefined reference to `main.main'
Changelog-entry: Fix resin-provisioner 1.0.4 compile error on Poky Rocko
--- …
> resin-provisioner_1.0.4.bbappend: Fix compile issue on Poky Rocko

- meta-resin-common/recipes-core/images/resin-image-flasher.bb
Poky Rocko has deprecated the IMAGE_DEPENDS variable.
This commit fixes the following bitbake error:
resin-image-flasher.bb: Deprecated variable(s) found: "IMAGE_DEPENDS_resinos-img". Use do_image_<type>[depends] += "<recipe>:<task>" instead
Changelog-entry: Replace deprecated variable IMAGE_DEPENDS from resin-image-flasher.bb
--- …
> resin-image-flasher.bb: Replace deprecated variable IMAGE_DEPENDS

- meta-resin-common/classes/image_types_resin.bbclass
Poky Rocko has deprecated the IMAGE_DEPENDS variable.
Added dependencies to do_deploy tasks for target packages and do_populate_sysroot for native packages.
This commit fixes the following bitbake errors:
resin-image.bb: Deprecated variable(s) found: "IMAGE_DEPENDS_resinos-img, IMAGE_DEPENDS_hostapp-ext4". Use do_image_<type>[depends] += "<recipe>:<task>" instead
resin-image-flasher.bb: Deprecated variable(s) found: "IMAGE_DEPENDS_resinos-img". Use do_image_<type>[depends] += "<recipe>:<task>" instead
Also, some boards may define multiple bootloaders. An example:
https://github.com/resin-os/resin-intel/blob/master/layers/meta-resin-genericx86/recipes-core/images/resin-image.inc#L12
Given the above fact, we also needed to process this bootloader list and append to appropeiate do_deploy …
> image_types_resin.bbclass: Replace deprecated variable IMAGE_DEPENDS

- meta-resin-common/recipes-connectivity/openvpn/openvpn/openvpn
- meta-resin-common/recipes-connectivity/openvpn/openvpn/openvpn-volatile.conf
- meta-resin-common/recipes-connectivity/openvpn/openvpn/openvpn@.service
- meta-resin-common/recipes-connectivity/openvpn/openvpn_2.4.3.bb
Connected to https://github.com/resin-os/meta-resin/issues/997
This recipe is imported from meta-oe/rocko.
ResinOS needs dualstack support which is included from openvpn 2.4. We add this
recipe in the common meta-resin layer to make sure that all of our supported
boards have this available.
Changelog-entry: Update OpenVPN to 2.4.3
--- …
> openvpn: Update to 2.4.3

- meta-resin-pyro/recipes-core/systemd/systemd/0001-core-Don-t-redirect-stdio-to-null-when-running-in-co.patch
- meta-resin-pyro/recipes-core/systemd/systemd_%.bbappend
This issue affects console output when running systemd in docker container
because moby doesn't correctly manage POLLHUP hangup. The issue was initially
created in systemd https://github.com/systemd/systemd/pull/4262 and later
redirected to moby https://github.com/moby/moby/issues/27202 .
This affects versions after 232 where fd0 fd1 fd2 are redirected to /dev/null
leaving no file descriptor pointing to /dev/console. When that happens docker,
the pty master, will close the pty and any attempts to open /dev/console will
return EIO.
This patch removes the /dev/null redirection when running in container. We can
get rid of it when moby fixes the issue referenced above.
CHangelog-entry: Fix console output when running resinOS with systemd >= 232
Signed-off-by: Andrei Gherzan …
> systemd: Add a temporary console fix until moby fixes it

- meta-resin-common/recipes-core/base-files/base-files_%.bbappend
Resin supervisor expects /lib/modules in places and bind mounts it in the user
container. Make sure we package this directory to avoid runtime error.
Changelog-entry: Always have /lib/modules directory in rootfs as supervisor requires it
--- …
> base-files: Package /lib/modules directory

- meta-resin-pyro/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
If this is not the case, other packages will include the files which should get
into the 8000c.
CHangelog-entry: Fix 8000c in PACKAGES
---
> linux-firmware: Have 8000c package before others

- meta-resin-common/recipes-containers/balena/balena_git.bb
- meta-resin-fido/recipes-devtools/go-cross/go-1.7.3/0007-fix-cc-cxx-with-multiple-words.patch
- meta-resin-fido/recipes-devtools/go-cross/go_1.7.3.inc
- meta-resin-jethro/recipes-devtools/go-cross/go-1.7.3/0007-fix-cc-cxx-with-multiple-words.patch
- meta-resin-jethro/recipes-devtools/go-cross/go_1.7.3.inc
- meta-resin-krogoth/recipes-devtools/go-cross/go-1.7.3/0007-fix-cc-cxx-with-multiple-words.patch
- meta-resin-krogoth/recipes-devtools/go-cross/go_1.7.3.inc
- meta-resin-morty/recipes-devtools/go-cross/go-1.7.3/0007-fix-cc-cxx-with-multiple-words.patch
- meta-resin-morty/recipes-devtools/go-cross/go_1.7.3.inc
Connected to https://github.com/resin-os/meta-resin/issues/919
---
> Use the correct, full yocto CC/CXX variables when using go

- meta-resin-common/recipes-containers/docker-disk/files/entry.sh
when not including any docker image
When building without the resin-supervisor (unmanaged production build for example)
then we do not include the supervisor image. In such a case, if we also do not bundle in
any container, the entry.sh script will not do any "docker pull" commands and then when sending
SIGTERM to the docker daemon it will shutdown immediately so that the subsequent wait() will
error out.
Changelog-entry: Fix docker-disk when not including any docker image
--- …
> docker-disk: Fix compile error

- meta-resin-common/classes/kernel-resin.bbclass
Changelog-entry: Add missing kernel config dependency for leds-gpio
---
> kernel-resin.bbclass: Add missing dependency for leds-gpio

- meta-resin-common/recipes-containers/docker-disk/files/Dockerfile
- meta-resin-common/recipes-containers/docker-disk/files/entry.sh
Changelog-entry: Fix docker-disk when docker build fails to not leave root files behind
---
> docker-disk: Don't leave root files if docker build fails

- meta-resin-common/recipes-connectivity/openvpn/openvpn/openvpn.service
We rename resin-openvpn.service to openvpn.service but there are still
components that are using the old name (for example: supervisor). This
patch adds a service alias to the old name.
Changelog-entry: Add resin-openvpn.service alias for openvpn.service
--- …
> openvpn: Add alias for old service name

- meta-resin-common/recipes-connectivity/openvpn/openvpn/resin.conf
openvpn: disable tls renegotiation hourly in favour of every 1GB
This discourages all clients from rekeying their sessions at the same time, which in turn causes vpn/api load spikes.
Fixes #1023
Changelog-Entry: disable openvpn time-based tls key renegotiation
Signed-off-by: Will Boyce <will@resin.io>
--- …
> disable openvpn tls renegotiation hourly in favour of every 1GB

- meta-resin-common/recipes-support/resin-init/resin-init-flasher.bb
Changelog-entry: Remove bashisms in resin-init-flasher recipe
---
> resin-init-flasher: Remove [[ bashism

- meta-resin-common/classes/kernel-resin.bbclass
Tested on Raspberry Pi 3 and Intel NUC builds.
Fixes #1033
Changelog-entry: USB Modem (CDC ACM) support enabled as kernel module
---
> kernel-resin.bbclass: Enable CONFIG_USB_ACM as module by default

- meta-resin-common/recipes-support/resin-persistent-logs/resin-persistent-logs/resin-persistent-logs
Fixes #1035
Mount systemd units create directories when not available. We switched to
service units based on bindmount tool which expects the destination to be in
place. This change fixes this by making sure /var/log/journal is in place
before starting the bind mount service.
Change-type: Patch
Changelog-entry: Fix persistent logging
--- …
> resin-persistent-logs: Fix persistent logging

- meta-resin-common/recipes-core/initrdscripts/files/machineid
Changelog-entry: Fix racing issue of state label existance in initramfs
---
> initrdscripts: Make machineid wait with timeout for label to appear

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
Brings in the following improvements since 7.1.18:
- Replace the gosuper component with a node module that handles communication with systemd, and stop using an init system in the supervisor container
- Remove any leftover knex migrations locks before running migrations
Changelog-Entry: Update supervisor to v7.1.20
Signed-off-by: Akis Kesoglou <akis@resin.io>
--- …
> docker-resin-supervisor-disk: Update to v7.1.20

- meta-resin-common/recipes-connectivity/redsocks/files/0001-using-libevent-2_1_x.patch
- meta-resin-common/recipes-connectivity/redsocks/redsocks_0.5.bb
Current version of redsocks cannot use libevent 2.1.x because of a breaking change, and that results in the `http-connect` (and possibly other) operation being broken (regression since meta-resin 2.10.0)
This commit pulls in a proposed patch from redsocks:  https://github.com/darkk/redsocks/pull/123
This should fix https://github.com/resin-os/resinos/issues/461 and has been tested with a custom build.
Changelog-entry: Apply upstream patch for redsocks to fix http-config regression
Signed-off-by: Gergely Imreh <imrehg@gmail.com>
--- …
> redsocks: patch to be able to use libevent 2.1.x

- meta-resin-common/recipes-support/resin-state-reset/resin-state-reset/resin-state-reset
Prevent failure by testing for /etc/resin-supervisor/supervisor.conf
file existence before copying.
---
> resin-state-reset: Allow not existing supervisor.conf file

- meta-resin-common/recipes-core/packagegroups/packagegroup-resin.inc
- meta-resin-common/recipes-core/resin-extra-udev-rules/files/49-teensy.rules
- meta-resin-common/recipes-core/resin-extra-udev-rules/resin-extra-udev-rules.bb
This PR relates to issue #1063 to add teensy udev rules.
These changes add the [49-teensy.rules](https://www.pjrc.com/teensy/49-teensy.rules) within a connectivity recipe called `resin-extra-udev-rules`. The recipe attempts to copy [resin-edison/.../modemmanager.bbappend](https://github.com/resin-os/resin-edison/blob/master/layers/meta-resin-edison/recipes-connectivity/modemmanager/modemmanager_%25.bbappend) to add the required rules. However, uses a `bb` file as this is not modifying the existing modem manager.
I was considering whether adding the udev rules from a URL with a md4 checksum would have been more appropriate. This would mean that were the rules ever updated the process would fail and mean that the new rules could be reviewed. Having the rules copied directly into the repo is …
> Adds teensy udev rules to resin extra udev rules

- meta-resin-common/recipes-connectivity/networkmanager/networkmanager_1.10.2.bb
Changelog-entry: Update Network Manager to version 1.10.2
---
> networkmanager: Update to version 1.10.2

- meta-resin-common/recipes-core/resin-extra-udev-rules/files/99-misc.rules
- meta-resin-common/recipes-core/resin-extra-udev-rules/resin-extra-udev-rules.bb
Fixes #1089
ChangeType: patch
Changelog-entry: Set ModemManager to ignore STM32F407 devices
Testing was only done at the level of build - no hardware available.
---
> resin-extra-udev-rules: Instruct ModemManager to ignore STM32F407 devices

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
Brings in the following changes since 7.10.0:
- Allow pinning of preloaded devices
Changelog-entry: Update resin-supervisor to 7.11.0
---
> docker-resin-supervisor-disk: Update supervisor to 7.11.0

- meta-resin-common/recipes-containers/balena/balena_git.bb
- meta-resin-sumo/recipes-containers/balena/balena_git.bbappend
compiled with gcc 7.3.0 with static PIE support enabled
mobyinit is the init we use in resinOS. It is a static golang binary. When compiling
mobynit on a Yocto platform that uses gcc 7.3.0 (Yocto Sumo) with static PIE enabled,
mobynit will crash at runtime and the kernel will panic:
[    4.672896] Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b
[    4.672896]
[    4.682177] CPU: 3 PID: 1 Comm: init Not tainted 4.9.80 #2
[    4.687735] Hardware name: BCM2835
[    4.691198] [<80111b44>] (unwind_backtrace) from [<8010d094>] (show_stack+0x20/0x24)
[    4.699054] [<8010d094>] (show_stack) from [<804aa7ac>] (dump_stack+0xcc/0x110)
[    4.706471] [<804aa7ac>] (dump_stack) from [<80216b00>] (panic+0x104/0x274)
[    4.713534] [<80216b00>] (panic) from [<80124068>] …
> balena_git.bb: Fix mobynit runtime crash when

- meta-resin-common/recipes-connectivity/networkmanager/files/NetworkManager.conf
We switch the DHCP IPv4 request timeout to infinity so that we circumvent
situations when the DHCP server times out for long periods of time during
which the lease may also expire and thus when the DHCP server is restored
NetworkManager will not retry at that point as the timeout interval may be
long expired.
We set the timeout to 2147483647 which is basically MAXINT32, but NM will
efectively never timeout in fact.
Changelog-entry: Set DHCP timeout to infinity for IPv4
--- …
> networkmanager: Set DHCP timeout to infinity for IPv4

- meta-resin-common/recipes-containers/balena/balena_git.bb
This fixes a boot lag due to OS not having enough entropy during early boot.
Changelog-entry: Update balena to fix boot lag
---
> balena: Update to current HEAD of 17.06-resin

- meta-resin-common/recipes-containers/tini/tini_0.14.0.bb
- meta-resin-krogoth/recipes-containers/tini/tini_0.14.0.bbappend
- meta-resin-morty/recipes-containers/tini/tini_0.14.0.bbappend
- meta-resin-pyro/recipes-containers/tini/tini_0.14.0.bbappend
- meta-resin-rocko/recipes-containers/tini/tini_0.14.0.bbappend
- meta-resin-sumo/recipes-containers/tini/tini_0.14.0.bbappend
Even though the GCC in sumo comes with static PIE support, this functionality
looks broken as it fails at runtime with segfault: Program received signal
SIGSEGV, Segmentation fault.
_dl_relocate_static_pie () at /usr/src/debug/glibc/2.27-r0/git/elf/dl-reloc-static-pie.c:41
41    /usr/src/debug/glibc/2.27-r0/git/elf/dl-reloc-static-pie.c: No such file or directory.
Tini is compiled with PIE because since sumo update, PIE is enabled by default:
commit 6733a7873ca121295a2e309a6915b9816e1ae36b
Author: Khem Raj <raj.khem@gmail.com>
Date:   Sat Jun 10 07:57:34 2017 -0700
security_flags.inc: Delete pinnings for SECURITY_NO_PIE_CFLAGS
Fix this by passing the `no pie` flags in sumo and avoiding passing pie flags
in all the older versions.
Changelog-entry: Fix tini segfault after …
> tini: Fix PIE segfault

- meta-resin-krogoth/recipes-containers/tini/tini_0.14.0.bbappend
- meta-resin-morty/recipes-containers/tini/tini_0.14.0.bbappend
- meta-resin-pyro/recipes-containers/tini/tini_0.14.0.bbappend
- meta-resin-rocko/recipes-containers/tini/tini_0.14.0.bbappend
- meta-resin-sumo/recipes-containers/tini/tini_0.14.0.bbappend
Changelog-entry: Avoid overwriting SECURITY_CFLAGS for tini recipe
---
> tini: Avoid overwriting SECURITY_CFLAGS

- meta-resin-common/recipes-core/images/resin-image.bb
Since rocko update, this commit ended up in poky:
commit bb81ff1343d8d6213f0418fd18b10312c96c4617
Author: Richard Purdie <richard.purdie@linuxfoundation.org>
Date:   Fri Aug 11 08:10:33 2017 +0100
image-prelink: Disable for musl images
This switched the use of `+=` to `_append` when adding the prelink hooks to
IMAGE_PREPROCESS_COMMAND. Because we are using `+=` for adding our fingerprints
hook, we end up having the prelink hooks after the fingerprints one (append is
evaluated after parsing - see
https://www.yoctoproject.org/docs/1.6/bitbake-user-manual/bitbake-user-manual.html#appending-and-prepending-override-style-syntax).
This results in wrong artifacts when prelink modifies the binaries - rootfs
ends up with wrong fingerprints. We fix this be using `_append` as well.
Change-type: …
> resin-image: Fix fingerprints

- meta-resin-common/classes/kernel-resin.bbclass
Currently if the kernel panics, it is up to the device kernel
configuration if it timesout and reboots on a kernel panic.
Also, the watchdog if present does not reboot a device that is in
a panic state as the kernel watchdog driver keeps touching it.
Enforce a reboot on kernel panic from meta-resin.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand …
> Reboot if the kernel panics

- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
- meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/start-resin-supervisor
Brings in the following changes since 7.13.2:
* Correctly apply current commit values to running applications
* Remove the use of the meta-config resinApiEndpoint, and remove env var
for this
Changelog-entry: Update resin-supervisor v 7.14.0
--- …
> docker-resin-supervisor-disk: Update supervisor to 7.14.0

- meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
openssl/bio.h when compiling on kernel
version 4.16
Adding the dependency on openssl fixes the following error:
|   HOSTCC  scripts/extract-cert
| scripts/extract-cert.c:21:10: fatal error: openssl/bio.h:
No such file or directory
Changelog-entry: Fix kernel-modules-headers compile missing bio.h
--- …
> kernel-modules-headers.bb: Fix missing

- meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
This version uses hostcc (last argument) for modules_prepare as well
(not only for for compiling the scripts). On newer kernel versions,
modules_prepare needs more than just the CC but also sysroot, ld flags
etc. Add all these so tools like extract_cert can be compiled during
modules_prepare.
Fixes #1143
Changelog-entry: Update kernel-modules-headers to v0.0.11
---
- …
> kernel-modules-headers: Update version to v0.0.11

- meta-resin-common/recipes-core/upx/upx_3.94.bb
Package depends on ucl not ucl-native. This fixes the case were we
compile this package for target.
Changelog-entry: Fix ucl dependency in upx
---
> upx: Fix dependency

- meta-resin-common/recipes-containers/balena/balena_git.bb
balena has a few fixes for libnetwork and container pull.
Update to incorporate them
**Change-type: minor**
Changelog-entry: Bump balena version to latest 17.12-resin
Signed-off-by: Zubair Lutfullah Kakakhel <zubair@resin.io>
Sanity test on pi3b+
--- …
> balena: update to current HEAD of 17.12-resin

- meta-resin-common/recipes-connectivity/resin-proxy-config/resin-proxy-config/resin-proxy-config
Make sure the reading of the lines in the no_proxy file still return a
line if it is the last one in the file and it doesn't have a newline
at the end.
Connects-to: #1164
Signed-off-by: Rich Bayliss <rich@resin.io>
---- Autogenerated Waffleboard Connection: Connects to #1164
> resin-proxy-config: The no_proxy file fails to parse when missing EOL

- meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor/resin-supervisor.service
As highlighted in
https://lists.freedesktop.org/archives/systemd-devel/
2015-July/033513.html
we now have a problem if balena.service fails initially but afterwards
it succeeds. In such a case, resin-supervisor.service will fail with a
dependency error and won't get restarted later on automatically.
Changelog-entry: Rework resin-supervisor systemd dependency on balena
---
- …
> resin-supervisor.service: Rework dependency on balena.service

- meta-resin-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
This commit got left out from https://github.com/resin-os/meta-resin/pull/1153
Tested on a nuc in virtualbox
---
> Add kernel to rootfs 2

- meta-resin-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
This commit got left out by mistake for v2.18
---
> merge development into master for v2.18 part 2

- meta-resin-common/recipes-core/images/resin-image.bb
- meta-resin-common/recipes-core/packagegroups/packagegroup-resin.inc
The kernel was included in the rootfs in v2.18. But didn't reach the rootfs in the flasher images.
Tested on resin-intel in a VM.
---
> Move kernel from image recipe to packagegroup

- meta-resin-common/recipes-bsp/u-boot/patches/env_resin.h
- meta-resin-common/recipes-containers/balena/balena/balena-host.service
- meta-resin-common/recipes-containers/balena/balena/balena.service
- meta-resin-common/recipes-containers/hostapp-update/files/hostapp-update
- meta-resin-common/recipes-core/balena-rollback/balena-rollback.bb
- meta-resin-common/recipes-core/balena-rollback/files/rollback-altboot
- meta-resin-common/recipes-core/balena-rollback/files/rollback-altboot.service
- meta-resin-common/recipes-core/balena-rollback/files/rollback-health
- meta-resin-common/recipes-core/balena-rollback/files/rollback-health.service
- meta-resin-common/recipes-core/balena-rollback/files/rollback-parse-bootloader
- meta-resin-common/recipes-core/balena-rollback/files/rollback-stop
- meta-resin-common/recipes-core/balena-rollback/files/rollback-tests
- meta-resin-common/recipes-core/packagegroups/packagegroup-resin.bb
- meta-resin-common/recipes-support/hostapp-update-hooks/files/80-rollback
- meta-resin-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
- meta-resin-common/recipes-support/hostapp-update-hooks/files/99-resin-uboot
- meta-resin-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb
This PR adds automated OS rollback recipe.
The rollback structure is as follows
There are 2 scripts rollbacks-altboot and rollbacks-health.
After a HUP, rollbacks-altboot checks if the bootloader bootcount has triggered and the bootloader has run the previous rootfs. If rollbacks-altboot detects we are running the previous rootfs, then rollbacks-altboot tries to recover the bootfiles and reboots.
After a HUP, rollbacks-health checks if the state of the new resin OS is working. The basic check we have at the moment is that the vpn comes back online after a HUP. This is a mandatory requirement of HUP at the moment. This will prevent bricks happening in case modem drivers bugger up e.g.
Again, if rollbacks-health detects that the vpn has not come back online after a timeout, script tries to …
> Add support for Automated OS Rollbacks

- meta-resin-common/recipes-containers/balena/balena_git.bb
This patch bumps the balena version in meta-resin.
Tested on a nuc image running on a VM
---
> balena: Add support for mounting rootfs from a custom path in mobynit

- meta-resin-common/classes/kernel-resin.bbclass
MBIM and QMI support needs USB_NET_DRIVERS and USB_USBNET enabled.
Changelog-entry: Enable kernel config dependencies for MBIM and QMI
---
> kernel-resin.bbclass: Add required mbim and qmi configs

- meta-resin-common/recipes-core/packagegroups/packagegroup-resin.bb
- meta-resin-common/recipes-utils/aufs-util/aufs-util_%.bbappend
From the aufs-util package only the auplink binary is needed and that
dependency is from balena. So we package auplink in a separate package
and just install that package into the rootfs.
Chanelog-entry: Only add auplink binary into the rootfs to decrease rootfs size
--- …
> aufs-util: Package auplink separately

- meta-resin-common/recipes-connectivity/networkmanager/networkmanager/balena-client-id.patch
- meta-resin-common/recipes-connectivity/networkmanager/networkmanager_1.12.2.bb
This patch replaces the "Client identifier" option from
DHCP packets sent by NM to resemble the way udhcpc does it.
The reason is that the Cisco RV325 router with fw older than
v1.2.1.14 doesn't reply to DHCP requests or discovery packages
if the "Client identifier" option is formatted in NM's style.
Even though this is a bug in the router's fw, we are going to
fix it here because we encountered clients that couldn't get
an IP address on these routers and we want to avoid that
Changelog-entry: Replace NM's DHCP request option "Client indentifier" with udhcpc style option
Signed-off-by: Sebastian Panceac <sebastian@balena.io>
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic …
> Replace NM's DHCP request option "Client indentifier"

- meta-resin-common/recipes-core/initrdscripts/files/resindataexpander
The current implementation checks for the existence of the `flash-boot`
label. This breaks when after flashing the flashing device is left
plugged. Change this with a check based on the root kernel argument.
Fixes #1210
Changelog-entry: Avoid expander on flasher based on root kernel argument
--- …
> Avoid expander on flasher based on root kernel argument

- CONTRIBUTING.md
- README.md
Fixes #422
Changelog-entry: Include a CONTRIBUTING.md file
---
> README.md: Move contributing section to CONTRIBUTING.md

- meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc
Changelog-entry: Update resin-supervisor to v7.25.3
---
> resin-supervisor: Update to v7.25.3

- meta-resin-common/classes/kernel-resin.bbclass
This is not needed as bitbake already expands KERNEL_CONFIG_COMMAND
See Poky commit 95909bc788bef1baabead94231dffb3b7f59fb00 for details
Changelog-entry: Drop obsolete eval from kernel-resin's do_kernel_resin_reconfigure
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of …
> kernel-resin: Drop obsolete eval from do_kernel_resin_reconfigure

- meta-resin-common/recipes-core/dropbear/files/dropbearkey.conf
Changelog-entry: Generate ssh host key at first boot (not at first connection)
---
> dropbear: Generate host key at first boot

- README.md
We remove SIM7100E in favour of SIM7600E and
also add Huawei ME909s-120.
Changelog-entry: Update supported modems list
---
> README.md: Update supported modems list

- meta-resin-common/recipes-connectivity/avahi/avahi_%.bbappend
Poky removes the dbus introspection description documents for avahi.
See:
http://git.yoctoproject.org/cgit.cgi/poky/commit/?id=59a08907eafffde664079b9a2068f47131dd3f5d
dbus-native node module requires this data to be available to allow
access to interfaces.
Fixes #1140
Changelog-entry: Include avahi d-bus introspection files in rootfs
--- …
> avahi: Bring back avahi dbus introspection files

- meta-resin-common/recipes-connectivity/resin-proxy-config/resin-proxy-config/resin-proxy-config
There are other components setting up iptables rules - for example
balena. In order to avoid a lock race, run iptables commands with a 10
seconds wait flag.
Changelog-entry: Avoid xtables lock in resin-proxy-config
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the …
> resin-proxy-config: Avoid iptables race

- meta-resin-sumo/recipes-core/systemd/systemd/0003-mount-util-add-mount_option_mangle.patch
- meta-resin-sumo/recipes-core/systemd/systemd/0004-umount-Fix-memory-leak.patch
- meta-resin-sumo/recipes-core/systemd/systemd/0005-umount-Add-more-asserts-and-remove-some-unused-argum.patch
- meta-resin-sumo/recipes-core/systemd/systemd/0006-umount-Decide-whether-to-remount-read-only-earlier.patch
- meta-resin-sumo/recipes-core/systemd/systemd/0007-umount-Provide-the-same-mount-flags-too-when-remount.patch
- meta-resin-sumo/recipes-core/systemd/systemd/0008-umount-Try-unmounting-even-if-remounting-read-only-f.patch
- meta-resin-sumo/recipes-core/systemd/systemd/0009-umount-Don-t-bother-remounting-api-and-ro-filesystem.patch
- meta-resin-sumo/recipes-core/systemd/systemd/0010-shutdown-Reduce-log-level-of-unmounts.patch
- meta-resin-sumo/recipes-core/systemd/systemd_%.bbappend
OS 2.26.0+rev1 reports the following at reboot:
systemd-shutdown[1]: Failed to wait for process: Protocol error
systemd-shutdown[1]: Failed to wait for process: Protocol error
As per systemd/systemd#8155 (comment), systemd/systemd#8429
needs to be backported.
Changelog-entry: Backport systemd sd-shutdown improvements
--- …
> systemd/sumo: Backport sd-shutdown improvements

- meta-resin-common/recipes-support/resin-mounts/resin-mounts/resin-partition-mounter
The label is actually a udev symlink, but we're keeping
this naming to be consistent across the file.
The error seen is that the balena-host service wasn't
able to start because of a mnt-sysroot-active.service dependency:
resin-partition-mounter[440]: ERROR: Timeout while waiting
for filesystem label to appear
By increasing this timeout, the filesystem symlink should
already exist, at the time the mnt-sysroot-active service is
looking for this dependency.
Changelog-entry: Increase timeout for filesystem label
Signed-off-by: Vicentiu Galanopulo <vicentiu@resin.io>
---
- '*Request Changes*' if this …
> resin-mounts: Increase timeout for the filesystem label

- meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor
When the device hasn't joined a backend, there is no API key available
and the update supervisor tool currently just bails out. This blocks
switching the supervisor version on an unmanaged device.
Changelog-entry: Allow supervisor update on unmanaged devices
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, …
> update-resin-supervisor: Allow update when there is not API key

- meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
Fixes https://github.com/balena-io-playground/kernel-module-build/issues/7
Fixes #1303 
Fixes #1302 
Tested pi3, jetson and nuc image.
NUC image needs the following workaround 
```
ln -s /lib64/ld-linux-x86-64.so.2  /lib/ld-linux-x86-64.so.2
```
in  build.sh in https://github.com/balena-io-playground/kernel-module-build/
The baselib in balenaOS is `/lib` which is used by the recipe. So the tools built inside the tarball have the interpreter path as  `/lib/ld-linux-x86-64.so.2`. But the baselib in the debian image is `/lib64`. This needs more thought on how to go about fixing this.
---
- '*Request Changes*' if this …
> Fix kernel header for modules generation

- meta-resin-krogoth/recipes-core/chrony/chrony/arm_eabi.patch
- meta-resin-krogoth/recipes-core/chrony/chrony_3.2.bb
- meta-resin-morty/recipes-core/chrony/chrony/arm_eabi.patch
- meta-resin-morty/recipes-core/chrony/chrony/chrony.conf
- meta-resin-morty/recipes-core/chrony/chrony/chronyd
- meta-resin-morty/recipes-core/chrony/chrony_3.2.bb
- meta-resin-pyro/recipes-core/chrony/chrony/arm_eabi.patch
- meta-resin-pyro/recipes-core/chrony/chrony/chrony.conf
- meta-resin-pyro/recipes-core/chrony/chrony/chronyd
- meta-resin-pyro/recipes-core/chrony/chrony_3.2.bb
- meta-resin-rocko/recipes-core/chrony/chrony/arm_eabi.patch
- meta-resin-rocko/recipes-core/chrony/chrony/chrony.conf
- meta-resin-rocko/recipes-core/chrony/chrony/chronyd
- meta-resin-rocko/recipes-core/chrony/chrony_3.2.bb
We added an option in chrony.conf (`hwtimestamp *`) via meta-resin-common in https://github.com/balena-os/meta-balena/commit/d4f5a022799b5648dc2fcaef70435cc7abae5fb7
That option is supported in newer versions of chrony.
Add chrony 3.2 recipe to krogoth,morty,pyro,rocko layers as the chrony version in them is old.
sumo is already on chrony v3.2
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you …
> Add chrony v3.2 recipe to ensure minimum chrony version in devices

- meta-resin-common/classes/image-resin.bbclass
Fixes #1330
Changelog-entry: Fix cases where RESIN_BOOT_PARTITION_FILES includes invalid entries
---
> image-resin.bbclass: Fix cases where RESIN_BOOT_PARTITION_FILES contains invalid entries

- meta-resin-common/recipes-containers/balena/balena_git.bb
This includes changes which target fixing hanging on low entropy
situation.
Fixes #1208
Changelog-entry: Update balena-engine to include low entropy fixes
--- …
> balena: Update to 17.12-resin's HEAD

- meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor
Currently, because we bind mount apps.json unconditionally, when this
file doesn't exist, balena engine will create a directory on the data
filesystem. This breaks when we add an apps.json file after the
supervisor container was already created.
Fixes #1325
--- …
> resin-supervisor: Use an empty apps.json when nonexistent

- meta-resin-common/recipes-connectivity/networkmanager/resin-files/NetworkManager.conf
Under the current configuration we instruct NetworkManager through its
configuration to completely ignore all the tun devices. This was
enforced as an extra precation as we run an openvpn client which
connects to the balena-cloud backend. This client creates, on the host,
the interface `resin-tun` currently (rename pending). We want to loosen
up this restriction to only unmanage this specific device - `resin-tun`
- so that users can take advantage of NetworkManager managing other tun
devices.
Changelog-entry: Configure NetworkManager to only ignore our vpn interface but manage other tun devices
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are …
> networkmanager: Remove tun devices from unmanaged list

- CONTRIBUTING.md
Signed-off-by: Giovanni Garufi <giovanni@balena.io>
---
> docs: Add documentation on nested changelogs

- meta-resin-common/classes/image-resin.bbclass
- meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
- meta-resin-common/recipes-kernel/linux/kernel-devsrc.bbappend
Currently we ship the kernel headers using the kernel-modules-headers recipe.
That recipe pre-compiles tools to run on the device only. Using the kernel-devsrc recipe, we now want to tarball and ship the entire kernel source tree as well. This will enable people to cross-compile external modules as well and is a more robust solution compared to kernel-modules-headers.
--- …
> Tarball and deploy complete kernel source

- README.md
- meta-resin-common/classes/resin-sanity.bbclass
- meta-resin-common/conf/layer.conf
- meta-resin-krogoth/conf/layer.conf
- meta-resin-morty/conf/layer.conf
All of the devices supported by balenaCloud run pyro or above.
Deprecate krogoth and morty
---
> Deprecate Krogoth and Morty layers

- meta-resin-common/classes/image_types_resin.bbclass
There can be cases where a image type gets invalidated (due to a
variable change or so) and the dependency of it not. For example the img
type can get invalidated while the hostapp ext3 type doesn't. The img
generatiton script consumes/uses the rootfs generated by the hostapp
type but, it references the artifact based on IMAGE_NAME variable which
includes a time stamp. See bitbake.conf:
IMAGE_NAME = "${IMAGE_BASENAME}-${MACHINE}-${DATETIME}"
When that happens, the new timestamp will change and img will fail to
find the old artifact of hostapp. Change this behaviour by using the
symlink reference IMAGE_LINK_NAME which doesn't include a timestamp.
Changelog-entry: Fix img to rootfs dependency when img is invalidated
---
- …
> image_types_resin.bbclass: Fix img dependency on rootfs

- meta-resin-common/recipes-containers/balena/balena_git.bb
The 17.12-resin branch was modified and the old revision is not
there anymore.
Changelog-entry: Use the new revision for balena source code
---
> balena_git: Use the new revision for the source code

- meta-resin-common/recipes-connectivity/networkmanager/resin-files/99dhcp_ntp
We have noticed devices in support that show high cpu usage because
the process chronyc online seems to be eating up 50% cpu.
This is probably fixed upstream https://github.com/mlichvar/chrony/commit/6863e43269fe27ce2744eb643295f31c00ec176d#diff-50898f0cb35139d87132f4732a029213
Add a timeout in any case as its a lower risk option
Changelog-entry: Add a workaround for a bug where the chronyc online command in network manager hook would get stuck and eat cpu cycles
--- …
> Add timeout to chronyc online command

- meta-resin-common/recipes-support/resin-persistent-logs/resin-persistent-logs/resin-persistent-logs.service
Found while looking at https://github.com/balena-os/meta-balena/issues/1367
We need the state partition and boot partition ready before we try to run the persistent logging service.
---
> resin-persistent-logs: Add boot and state partition dependency

- meta-resin-common/recipes-connectivity/networkmanager/resin-files/99dhcp_ntp
> networkmanager: fix ntp server hook if there are no custom ntp servers

- meta-resin-common/recipes-core/initrdscripts/files/resindataexpander
Fixed typo that caused flashing process to block
on some corrupted eMMCs due to parted command failure.
Flashing process hanged during boot with this log:
- Error: Can't have overlapping partitions.
Changelog-entry: Fixed "Can't have overlapping partitions." error in flasher
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if …
> resindataexpander: Fix typo in Resin Flasher detection

- meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.bb
- meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor/tmpfiles-supervisor.conf
There are tmp directories supervisor assumes nobody touches in which
things like update lock files are stored. This patch configures systemd
tmpfiles to ignore these tmp paths.
Fixes #1377
Changelog-entry: Configure systemd tmpfiles to ignore supervisor tmp directories
--- …
> resin-supervisor: Configure systemd tmpfiles exceptions

- meta-resin-common/classes/kernel-resin.bbclass
We will only have the out of tree module which allegedly
is more stable:
https://github.com/raspberrypi/linux/issues/1866
The configs for disabling it were added but apparently
they were never applied.
Changelog-entry: Disable in-tree rtl8192cu driver
--- …
> kernel-resin.bbclass: Disable in-tree rtl8192cu driver

- meta-resin-common/recipes-core/balena-rollback/balena-rollback.bb
- meta-resin-common/recipes-core/balena-rollback/files/rollback-altboot
- meta-resin-common/recipes-core/balena-rollback/files/rollback-altboot.service
- meta-resin-common/recipes-core/balena-rollback/files/rollback-check-version
- meta-resin-common/recipes-core/balena-rollback/files/rollback-health
- meta-resin-common/recipes-core/balena-rollback/files/rollback-parse-bootloader
- meta-resin-common/recipes-core/systemd/systemd/poweroff.target.conf
- meta-resin-common/recipes-core/systemd/systemd/reboot.target.conf
- meta-resin-common/recipes-core/systemd/systemd_%.bbappend
- meta-resin-common/recipes-support/hostapp-update-hooks/files/99-resin-uboot
https://github.com/balena-os/meta-balena/pull/1349 will take some time to restructure and miss v2.30
These fixes from there should go into v2.30
---
> A few rollback and related fixes for v2.30

- meta-resin-common/recipes-connectivity/networkmanager/resin-files/99dhcp_ntp
- meta-resin-common/recipes-connectivity/resin-ntp-config/resin-ntp-config/resin-ntp-config
A few subtle improvements for custom ntp servers
---
> Improve ntp dhcp server sync time

- meta-resin-common/recipes-containers/balena/balena/balena-host.service
- meta-resin-common/recipes-containers/balena/balena/balena-host.socket
- meta-resin-common/recipes-containers/balena/balena_git.bb
Fixes #1405
We'd like the balena-host daemon to be socket activated so that it does
not consume any cpu/memory resource until used.
---
> Make balena-host daemon socket activated

- meta-resin-common/recipes-kernel/linux/kernel-devsrc.bbappend
It is best to not create anything in ${B} even if just temporary because
it alters the directory in ways which can break other parts of the build
system. For example, if there is a leftover kernel_source.tar.gz in B,
then the current kernel-devsrc will create a hardlink of this file in
the kernel source tree and then the command
tar -czf ${B}/kernel_source.tar.gz -C "$kerneldir/../" .
will fail like:
tar: ./kernel/kernel_source.tar.gz: file changed as we read it
Changelog-entry: Generate the temporary kernel-devsrc compressed archive in WORKDIR instead of B
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be …
> meta-resin-common: kernel-devsrc: Generate the tar archive in WORKDIR

- meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor
When starting the supervisor container, check that the values already configured in the environment match the ones held in the config.
Signed-off-by: Rich Bayliss <rich@balena.io>
> resin-supervisor: Recreate on start if config has changed

- meta-resin-common/recipes-containers/balena/balena_git.bb
- meta-resin-common/recipes-core/os-config/os-config.inc
We currently upx `os-config` and `mobynit`. runtime decompression slows down the binaries. This becomes evident for slow devices like the pi0/beagle pocket etc.
We have space in the OS at the moment. Lets un-upx binaries to speed things up.
On a pi3, with this PR.
```
root@8e1b3fb:~# df -kh .
Filesystem      Size  Used Avail Use% Mounted on
none            300M  239M   41M  86% /
root@8e1b3fb:~# du -hs /usr/bin/os-config
2.5M    /usr/bin/os-config
root@8e1b3fb:~# du -hs /mnt/sysroot/active/current/boot/init
5.6M    /mnt/sysroot/active/current/boot/init
root@8e1b3fb:~# 
```
```
root@62d0b9a:/mnt/data# du -hs os-config*
2.6M    os-config
700K    os-config_upxed
root@62d0b9a:/mnt/data# du -hs mobynit*
5.7M    mobynit
1.7M    mobynit_upxed
root@62d0b9a:/mnt/data#
```
---
- When submitting a …
> un-upx binaries

- meta-resin-common/recipes-core/systemd/systemd_%.bbappend
During build, we generate the binary `/etc/udev/hwdb.bin` that is used at runtime. The source rules are still left in `/lib/udev/hwdb.d`. These are useful for distros that want to regenerate the `hwdb.bin` at runtime. but we don't really do that. 
We can remove the source files to conserve 5.9Mb.
#810 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand …
> systemd: Trim udev hwdb source files

- meta-resin-common/recipes-containers/balena/balena_git.bb
The version is 17.13.3. We'll need to bump the version string as well
now that versionbot is being used in the balena-engine repo.
Fixes #1433 
Changelog-entry: Fix the balena version string reported by balena-engine info
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand …
> balena-engine: Fix version string

- meta-resin-common/recipes-support/resin-vars/resin-vars.bb
- meta-resin-common/recipes-support/resin-vars/resin-vars/os-networkmanager
The device section in networkmanager.conf is [device] not [Device].
Fix the typo
Fixes #1448
---
> resin-vars: fix typo in os-networkmanager

- meta-resin-common/recipes-core/initrdscripts/files/fsck
- meta-resin-common/recipes-devtools/e2fsprogs/e2fsprogs_%.bbappend
- meta-resin-common/recipes-devtools/e2fsprogs/os-files/e2fsck.conf
- meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand.bb
```
Mar 11 15:29:58 localhost sh[476]: Superblock last mount time (Thu Mar 14 17:13:02 2019,
Mar 11 15:29:58 localhost sh[476]:         now = Mon Mar 11 15:29:56 2019) is in the future.
Mar 11 15:29:58 localhost sh[476]: Fix? yes
```
when `resin-filesystem-expand` runs fsck on the data partition, the system time is older than the previous boots time. This causes a full fsck to run on the data partitoin which slows down boot.
This PR prevents this from happening by passing `broken_system_time` in `/etc/e2fsck.conf`
Fixes #1438 
Linked with #946 
--- …
> Avoid uselessly running fsck on the data partition

- meta-resin-common/recipes-containers/docker-disk/files/entry.sh
By default, the supervisor container is created with the default bridge
network docker0. Which causes spurious warnings in balenaOS.
Disable the bridge network during build as we don't need it
Addresses one of warnings in https://github.com/balena-os/balena-engine/issues/153
--- …
> docker-disk: disable the default bridge network to avoid warnings

- meta-resin-common/recipes-core/packagegroups/packagegroup-resin.inc
We'd like to track boot time in production images as well.
As we currently have space in the OS, lets add it.
---
> Add systemd-analyze to production images as well

- meta-resin-common/recipes-connectivity/dnsmasq/dnsmasq_%.bbappend
- meta-resin-common/recipes-connectivity/dnsmasq/files/dnsmasq.conf
The dbus interface is useful for containers to qeury dnsmasq if needed.
Fixes #1453 
---
> dnsmasq: Enable dbus interface

- meta-resin-common/recipes-connectivity/libmbim/libmbim_1.18.0.bb
- meta-resin-common/recipes-connectivity/libqmi/libqmi_1.22.2.bb
- meta-resin-common/recipes-connectivity/modemmanager/modemmanager_1.10.0.bb
Update to latest stable ModemManager and libqmi and libmbim accompanying libraries. I did a quick test with a couple of devices here, but nothing more comprehensive than that.
---
> Update to ModemManager v1.10.0

- meta-resin-common/conf/distro/include/balena-os.inc
balenaOS comes in two flavours, production/development. production
images have various options passed to the kernel cmdline.
Currently some devices BSPs have those options passed and some dont.
It'll be hard to keep the common options consistent.
e.g. consoleblank=0 is passed for some devices and not for others.
We'd like the extra options we pass to be in one place. All BSPs can
then append this variable in their respective recipe/bootloader config
etc.
Fixes #1464
Tested by modifying `DEVELOPMENT_IMAGE`  in local.conf,
running `bitbake -e resin-image > tmp.log` and then grepping for the parameter.
---
- '*Request …
> Add OS_KERNEL_CMDLINE option

- meta-resin-common/recipes-containers/docker-disk/docker-disk.inc
_Note: As i am not the original owner of #1419 this is a new pull request with hopefully proper commenting for the commit._
FYI: @ZubairLK @agherzan
By checking for a pid you are prevented from building Balena inside
of a privileged container with a bind mount on /var/run/docker.sock
The "Test docker execute permission" stanza is adequate for testing
if docker is operational.
Changlog-entry: Disable unnecessary docker pid check
Signed-off-by: Armin Schlegel <armin.schlegel@gmx.de>
--- …
> docker-disk: Disable unnecessary docker pid check

- meta-resin-common/classes/resin-u-boot.bbclass
devtool moves the files from the WORKDIR into ${S}/oe-local-files which makes
copying of env_resin.h fail if the u-boot source is being modified using
devtool. Since devtool also alters FILESPATH to include said oe-local-files
directory, we can iterate over those paths instead of relying on WORKDIR.
Changelog-entry: Make resin-u-boot.bbclass devtool-compatible
Signed-off-by: Sven Schwermer <sven.schwermer@disruptive-technologies.com>
---
- …
> resin-u-boot: make devtool-compatible

- meta-resin-common/recipes-core/systemd/systemd/journald-balena-os.conf
- meta-resin-common/recipes-core/systemd/systemd_%.bbappend
Since yocto thud systemd main configuration files are part of another
recipe - systemd-conf. See poky commit:
28c2f0dfe3ae06d87772b2a88fcace5a03e09143
This commit prepares meta-balena for thud support.
--- …
> systemd: Use a conf.d file for journald configuration

- meta-resin-common/recipes-core/systemd/systemd_%.bbappend
- meta-resin-krogoth/recipes-core/systemd/systemd/0004-core-Avoid-empty-directory-warning-when-we-are-bind-.patch
- meta-resin-krogoth/recipes-core/systemd/systemd_%.bbappend
- meta-resin-morty/recipes-core/systemd/systemd/0003-core-Avoid-empty-directory-warning-when-we-are-bind-.patch
- meta-resin-morty/recipes-core/systemd/systemd_%.bbappend
- meta-resin-pyro/recipes-core/systemd/systemd/0004-core-Avoid-empty-directory-warning-when-we-are-bind-.patch
- meta-resin-pyro/recipes-core/systemd/systemd_%.bbappend
- meta-resin-rocko/recipes-core/systemd/systemd/0004-core-Avoid-empty-directory-warning-when-we-are-bind-.patch
- meta-resin-rocko/recipes-core/systemd/systemd_%.bbappend
- meta-resin-sumo/recipes-core/systemd/systemd/0011-core-Avoid-empty-directory-warning-when-we-are-bind-.patch
- meta-resin-sumo/recipes-core/systemd/systemd_%.bbappend
We used to have this patch applied for all the supported yocto versions.
Since thud, this patch is included by default so this change backports
it on all the rest of the supported mate-balena yocto version specific
layers.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context …
> systemd: Make directory warning patch yocto version specific

- meta-resin-common/conf/distro/include/balena-os.inc
- meta-resin-krogoth/conf/distro/include/balena-os-yocto-version.inc
- meta-resin-morty/conf/distro/include/balena-os-yocto-version.inc
- meta-resin-pyro/conf/distro/include/balena-os-yocto-version.inc
- meta-resin-rocko/conf/distro/include/balena-os-yocto-version.inc
- meta-resin-sumo/conf/distro/include/balena-os-yocto-version.inc
Since thud, poky distro file on which balena OS is based, already
includes security_flags.inc. Because of this change, this version throws
a build warning similar to:
WARNING: Duplicate inclusion for /build/../layers/poky/meta/conf/distro/include/security_flags.inc
in
/build/../layers/meta-resin/meta-balena-thud/conf/distro/include/balena-os-yocto-version.inc
This happens because again, we import `poky` and `security_flags` but
since thud, poky includes security_flags by default. In order to avoid
this warning we import it (security_flags) now using an .inc file at the
level of the yocto version meta-balena layer. There is as well a small
additional wrinkle here. We switch the include statement from `require`
to `include` so new layers (like thud) don't have to carry this hack in
the …
> balena-os.inc: Don't include security flags by default

- meta-resin-common/recipes-core/systemd/systemd/60-resin-update-state.rules
- meta-resin-common/recipes-core/systemd/systemd/resin_update_state_probe
When we set the udev rule we use IMPORT{program} to know what symlinks
to create in the sysroot directory. The problem is that we don't use
absolute paths and from the documentation udev uses /usr/lib/udev as the
default path while we install the invoked script in /lib/udev.
```
Execute an external program specified as the assigned value. If no
absolute path is given, the program is expected to live in
/usr/lib/udev; otherwise, the absolute path must be specified.
```
This PR changes the udev rule to use an absolute path for the
resin_update_state_probe script. Also it fixes some typos in the script
itself.
Changelog-entry: Fixes for sysroot symlinks creation
---
- '*Approve*' if …
> systemd: Fixes for sysroot symlinks creation

- meta-resin-common/recipes-core/images/resin-image-initramfs.bb
- meta-resin-common/recipes-core/initrdscripts/files/prepare
- meta-resin-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend
We run some operations in the initramfs. fsck, expand partitions etc.
Any error messages or warnings printed here are invisible in production
images. This line from debian initramfs-tools configures the initramfs
shell to log all output in /dev/kmsg so dmesg shows the output of
initramfs commands as well.
Fixes #1459
With this PR, on a pi3, we see the initramfs output like this in dmesg. (the fsck lines are from initramfs)
```
[    2.950758] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.961012] hub 1-1.1:1.0: USB hub found
[    2.967212] hub 1-1.1:1.0: 3 ports detected
[    2.970071] CP437: Invalid argument
[    3.063691] fsck.fat 4.1 (2017-01-24)
0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Automatically removing dirty …
```
> Log all messages in initramfs to dev-kmsg

- meta-resin-common/recipes-containers/balena/balena/balena-host.service
- meta-resin-common/recipes-containers/balena/balena/balena.conf.systemd
- meta-resin-common/recipes-containers/balena/balena/balena.service
- meta-resin-common/recipes-containers/balena/balena_git.bb
This PR updates balena-engine to 18.09.5 which supports the `--max-download-attempts` flag
Pass `--max-download-attempts=10` to improve performance on flaky connections.
Fixes #1493
---
> Update balena-engine and add max-download-attempts=10

- meta-resin-common/recipes-core/systemd/systemd/journald-balena-os.conf
9a8f1f1b744248964d4d1b2eb2c8dd732a753980 switched to a config file
fragment but when doing so the section was missed. This patch fixes
that.
---
> systemd: Fix journald configuration file

- README.md
- meta-resin-common/recipes-support/resin-vars/resin-vars.bb
- meta-resin-common/recipes-support/resin-vars/resin-vars/os-networkmanager
- meta-resin-common/recipes-support/resin-vars/resin-vars/os-networkmanager.testconfig6.json
We don't have a connectivity section configured in NetworkManager config at the moment.
This causes issues for devices with multiple interfaces that are active but only one has actual internet connectivity. NM doesn't know and does not adjust route metrics.
We now default to having the following in NetworkManager.conf
```
[connectivity]
uri=https://api.balena-cloud.com/connectivity-check
interval=3600
request=
```
The uri and interval are editable via config.json. See readme.md
Fixes #1199 
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development …
> Add support to update a connectivity section in NetworkManager via config.json

- meta-resin-common/recipes-core/systemd/systemd_%.bbappend
This code was deleted by mistake so let's add it back.
Changelog-entry: Do not spawn getty in production images
---
> systemd_%.bbappend: Do not spawn getty in production images

- meta-balena-thud/recipes-kernel/linux/linux-firmware_git.bbappend
This is done so we can save considerable amount of space on the root
partition.
See #810
Changelog-entry: Cleanup old versions of iwlwifi firmware files in Yocto Thud
--- …
> linux-firmware/thud: Cleanup iwlwifi by using balena-linux-firmware

- meta-resin-common/recipes-core/busybox/busybox/balenaos.cfg
- meta-resin-common/recipes-core/busybox/busybox_%.bbappend
Since 1.29, busybox switched to an internal implementation of the
resolver based on a feature config, NSLOOKUP_BIG. This is enabled by
default and it's meant to be musl compatible. In BalenaOS we use glibc
and we rely on it for being able to resolve names using NSS modules
(libmdns).
Changelog-entry: Fix busybox nslookup mdns lookups
--- …
> busybox: Use glibc's resolver as opposed to the internal one

- meta-resin-common/recipes-core/packagegroups/packagegroup-resin-connectivity.bb
Fixes: #1511
Add wifi firmware for rtl8192su
Only tested to see if the firmware file appears in the right place
```
bash-4.4# ls  /lib/firmware/rtlwifi/rtl8712u.bin -al
-rw-r--r-- 1 root root 122328 May 20 12:23 /lib/firmware/rtlwifi/rtl8712u.bin
bash-4.4#
```
--- …
> packagegroup-resin-connectivity: Add rtl8192su firmware

- meta-balena-common/recipes-containers/balena/balena_git.bb
In preparation for warrior. Bumps containerd which works with the newer
systemd in warrior.
---
> balena-engine: bump to v18.9.6

- meta-balena-common/recipes-core/os-release/os-release.bbappend
VERSION and VERSION_ID had a slightly different semantics in balenaOS.
VERSION was referring to the BalenaOS (host OS) version (which is coming from
device repositories) while VERSION_ID was set to the DISTRO_VERSION.
This brings confusion so we change it to adhere to
https://www.freedesktop.org/software/systemd/man/os-release.html.
Fixes #1546
Changelog-entry: Set both VARIANT_ID and VARIANT in os-release to host OS version
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development …
> os-release: Set VARIANT_ID to hostOS version too

- meta-balena-common/recipes-connectivity/bluez5/bluez5_%.bbappend
- meta-balena-common/recipes-connectivity/bluez5/files/bluetooth.conf.systemd
- meta-balena-common/recipes-support/resin-mounts/resin-mounts.inc
Currently, bluez's storage data is set to /var/lib/bluetooth which
in turn is a tmpfs location. We want this location persistent so we can
save paired devices over reboot. We do that by adding the corresponding
bind mount to the state partition and setting bluez to depend on this
mount unit.
Fixes #1544
Changelog-entry: Persist bluetooth storage data over reboots
---
- …
> bluez5: Persist storage directory over reboots

- meta-balena-common/classes/resin-u-boot.bbclass
Currently once config_resin.h is generated, a change in these variables
doesn't regenerate the file. Add vardeps so that bitbake can regenerate
config_resin.h in case these variables are changed.
Fixes #1530
Build tested on pi3
--- …
> u-boot.bbclass: Add vardeps to regenerate config_resin.h

- meta-balena-thud/recipes-core/systemd/systemd/backport-6caa14f763c11630f28d587b3caa5f0e6dc96165.patch
- meta-balena-thud/recipes-core/systemd/systemd_%.bbappend
- meta-resin-pyro/recipes-core/systemd/systemd/backport-6caa14f763c11630f28d587b3caa5f0e6dc96165.patch
- meta-resin-pyro/recipes-core/systemd/systemd_%.bbappend
- meta-resin-rocko/recipes-core/systemd/systemd/backport-6caa14f763c11630f28d587b3caa5f0e6dc96165.patch
- meta-resin-rocko/recipes-core/systemd/systemd_%.bbappend
- meta-resin-sumo/recipes-core/systemd/systemd/backport-6caa14f763c11630f28d587b3caa5f0e6dc96165.patch
- meta-resin-sumo/recipes-core/systemd/systemd_%.bbappend
> Default rp_filter to 2

- meta-balena-common/recipes-core/os-release/os-release.bbappend
Since #1550, os-release doesn't reference meta-balena distro version anymore. Restore
that by providing this information in a new variable called META_BALENA_VERSION.
Fixes #1558
Changelog-entry: Introduce META_BALENA_VERSION in os-release
--- …
> os-release: Introduce META_BALENA_VERSION

- meta-balena-common/recipes-core/os-release/os-release.bbappend
Poky, following os-release(5), sanitizes VERSION_ID accordingly but in
doing so it produces a nonisemver compliant version. For example:
VERSION="2.37.0+rev1"
VERSION_ID="2.37.0-rev1"
This patch reverts that to make sure rev is a build tag.
Fixes #1560
Changelog-entry: Fix VERSION_ID os-release to be semver complient
--- …
> os-release: Make sure VERSION_ID is semver compliant

- meta-balena-thud/recipes-kernel/linux/kernel-devsrc.bbappend
Thud breaks when building against kernel version < 4.10. This is a known
issue which is fixed in poky warrior[1]. This patch includes a
workaround for thud.
[1] http://lists.openembedded.org/pipermail/openembedded-core/2019-February/278695.html
Changelog-entry: Fix kernel-devsrc on thud when kernel version < 4.10
--- …
> kernel-devsrc/thud: Fix package when kernel version < 4.10

- meta-balena-common/conf/layer.conf
In addition we delete krogoth and morty from the supported list
as we also removed the actual layers from the repository.
Changelog-entry: Add warrior to compatible layers for meta-balena-common
--- …
> layer.conf/common: Add warrior to compatible layers 

- meta-balena-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
This version fixes using wrong fixdep binary (the bug makes it use
target fixdep binary instead of cross fixdep binary) used for compiling
the target objtool binary.
Changelog-entry: Update to kernel-modules-headers v0.0.19 to fix target objtool compile issue on kernel 5.0.3
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have …
> kernel-modules-headers: Update to v0.0.19

- meta-balena-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
This version fixes the missing target modpost binary
on kernel version 5.0.3.
Changelog-entry: Update to kernel-modules-headers v0.0.20 to fix missing target modpost binary on kernel 5.0.3
--- …
> kernel-modules-headers: Update to v0.0.20

- meta-balena-common/recipes-containers/docker-disk/docker-disk.bb
The data partition contains the supervisor which is only about 61M on
the pi3. We compress the data partition later on so don't notice these
zeros. But lets reduce the size of the data partition to eat less
space whenever an uncompressed image is used anywhere. e.g. when
extracting the zip to dd or using balena-migrate etc.
The partition expands on first boot to fill the rest of the disk
anyways.
Changelog-entry: Reduce data partition size from 1G to 128M
--- …
> docker-disk: Reduce data partition size from 1G to 192M

- meta-balena-common/recipes-connectivity/resin-proxy-config/resin-proxy-config/resin-proxy-config
There are still a more [rfc5735](https://tools.ietf.org/html/rfc5735) ranges not in the default here (192.0.2.0/24, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24 - 192.18/15 being the only one of which is listed in the [redsocks example configuration](https://github.com/darkk/redsocks#iptables-example)), and while they should not be routed to the internet I think there is an argument to let users control the proxying of these (obscure) subnets themselves should they want to do some interesting things with their internal networks.
---
- '*Request …
> resin-proxy-config: add missing reserved ip ranges to default noproxy

- meta-balena-common/classes/kernel-resin.bbclass
Changelog-entry: kernel-resin: Add support for CH340 family of usb-serial adapters
Signed-off-by: Sebastian Panceac <sebastian@balena.io>
---
> kernel-resin: Add support for CH340 family of usb-serial adapters

- meta-balena-common/classes/image-resin.bbclass
>  image-resin.bbclass: fixed a typo in image size sanity check

- meta-balena-common/recipes-core/systemd/systemd/balena-os-sysctl.conf
- meta-balena-common/recipes-core/systemd/systemd_%.bbappend
This defaults to 128. BoB hit the limit. Increase to 512
Fixes #1592
Changelog-entry: Increase fs.inotify.max_user_instances to 512
---
> Increase fs.inotify.max_user_instances to 512

- meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
Use ext4 FSTYPE to filter out automount with SOURCE "systemd-1" when determining the new parition label.
findmnt will report two sources, one being the systemd mnt-sysroot-inactive automount:
| -/mnt/sysroot/inactive    systemd-1             autofs
| `-/mnt/sysroot/inactive   /dev/mmcblk0p2   ext4
Since its output is used directly to find the new label and not filtered out by "basename" as in the u-boot hook case, an empty label will be written to the grub config file thus breaking booting after hup.
This fixes failed hostapp-update on the up-board and probably other grub based boards as well.
---
- '*Request …
> Fix grub hostapp-update hook

- meta-balena-common/recipes-connectivity/networkmanager/networkmanager_%.bbappend
- meta-balena-common/recipes-connectivity/networkmanager/resin-files/remove-https-warning.patch
Fixes #1597
The warning doesn't apply for our use case and confuses customers
Changelog-entry: Remove confusing networkmanager https connectivity warning
Tested on NUC in a VM
--- …
> networkmanager: Remove redundant https warning

- meta-balena-common/recipes-support/usb-modeswitch-data/patches/huawei-e3372.patch
- meta-balena-common/recipes-support/usb-modeswitch-data/usb-modeswitch-data_%.bbappend
Customer reported Huawei E3372 not working
anymore starting with balenaOS v2.32.
The fix for this appears to be switching the modem with
vid and pid 12d1:1f01 from the cdc_ether legacy mode to
the faster mbim mode and setting mtu=1460 in the modem
connection file.
Fixes https://github.com/balena-os/meta-balena/issues/1599
--- …
> Fix Huawei E3372 modem not working after v2.32

- meta-balena-common/recipes-core/systemd/systemd/vacuum.conf
- meta-balena-common/recipes-core/systemd/systemd_%.bbappend
We have found a rare corner case bug where the journal bloats beyond
its limit and fills the state partition. Triggering a vacuum on reboot
helps a bit in case the device is restarted to recover its function.
Fixes #1423
Changelog-entry: Workaround for a cornercase bug in PersistentLogging where journalctl filled the state partition. Vacuum the journal on boot.
--- …
> systemd: Vacuum journald on boot

- meta-balena-common/recipes-containers/balena/balena_git.bb
Includes improvements and fixes to the journald logdriver
Changelog-entry: Update balena-engine to 18.09.8
---
> balena-engine: Bump to 18.09.8

- meta-balena-thud/recipes-core/volatile-binds/volatile-binds.bbappend
- meta-balena-thud/recipes-core/volatile-binds/volatile-binds/mount-copybind
- meta-balena-warrior/recipes-core/volatile-binds/volatile-binds.bbappend
- meta-balena-warrior/recipes-core/volatile-binds/volatile-binds/mount-copybind
Our root filesystem is overlayfs or aufs. When latter, the system crashes when reading a lower directory file. We avoid this by always falling back to copy and mount (as if overlayfs is not available).
Fixes #1618
--- …
> volatile-binds: Avoid overlayfs mounts

- meta-balena-warrior/recipes-core/images/resin-image-initramfs.bbappend
- meta-balena-warrior/recipes-core/initrdscripts/files/console_null_workaround
- meta-balena-warrior/recipes-core/initrdscripts/initramfs-framework_%.bbappend
Tested on nuc and pi warrior
---
> Fix for production images when console=null is passed in kernel cmdline

- meta-balena-common/recipes-core/balena-rollback/files/rollback-altboot.service
- meta-balena-common/recipes-core/balena-rollback/files/rollback-health.service
Fixes bug introduced by #1441 
Add systemd-udev-settle.service to the rollback services.
Tested on pi3.
Fixes #1635
---
> balena-rollback: Fix service dependency

- meta-balena-common/recipes-containers/balena/balena/balena-host.service
- meta-balena-common/recipes-containers/balena/balena/balena.conf.systemd
- meta-balena-common/recipes-containers/balena/balena/balena.service
The default driver is cgroupfs. We switch to systemd so that there is
one cgroup manager in our OS.
Otherwise, systemd will have its own cgroup manager and cgroupfs will
be another cgroup manager via balenaEngine daemon.
Fixes #1645 which contains more information
Changelog-entry: Fix a bug where application containers with new systemd versions were failing to start in cases. Switch to systemd cgroup driver in balenaEngine
--- …
> balenaEngine: Switch cgroup driver to systemd

- meta-balena-warrior/recipes-core/initrdscripts/files/console_null_workaround
We would just check for the existence of console=null in kernel cmdline
A better way would be to check the presence of a valid symlink for fd0,
fd1 and fd2. And assign them to /dev/null if unavailable.
Changelog-entry: A small fix in initramfs when /dev/console is invalid due to whatever reason
--- …
> initrdscripts: Improve workaround

- meta-balena-common/classes/image-resin.bbclass
These can take quite a bit of build time. Add an option to disable
the recipes from being built.
Changelog-entry: Add option to disable kernel headers from being built.
--- …
> image-resin: Add option to disable kernel headers from being built

- meta-balena-common/recipes-containers/balena/balena_git.bb
Includes feature to populate container environment with container id
variable and bug fix for tagging deltas on the fly.
Changelog-entry: Update balena-engine to 18.9.10
--- …
> balena-engine: Bump to 18.9.10

- meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-uboot
Use ext4 FSTYPE to filter out automount with source "systemd-1" when determining the new parition label in the u-boot hook, just like we already do for grub.
findmnt will report two sources, one being the systemd mnt-sysroot-inactive automount:
| -/mnt/sysroot/inactive systemd-1 autofs
| `-/mnt/sysroot/inactive /dev/mmcblk0p2 ext4
Currently there's no failure observed because the output is filtered trough 'basename':
root@81dd8a3:~# findmnt --noheadings --canonicalize --output SOURCE /mnt/sysroot/inactive       
systemd-1
/dev/mmcblk0p14
Fix this so it doesn't become a possible point of failure at a later time.
---
- …
> hostapp-update-hooks: Filter out automount for inactive sysroot

- meta-balena-common/recipes-connectivity/openssh/openssh_%.bbappend
PasswordAuthentication defaults to yes. Make it no for production
images.
Fixes #1678
Changelog-entry: Disable PasswordAuthentication in sshd in production images as an extra precautionary measure.
--- …
> openssh: Disable PasswordAuthentication on production images

- meta-balena-common/recipes-kernel/linux/kernel-devsrc.bb
Necessary to avoid error:
"No rule to make target 'arch/arm64/kernel/vdso/vdso.lds', needed
by 'arch/arm64/kernel/vdso/vdso.so.dbg'"
when doing "make  modules_prepare"
Changelog-entry: kernel-devsrc: Copy vdso.lds.S file in source archive if available
Signed-off-by: Sebastian Panceac <sebastian@balena.io>
---
- [ x] Changes have been tested
- [ x] `Change-type` present on at least one commit
- [ x] `Signed-off-by` is present
- [ x] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)
- '*Request Changes*' if this …
> kernel-devsrc: Copy vdso.lds.S file in source archive if available

- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/resin-supervisor-healthcheck
- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor
Currently balenaEngine knows a supervisor is unhealthy but we wait for
healthdog to check the status and then restart supervisor.
Lets ask balenaEngine to restart the supervisor if it knows the
supervisor is unhealthy.
Healthdog is now restricted to checking presence of the supervisor
image itself.
Changelog-entry: Modify supervisor healthcheck. balenaEngine will restart an unhealthy supervisor if needed
--- …
> resin-supervisor: Ask balenaEngine to restart an unhealthy

- meta-balena-common/recipes-core/systemd/systemd/os.conf
- meta-balena-common/recipes-core/systemd/systemd_%.bbappend
Reduces redundant logs.
Fixes #1691
Changelog-entry: Reduce systemd logging level from info to notice
---
> systemd: Change loglevel from info to notice

- meta-balena-common/classes/kernel-resin.bbclass
Add dummy net driver support, which is used to
check if a container is privileged during
udev initialization.
Building it as module ensures that dummy
devices are not needlessly created during boot.
Addresses: 
- https://github.com/balena-os/meta-balena/issues/1606
- https://github.com/balena-os/balena-jetson-skx2/issues/163
Privileged checks will be improved on container side.
--- …
> kernel-resin: Build net/dummy as module

- meta-balena-common/recipes-connectivity/wpa-supplicant/wpa-supplicant/0001-replace-systemd-install-Alias-with-WantedBy.patch
- meta-balena-common/recipes-connectivity/wpa-supplicant/wpa-supplicant/99_wpa_supplicant
- meta-balena-common/recipes-connectivity/wpa-supplicant/wpa-supplicant/defconfig
- meta-balena-common/recipes-connectivity/wpa-supplicant/wpa-supplicant/wpa-supplicant.sh
- meta-balena-common/recipes-connectivity/wpa-supplicant/wpa-supplicant/wpa_supplicant.conf
- meta-balena-common/recipes-connectivity/wpa-supplicant/wpa-supplicant/wpa_supplicant.conf-sane
- meta-balena-common/recipes-connectivity/wpa-supplicant/wpa-supplicant_2.9.bb
Fetched from http://cgit.openembedded.org/openembedded-core/commit/meta/recipes-connectivity/wpa-supplicant?id=95507898ad6a7b88c83ef376c1cb8b3b3a685c96
Connects-to: #1711
Changelog-entry: Add wpa-supplicant recipe and update to v2.9
--- …
> wpa-supplicant: Add v2.9 recipe from upstream

- meta-balena-common/recipes-core/systemd/systemd/balena-os-sysctl.conf
Connects-to: #1726
Changelog-entry: Set `net.ipv4.ip_local_port_range` to recommended range (49152-65535)
---
> systemd/sysctl: Set `net.ipv4.ip_local_port_range` to 49152-65535

- meta-balena-warrior/recipes-core/images/resin-image-initramfs.bbappend
Without the new line, the last package name is
concatenated with the oneadded in this recipe resulting
in the following error
opkg_prepare_url_for_install
Couldn't find anything to satisfy
'kernel-module-sdhci-pciinitramfs-module-console-null-workaround'
Changelog-entry: Add leading new line for PACKAGE_INSTALL variable
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>
--- …
> resin-image-initramfs.bbappend: Add leading new line for PACKAGE_INSTALL

- meta-balena-common/recipes-core/balena-rollback/files/rollback-check-version
ESR releases have the VERSION string in /etc/os-release in a date
format. 2019.10.0 etc.
We added META_BALENA_VERSION in os-release from v2.38.0 via
b0e0c77a26f3fad51e2923ab416fdd2af2a5a033
Lets use META_BALENA_VERSION if available for our os version checks.
Changelog-entry: No user impact, subtle fix in rollback version checks
--- …
> rollback: Fix for ESR version naming scheme

- CONTRIBUTING.md
- README.md
- contributing-device-support.md
- meta-balena-common/README.md
- meta-balena-common/recipes-connectivity/openvpn/files/prepare-openvpn
- meta-balena-common/recipes-connectivity/openvpn/openvpn/resin.conf
- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc
- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/resin-supervisor.service
- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor
- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor.service
- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor.timer
- meta-balena-thud/README.md
- meta-balena-warrior/README.md
- meta-resin-pyro/README.md
- meta-resin-rocko/README.md
- meta-resin-sumo/README.md
> Rename resin to balena where possible

- meta-balena-common/classes/image-resin.bbclass
We inherit do_populate_lic_deploy from poky. It uses IMAGE_NAME
which includes DATETIME
DATETIME changes between runs so we can sometimes get into a state
where the do_populate_lic_deploy task has its stamp file set.
But when our subsequent deploy_image_license_manifest task runs, the
DATETIME is different. Hence we get into a state where we have to
run cleanall on the resin-image-flasher recipe to clean up directories.
Lets mark do_populate_lic_deploy with nostamp. This should make it
run every time we need to run deploy_image_license_manifest with the
most up to date DATETIME variable to prevent any hiccups
---
- '*Approve*' if this change would be acceptable in the …
> image-resin.bbclass: Mark do_populate_lic_deploy with nostamp

- meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
It is better to use fdisk to check that an internal media
is a suitable block device rather than using the shell
internal block testing feature. This is because there is
at least a case when the kernel lists an ASMT 2115 controller
as /dev/sda but that is not an actual drive so it cannot be
written to and the flashing procedure will error out.
Changelog-entry: Tweak how the flasher asserts that internal media is valid for being installed balena OS on
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes …
> resin-init-flasher: Tweak detection of internal media

- meta-balena-common/classes/kernel-resin.bbclass
Fixes #1770
Fixes #1761
Changelog-entry: Enable kernel configs for USB_SERIAL and HFS for all devices
---
> kernel-resin.bbclass: Enable CONFIG_USB_SERIAL and hfs support

- meta-balena-common/recipes-connectivity/networkmanager/resin-files/99dhcp_ntp
- meta-balena-common/recipes-connectivity/resin-ntp-config/resin-ntp-config/resin-ntp-config
- meta-balena-common/recipes-core/chrony/files/chrony.conf
This commit increases the default NTP poll rate to around 4 hours.
BalenaOS uses chronyd for time synchronization, and it allows to specify
a minpoll and maxpoll values per server with a power of two number of
seconds for the minimum and maximum polling time respectively.
With those constraints, the change set both limits to 2^14s (4.55h) for
all servers.
To allow fo backwards compatibility, when setting custom NTP servers the
maxpoll and minpoll rates can be configured in config.json for those
users who require the previous values.
Fixes #1780.
Changelog-entry: Increase NTP polling time to around 4.5 hours.
---
- '*Approve*' if this change would be acceptable in the codebase (even …
> Increase the NTP poll rate

- meta-balena-thud/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
- meta-balena-warrior/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
Since poky thud, the linux-firmware recipe in poky is packaging
the wl18xx firmware in its own package rather than add it in the
linux-firmware-wl12xx package.
Changelog-entry: Make sure to add in rootfs the wifi firmware for wl18xx
--- …
> packagegroup-resin-connectivity: Add wifi firmware for wl18xx

- meta-balena-common/recipes-core/systemd/systemd/balena-os-sysctl.conf
Move the memory overcommit settings from the Raspberry Pi integration
layer to meta-balena so it applies to all device types.
Fixes #1791
Changelog-entry: Enable memory overcommit
--- …
> Enable memory overcommit

- meta-balena-common/recipes-connectivity/dnsmasq/balena-files/resolv-conf.dnsmasq
The DNS clients (applications) resolver libraries use the timeout value in
/etc/resolv.conf to set the time between DNS attempts. The default is 5
secs which for slow networks like cellular mean lots of DNS requests on
a bandwidth sensitive channel.
This change modifies the default to 15 secs. This timeout only applies
when DNS servers are unresponsive so it will not affect the normal
functionality.
Fixes #1800
Changelog-entry: Increase DNS clients timeout to 15 seconds
--- …
> resolv.conf: Increase DNS client's timeout to 15 seconds

- meta-balena-common/recipes-containers/mkfs-hostapp-native/mkfs-hostapp-native.bb
- meta-balena-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
- meta-balena-common/recipes-kernel/linux/kernel-headers-test.bb
Apache 2.0 and MIT, though similar, are not the same license.
---
- Builds for balena-raspberrypi
> Match licenses with license files.

- meta-balena-common/recipes-core/systemd/periodic-vacuum-logs.bb
- meta-balena-common/recipes-core/systemd/periodic-vacuum-logs/periodic-vacuum-logs.service
- meta-balena-common/recipes-core/systemd/periodic-vacuum-logs/periodic-vacuum-logs.timer
- meta-balena-common/recipes-core/systemd/systemd_%.bbappend
Daily vacuuming of log files to avoid the partition filling up if
corrupted files appear.
Fixes #1792
Changelog-entry: Add periodic vacuuming of journald log files
--- …
> balena-vacuum-logs: Periodic vacuuming of log files

- meta-balena-common/recipes-connectivity/networkmanager/networkmanager_1.20.2.bb
ppp version is 2.4.7. Without defining the right path, the path defaults
to v2.4.5 in NM configure scripts.
Lets pass it here to keep it correct.
Should not have any actual affect. NM plugin was built with reference
to the 2.4.7 headers. Just the directoy path would say 2.4.5 misleading
some debug effort
Sanity test on pi3
```
root@balena:~# find /usr/ | grep pppd
/usr/sbin/pppd
/usr/lib/pppd
/usr/lib/pppd/2.4.7
/usr/lib/pppd/2.4.7/nm-pppd-plugin.so
root@balena:~# 
```
--- …
> networkmanager: Fix a typo in a plugin path

- meta-balena-common/recipes-containers/balena/balena/balena.service
We need to allow user containers to do some clean-up if they wish to on
reboot / shutdown through systemctl so let's add KillMode set to process
so that systemd won't directly kill the user containers first.
For reference see also upstream moby:
https://github.com/moby/moby/pull/23636/commits/
db435f526ac5703276ad1add28188c0c8c6e4c2a
Changelog-entry: Do not send SIGKILL directly to user containers (set KillMode=process in balena.service)
--- …
> balena.service: Set systemd KillMode to process

- meta-balena-common/recipes-core/packagegroups/packagegroup-resin-connectivity.bb
- meta-balena-thud/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
- meta-balena-warrior/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
- meta-resin-pyro/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
- meta-resin-rocko/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
- meta-resin-sumo/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
This package adds to rootfs the regulatory database into /lib/firmware/regulatory.db which can be loaded by kernel versions >= v4.15
Changelog-entry: Add regulatory.db (Wireless Central Regulatory Domain Database) to rootfs so kernel versions >= v4.15 can load it
--- …
> packagegroup-resin-connectivity: Add wireless-regdb-static to rootfs

- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor
This commit removes the requirement of only running an image that has been
successfully pulled. If the specified image is available locally, let's
use it.
The process to run a local image would be:
* Create a tarball with "balena save"
* Load it locally with "balena load -i <tarball>"
* Tag it with "balena tag <image id> <repo>:<tag>
* Update resin-supervisor with:
```
update-resin-supervisor -i <repo> -i <tag>
```
This provides a way to perform local offline updates as requested in:
https://github.com/balena-os/meta-balena/pull/1827
Changelog-entry: Allow local resin-supervisor image updates
Changelog-type: patch
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are …
> update-resin-supervisor: Allow to run any image locally available

- meta-balena-common/recipes-containers/balena/balena_git.bb
which includes Roman's work to fix the layer leaking bugs
Also switch to 18.09-balena branch to prepare for the release of
balena-engine 19.03
Changelog-entry: Update balena-engine to 18.09.16
--- …
> Bump balena-engine to 18.09.16

- meta-balena-common/recipes-connectivity/networkmanager/resin-files/NetworkManager.conf.systemd
systemd requires executable paths to be absolute. This causes an error
in the system journal.
Signed-off-by: Sven Schwermer <sven.schwermer@disruptive-technologies.com>
---
> networkmanager: Use absolute path in drop-in

- meta-balena-common/recipes-containers/balena/balena/balena-host.service
Instruct the service to ignore the environment file if it does not exist.
This avoids the service failing if the file does not exist.
---
> balena-host: Ignore environment file if it does not exist

- meta-balena-common/recipes-support/resin-init/resin-init/resin-init
The power save has been switched from 'off' to 'on' in adf69fb
with no apparent motivation, we consider it an oversight
and the desired state is 'off'.
Changelog-entry: Turn off wlan0 power save
--- …
> resin-init: turn off wlan0 power save by default

- meta-balena-common/recipes-core/initrdscripts/files/rootfs
- meta-balena-common/recipes-core/systemd/systemd/resin_update_state_probe
From v2.49, the hostapp-update utility creates the /run directory in the
root filesystem, however when huping from previous versions /run is not there.
This commit switches to use /tmp to store the new UUID for the root partition on
first boot after generating new UUIDs.
Changelog-entry: Use /tmp as bootparam_root storage
--- …
> initrdscripts: Use /tmp as bootparam_root storage

- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.bb
- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor
Changelog-entry: update-resin-supervisor: short circuit if remote image cannot be fetched
HQ: https://github.com/balena-io/balena/issues/2108
Connects-to: #1869
--- …
> update-resin-supervisor: short circuit if remote image cannot be fetched

- meta-balena-common/recipes-connectivity/networkmanager/networkmanager/0001-wwan-Set-MTU-based-on-what-ModemManager-exposes.patch
- meta-balena-common/recipes-connectivity/networkmanager/networkmanager_%.bbappend
Changelog-entry: Backport NM patch for setting modem MTU correctly
---
> networkmanager: Set modem MTU correctly

- meta-balena-common/conf/distro/resin-systemd.conf
All logging is handled by journald so remove the logging features in
systemd.
Changelog-entry: Remove busybox-syslog to use only systemd's journald
--- …
> distro: resin-systemd: Remove dependency on busybox-syslog

- meta-balena-common/recipes-connectivity/networkmanager/networkmanager_%.bbappend
Include BPN in the generic bbappends extra path to avoid the
following warning:
WARNING: networkmanager_1.16.0.bb: Unable to get checksum for networkmanager SRC_URI entry 0001-wwan-Set-MTU-based-on-what-ModemManager-exposes.patch: file could not be found
Changelog-type: patch
--- …
> networkmanager: Remove build warning

- meta-balena-common/recipes-core/resin-extra-udev-rules/files/79-wlan-power.rules
- meta-balena-common/recipes-core/resin-extra-udev-rules/resin-extra-udev-rules.bb
- meta-balena-common/recipes-support/resin-init/resin-init/resin-init
resin-init has a hardcoded command to disable power management
on wlan0. This commit moves the logic to udev rule as there is
no guarantee wlan0 is the only or default wlan adapter in the system.
There seems to be no better way to identify a wlan device in udev
than KERNEL=="wl*" which should match both net.ifnames=0 (wlanX)
and net.ifnames=1 (wlpX).
Fixes #1422
Changelog-entry: Use udev for setting up wlan power management
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development …
> resin-init: Move wlan power management setup to udev rule

- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor
This makes sure the source path refers to an existing file/directory on
the host.
https://docs.docker.com/engine/reference/commandline/service_create/#differences-between---mount-and---volume
This avoids situations where --volume implicitely creates a directory (see #1748)
Fixes #1754
Changelog-entry: Use --mount instead of --volume for bind mounts to the supervisor container.
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, …
> resin-supervisor: Bind mount using --mount

- meta-balena-common/classes/kernel-resin.bbclass
At customer request we enable this driver.
Changelog-entry: Enable the Analog Devices AD5446 kernel driver
---
> kernel-resin.bbclass: Enable the Analog Devices AD5446 kernel driver

- meta-balena-common/recipes-containers/docker-disk/files/Dockerfile
- meta-balena-common/recipes-containers/docker-disk/files/entry.sh
The `docker` Docker Hub repository lists what versions of the image are supported and 18.6 is not among them at all. Use the current stable line of 18.09 instead, to stay on supported versions. See more info at: https://hub.docker.com/_/docker
Also add a required parameter to run images from 18.09.8-dind onwards, due to this change: https://github.com/docker-library/docker/pull/166
Update the test checking for docker being up, too.
Signed-off-by: Gergely Imreh <gergely@balena.io>
--- …
> docker-disk: Update to still supported dind container

- meta-balena-common/recipes-connectivity/openvpn/openvpn_%.bbappend
The dependency is introduced by the upstream.sh and downstream.sh scripts.
Bash is also a dependency not only for internal packages but for external
scripts too.
---
> openvpn: Add runtime dependency on bash

- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor
The change this commit reverts allowed to update with a locally
available image - but it also has the side effect of restarting the
supervisor even if no update is required and that has unintentional
consequences as https://github.com/balena-io/balena-supervisor/issues/1358
This commit reverts 646e4ae809375f4abf35c55cd580e2c62a8812e2
Changelog-entry: Revert allowing local resin-supervisor image updates
--- …
> update-resin-supervisor: Revert local resin-supervisor image updates

- meta-balena-common/recipes-core/chrony/files/chrony.conf
the `maxsources` directive is simply to maintain the current behavior of
resolving four servers for synchronization. as noted in chrony's docs:
> When a pool source is unreachable, marked as a falseticker, or has a distance larger than the limit set by the maxdistance directive, chronyd will try to replace the source with a newly resolved address from the pool.
Connects-to: #1852
Changelog-entry: Set chrony default servers as pools
--- …
> timesync: specify that default NTP options are pools

- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor
- meta-balena-common/recipes-support/resin-device-progress/resin-device-progress/resin-device-progress
- meta-balena-common/recipes-support/resin-device-register/resin-device-register/resin-device-register
Changelog-entry: Use UUID rather than ID when communicating with API
HQ: https://github.com/balena-io/balena-io/issues/2227
---
> use device UUID not ID where possible

- meta-balena-common/recipes-connectivity/resin-ntp-config/resin-ntp-config/resin-ntp-config
When the user supplies an additional NTP server source which is a pool URL the 'burst' command may fail. This occurs when the pool URL resolves to a different IP addresses for the 'add server' and 'burst' commands.
To avoid this issue we can combine the burst functionality into the 'add server' command by using the 'iburst' option. Although this option is not documented by the chronyc man page it has been present since v1.25 released in 2011.
This fix has been tested via the balenaOS (2.51.1+rev1) command line running on a RPi3.
Connects-to: #1903
---
- …
> resin-ntp-config: merge 'burst' command with 'add server' line

- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor
- meta-balena-common/recipes-support/resin-device-progress/resin-device-progress/resin-device-progress
HQ: https://github.com/balena-io/balena-io/issues/2227
Changelog-entry: Fix up UUID variable when communicating with API
---
> scripts: fix up UUID reference

- meta-balena-common/recipes-core/systemd/systemd/dev-zram0.swap
The default dependency:
Before=swap.target
Causes randomly appearing ordering cycles that leave the system in not
functioning states.
---
> systemd: Simplify zram swap unit dependencies to avoid ordering cycle

- meta-balena-common/classes/kernel-resin.bbclass
Kernel versions between 4.0 and 4.9 use
CONFIG_ZRAM_LZ4_COMPRESS, whereas newer ones
use CONFIG_CRYPTO_LZ4.
---
> Add LZ4 support config for older kernels

- meta-balena-common/recipes-support/resin-device-register/resin-device-register/resin-device-register
In order to get closer to formally requiring a target supervisor release
in the model, we should expand our provisioning process to provide the
initial supervisor_version metadata. This connects back to tri-app.
Depends-on: https://github.com/balena-io/open-balena-api/pull/394
HQ: https://github.com/balena-io/balena-io/pull/2177
--- …
> provisioning: provide base supervisor_version during provision

- meta-balena-common/recipes-core/busybox/busybox_%.bbappend
Otherwise, as util-linux has a higher default alternative priority, the
version in util-linux is chosen. It would seem they are exchangeable, but
the busybox version reportedly works even if the RTC interrupt line is not
connected.
Fixes #1936
Changelog-entry: Force choosing busybox-hwclock over util-linux-hwclock
--- …
> busybox: Force to use the busybox version of hwclock

- meta-balena-common/classes/kernel-resin.bbclass
We add support for aufs on kernels 5.x variants
Changelog-entry: Add support for aufs5 on kernel 5.x variants
---
> kernel-resin.bbclass: Add support for aufs5

- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc
Update balena-supervisor from 11.9.4 to 11.9.6
Backport-to: next
Signed-off-by: Rich Bayliss <rich@balena.io>
> balena-supervisor: Update to v11.9.6

- meta-balena-common/recipes-containers/balena/balena/balena-healthcheck-image-load.service
- meta-balena-common/recipes-containers/balena/balena/balena.service
- meta-balena-common/recipes-containers/balena/balena_git.bb
In rocko, systemd kills any script started in background,
same thing happening to children that get re-parented.
One solution is to use a separate service file for
starting the healtcheck image load script, after balena.service
was started.
This PR replaces https://github.com/balena-os/meta-balena/pull/1858 , which was older and open against the development branch.
Change that added the necessity of this PR is https://github.com/balena-os/meta-balena/commit/4ec47419b97cf5ca6fe15436a32348e1dc7b5d9d
As a difference from the old PR, added "Requires=balena.service".
The original healthcheck script already waits for the balena service to become active: https://github.com/balena-os/meta-balena/blob/master/meta-balena-common/recipes-containers/balena/balena/balena-healthcheck-image-load#L5 …
> Use separate service for loading healthcheck image

- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor
On commit a4ce26caadabcb1e87d944d78218cc32c579914e the supervisor moved
from using --volume to using --mount to avoid the implicit creation of
directories instead of files.
However, in the case where the mount referred to a directory, these have
to exist in the rootfs beforehand as --mount will not create them.
This commit checks for the existence of the /var/log/supervisor-log
directory and creates it if required.
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in …
> resin-supervisor: Create required directories before launch

- meta-balena-common/recipes-core/systemd/systemd/balena-os-sysctl.conf
The warrior branch does not backport this configuration
like the older branches do. Let's move this setting in the
balena-os-sysctl file to avoid issues where some device integration
layers set the rp_filter mode to strict and break connectivity.
One example of layer that sets this config to 1 is warrior meta-fsl-bsp-release.
Our sumo configuration includes this, but warrior doesn't: 
https://github.com/balena-os/meta-balena/blob/master/meta-resin-sumo/recipes-core/systemd/systemd/backport-6caa14f763c11630f28d587b3caa5f0e6dc96165.patch
--- …
> systemd: Set net.ipv4.conf.all.rp_filter in balena-os-sysctl

- meta-balena-common/recipes-support/resin-device-register/resin-device-register/resin-device-register
In b791055f3f6ffd6cc5796569a7321c5060129eea I attempted to have flasher
images report their preconfigured supervisor version without a good
understanding of how flasher images work. As it turns out no supervisor
information is maintained in the flasher image itself, so until that is
sorted stop reporting a blank string for the supervisor version.
---
- '*Comment*' if you …
> flasher-register: if no supervisor information found, report null

- meta-balena-common/recipes-support/balena-unique-key/balena-unique-key/balena-unique-key
Ensuring changes are flushed to the filesystem at this point
helps prevent config.json from becoming corrupt if power is cut.
---
> balena-unique-key: Ensure config.json is synced after replacing

- meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
We add this fw on its own package so that boards can add it to
rootfs (for Microsoft Surface Go 2 more specifically)
Changelog-entry: Package iwlwifi-cc-a0-48 firmware separately
--- …
> linux-firmware: Package iwlwifi-cc-a0-48 firmware

- meta-balena-common/recipes-devtools/kernel-modules-headers/files/gen_mod_headers
For the updated 5.4 kernel or RPI4 , kernel-headers-test fails with
arch/arm64/kernel/vdso/Makefile lib/vdso/Makefile No such file or directory
make[1] *** No rule to make target 'lib/vdso/Makefile'.  Stop.
make *** [vdso_prepare] Error 2
when doing modules_pepare in the docker build
This patch adds /lib/vdso/Makefile to kernel-modules-headers
compressed archive
Changelog-entry: Pack /lib/vdso/Makefile in kernel-modules-headers
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>
--- …
> kernel-modules-headers: Pack /lib/vdso/Makefile

- meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-logging
This is where the logs and error messages should go by default
as they are not part of the tool's output.
---
> os-helpers-logging: Log to stderr rather than stdout

- meta-balena-common/recipes-support/ca-certificates/ca-certificates/extract-balena-ca
- meta-balena-common/recipes-support/ca-certificates/ca-certificates/extract-balena-ca.service
- meta-balena-common/recipes-support/ca-certificates/ca-certificates_%.bbappend
- meta-balena-common/recipes-support/resin-mounts/resin-mounts.inc
We allow the user to specify a custom CA in the .balenaRootCA key
of config.json but at this moment this is only respected by
the supervisor. This commit adds it to the system-wide CA bundle
so that the CA is respected everywhere.
Fixes #1398
--- …
> Respect balenaRootCA system-wide

- meta-balena-common/recipes-core/initrdscripts/files/fsuuidsinit
If the rootfs is on a slow-to-bring-up device (e.g. RPi4 + USB)
the fsuuidsinit_enabled() function may return before the balena symlinks
are created. This gets wrongly interpreted as missing UUIDs leading to
a chain of failures in the subsequent scripts.
This patch moves the symlink waiting loop from fsuuidsinit_run()
to fsuuids_enabled() before the first usage of the symlink.
Changelog-Entry: Wait for the root device to come up when necessary
--- …
> initrdscripts: Wait for root device to come up in fsuuid script

- meta-balena-common/recipes-support/hostapp-update-hooks/files/0-bootfiles
The hostapp update process should not overwrite the supervisor configuration
backend files to avoid the supervisor being forced to set the target state
after HUP and reboot the device during the rollback period.
This only applies to the host configuration files which are the only ones
that force a reboot.
Connects-to: https://github.com/balena-io/balena-supervisor/issues/1464
Changelog-entry: Blacklist supervisor configuration backend files during HUP
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes …
> hostapp-update-hooks: Blacklist supervisor configuration backends

- meta-balena-common/recipes-containers/docker-disk/docker-disk.bb
- meta-balena-common/recipes-containers/docker-disk/files/entry.sh
Switch to 4k block size for the resin-data filesystem
so it can be expanded to sizes greater than 1023GiB.
Usage type set to 'default' to allow for the fs to
be optimized for expanding to sizes greater than 512MB.
See: https://github.com/tytso/e2fsprogs/issues/50
Changelog-entry: docker-disk: Allow expanding data filesystem on 2TB disks
Tested on Pi4
Addresses: https://github.com/balena-os/meta-balena/issues/1977#issuecomment-669119901
--- …
> docker-disk: Allow expanding data filesystem on 2TB disks

- meta-balena-common/recipes-core/chrony/files/chronyd.conf.systemd
- meta-balena-common/recipes-core/systemd/timeinit.bb
- meta-balena-common/recipes-core/systemd/timeinit/fake-hwclock
- meta-balena-common/recipes-core/systemd/timeinit/fake-hwclock-update.service
- meta-balena-common/recipes-core/systemd/timeinit/fake-hwclock-update.timer
- meta-balena-common/recipes-core/systemd/timeinit/fake-hwclock.service
- meta-balena-common/recipes-core/systemd/timeinit/time-set.target
- meta-balena-common/recipes-core/systemd/timeinit/time-sync.conf
- meta-balena-common/recipes-core/systemd/timeinit/timeinit-buildtime.service
- meta-balena-common/recipes-core/systemd/timeinit/timeinit-buildtime.sh
- meta-balena-common/recipes-support/resin-mounts/resin-mounts.inc
In order to produce sensible timestamps for journald log messages:
a) the system time needs to be maintained correctly over a reboot, and
b) the system time needs to be set before journald is started.
Currently the system time is maintained over reboots on systems without an RTC using the last modified time of the chrony drift file. However there are a couple of issues with this approach:
a) /var/lib/chrony/ is not mounted early enough in the boot process to be available for setting the time before journald is started.
b) there is an issue with the current systemd dependencies that result in the last modified time of the drift file not being updated when the system is shutdown or rebooted (see #1995).
The Debian fake-hwclock service (as used by Raspberry Pi OS) has been added to overcome …
> systemd/timeinit: add fake.hwclock to maintain system time over reboots

- meta-balena-common/recipes-core/chrony/files/chrony.conf
By default chrony uses a random UDP source port for each NTP request. This can cause problems with particular routers/firewalls (issues have been reported for the Phicomm KE 2P).
The chrony `acquisitionport` configuration setting has been added to the chrony.conf file to change the UDP source port for NTP requests to 123 (this is the same as the default source port used by both ntpdate and ntpd).
Tested on a RPi3 using balenaOS 2.58.6+rev4.
Connects-to: #2000
--- …
> chrony: set the source UDP port for NTP requests to 123

- meta-balena-common/classes/kernel-resin.bbclass
This is needed to make use of eBPF and all the debugging and extra
features it brings.
Changelog-entry: Enable kernel user space probes support
---
> kernel-resin: Configure uprobes support by default

- meta-balena-common/recipes-core/os-config/os-config.inc
- meta-balena-common/recipes-core/os-config/os-config/os-config.timer
> os-config: Add systemd timer to run once a day

- meta-balena-common/recipes-connectivity/modemmanager/balena-files/77-mm-u-blox-modeswitch.rules
- meta-balena-common/recipes-connectivity/modemmanager/balena-files/u-blox-switch.sh
- meta-balena-common/recipes-connectivity/modemmanager/balena-files/u-blox-switch@.service
- meta-balena-common/recipes-connectivity/modemmanager/modemmanager_%.bbappend
Add the u-blox-modeswitch scripts to modemmanager. The scripts are generic and therefore it makes sense to provide them as part of meta-balena instead of balena-raspberrypi.
Connects-to: #1789
Connects-to: #510 (in balena-raspberrypi)
--- …
> modemmanager: add u-blox-modeswitch scripts

- meta-balena-common/recipes-core/systemd/timeinit.bb
- meta-balena-common/recipes-core/systemd/timeinit/fake-hwclock.service
- meta-balena-common/recipes-core/systemd/timeinit/timeinit-buildtime.service
- meta-balena-common/recipes-core/systemd/timeinit/timeinit-buildtime.sh
- meta-balena-common/recipes-core/systemd/timeinit/timeinit-rtc.service
- meta-balena-common/recipes-core/systemd/timeinit/timeinit-rtc.sh
- meta-balena-common/recipes-support/os-helpers/os-helpers.bb
- meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-time
The handling of the RTC at boot time has been improved as follows:
1) A 'timeinit-rtc.sh' script has been added to improve logging of system time updates from the RTC and to prevent system time being set when RTC time is behind system time. If RTC time is found to be behind system time a warning is issued regarding potential RTC battery failure.
2) The 'timeinit-rtc.service' has been added to the new systemd 'time-set.target'. This allows for better control and co-ordination between the various time source services.
3) Systemd dependencies have been updated to ensure that the RTC is the final time service before the 'time-set.target' is reached.
Some support functions for system date/time handling have been added via the 'os-helpers-time' script. The 'timeinit-buildtime.sh' script has …
> systemd/timeinit: improve RTC handling at boot

- meta-balena-common/recipes-core/chrony/files/chrony.conf
Change the chrony UDP source port from 123 (privileged) to 1234 (non-privileged).
Previous issues with Phicomm routers had required the use of a fixed UDP source port, so port 123 was chosen as this is used by both ntpd and ntpdate. However recent testing has shown that using a privileged port such as 123 can cause issues on other networks. By changing the port to be non-privileged (i.e. 1234) we can satisfy both network requirements.
Connects-to: #2000
Changelog-entry: chrony: use a non-privileged UDP source port
---
- '*Request Changes*' if this change …
> chrony: use a non-privileged UDP source port

- meta-balena-common/recipes-core/systemd/systemd/zram-swap-init
Adjust zram to lesser of 50% or 4GB, inline with defaults used by Fedora.
Related issue: https://github.com/balena-os/meta-balena/issues/2056
---
> zram-swap-init: adjust default to lesser of 50%/4GB

- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor
Ensure that the /var/log/supervisor-log directory exists prior to running 'balena start --attach resin_supervisor' as well as 'runSupervisor'.
Updates to the 'start-resin-supervisor' script in v2.62.1 removed the check for updates to the REGISTRY_ENDPOINT variable. Previously this had been detected as changing every time the script was run due to a comparison between 'null' and ''. This resulted in the 'start-resin-supervisor' script always running through the 'runSupervisor' path. With this variable check removed, and no config updates being detected, the script was trying to run 'balena start --attach resin_supervisor' and failing due to the absence of the /var/log/supervisor-log directory. To fix this problem we unconditionally test for and create this directory (if necessary) so that …
> start-resin-supervisor: fix directory creation for 'balena start'

- meta-balena-common/recipes-containers/mobynit/mobynit_1.0.bb
- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/resin-data.mount
- meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor
- meta-balena-common/recipes-support/hostapp-update-hooks/files/75-supervisor-db/75-forward_supervisor-db
- meta-balena-common/recipes-support/hostapp-update-hooks/files/75-supervisor-db/75-fwd_commit_supervisor-db
- meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb
Correct the mount point for the resin-data directory.
Fixes https://github.com/balena-os/meta-balena/issues/2070
---
> Correctly mount data partition

- meta-balena-common/classes/kernel-resin.bbclass
Add IPV6 multicast routing capability to the default configuration.
Fixes #2051
Changelog-entry: Add IPV6 multicast routing capability
---
> kernel-resin: Add IPV6 multicast routing capabilities
