balena-os/meta-balena

meta-balena-common/recipes-core/chrony/chrony_4.0.bb
meta-balena-common/recipes-core/chrony/files/0001-Fix-compilation-with-musl.patch
meta-balena-common/recipes-core/chrony/files/arm_eabi.patch
meta-balena-common/recipes-core/chrony/files/chronyd

Update chrony from version 3.4 to version 4.0.
The new version has enhancements and new features that will help to improve time synchronisation, including:
- the ability to add server pools via scripts using chronyc.
- support for dynamic NTP source files that can be reloaded as necessary (useful for DHCP and config.json sources).
- source name options for improved handling of pool addresses.
- repeat 'iburst' when a source is changed from offline to online state.
Tested on a Raspberry Pi 4.
Changelog-entry: chrony: bump to version 4.0
---
- '*Request …

chrony: bump to version 4.0

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor

Node has a built-in CA bundle and ignores the system-wide bundle.
---

start-resin-supervisor: populate NODE_EXTRA_CA_CERTS when custom CA is defined

---

meta-balena-common/recipes-support/resin-device-register/resin-device-register/resin-device-register

Starting with dee971c0dbeb6e8363f3e321af582e99627626e9, flasher
images, which don't contain a supervisor version, try to register
in the API using the parameter supervisor_version='null'.
However, the API expects this parameter to be unset completely if
there's no version to be reported during registration, otherwise
the call fails and the device doesn't show up in dashboard during
flashing or report the post-provisioning state.
Change-type: Patch
Root cause discussed internally in https://www.flowdock.com/app/rulemotion/resin-devices/threads/EcpplGAu7uIsW87UZYSpMU88qR2
Fixes https://github.com/balena-os/meta-balena/issues/2082
Tested on BeagleboneBlack, TX2 and Nano SD-card
---
- '*Approve*' …

resin-device-register: Fix post provisioning state not reported

---

meta-balena-common/recipes-connectivity/ppp/ppp_%.bbappend

Fixes #1846
UART modems (RaspberryPi HATs) are not working currently under
balenaOS as NetworkManager times out while attempting to establish
ppp connection. This is not a balenaOS specific issue.
This commits adds a `connect ""` declaration to `/etc/ppp/options`
to workaround this as the NULL default value causes the timeout.
The connect option specifies an external script to establish the
physical link. When using NetworkManager/ModemManager it is
ModemManager that establishes the physical link before passing it
to NetworkManager. Thus `connect` should be empty.
Changelog-entry: Fix pppd timeout when launched by NetworkManager
---
- '*Approve*' if this change would be acceptable …

ppp: Fix timeout when launched by NetworkManager

---

meta-balena-common/recipes-kernel/linux/files/Dockerfile

Some makefiles for the kernel modules build, like for
instance the one in the kernel for the lec-px30 machine,
want python to be available in the environment. Let's add
it to the build dependencies.
Change-type: Patch
Tested on the lec-px30 yocto build.
--- …

kernel-headers-test: Install python dependency

---

meta-balena-common/recipes-containers/balena/balena_git.bb
meta-balena-dunfell/recipes-extended/procps/procps/sysctl.conf
meta-balena-dunfell/recipes-extended/procps/procps_3.3.16.bb
meta-balena-thud/recipes-extended/procps/procps/sysctl.conf
meta-balena-thud/recipes-extended/procps/procps_3.3.16.bb
meta-balena-warrior/recipes-extended/procps/procps/sysctl.conf
meta-balena-warrior/recipes-extended/procps/procps_3.3.16.bb
meta-resin-pyro/recipes-extended/procps/procps/sysctl.conf
meta-resin-pyro/recipes-extended/procps/procps_3.3.16.bb
meta-resin-rocko/recipes-extended/procps/procps/sysctl.conf
meta-resin-rocko/recipes-extended/procps/procps_3.3.16.bb
meta-resin-sumo/recipes-extended/procps/procps/sysctl.conf
meta-resin-sumo/recipes-extended/procps/procps_3.3.16.bb

Replace busybox ps link with ps.procps without installing
any other procps packages. This will avoid regression and bloat
from swapping existing busybox links with procps variants.
By using procps as docker expects we can properly handle ps args
such as -e and -o to format output. Busybox is only capable of this
when compiled in "desktop" mode.
This upstream commit to poky has already split the ps binary into
a separate procps package:
https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=507a47a4e5077d5f8f76d9629be6b871dfd8eb90
So for now we can copy this recipe at the commit above into compat branches
and use that version until we pick up a branch newer than gatesgarth.
Connects-to: https://github.com/balena-os/balena-engine/issues/236
Changelog-entry: replace …

procps: use procps recipe from upstream poky master

---

meta-balena-common/classes/balena-linux-firmware.bbclass

We need to make sure the firmware cleanup function runs before
do_populate_sysroot otherwise do_populate_sysroot will race with it and
will fail complaining about the missing firmware that
iwlwifi_firmware_clean had just deleted at the same time.
Changelog-entry: Fix task ordering for the iwlwifi_firmware_clean task
--- …

classes:balena-linux-firmware: Fix fw cleanup task ordering

---

meta-balena-common/recipes-core/systemd/timeinit/fake-hwclock.service
meta-balena-common/recipes-support/resin-mounts/resin-mounts.bb
meta-balena-common/recipes-support/resin-mounts/resin-mounts.inc
meta-balena-common/recipes-support/resin-mounts/resin-mounts/etc-fake-hwclock.mount

Replace the 'bind-etc-fake-hwclock.service' with a systemd mount unit (etc-fake\x2dhwclock.mount).
Using a systemd service to bind mount the /etc/fake-hwclock directory results in systemd generating an internal mount unit for the same directory. This causes problems at shutdown when both methods try to unmount the directory. This frequently leads to the directory being unmounted before the fake-hwclock service has managed to save the system time. This results in an inaccurate fake-hwclock time at next boot and corruption of the journal log.
Testing on a RPi3 shows that the original problem occurs on average every 2-3 boots. With this fix deployed no errors were observed after an overnight test of 563 consecutive reboots.
Connects-to: #1919 #2107
Changelog-entry: …

systemd/timeinit: use systemd mount unit for /etc/fake-hwclock

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

Update the codeowners list so that all OS team members are default reviewers. This should speed up the PR approvals.
Also, include test coverage details as part of the PR. For external contributions this can be just  a manual test case described in the comments or PR body.

Update codeowners and test coverage details

---

meta-balena-common/recipes-bsp/grub/grub-efi_%.bbappend
meta-balena-common/recipes-bsp/grub/grub_%.bbappend

GRUB builds modules with both debug and release variants, with *.module
and *.mod extensions respectively.
Install only the release modules in do_deploy() to avoid balooning the
size of the boot partition.
--- …

recipes-bsp: grub: install only release modules

---

meta-balena-common/recipes-containers/balena/balena/balena-healthcheck-image-load
meta-balena-common/recipes-containers/balena/balena/balena-healthcheck-image-load.service

This prevents issues with the health check when the image is manually
removed.
Connects-to: https://github.com/balena-os/meta-balena/issues/2010

balena: Make the healthcheck loading service part of balena.service

---

meta-balena-common/recipes-core/initrdscripts/files/rootfs

If the device with flasher rootfs is slow to bring up and rootfs is defined
as UUID=xxx the waiting loop in rootfs initrd script would assume UUIDs have
just been regenerated and wait for a by-state symlink instead. This only works
for the OS - flasher does not use the dynamically generated UUIDs
therefore we always want to use the by-uuid link for it.
---
- '*Comment*' if you …

initrdscripts: always use by-uuid symlink looking for flasher rootfs

---

meta-balena-common/recipes-bsp/grub/grub-efi_%.bbappend
meta-balena-common/recipes-bsp/grub/grub_%.bbappend

grub-efi requires modules to be installed in the boot partition, and
resin-image installs them from `${DEPLOYDIR}`.
A normal grub installation installs those modules to `${PREFIX}/${libdir}`
to allow grub tooling to install them at runtime, but we're building the
image with GRUB baked in, so we don't need those in the sysroot.
The first iteration of this bbappend attempted to solve these
constraints by copying the modules from `${D}/${libdir}/grub/` to
`${DEPLOYDIR}` in `do_deploy()`, then removing `${D}${prefix}`. This had the
unfortunate side effect of breaking the build in certain cases, such as
clean builds or reexecuting `do_deploy()` without the other steps of the
build.
Instead, remove the unwanted files in `do_install()`, and append the
required modules to GRUB_BUILDIN to create a …

grub-efi: build required modules into grub image

---

meta-balena-common/classes/kernel-resin.bbclass

Allow installing and patching aufs even if BALENA_STORAGE is overlay2
Changelog-entry: Apply aufs patches if aufs is present in kernel config
---

kernel-resin: Apply aufs patches if aufs is present in kernel config

---

meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update

Symlinks to /boot and /sbin/init are absolute, which breaks them when
the sysroot is mounted under another system.
Convert them to relative links, so they work in all cases.
--- …

hostapp-update: convert absolute symlinks to relative

---

README.md

Quick fix on the README, removed link to the official Raspberry Pi WiFi dongle since it's now been discontinued.
This is required to remove it from the docs in this page: https://www.balena.io/docs/reference/hardware/wifi-dongles/
Related docs release party PR: https://github.com/balena-io/docs/pull/1672
Signed-off-by: Tomás Migone <tomas@balena.io>

wifi: remove listed example as it's discontinued

---

README.md

- Adding more context to persistent logging definition so that it shows up in docs
Related: https://github.com/balena-io/docs/issues/597
Signed-off-by: Andrew Nhem <andrew@balena.io>

Add to persistent logging defn

---

meta-balena-common/recipes-core/systemd/systemd/60-resin-update-state.rules
tests/suites/os/suite.js
tests/suites/os/tests/udev.js

At this moment `resin_update_state_probe` is scanning pretty much every block device for rootfs. This include ramdisks, zram and loop devices which, when scanned, even spam warnings in logs. This patch updates the udev rule to skip such devices and only trigger on add or change events.
We are also suspecting this rule may be causing performance issues during first boot but after looking deeper I am not sure this is the case.
---
- '*Comment*' …

udev: Silence warnings from resin_update_state_probe

---

meta-balena-common/recipes-support/resin-mounts/resin-mounts/etc-fake-hwclock.mount

Added a dependency on resin-state.service and resin-state-reset.service to etc-fake-hwclock.mount.
On initial boot after flashing a device the resin-state-reset.service was running after etc-fake-hwclock.mount causing the bind mount point /mnt/state/root-overlay/etc/fake-hwclock to be deleted after it had been mounted. This resulted in a failure to save the date/time at shutdown which caused problems with persistent logging at next boot. Subsequent boots are unaffected as resin-state-reset does not run. Adding a dependency on the resin-state services ensures that the bind mount point is created after the state reset has been performed.
This issue was noticed when running the testbot unmanaged OS image persistent logging test. When running a managed OS image the device normally reboots …

resin-mounts/etc-fake-hwclock: add dependency on resin-state services

---

repo.yml

The balena-supervisor repository has been moved to balena-os so the
repo.yml file needs to be corrected for nested changelogs to work again.
---

repo.yml: Move balena-supervisor reference to balena-os

---

meta-balena-common/recipes-support/resin-device-progress/resin-device-progress/resin-device-progress

this script is only used during provisioning and HUP. in provisioning we `|| true` anyway, and
in HUP we would like to use the exit code for retrying
--- …

device-progress: do not force an exit code

---

meta-balena-common/recipes-containers/balena/balena_git.bb

This brings in the aufs-to-overlay migrator. Which won't run until we
configure the engine service to include an `BALENA_MIGRATE_OVERLAY=1`
env var.
The other notable change is the fix for
https://github.com/balena-os/balena-engine/issues/236 which allows
`balena top` to work as expected on balenaOS

balena-engine: Update to 19.03.18

---

meta-balena-common/classes/kernel-resin.bbclass

This is needed in preparation for storage migration.
When running hostapp-update, we need to create the target hostapp on
overlayfs, which implies the OS we update from can support both drivers

kernel: Always include overlayfs support

---

meta-balena-common/recipes-core/os-config/os-config_1.2.1.bb

Includes rename of resin-supervisor to balena-supervisor.
Connects-to: https://github.com/balena-os/meta-balena/pull/2171
---

Update os-config from v1.2.0 to v1.2.1

---

tests/suites/os/suite.js
tests/suites/os/tests/device-tree/dtoverlay.sh
tests/suites/os/tests/device-tree/dtparam.sh
tests/suites/os/tests/device-tree/index.js

Device tree tests are meant to check if DToverlays and DTparams are being applied accurately on unmanaged OS. I have made some minor indentation changes as well to other tests.
I am keeping device-tree tests at the top of the suite.js to hack Jenkins and get the test being added in this PR implemented and run first. I would also like to test if having this new test doesn't affect other tests in the queue.
In the final change, I do want device-tree tests to be at the bottom. So don't merge before that happens, will make the change. Once we get the first run going.

Add device tree test to unmanaged suite

---

meta-balena-common/conf/distro/include/balena-os.inc

With Go 1.16 a precompiled go-binary-native that provides go-native was
introduced to bootstrap the Go compilation.
Specify to use the go-native recipe and not go-binary-native when
requiring go-native.
--- …

balena-os: Add preferred provider for Go native

---

tests/suites/os/suite.js
tests/suites/os/tests/boot-splash/index.js

This PR adds an equivalent test for testlodge TC96.
The test contains a reference image of the balena boot-splash screen. During the test, the DUT is rebooted, and the HDMI output of the DUT is captured, and compared to this reference image. If the boot-splash is detected on the HDMI output o the DUT, the test will pass. All captured frames are archived and sent back to jenkins at the end of the test.
--- …

Add boot-splash test to unmanaged suite

---

meta-balena-common/classes/kernel-resin.bbclass

Some BSPs have enabled CONFIG_BOOTPARAM_HUNG_TASK_PANIC which
can trigger panics upon high iowait, such as balena-engine
downloading/writing a large image to disk.
Kconfig says the following:
Say Y here to enable the kernel to panic on "hung tasks",
which are bugs that cause the kernel to leave a task stuck
in uninterruptible "D" state.
The panic can be used in combination with panic_timeout,
to cause the system to reboot automatically after a
hung task has been detected. This feature is useful for
high-availability systems that have uptime guarantees and
where a hung tasks must be resolved ASAP.
Say N if unsure.
Hung tasks are not normally terminal, nor do they affect system
stability, but panicking during an image write forces a device into a
bootloop that requires manual intervention …

kernel-resin: disable panic on hung task

---

meta-balena-common/recipes-core/systemd/systemd/dev-zram0.swap
meta-balena-common/recipes-support/resin-mounts/resin-mounts/mnt-sysroot-inactive.automount
meta-balena-common/recipes-support/resin-mounts/resin-mounts/mnt-sysroot-inactive.mount

* skip setting up zram swap
* dont' attempt to mount inactive partition

Skip some services when running under docker

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.bb
meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/balena-supervisor.service
meta-balena-common/recipes-support/hostapp-update-hooks/files/65-migrate-supervisor-state
meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb

Resolves: https://github.com/balena-os/meta-balena/issues/2201, https://github.com/balena-os/balenahup/issues/347
**Manual test case**
1. Provision a Pi4 to 2.75.0+rev1
2. Perform HUP with hostapp-update script to a release from this PR
3. After booting in the new OS check if supervisor is running and check journal logs
**Automated test case**
HUP test cases are WIP here: https://github.com/balena-os/meta-balena/pull/2174
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder …

supervisor: Migrate from legacy namespace during updates

---

meta-balena-common/recipes-connectivity/bluez5/files/main.conf

This reverts to the behavior before bluez v5.56 as it interferes with user defined
Device Information profiles.
For more information: https://github.com/bluez/bluez/issues/101
--- …

bluez5: Disable PnP Device Information service

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor

This is a rebase of [PR 2180](https://github.com/balena-os/meta-balena/pull/2180) by Miguel, which improves stability for the
supervisor update.
Currently, the SV does not get updated when HUP-ing a Pi4 from 2.41 to v2.80.0. @20k-ultra looked into this and determined that what is happening is this issue: https://github.com/balena-os/meta-balena/issues/2179 and it should be fixed by https://github.com/balena-os/meta-balena/pull/2180 , which we rebase in this PR.
Internal discussion: https://www.flowdock.com/app/rulemotion/r-supervisor/threads/O8fifLL0sgPfQY5WDOezv3Ime4u
---
- '*Approve*' if this change would be acceptable in …

update-balena-supervisor: Refactor script to ensure target version is ran

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor

…name
There are better ways of getting the supervisor
configuration directory name, let's switch to
them to improve robustness.
---

update-balena-supervisor: Improve obtaining the supervisor directory

---

tests/suites/os/suite.js

This is to prevent situations such as this: https://jenkins.dev.resin.io/job/leviathan-raspberry-pi/852/console
where for some reason the unpacked image didn't exist (probably due to an earlier failure), and when attempting to remove it there is an error and the suite hangs and doesn't exit. This patch simply checks the path exists before trying to remove it
---
- '*Comment*' if you …

prevent failed teardown from making test suite hang

---

meta-balena-common/recipes-containers/balena/balena/balena-host.service
meta-balena-common/recipes-containers/balena/balena/balena.conf.systemd
meta-balena-common/recipes-containers/balena/balena/balena.service

This makes it easier to overwrite the arguments passed in the engine
unit from drop-in overwrites. See the development image drop-in unit for
reference.

balena-engine: refactor systemd service

---

meta-balena-common/recipes-connectivity/balena-net-connectivity-wait/balena-net-connectivity-wait.bb
meta-balena-common/recipes-connectivity/balena-net-connectivity-wait/balena-net-connectivity-wait/balena-net-connectivity-wait
meta-balena-common/recipes-connectivity/balena-net-connectivity-wait/balena-net-connectivity-wait/balena-net-connectivity-wait.service
meta-balena-common/recipes-connectivity/balena-net-connectivity-wait/balena-net-connectivity-wait/balena-net-connectivity-wait.target
meta-balena-common/recipes-core/packagegroups/packagegroup-balena-connectivity.bb

Add a new systemd service to check for full network connectivity. This service is required because the default NetworkManager (NM) connectivity checker doesn't differentiate between the CONNECTED_LOCAL, CONNECTED_SITE and CONNECTED_GLOBAL states. This service checks for the CONNECTED_GLOBAL state only and can be used to delay the start of other services which require full network access to be available. This can help to avoid startup problems on networks with slow DNS access or that utilise a captive portal.
The script does an initial oneshot check of the NM state to make sure that we don't wait for an event that doesn't come. This check is redundant at boot time due to the fact that the service is started before NM to ensure that no NM DBus events are missed. The initial check is useful …

recipes-core: add a 'network connectivity wait' service

---

tests/config.js
tests/suites/.editorconfig
tests/suites/.eslintrc.json
tests/suites/.prettierrc
tests/suites/Dockerfile
tests/suites/Makefile
tests/suites/config.js
tests/suites/hup/README.md
tests/suites/hup/conf.js
tests/suites/hup/package.json
tests/suites/hup/suite.js
tests/suites/hup/tests/smoke.js
tests/suites/package-lock.json
tests/suites/package.json

There is an overview over what this is doing here https://github.com/balena-os/meta-balena/blob/rgz/hup-tests/tests/suites/hup/README.md
This depends on:

tests: Add a suite for checking HUPs

---

meta-balena-common/recipes-kernel/linux/files/Dockerfile

Since we don't have devices using older 3.x kernels we update to a newer
base image so that we don't have problems compiling this test kernel
module on newer kernels. This avoids the following error on kernel
5.10.31 on arm64 raspberrypicm4-ioboard for example:
ERROR: modpost: "_mcount"
[/usr/src/app/example_module_headers_src/hello.ko] undefined!
Changelog-entry:
---
- …

kernel-headers-test: Update base image to buster

---

meta-balena-common/recipes-connectivity/balena-net-config/balena-net-config/balena-net-config.service
meta-balena-common/recipes-connectivity/balena-ntp-config/balena-ntp-config/balena-ntp-config.service
meta-balena-common/recipes-connectivity/dnsmasq/balena-files/dnsmasq.conf.systemd
meta-balena-common/recipes-connectivity/openvpn/files/prepare-openvpn.service
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars.bb
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/balena-config-vars
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/config-json.service
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/config-json.target

Create a target that different services can be `PartOf` that will get restarted on `config.json` change.
Add `dnsmasq` to this list of services to resolve https://github.com/balena-os/meta-balena/issues/2235.
This PR also avoids a dnsmasq error when `dnsServers="null"` in config.json
that was accidentally removed in https://github.com/balena-os/meta-balena/pull/2168.
---
1. Apply custom servers via `config.json` https://www.balena.io/docs/reference/OS/configuration/#dnsservers
2. Confirm `dnsmasq` has restarted and is active with new servers
```bash
jq '.dnsServers = "1.2.3.4"' /mnt/boot/config.json > /mnt/data/config.json && mv /mnt/data/config.json /mnt/boot/config.json
systemctl status dnsmasq.service config-json.*
jq …
```

Restart services when config.json changes

---

meta-balena-common/recipes-containers/balena/balena_git.bb

Update balena-engine from 19.03.18 to 19.03.23
Which brings more resilient layer download (allows proper resuming after
network failures).
Signed-off-by: Leandro Motta Barros <leandro@balena.io>
Changelog-entry: Update balena-engine to v19.03.23
--- …

balena-engine: Update to 19.03.23

---

meta-balena-dunfell/recipes-kernel/linux/kernel-devsrc.bb

In recent kernels (i.e. 5.10.31 for Raspberry Pi) the
arch/arm/kernel/module.lds file got moved. See
https://github.com/torvalds/linux/commit/
596b0474d3d9b1242eab713f84d8873f9887d980 for details.
Hence we use in meta-balena-dunfell the upstream kernel-devsrc from the
hardknott-3.3.1 Poky release which handles this module.lds move.
--- …

kernel-devsrc: Add upstream recipe from hardknott-3.3.1 for dunfell

---

tests/suites/Makefile
tests/suites/config.js
tests/suites/hup/suite.js
tests/suites/hup/tests/smoke.js
tests/suites/os/suite.js
tests/suites/os/tests/bluetooth/index.js
tests/suites/os/tests/boot-splash/index.js
tests/suites/os/tests/chrony/index.js
tests/suites/os/tests/config-json/index.js
tests/suites/os/tests/connectivity/index.js
tests/suites/os/tests/device-tree/index.js
tests/suites/os/tests/engine-healthcheck/index.js
tests/suites/os/tests/fingerprint/index.js
tests/suites/os/tests/healthcheck/index.js
tests/suites/os/tests/kernel-overlap/index.js
tests/suites/os/tests/led/index.js
tests/suites/os/tests/os-release/index.js
tests/suites/os/tests/udev/index.js
tests/suites/os/tests/variables/index.js
tests/suites/package.json

- As the image being unzipped into a temporary directory which is automatically cleaned up in the test. There is no need to delete the image inside the suite teardown https://github.com/balena-os/leviathan/pull/433/
- The fetch() function has had its arguments removed as they were redundant, so we can remove those arguments in suite.js including the downloadType property from config.js  https://github.com/balena-os/leviathan/pull/433/
- With the introduction of new helpers, we can replace old code with helpful new helpers https://github.com/balena-os/leviathan/pull/439
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that …

patch: Make OS test suite compatible with current helpers

---

meta-balena-common/recipes-bsp/grub/grub_%.bbappend

These utilities aren't used on device. Don't install them to save space.
---

common: grub: don't install sbin utils

---

tests/suites/hup/tests/rollback-health.js

Triggered by a failue in the VPN test - the bash binary is bigger than the openvpn binary and on devices with limitted rootfs space the copying is not possible. Symlinking /dev/null will break the services as well.
--- …

tests: Symlink /dev/null instead of copying bash to break services

---

meta-balena-common/classes/kernel-resin.bbclass
meta-balena-common/recipes-core/images/balena-image-initramfs.bb
meta-balena-common/recipes-core/packagegroups/packagegroup-resin.inc

Tested and working with
- VM + two SATA drives
- NUC + one NVME & one SATA drive (intentionally)
- RPi4 + two USB drives
RPi4 + USB drive & SD card is somewhat unstable (freezes at a random point), at this point not clear why.
No flashing procedure so far, one needs to manually create an MD RAID1 device (metadata 0.90 - the partitions must be visible to GRUB/u-boot) and flash the image to it.
--- …

Add support for rootfs on MD RAID1

---

meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_%.bbappend

Package Intel graphics firmware generations separately, allowing GPU
firmware to be installed for specific SoCs.
---

linux-firmware: package i915 generations separately

---

meta-balena-common/classes/resin-u-boot.bbclass

There is at least a case in a board where the puts function in u-boot's
common/console.c is #ifdef'ed and defined twice. Let's accomodate for
such cases by correctly looping through more than one function
definition if present.
--- …

resin-u-boot.bbclass: Make console silencing change more resilient

---

meta-balena-common/recipes-bsp/grub/grub_%.bbappend

Remove ${bindir} from FILES_grub-common, ensuring grub utilities aren't
installed to /usr/bin, in addition to a previous similar commit that
removed sbin utils. This frees approximately 5.5M.
--- …

grub: don't package or install bindir utils

---

meta-balena-common/recipes-connectivity/networkmanager/balena-files/99onoffline_ntp

Change the NetworkManager NTP dispatcher script to update the on/offline status of the NTP sources on `connectivity-change` events instead of up/down events.
Currently `chronyc onoffline` is run for 'up/down' events on any network interface. It makes more sense to run it for
`connectivity-change` events as we are really interested in whether the internet is there or not rather than whether an interface is up or down.
Changelog-entry: recipes-connectivity: improve NTP dispatcher script
--
Tested on a RPi3 under balenaOS v2.82.10+rev2 by manually connecting and disconnecting both WiFi and Ethernet connections.
---
- '*Approve*' if this change would be acceptable in the codebase (even if …

recipes-connectivity: improve NTP dispatcher script

---

meta-balena-common/recipes-devtools/kernel-modules-headers/files/gen_mod_headers

Since kernel v5.10 this file is generated when using modules-prepare. As
the kernel-modules-headers container pre-built target binaries, we also
need to include this file in the package.
This is not a problem when using kernel-source as a modules-prepare is
always required.
Fixes: #2289
Relates-to: #1822
--- …

kernel-modules-headers: Copy module.lds

---

meta-balena-common/recipes-containers/balena/balena/balena-healthcheck

This avoids confusion when new containers with random names
appear in the runtime history of the engine.
Resolves: https://github.com/balena-os/meta-balena/issues/2256
--- …

Assign a fixed name to the balena-healthcheck container

---

tests/suites/hup/suite.js

Some OS versions before HUP do not support the '-b all' flag
to journalctl. This commit reverts to the original behaviour
that lists the boots and requests the logs for each boot.
--- …

tests: List boots when collecting journal logs in hup suite

---

tests/suites/os/tests/healthcheck/index.js

Sometimes in the container healthcheck test there is a race condition - -the test causes a containers docker healthcheck to fail, and expects the container to go from healthy to unhealthy - however depending on when this happens, the test may never detect the healthy state first - causing the test to fail. 
This PR alters the test so that it waits to confirm a healthy state, before making the container unhealthy 
--- …

tests: remove healthcheck test race condition

---

meta-balena-common/recipes-containers/balena/balena/balena-host.service
meta-balena-common/recipes-containers/balena/balena/balena.conf.storagemigration
meta-balena-common/recipes-containers/balena/balena/balena.service
meta-balena-common/recipes-containers/balena/balena_git.bb

~~This PR bumps balena-engine to include some additional logic that should make debugging migration failures easier, it will dump some logs to `/mnt/state/balena-engine-storage-migration.log` in case it encounters an internal error.~~
~~Also included is a set of tests around various migration scenarios, see [here](https://github.com/balena-os/meta-balena/blob/rgz/a2o_migrate/tests/suites/hup/tests/storagemigration.js)~~
~~This includes #2174 until that merges~~
Drop the tests from this PR, this one only enables storage migration now.

Enable balena-engine storage migration

---

tests/suites/os/tests/healthcheck/Dockerfile.template
tests/suites/os/tests/variables/Dockerfile.template

Replace Dockerfile image %%BALENA_MACHINE_NAME%% var with
%%BALENA_ARCH%% for better compatibility
Device types lacking matching tags in the balenalib Docker Hub account
will fail tests when a matching image is not found. Switch to
BALENA_ARCH instead, to maintain compatibility.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you …

tests: s/BALENA_MACHINE_NAME/BALENA_ARCH

---

tests/suites/hup/suite.js

Should prevent failures like this:
```
[2021-09-02T18:44:38.470Z][b03426f-hup] Couldn't retrieve logs with error: Error: "journalctl --no-pager --no-hostname --list-boots | awk '{print $1}' | xargs -I{} sh -c 'set -x; journalctl --no-pager --no-hostname -a -b {};'" failed. stderr: + journalctl --no-pager --no-hostname -a -b -2
Data from the specified boot (-2) is not available: No such boot ID in journal
+ journalctl --no-pager --no-hostname -a -b -1
+ journalctl --no-pager --no-hostname -a -b 0, stdout: -- Logs begin at Mon 2020-01-27 17:11:36 UTC, end at Thu 2021-09-02 18:43:37 UTC. --
```
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor …

tests: Prevent failure when journalctl has no logs for some boots

---

tests/suites/os/tests/led/index.js

Only run LED test when device type contract specifies support for it
---

tests: led: require led property from device type

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/0-bootfiles

The extlinux.conf file path in meta-balena is currently
incorrect, let's update it's boot partition path so that
BalenaHUP won't need to transfer the isolcpus setting to
the new OS anymore. This is necessary only when updating from older
OS versions in which the supervisor adds the isolcpus
setting to the boot partition extlinux.conf file.
--- …

hostapp-update-hooks: Fix blacklisted extlinux.conf file path

---

meta-balena-common/conf/distro/include/balena-os.inc
tests/suites/os/conf.js
tests/suites/os/suite.js
tests/suites/os/tests/healthcheck/index.js
tests/suites/os/tests/led/index.js
tests/suites/os/tests/os-release/index.js
tests/suites/os/tests/variables/index.js

The OS is now a single image that can switch between development and
production modes at runtime.
See: https://github.com/balena-os/meta-balena/pull/2227
--- …

tests: Remove OS variants

---

meta-balena-common/recipes-containers/balena/balena_git.bb

Update balena-engine from 19.03.26 to 19.03.29
Changelog-entry: Update balena-engine to v19.03.29

balena-engine: Update to 19.03.29

---

meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-core/systemd/systemd/balena-os-sysctl.conf
meta-balena-common/recipes-core/systemd/systemd/disable-user-ns.conf
meta-balena-common/recipes-core/systemd/systemd_%.bbappend

When user namespacing was enabled in the kernel by default, a separate
commit [0] was introduced to disable the feature at runtime, to allow
users/administrators to explicitly choose to enable it, avoiding
potential security implications.
However, some applications such as Chromium's sandbox, require either
SUID or user namespacing to work. Disabling this feature on boards
that previously enabled it necessitates container modifications and
potentially breaks previously working applications.
Create a distro feature to disable user namespacing by default in
meta-balena, while allowing device types to keep it enabled to maintain
compatibility with their original behavior.
https://github.com/balena-os/meta-balena/commit/31c3ae8ad5c7ad45e450349b6972524da120e96c …

common: conf: create disable-user-ns distro feature

---

meta-balena-common/classes/balena-linux-firmware.bbclass

This prevents downstream linux-firmware fakeroot tasks, such as
firmware compression, from encountering Pseudo Abort due to files
changing outside the fakeroot context.
--- …

Run iwlwifi firmware cleanup in fakeroot

---

meta-balena-common/recipes-containers/balena/balena/balena-healthcheck

In situations with limited resources the info and ps commands can take
an unecessarily long time when we really only need to know that a
container can be started.
--- …

balena-healthcheck: Remove redundant steps and rely on hello-world

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/0-bootfiles

The Rock Pi 4B uses a file named hw_intf.conf for
enabling/disabling interfaces and for loading overlays.
Just noting that the syntax is also slightly different
from the config.txt file on RaspberryPi.
Let's blacklist this file to avoid overriding
it during OS updates.
Connects-to: https://github.com/balena-os/balena-rockpi/issues/13
--- …

hostapp-update-hooks: Blacklist Rock Pi configuration file

---

meta-balena-common/classes/resin-u-boot.bbclass

Let's increase the current value for the rollback-altboot
bootcount to 5, to account for accidental poweroffs triggered
by users or by power supplys when booting into the new OS,
during HUP.
When the limit is reached, u-boot will proceed to try
to boot into the old OS.
Connects-to: https://github.com/balena-os/meta-balena/issues/2301
--- …

classes/resin-u-boot: Increase OS_BOOTCOUNT_LIMIT to 3

---

meta-balena-common/classes/image-balena.bbclass

The boot partition needs to be generated before creating the balenaos-img
but is not part of the root filesystem generation.
The decoupling allows to build just the docker rootfs image without
having to build the balenaos-img target.
--- …

image-balena: Decouple boot directory generation from rootfs task

---

meta-balena-common/recipes-core/base-files/base-files_%.bbappend
tests/suites/os/suite.js
tests/suites/os/tests/issue/index.js

This allows to display ESR releases on the welcome login.
---

base files: Use HOSTOS_VERSION in issue and issue.net

---

tests/suites/os/suite.js
tests/suites/os/tests/chrony/index.js

Add a test to wait for the chronyd service to become active before starting the time sync tests.
The current chronyd tests assume that the chronyd service is instantly available at boot time. With the addition of the new
HTTPS time synchronisation service the starting of chronyd can be delayed by a few seconds so we need to ensure that the service is actually running before proceeding.
Changelog-entry: tests: wait for the chronyd service become active
--
Tested locally on a testbot rig with a RPi4.
---
- '*Request Changes*' if this change would not be …

tests: wait for the chronyd service become active

---

meta-balena-common/recipes-devtools/dosfstools/dosfstools_%.bbappend
meta-balena-common/recipes-devtools/dosfstools/dosfstools_4.1.bbappend

This patch was submitted and accepted upstream, and is present since
v4.2.
https://github.com/dosfstools/dosfstools/commit/87a8f29785bb605350821f1638a42e6cf3e49ce3
This fixes a build error applying a patch that's already been applied
when building newer versions of dosfstools.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have …

dosfstools: selectively apply upstreamed patch

---

meta-balena-common/recipes-core/initrdscripts/files/resindataexpander

The behaviour for non-LUKS system should be the same as before,
an extra step is performed when LUKS resize is necessary.
---

resindataexpander: also resize LUKS volume if necessary

---

tests/suites/os/package.json
tests/suites/os/suite.js
tests/suites/os/tests/engine-socket/index.js

This tests the engine socket being exposed in development mode but not
in production mode.
---

tests: os: Add exposed engine socket test

---

tests/suites/os/tests/connectivity/Dockerfile.aarch64
tests/suites/os/tests/connectivity/Dockerfile.amd64
tests/suites/os/tests/connectivity/Dockerfile.armv7hf
tests/suites/os/tests/connectivity/Dockerfile.template
tests/suites/os/tests/connectivity/docker-compose.yml
tests/suites/os/tests/connectivity/index.js

Previously, the core service exposed a /proxy endpoint that would start
up a proxy remotely, which would be used by a test in the connectivity
module. However, the endpoint returned the address for the testbot to be
used as the proxy in the response, and this required manual
configuration of the interface. Additionally, it requires the worker
service to install and provide glider for forward proxying.
Move the proxy (glider) to a container on the device being tested,
which simplifies configuration, and reduces the complexity and size of
the interface of Leviathan.
See: https://github.com/balena-os/meta-balena/issues/2352
---
- '*Approve*' if this change would be acceptable in the …

connectivity: proxy: move nadoo/glider to container

---

meta-balena-common/recipes-core/packagegroups/packagegroup-balena-connectivity.bb

The driver for RTL8723BU wireless chipset is present, but its firmware
files are not loaded. This patch includes them.
---

linux-firmware: Include RTL8723BU firmware files

---

meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-support/balena-keys/balena-keys.bb

Add a recipe to deploy the signing keys to the deploy directory.
Device types that use them should copy them into the boot partition.
---

balena-keys: Add recipe

---

meta-balena-common/classes/sign-efi.bbclass
meta-balena-common/classes/sign-kmod.bbclass

This reverts commit 853656e6bcfed0b0206d031c32cd1cde811b8146.
The change overwrites build files, though that is what we need, it is a hacky
approach and we will look for a clean solution.
--- …

Revert "sign-efi.class, sign-kmod.class: Replace original files with signed ones"

---

meta-balena-common/recipes-core/packagegroups/packagegroup-balena-connectivity.bb

The MT7601U WiFi driver fails to find its firmware, so it is included now.
---

linux-firmware: Include MT7601U firmware

---

meta-balena-common/recipes-bsp/grub/grub-efi/0001-Add-dummyterm-module.patch
meta-balena-common/recipes-bsp/grub/grub-efi_%.bbappend

At this moment GRUB drops to rescue shell if config is invalid
or if signatures are missing/wrong. This lets the user disable the signature
checks altogether.
With this patch GRUB outputs nothing and accepts no user input if signing
is configured.
--- …

grub-efi: Accept no input and output nothing when in secure boot mode

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/0-signed-update

The hook tries to read EFI variables from efivarfs but this is not always
mounted within the container. We have already validated that we are running
in EFI mode therefore we can just check whether it is already mounted
and eventually mount with no further checks.
--- …

0-signed-update HUP hook: mount efivarfs if necessary

---

tests/suites/os/tests/connectivity/index.js

The interface test uses a simple ping to ensure a specific interface
works. It sends ten packets, and expects ten packets back. However, the
default interval is one second, which increases the time taken for the
test while not adding anything of value.
Reduce the timeout to the minimum non-privileged interval of 2ms.
--- …

connectivity: reduce ping interval to minimum

---

meta-balena-common/conf/distro/include/balena-os.inc

BalenaOS does not use PAM but some vendor BSPs enable it and misconfigure
the hostOS authentication.
---

balena-os: make sure PAM support is not configured

---

meta-balena-common/recipes-core/images/balena-image-flasher.bb

Having the keys available in the flasher image allows to use the
flasher image as source to program the keys in the EFI.
Changelog-entry: Add secure boot keys to the flasher boot partition
--- …

balena-image-flasher: Add secure boot keys to boot partition

---

meta-balena-common/recipes-connectivity/networkmanager/balena-files/NetworkManager.conf.systemd
meta-balena-common/recipes-connectivity/openvpn/files/openvpn.service
meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/balena-supervisor.service
meta-balena-common/recipes-core/chrony/files/chronyd.conf.systemd
meta-balena-common/recipes-core/systemd/timeinit.bb
meta-balena-common/recipes-core/systemd/timeinit/time-sync-https-wait.target
meta-balena-common/recipes-core/systemd/timeinit/timesync-https.service
meta-balena-common/recipes-core/systemd/timeinit/timesync-https.sh
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-time

Add a new timesync-https systemd service to synchronise the system time at boot using an HTTPS header. The service uses curl to request an HTTPS header from either $API_ENDPOINT/connectivity-check (default) or the URL defined by the os.network.connectivity.uri field in config.json. The URL used *must* return HTTP code 204 (No Content) in response to a request so that we can determine that we have full network connectivity and are not operating behind a captive portal.
The date field returned by a valid header is used to set the current system time. The date/time derived from the header is assumed to be a reasonable source of 'truth' such that it can be used to adjust the system time both backwards and forwards. This will compensate for any erroneous timestamps saved via fake-hwclock or …

systemd/timeinit: add HTTPS time synchronisation service

---

meta-balena-common/classes/kernel-balena.bbclass
meta-balena-common/classes/sign-efi.bbclass
meta-balena-common/classes/sign-gpg.bbclass
meta-balena-common/recipes-core/initrdscripts/files/kexec
meta-balena-common/recipes-kernel/linux/kernel-image-initramfs.bb

In the current state this produces an unbootable system - the unsigned bzImage is shipped within the image but the attached bzImage.sig is for the EFI-signed version.
- EFI sign bzImage first
- GPG sign the result
- Enable kexec signature check in the kernel
- Load EFI keys to the kernel keyring
- Use -s with kexec load command
--- …

Make kexec work under kernel lockdown

---

tests/suites/os/suite.js

Handle ENOENT ErrnoException when attempting to unwrap non-flasher image
in os/suite.js.
---

tests: os: fix unhandled exception when unwrapping non-flasher image

---

tests/suites/os/tests/bluetooth/index.js

The CM4 IO-Board exhibited an issue in which
the MAC address was set to an
un-programmed value AA:AA:AA...:AA.
We've addressed this in the device repo,
meanwhile it has been fixed in upstream
too, so let's check and catch this should
it happen again.
Connects to: https://github.com/balena-os/balena-raspberrypi/issues/731
--- …

tests: Ensure BDADDR is initialized

---

tests/suites/hup/suite.js
tests/suites/os/tests/device-tree/index.js

Added additional suite level teardown to get journalctl logs even for the scenario when - HUP fails in the first test of HUP suite or 
- If the registry fails to start. 
In both cases, journalctl logs weren't recorded and we all like some journalctl logs whenever we can have them. So why not. 
Also, patching a small issue in Dtoverlay test.

patch: Add archiveLogs Teardown for HUP suite

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

Version has been released for 14 days..provides happy eyeballs algorithm which improves device connectivity on IPv6 networks. Otherwise also allows nano 2gb dev kit to be configured via extra-uEnv backend.

balena-supervisor: Update balena-supervisor to v12.11.16

---

meta-balena-common/recipes-core/systemd/timeinit/timesync-https.sh

Update the timesync-https.sh script to handle the case where the date field is missing from the returned HTTPS header.
When the date field is not present the script will now exit with a warning rather than blocking indefinitely.
Changelog-entry: systemd/timeinit: handle missing date field in HTTPS header
--
Built and tested against balena-raspberrypi v2.88.5+rev1 and meta-balena v2.88.11 for Raspberry Pi 4. A text file was used to simulate an HTTPS header with no date field.
--- …

systemd/timeinit: handle missing date field in HTTPS header

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/1-bootfiles

When updating from a legacy development image which has no developmentMode
set in config.json to an image configured with development mode, the hooks
need to set developmentMode accordingly in config.json.
Updating to a development mode image from a production image will not
set developmentMode.
--- …

hostapp-update-hooks: Handle developmentMode updates

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor

This is to try and improve the robustness of the Supervisor update mechanism.
Originally I was trying to make the updates atomic but then say `sed -i` is atomic since it writes to a tmp file then moves tmp to /etc conf location.

Sync cached writes to disk when updating supervisor.conf

---

meta-balena-common/classes/image_types_balena.bbclass
meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-core/coreutils/coreutils_%.bbappend
meta-balena-common/recipes-devtools/go/go-native.inc
meta-balena-common/recipes-devtools/go/go-native_1.12.bb

While working on the Honister switch for the RPI boards we noticed that for some releases, like for instance the Pi3 32bit v2.83, the boot partition files timestamps were incorrect, for instance:
```
root@6335d78:~# stat /mnt/boot/overlays/audremap.dtbo
File: /mnt/boot/overlays/audremap.dtbo
Size: 971             Blocks: 2          IO Block: 512    regular file
Device: b301h/45825d    Inode: 2436        Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 1961-11-25 17:31:44.000000000 +0000
Modify: 1961-11-25 17:31:44.000000000 +0000
Change: 1961-11-25 17:31:44.000000000 +0000
Birth: -
```
This caused the commands stat, mv, mkdir etc in the new Honister release to fail with ' Value too large for defined data type', although the file on which the …

Fix issues related to boot partition file timestamps

---

meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-dunfell/conf/distro/include/balena-os-yocto-version.inc
meta-balena-thud/conf/distro/include/balena-os-yocto-version.inc
meta-balena-warrior/conf/distro/include/balena-os-yocto-version.inc
meta-resin-rocko/conf/distro/include/balena-os-yocto-version.inc
meta-resin-sumo/conf/distro/include/balena-os-yocto-version.inc

Poky releases older than Honister should stick to rust v1.36
which has been used in balenaOS builds so far.
Newer ones should prefer v1.54, which is the latest rust
version to use the Honister syntax.
--- …

conf/distro: Prefer rust v1.36 for releases older than Honister

---

meta-balena-common/recipes-core/chrony/files/chronyd.conf.systemd

The chrony driftfile is not being updated at shutdown due to an incorrect mount service dependency in the systemd chronyd.service file. The current dependency on 'var-volatile-lib' does not cover the subsequent bind mounting of the '/var/lib/chrony' sub-directory, so the chrony directory gets unmounted at shutdown before the drift file has been updated.
This issue is solved by changing the mount service dependency from 'var-volatile-lib' to 'bind-var-lib-chrony' (which is similar to the way bind mount dependencies are already handled for the NetworkManager and bluetooth services).
Connects-to: #1995
Changelog-entry: chrony: fix mount service dependency for driftfile
--
Built and tested against balena-raspberrypi v2.88.5+rev1 …

chrony: fix mount service dependency for driftfile

---

tests/suites/os/suite.js
tests/suites/os/tests/config-json/index.js

This PR aims to make several tests in the config-json module more concise and readable, primarily with the use of the `waitForServiceState()` helper. Additionally, several unnecessary reboots were removed to save time.
--- …

Cleanup config json tests

---

meta-balena-common/recipes-core/busybox/busybox_%.bbappend
meta-balena-common/recipes-core/systemd/systemd_%.bbappend
meta-balena-common/recipes-extended/bash/bash_%.bbappend
meta-balena-common/recipes-support/hostapp-update-hooks/files/1-bootfiles

Files in the boot partition may have incorrect modification
timestamps which can cause problems for programs that have
been compiled against glibc 2.34 or newer. stat() fails in
such cases with EOVERFLOW, so let's ensure that files have
correct modification timestamps.
Connects to and needs to be included in: https://github.com/balena-os/balena-raspberrypi/pull/755
--- …

Update bootfiles timestamps

---

meta-balena-common/recipes-devtools/jq/jq_%.bbappend
meta-balena-common/recipes-support/hostapp-update-hooks/files/1-bootfiles

We noticed that when performing a touch on blacklisted files, like for instance config.json, in order to update their bootstamps, services are reloaded and this implies the registry on the DUT is also restarted. This happens when the starting BalenaOS version is newer and includes dev/prod unification. Also, the ssh connection over which hup is triggered (i.e webterminal) is lost when updating from the newer unified images.
This behavior isn't visible if testing from an older release, or if triggering hup from uart using a remote registry, i.e dockerhub.
The issue has been introduced in 2.88.22 in https://github.com/balena-os/meta-balena/commit/96cecbeac2887d2fc78817c9bfd10746bd139960 so in this PR we avoid touching files that are blacklisted and which may be watched by other services. …

Don't update bootstamps on blacklisted files

---

meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend

To avoid issues, move the udev database cleanup just before switching
roots.
---

initramfs-framework: Make cleaning udev database the last step

---

tests/suites/cloud/conf.js
tests/suites/cloud/package.json
tests/suites/cloud/suite.js
tests/suites/cloud/tests/multicontainer/index.js
tests/suites/cloud/tests/preload/index.js
tests/suites/cloud/tests/supervisor/index.js
tests/suites/config.js

This PR adds equivalent automated tests for the following testlodge tests:
- TC43 Pre-load  and pin release
- TC38 Move device to multicontainer app
- TC132 Apply device variables
- TC128 Move device back to app
- TC09 normal provisioning without deltas
- ~~TC26 supervisor reload test~~ (covered in https://github.com/balena-os/meta-balena/pull/2342)
- TC49 Override lock
These tests differ from the `os` test suite, which tests unmanaged OS features in that they require a managed device.
This PR requires the following to be merged first: 
- https://github.com/balena-os/leviathan/pull/402 (this PR adds some helpers to leviathan for interacting with balenaCloud
- https://github.com/balena-os/leviathan/pull/393 (this allows us to run multiple suites on either the same testbot, or multiple in …

Add cloud test suite 

---

meta-balena-thud/recipes-bsp/u-boot/u-boot_%.bbappend
meta-resin-pyro/recipes-bsp/u-boot/u-boot_%.bbappend
meta-resin-rocko/recipes-bsp/u-boot/u-boot_%.bbappend
meta-resin-sumo/recipes-bsp/u-boot/u-boot_%.bbappend

Let's only apply this code to pre-warrior as intended. Starting
with warrior this code is in poky so we can rely on it from
there instead of keeping a duplicate in meta-balena-common.
This helps with BSPs that may define their own tasks (configure,
compile and so on) for u-boot (keeping this fragments merging
code in meta-balena-common would have the effect of overwriting
these tasks from here and thus breaking the build).
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development …

u-boot: Move config fragments merging code out of common layer

---

tests/suites/cloud/suite.js

Occasionally the recently merged cloud test suite will fail - the device never connects to the dashboard - e.g https://jenkins.product-os.io/job/leviathan-genericx86-64-ext/283/artifact/client/build/reports/worker-localho-cloud.log
Here I add some extra logging to see if we can tell why this might be.
---
- '*Comment*' if you don't feel you have enough information to decide either …

tests: add extra logging to cloud suite

---

meta-balena-common/classes/image_types_balena.bbclass

Some BSPs might only make use of UBOOT_MACHINE so let's consider
this case in addition to UBOOT_CONFIG when setting dependency for
u-boot's do_deploy task.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make …

image_types_balena: Augment dependency on u-boot do_deploy task

---

meta-balena-common/recipes-core/initrdscripts/files/resindataexpander

When resizing the filesystem fails, such as when resize2fs won't touch
it because it's dirty, the partition gets resized, but not the
filesystem. The script will not attempt to resize the filesystem again,
as it detects the partition has already been resized.
Split these actions apart, so that the filesystem resize is always
attempted. If resize2fs detects that the filesystem is already filling
available space, it will exit with no action taken.
--- …

resindataexpander: expand fs independent of partition

---

meta-balena-common/recipes-containers/docker-disk/files/entry.sh

This will allow us to refer to the supervisor image by the repo name
in docker commands, like docker inspect, and prevent re-downloading the
image even though it already exists as an untagged digest.
Resolves: https://github.com/balena-os/meta-balena/issues/2492
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, …

docker-disk: Tag the supervisor digest with the repo name

---

meta-balena-common/classes/resin-u-boot.bbclass

The header has been removed in this commit:
https://github.com/u-boot/u-boot/commit
/5c6a4d5a2779d7c2611319076d9aa4a23981855f
---

resin-u-boot.bbclass: Do not error if no config_defaults.h

---

meta-balena-common/recipes-core/initrdscripts/files/resindataexpander

After moving the partition resizing code to execute on each boot,
we made it unreachable on first boot. We must not exit the script
after resizing the partition only because that way the resizing
is only finished on 2nd boot.
--- …

resindataexpander: do not return after resizing the partition only

---

tests/suites/hup/suite.js
tests/suites/hup/tests/smoke.js
tests/suites/os/suite.js
tests/suites/os/tests/under-voltage/index.js

We add this this check since we discovered
that with newer boot firmware the Pi4 will
not reboot when under-voltage is reported.
We do not mark the test as failed in
this case, since there may be devices that
continue to work even if under-powered and we
do not want to block or delay development if the
DUT is remote and cannot be checked or replaced
easily.
This check provides an indication for further
debugging of failed test cases.
---
- …

[tests]: Add under-voltage check for OS and HUP suites

---

tests/suites/cloud/suite.js

This patch to the cloud suite is an attempt to stop a problem happening in the teardown. When used with real hardware, there's a possibility that some problem in the teardown leads to the core service crashing, which then can ruin the next test: example is here: https://jenkins.product-os.io/job/leviathan-raspberrypi4-64/1007/
I remove the archiving of the image during the teardown as it is no longer needed, and takes a long time. I think this long time when done on the testbot is partly responsible for the teardown problems in the cloud suite.
---
- …

fix cloud suite teardown

---

tests/suites/cloud/suite.js
tests/suites/cloud/tests/supervisor/index.js

This addresses 2 issues:
1. If the cloud test suite failed before the DUT would connect to balenaCloud, there would be no journal logs stored - making it impossible to determine why.
2. The `Override lock test` was flaking, with the `Updates are locked` message not appearing in the DUT logs - I think this most likely would be due to a race condition, as we check the logs only once. If this check happens too quickly, there is a chance that the message wouldn't have appeared yet. I added a retry to this check. It can be seen in this job: https://jenkins.product-os.io/job/leviathan-genericx86-64-ext/407/ where the test fails, that the update lock message does appear (check the journal logs stored in `artifacts-localho-cloud.tar.gz`
[artifacts-localho-cloud.tar.gz](https://jenkins.product-os.i …

fix journal log retrieval in cloud suite, and try to make override lock test consistant

---

tests/suites/os/suite.js
tests/suites/os/tests/config-json/index.js

Wait for os-config-json service to be inactive between tests
so the next changes to config.json are not missed by systemd.
---

tests/os: Wait for os-config-json service to be inactive

---

meta-balena-common/recipes-connectivity/openvpn/files/openvpn.service

We want the VPN to start unconditionally even if the connectivity URL
is not reachable.
The rationale for adding the dependency in the first place was that
without an initial timesync certificate checks may fail. This can still
happen, but the VPN will retry continuously and eventually succeed once
the time is synched.
What happens now is that the VPN is delayed until the http sync, so if
the connectivity URL is blocked or unreachable, but the internet is
accessible, VPN will not even launch and no remote debugging is possible.
Fixes #2508
---
- …

openvpn: Remove dependency on timesync-http target

---

README.md
meta-balena-common/classes/image-balena.bbclass
meta-balena-common/recipes-core/images/balena-image.bb

These image types are no longer generated and are not used for hostOS
updates any longer.
Changelog-entry: Remove legacy resinhup images.
---

images: Remove generation of legacy resinhup images

---

meta-balena-common/classes/kernel-balena.bbclass

Since https://github.com/raspberrypi/linux/commit/1eee36a5520b5a89fb4d0d6af6f9cb0217a3164f
was merged and included in kernel versions after 5.10.84,
building the kernel-modules-headers package fails due to various missing
headers from the gmp and mpc packages (mpc.h, gmp.h). This problem is visible
only after upgrading to a newer kernel, because until now the
gcc plugins kernel config was not enabled at all, due to the
[failed check](https://github.com/raspberrypi/linux/commit/1eee36a5520b5a89fb4d0d6af6f9cb0217a3164f#diff-5774ad0ce5325e4f3c86ecf168d1d719c34cc6fdc7592f72849641a6268b758aL12) in the above mentioned patch.
Since we are not using the functions provided
by the [gcc plugins](https://gcc.gnu.org/wiki/plugins) in the hostOS anyway, we can disable this
config. …

kernel-balena: Disable building of gcc plugins

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.bb
meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor

Improve the checks to make sure there is a valid target state and fallback to preloaded values.
Also, allow to pass a supervisor image in the command line to cater for updates in unmanaged/openBalena devices.
---

Supervisor update enhacements

---

meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update

In most cases there is not enough space on rootfs to extract
and load a local hostapp image when the balena-host tmpdir
is on the same partition.
This uses a tmpfs mount to ensure temporary extracted files of the
compressed image will not fill the target sysroot.
Resolves: https://github.com/balena-os/meta-balena/issues/2507
--- …

hostapp-update: Mount data partition on target balena/tmp

---

meta-balena-common/recipes-kernel/linux/files/Dockerfile
meta-balena-common/recipes-kernel/linux/files/example_module/hello.c

Let's ensure tools like fixdep are built in container
and not reused from the yocto build, otherwise they
may not run if they were linked against a different
version of libc that may not be available in the kernel
modules build container.
This fixes the following error encountered when doing
a Poky Honister build for the balena-intel repository:
scripts/basic/fixdep: /lib64/libc.so.6: version `GLIBC_2.34'
not found (required by scripts/basic/fixdep)
--- …

kernel-headers-test: clean tools like fixdep

---

meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_%.bbappend

We add this fw on its own package so that boards can add it to
rootfs (for Intel NUC 11th generation more specifically)
Changelog-entry: Package iwlwifi-QuZ-a0-hr-b0 firmware separately
--- …

linux-firmware: Package iwlwifi-QuZ-a0-hr-b0 firmware

---

meta-balena-common/recipes-support/resin-device-register/resin-device-register/resin-device-register

Starting with v2.91.6 device provisioning will not start if the device
was unable to register in the cloud due to lack of internet connectivity.
To avoid this, we switch to retrying 3 times with the usual 2 second delay
between attempts, after which the flashing process will start.
Fixes https://github.com/balena-os/meta-balena/issues/2576
--- …

resin-device-register: improve provisioning

---

meta-balena-common/classes/kernel-balena.bbclass

Github now requires for the https protocol to be used
when cloning repositories, so let's add this to the aufs
repository link.
---

kernel-balena: Mention https protocol for github repository

---

meta-balena-common/recipes-containers/balena/balena_git.bb

Update balena-engine from 20.10.12 to 20.10.16
The most important change on this version is some [improved logging](https://github.com/balena-os/balena-engine/commit/ab3db5c03663e0b2ee35213ceebf9038e4af6b62) that might help with https://github.com/balena-os/balena-engine/issues/244
For testing, I just did an OS build containing this new Engine version and run it on a device until it pulled the app container and ran it for some time.
---
- …

balena-engine: Update to 20.10.16

---

meta-balena-common/recipes-connectivity/openvpn/files/openvpn.service

* ensure OpenVPN client always starts with the latest CA certificate
from API config endpoint as this certificate may have changed and
we don't want VPN to be down for ~24 hours until os-config is triggered
by systemd timer
Fixes: #2569

Refresh PKI assets from config endpoint

---

meta-balena-common/recipes-containers/balena/balena/balena.service

There are known situations in which balenaEngine times out during
initialization (for example, during aufs to overlayfs migrations, or
when restarting a device that was running a large number of containers).
When these time outs occur, Systemd kills the Engine, causing further
problems.
To avoid these cases, this commit disables timeouts during the Engine
initialization.
This is also aligned with the default Systemd settings distributed with
the Moby project.
Did only manual smoke testing (building, running on a device), which I think is good enough for this change.
Related issues:
* https://github.com/balena-os/balena-engine/issues/289
* https://github.com/balena-os/balena-engine/issues/258
---
- '*Approve*' if this change would be acceptable in …

Disable Engine startup timeouts

---

meta-balena-common/recipes-core/systemd/timeinit/timesync-https.sh

This solves a problem seen on a device on which, although
timeinit-rtc finishes running before timesync-https, chronyd
sets the system time to the incorrect rtc time
as soon as timesync-https finished running and setting the correct date
from the servers.
---
Logs from when the issue occurred:
```
root@2ddeefa:~# journalctl | grep time | grep -v balena
Mar 25 11:42:50 localhost kernel:         Build-time adjustment of leaf fanout to 64.
Mar 25 11:42:50 localhost kernel: Architected cp15 timer(s) running at 24.00MHz (phys).
Mar 25 11:42:50 localhost kernel: Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=96000)
Mar 25 11:42:50 localhost kernel: AppArmor: AppArmor …
```

timeinit/timesync-https: Update rtc after setting system time

---

meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_%.bbappend

This is used by Intel Wireless-AC 9462
---

linux-firmware: package QuZ-a0-jf-b0 separately

---

.github/renovate.json

This way renovate can operate on tests/leviathan
Default ignorePaths from `config:base` preset were being inherited:
https://docs.renovatebot.com/configuration-options/#ignorepaths
```
{
"ignorePaths": [
"**/node_modules/**",
"**/bower_components/**",
"**/vendor/**",
"**/examples/**",
"**/__tests__/**",
"**/test/**",
"**/tests/**",
"**/__fixtures__/**"
]
}
```
So I copied them and changed the `"**/tests/**",` line to specify `"**/tests/suites/**",`.
--- …

renovate: Replace tests with tests/suites in default ignorePaths

---

.github/renovate.json

renovate: Override commit body for meta-balena to Change-type

---

meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_%.bbappend

Add a missing asterisk to FILES for iwlwifi-quz-a0-hr-b0 and iwlwifi-quz-a0-jf-b0 to include compressed firmware files. Without it the packages end up empty as we have compression enabled.
---

linux-firmware: Fix quz-a0-hr-b0 and quz-a0-jf-b0 packaging for compression

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor.timer
tests/suites/cloud/tests/supervisor/index.js

To avoid fleets updating the supervisor at the same time,
distribute the timer adding a random time between 0 and 1 hour.
Fixes #2631
---

balena-supervisor: Randomize the updater timer period

---

meta-balena-common/recipes-containers/balena/balena_git.bb

Update balena-engine from 20.10.16 to 20.10.17
Contains the fix to https://github.com/balena-os/balena-engine/issues/263
Fixes #2642

balena-engine: Update to 20.10.17

---

meta-balena-common/classes/image-balena.bbclass

The `localMode` variable in `config.json` is not longer used and it can be removed
Fixes #2041
Changelog-entry: Remove localMode setting from standalone image configuration
--- …

image-balena: Remove localMode from standalone image configuration

---

tests/suites/cloud/suite.js
tests/suites/cloud/tests/multicontainer/index.js
tests/suites/cloud/tests/preload/index.js
tests/suites/cloud/tests/ssh-auth/index.js
tests/suites/cloud/tests/supervisor/index.js

When the promise called in waitUntil fails, the function defaults to a
30s interval before trying again. Reduce this to a 5s interval w/
maximum 5m retry window in the cloud suite.
--- …

tests: cloud: reduce waitUntil interval

---

tests/suites/hup/tests/rollback-altboot.js
tests/suites/hup/tests/rollback-health.js
tests/suites/hup/tests/smoke.js

Reduce delay between retries when using waitUntil, reducing latency and
test runtime.
---

tests: hup: reduce delay between retries

---

tests/suites/cloud/suite.js

tests:cloud: Register teardown only when DUT is reachable

---

tests/suites/cloud/suite.js
tests/suites/cloud/tests/multicontainer/index.js
tests/suites/cloud/tests/preload/index.js
tests/suites/cloud/tests/supervisor/index.js

The container name for the conatiner in the node hello world example we use in the cloud test suite was changed here: https://github.com/balena-io-examples/balena-nodejs-hello-world/pull/38
Updated the tests to reflect that name change
-- BLOCKS ALL META BALENA TEST RUNS UNTIL MERGED --
Resolves: https://github.com/balena-os/meta-balena/issues/2676
--- …

tests: cloud: update container names

---

tests/suites/hup/package.json
tests/suites/hup/suite.js

zip hostapp before sending it to DUT to speed it up
resolves: https://github.com/balena-os/meta-balena/issues/2592
---

tests: hup: gzip hostapp before transfer to DUT

---

meta-balena-common/recipes-bsp/grub/grub-efi_%.bbappend

Recent versions of GRUB default to use shim_lock when in secure boot mode.
We do not use shim and do not build the shim_lock module into GRUB EFI binary
therefore this needs to be disabled.
---

grub-efi: disable shim_lock when in secure boot mode

---

meta-balena-common/recipes-support/resin-mounts/resin-mounts/balena-efi.service

This changes the condition in the unit file from checking whether
/dev/disk/by-state/balena-efi exists to checking whether /mnt/boot/EFI
is a symlink. The original approach has a race condition populating
the by-state symlink - it is depending on udev and if the link is
not present when the service is started (after the boot partition is mounted),
the service fails and the EFI partition is never mounted.
The new approach does the trick pretty well - /mnt/boot/EFI is a symlink
if the EFI partition is split and a regular directory in case there is a single
boot partition. That said the service is only started when necessary
and the waiting for udev is implemented as a part of the mount script.
---
- When submitting a review, …

balena-efi.service: Mount if /mnt/boot/EFI is a symlink

---

meta-balena-common/recipes-core/initrdscripts/files/resindataexpander
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs

This is useful outside of the expander script, specifically in the init-board
script in device repos.
---

resindataexpander: Move get_part_table_type to os-helpers-fs

---

tests/suites/cloud/suite.js
tests/suites/cloud/tests/preload/index.js

Resolves: https://github.com/balena-os/meta-balena/issues/2634
Bring preload test more in line with testlodge case - make sure on physical devices (not qemu), to check preloaded app starts without api connectivity. This is achieved by disabling the internet connected to the DUT. 
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have …

tests: cloud: check preloaded app starts w/o api

---

tests/suites/os/tests/chrony/index.js

This PR takes the chrony offline sources test from ~60s to a few hundred ms
---

Cleanup chrony tests

---

tests/suites/os/tests/modem/index.js

Reduce the interval between scans as well as the maximum number of scans
for modems, reducing the time spent waiting when no modem is present
from ~50s to ~5s.
--- …

tests: os: modem: reduce time taken scanning for modems

---

tests/suites/os/tests/purge-data/index.js

This reduces the time taken for the purge tests by approximately 30s
---

tests: os: purge-data: reduce intervals in waitUntil

---

tests/suites/os/suite.js

When accessing a test device as part of a fleet, a cloud API key is
required in order to generate an SSH key and access the device through
the VPN. However, when accessing a device locally, such as a QEMU
instance running on the workstation itself, we have a direct path, and
no VPN is necessary.
Make the apiKey optional, and don't login when it's not specified. This
allows direct connections to work without it.
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in …

tests: os: make apiKey an optional parameter

---

tests/suites/cloud/tests/os-config/index.js
tests/suites/cloud/tests/supervisor/index.js

This should prevent failed tests on slower devices.
Resolves: https://github.com/balena-os/balena-generic/issues/74
---

tests: Increase delay when testing randomized timers

---

tests/suites/cloud/tests/os-config/index.js
tests/suites/cloud/tests/supervisor/index.js

This prevents a race condition on slower hardware where
the systemd unit does not have a value for Trigger immediately
after skewing the clock.
Resolves: https://github.com/balena-os/balena-generic/issues/74
Resolves: https://github.com/balena-os/balena-raspberrypi/issues/852
Resolves: https://github.com/balena-os/balena-beaglebone/issues/351
--- …

tests: cloud: Wait for random triggers to be updated

---

tests/suites/os/tests/fingerprint/index.js

When parallelizing fingerprint checks with Promise.any(), the
unsuccessful command would continue retrying in the background, causing
spurious error messages.
With mDNS resolution memoization, this optimization no longer saves us
time, so remove it.
--- …

tests: os: fingerprint: fix errant promise

---

tests/suites/cloud/suite.js
tests/suites/cloud/tests/ssh-auth/index.js

Use a common function to apply settings in config.json to avoid
code duplication. It also provides timed results so we know
how long it took to apply a setting.
Resolves: https://github.com/balena-os/balena-generic/issues/118
Resolves: https://github.com/balena-os/meta-balena/issues/2726
Resolves: https://github.com/balena-os/meta-balena/issues/2679
Resolves: https://github.com/balena-os/balena-beaglebone/issues/335
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in …

tests: ssh-auth: Rework to prevent race conditions

---

meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/balena-config-defaults
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/balena-config-vars

Flasher images use an alternative configuration storage so skip caching.
---

balena-config-vars: Do not use cache in flasher images

---

tests/suites/cloud/suite.js
tests/suites/cloud/tests/device-specific-tests/hostapd/index.js
tests/suites/os/suite.js
tests/suites/os/tests/device-specific-tests/243390-rpi3/assets/helpers.sh
tests/suites/os/tests/device-specific-tests/243390-rpi3/index.js

This covers the unmanaged part of the tests for the CUS
and EUS wifi chipsets on this DT.
Implements https://github.com/balena-os/meta-balena/issues/2541
--- …

tests: Add 243390 unmanged Wifi HATs tests from testLodge

---

tests/suites/os/tests/engine-socket/index.js

During the engine-socket test, there was a race condition that developed because the test would progress with a `#todo` instead of waiting for the response from the DUT engine. This meant that in some cases (mainly with the pi3-64 DUT) the test would progress, the DUT put into prod mode, which would make the previous request to the engine fail, killing the test run
resolves https://github.com/balena-os/balena-raspberrypi/issues/895
--- …

tests: os: engine-socket - wait for response before continuing test

---

tests/suites/cloud/tests/ssh-auth/index.js

fixes 2 errors with the ssh keys test in the cloud suite:
1. When using the testbot setup, the error message that is returned on the expected failed ssh (no keys set up) is different to the qemu setup - fixed the check to check for both
2. the newly generated ssh keys were being sent to the wrong location on the testbot - fixed
I also reduced the timouts in the waituntils as they were multiple hours long
tested on pi4 and pi3
resolves:  https://github.com/balena-os/meta-balena/issues/2744
---
- '*Request Changes*' if this change would not be acceptable in …

tests/cloud: fix ssh prod test for physical duts

---

.github/renovate.json

renovate: Restore default commit body

---

meta-balena-common/recipes-containers/mobynit/mobynit_git.bb

Mobynit requires network access to fetch dependencies.
---

mobynit: allow compile task to use network

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Instead of querying devices w/ `fdisk -l`, glob match patterns specified in resin-init-flasher.conf with devices present in `/dev`. This allows us to specify devices like `hd? sd? mmcblk?` instead of individual device numbers, which don't consistently map to any particular disk.
This also allows RAID arrays to be matched with the array name and a pattern that glob matches even arrays assembled automatically on a non-matching host, such as `md/balena?(_?)` matching an array named `balena` and assembled on-device at `/dev/md/balena_0`.
---
- '*Request …

resin-init-flasher: support pattern matching of devices

---

meta-balena-common/recipes-containers/balena/balena_git.bb

This fixes the following error when building mkfs-hostapp-native with Honister for a Variscite iMX8MM which only has Hardknott support:
mkfs-hostapp-native-1.0-r0 do_prepare_recipe_sysroot:
Manifest /work/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-linux-libc-headers.populate_sysroot not found
in cortexa53 armv8a-crc armv8a aarch64 allarch x86_64_x86_64-nativesdk (variant '')?
Remove the module since it's not used by the build host anyway
--- …

balena: remove kernel-module-nf-nat-native dependency for host build

---

meta-balena-thud/recipes-containers/balena/balena_git.bbappend

Versions above 1.12 require GOCACHE to be used.
Required to unblock:
https://github.com/balena-os/balena-nanopc-t4/pull/44
https://github.com/balena-os/balena-tci/pull/24
--- …

meta-balena-thud: Enable GOCACHE

---

meta-balena-common/classes/kernel-balena.bbclass

On kirkstone, tasks need to be explicitely allowed to access the network.
---

classes: kernel-balena: Allow aufs patching to use network

---

meta-balena-common/recipes-connectivity/balena-ntp-config/balena-ntp-config/balena-ntp-config
meta-balena-common/recipes-connectivity/networkmanager/balena-files/98dhcp_ntp

Chronyd checks that the directory specified as `sourcedir` in `chrony.conf` (in this case `/var/chrony`) is not world accessible if it exists (chrony will create it correctly if it does not exist), and does not start if that's the case.
The way that the `/var/chrony` is created when it does not exist opens the possibility of the directory existing with the wrong permissions and hitting this problem.
This commit creates the directory with the correct permissions from the start to avoid the race condition.
Change-type@ patch
---
- '*Request Changes*' if this change would …

ntp: Remove race condition from directory creation

---

meta-resin-sumo/recipes-support/libical/libical_2.0.0.bbappend

Address the following build error:
```
ERROR: libical-2.0.0-r0 do_package: QA Issue: libical: Files/directories were installed but not shipped in any package:
/usr/lib/cmake
/usr/lib/cmake/LibIcal
/usr/lib/cmake/LibIcal/LibIcalTargets.cmake
/usr/lib/cmake/LibIcal/LibIcalConfig.cmake
/usr/lib/cmake/LibIcal/LibIcalConfigVersion.cmake
/usr/lib/cmake/LibIcal/LibIcalTargets-noconfig.cmake
```
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance …

meta-resin-sumo: libical: Fix build QA error

---

meta-balena-common/recipes-connectivity/openssh/openssh_%.bbappend

Openssh v8.8 removes this support by default but the backend still needs to be updated to drop these.
---

openssh: allow RSA signatures with SHA1 algorithms

---

tests/suites/hup/suite.js

Handle ENOENT ErrnoException when attempting to unwrap a non-flasher image in HUP tests. This mirrors a similar change made in ce2d33ad8.
Fixes: https://github.com/balena-os/balena-generic/issues/148
--- …

tests: hup: handle exception when unwrapping non-flasher image

---

meta-balena-common/recipes-connectivity/openvpn/files/prepare-openvpn

This script needs to update the VPN authentication with the currently configured keys so do not use cached values.
---

prepare-openvpn: do not use cached configuration

---

tests/suites/cloud/tests/ssh-auth/index.js

2 fixes:
1. use cloud ssh auth to avoid race condition in `setConfig`. This function is used to set a device to production mode - it then however tries to run one more command over the local ssh connection - there's a chance that the device would have toggled to prod mode before that command can be completed, which will cause it to fail
2. After toggling to prod mode we check that the local ssh auth fails - depending on the timing, you might get several messages - so I added another possible message to the ones we check for
--- …

tests: cloud: ssh-auth: multiple bugfixes

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

This PR includes some fixes for glob expansion in the flasher script, as well as a fix for properly detecting and excluding the installation media from the target disk pool.
Tested with the standalone script below, as well as with the flasher, [targeting a RAID disk](https://github.com/balena-os/balena-generic/pull/151):
```bash
#!/bin/bash
set -e 
CURRENT_ROOT="$(findmnt --noheadings --canonicalize --output SOURCE / | xargs lsblk -no pkname)"
INTERNAL_DEVICE_KERNEL="$*"
echo "INTERNAL_DEVICE_KERNEL=\"${INTERNAL_DEVICE_KERNEL}\""
internal_dev=""
for device_pattern in ${INTERNAL_DEVICE_KERNEL}; do
echo "Searching for devices matching pattern /dev/${device_pattern}"
! IFS=$'\n' read -rd '' -a devices <<< \
"$(ls $(eval echo "/dev/${device_pattern}") 2>/dev/null)"
for device in …
```

Flasher Glob Expansion Fixes

---

meta-balena-common/recipes-kernel/linux/kernel-devsrc.bbappend

Yocto builds will abort due to inconsistencies between the pseudo database and files modified outside of the pseudo context [0].
This will occasionally cause builds to fail in the do_deploy step of the kernel-devsrc recipe. [1]
Fix this by not removing the kernel_source tarball in the do_deploy step.
Fixes: https://github.com/balena-os/meta-balena/issues/2806
[0] https://wiki.yoctoproject.org/wiki/Pseudo_Abort
[1] https://github.com/balena-os/meta-balena/issues/2806
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. …

common: kernel-devsrc: fix pseudo abort

---

meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/balena-config-vars
tests/suites/cloud/tests/ssh-auth/index.js

The sshd daemon is configured to fetch keys from the API for local user connections. The script that fetches the keys, cloud-public-sshkeys, sources balena-config-vars and is run as am exclusive non-root user.
Let's set the correct permissions for this file to allow not to break the above.
Fixes #2785
--- …

balena-config-vars: Set permissions for cache file

---

meta-balena-common/recipes-connectivity/openvpn/files/openvpn.service
meta-balena-common/recipes-connectivity/openvpn/openvpn_%.bbappend

The `os-config` application stops the supervisor before fetching openvpn configuration and starting the `openvpn` service unit.
As the `openvpn` service units stops `os-config`, it might not get to restart the supervisor.
This commit checks that `os-config` is not already active before starting it.
Fixes #2855
--- …

openvpn: do not stop os-config if active

---

meta-balena-common/classes/kernel-balena.bbclass

Add the wireguard module by default so it is included in all device types. This is a frequently requested by customers and will avoid having to patch individual device repositories.
--- …

classes: kernel-balena: add wireguard module

---

meta-balena-common/classes/kernel-balena.bbclass

When adding a kernel configuration conditional in a provided kernel version, make the check include the provided kernel version as that is the intuitive way to understand it.
The two places that use this function already used it in this way.
--- …

kernel-balena: Kernel version check should include provided version

---

meta-balena-common/recipes-core/images/balena-image.bb

We want meta-balena to pull in these packages automatically when FDE is enabled rather than relying on device types to have them.
---

balena-image.bb: Include bits for LUKS when FDE is enabled

---

meta-balena-common/recipes-core/images/balena-image-flasher.bb

There are two GRUB config variants - one for regular devices and one for devices with FDE enabled. This commit makes flasher include the latter in the boot partition when secure boot and FDE is included in the image.
--- …

balena-image-flasher: Include LUKS variant of GRUB config with FDE in place

---

meta-balena-common/classes/image_types_balena.bbclass
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Generates sparse images, which speeds up image generation, reduces writes to disk, and speeds up flashing.
```
┌─[17:32:07]─[joseph@wash]
└──> balena-generic $ >> du -sh balena-nosparse.img 
2.3G	balena-nosparse.img
┌─[17:32:11]─[joseph@wash]
└──> balena-generic $ >> bmaptool copy --bmap build/tmp/deploy/images/generic-amd64/balena-image-generic-amd64-20221130012101.rootfs.bmap balena-nosparse.img balena-sparse.img
bmaptool: info: block map format version 2.0
bmaptool: info: 580608 blocks of size 4096 (2.2 GiB), mapped 216093 blocks (844.1 MiB or 37.2%)
bmaptool: info: copying image 'balena-nosparse.img' to file 'balena-sparse.img' using bmap file 'balena-image-generic-amd64-20221130012101.rootfs.bmap'
bmaptool: info: 100% copied
bmaptool: info: synchronizing 'balena-sparse.img'
bmaptool: …
```

Sparse images

---

meta-balena-common/classes/kernel-balena.bbclass

Enabling CONFIG_KERNEL_ZSTD=y improves the compression ratio compared to gzip while being faster to decompress. With kernel 5.15 in balenaOS v2.105, we see the 24 MB kernel compress to approximately 19 MB.
Zstd support was added in commit 48f7ddf, first introduced in kernel v5.9. Enable this config unconditionally in supported kernels.
Note that not every architecture and device support this option, but in those cases, Kconfig will automatically disable it as HAVE_ZSTD is also missing.
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. …

kernel-balena: enable zstd compression

---

tests/suites/os/package-lock.json
tests/suites/os/package.json
tests/suites/os/tests/fsck/index.js

This test fails with images built with older yocto releases (warrior)
This is because it uses the `-E force_fsck` argument for `tune2fs` to force a filesystem check of each partition on a reboot.
However this feature was only added to `tune2fs` version > 1.45.0, and images build with older yocto releases might not have a version of `tune2fs` that satisfies this. An example is the `etcher-pro` device type.
One solution suggested was to use `tune2fs -c 1` to force the `fsck` on the partition after a single reboot. However I tried this, and it did not work for the root partitions.
Instead, I've added a check to the test, that will skip it if `tune2fs` doesn't satisfy the version requirement on the DUT. 
This will unblock the tests for some device types - I'm not against refactoring this test …

tests: os: fsck: make compatible with old yocto releaes

---

meta-balena-kirkstone/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend

Some device types are being sold with this WiFi chipset so let's include the firmware.
---

connectivity: Add linux firmware for iwlwifi 9260

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup

In the current state the cryptsetup initrd script tries to unlock all LUKS volumes in the system using the TPM. This includes user-defined LUKS volumes that, if present, fail to unlock and make the system unbootable. We should also not touch user-defined volumes in the first place.
This patch modifies the cryptsetup script to only unlock LUKS volumes that are on the OS drive (same block device as the EFI partition).
---
- '*Comment*' if you …

initrdscripts: Only unlock LUKS partitions on the OS drive

---

tests/suites/hup/suite.js

resolves an issue where on some device types we would run out of space in the inactive partition during the hup
tested on beaglebone black DUT
---

tests: hup: clean up inactive partition pre hup

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup
meta-balena-common/recipes-core/initrdscripts/files/udevcleanup

When unlocking LUKS devices, udev events initializing the DM devices are still generated in the background even after cryptsetup luksOpen returns. We need to wait for the udev processing to finish before killing udev and cleaning up the udev database to avoid having to deal with partially initialized devices or corrupted udev database in the target OS.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. …

initrdscripts: Wait for udev processing to complete when unlocking LUKS devices

---

tests/suites/config.js

Following the conversation from https://balena.zulipchat.com/#narrow/stream/345889-loop.2Fbalena-os/topic/skipping.20tests.20on.20leviathan, I am adding a default debug object as a way to debug tests on production more easily. I will follow this up with parameters in Jenkins that can be modified as needed to derive more information out of a run. 
Additionally, this will also unblock PRs that are failing because there is no unstable object present in the config. 
--- …

patch: Add default debug object to test config

---

tests/suites/cloud/suite.js
tests/suites/cloud/test-app/containerA/Dockerfile.template
tests/suites/cloud/test-app/containerB/Dockerfile.template
tests/suites/cloud/test-app/docker-compose.yml
tests/suites/cloud/tests/multicontainer/index.js
tests/suites/cloud/tests/preload/index.js
tests/suites/cloud/tests/supervisor/index.js
tests/suites/os/tests/container-healthcheck/Dockerfile.template

Current steps of cloud suite: 
```
1. create an app
2. push hello-world to that app
3. preload image with that release
4. flash DUT
5. power on DUT
6. check preloading worked
7. disable deltas
8. push a new release to the app
9. wait for release to be downloaded, check it wasnt done via deltas
10. create lockfile
11. push another release
12. wait until its downloaded - then check its not being installed due to lockfile
13. create another app
14. push multicontainer example
15. move device to this new app
16. wait until dowoaded and started (takes a good chunk of time, times out often with slow devices with 5 -10 minute timeout)
17. check servcie / device env vars
18. os config tests
19. ssh keys tests ( flaky and kill test runs sometimes, but steps 1-17 have enough fat in them to try and …
```

tests: cloud: simplify apps to speedup suite

---

meta-balena-kirkstone/conf/distro/include/balena-os-yocto-version.inc
meta-balena-kirkstone/recipes-connectivity/resolvconf/resolvconf/0001-avoid-using-m-option-for-readlink.patch
meta-balena-kirkstone/recipes-connectivity/resolvconf/resolvconf/99_resolvconf
meta-balena-kirkstone/recipes-connectivity/resolvconf/resolvconf_1.91.bb

Current resolvconf version is broken for kirkstone, which is fixed upstream, so we reuse the fixed version from upstream.
The symptom is that DNS servers provided by DHCP are not being used.
Closes #2907
Changelog-entry: Add upstream resolvconf 1.91 recipe for kirkstone
--- …

resolvconf: Add upstream 1.91 recipe for kirkstone

---

meta-balena-common/classes/sign-efi.bbclass
meta-balena-common/classes/sign-gpg.bbclass
meta-balena-common/recipes-support/balena-keys/balena-keys.bb

If the signing server's response is anything other than successful, such as with an authentication failure or bad request, the HTTP status code and response are hidden due to the --silent flag passed to cURL.
Drop the stdio redirect to the output file along with the --silent flag, and instead use the -o parameter to output the response to the appropriate file on success. This allows the status code and response to be shown in the logs upon failure.
--- …

common: signing: improve debug output on failure

---

meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-bsp/grub/grub-conf/grub.cfg_external_template

Add graphical and serial console output when building in OS development mode.
---

distro: For OS development, enable serial console

---

tests/suites/os/tests/modem/index.js

There were issues in this PR: https://github.com/balena-os/balena-raspberrypi/pull/900 with the modem test
- after the modem test, the DUT had no internet connection
- this led to chrony not being able to sync with ntp servers
- eventually this led to the `config.hson` `ntpServers` test failing
- The reason why, it seemed, was that during the modem test, we set up a route, with a metric of 200, to make the modem interface the "default" interface. At the end of the modem test, we disconnect the modem, but to not delete this route - the OS seemed to try to use this route still
- As a "fix" I now remove this route in the teardown
However, I'd like to know if this is just covering up a legitimate problem. Why does this only fail now with the kirkstone PR?
Context: …

tests: os: fix modem test teardown

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.bb

This will reflect the included supervisor version in the hostapp manifest.
old manifest:
```
balena-supervisor armv7vet2hf-neon 1.0-r0
```
new manifest:
```
balena-supervisor armv7vet2hf-neon 14.4.9-r0
```
--- …

balena-supervisor: Set the supervisor package version

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher.service

In development mode, the flasher service is killed by getty. Revert this change to unbreak the flasher when OS development is enabled.
This reverts commit 131893e433ef64a1f3b05dfcd44b0e022f13646d.
--- …

Revert "flasher: output logs to serial console"

---

meta-balena-common/recipes-connectivity/balena-proxy-config/balena-proxy-config/redsocks.service

This increases the number of open connections that redsocks can support to a new maximum of 2048.
See https://github.com/darkk/redsocks/blob/19b822e345f6a291f6cff6b168f1cfdfeeb2cd7d/base.c#L419
It is motivated by a customer request to increase the number of maximum connections of the redsocks proxy:
https://jel.ly.fish/support-thread-1-0-0-front-cnv-dhcbthp
--- …

redsocks: Increase maximum number of open files

---

meta-balena-common/recipes-bsp/efitools/efitools_git.bb

This EFI image contains the secure boot certificates and when executed it is supposed to load the keys into the respective secure boot slots.
We don't use this binary in our secure boot implementation, but currently the build breaks as the binary is installed but not packaged.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have …

efitools: Package lock down EFI image into its own package

---

meta-balena-common/recipes-connectivity/networkmanager/balena-files/iptables-wait-for-xtables-lock.patch
meta-balena-common/recipes-connectivity/networkmanager/networkmanager_1.40.4.bbappend

iptables takes a file lock at `/run/xtables.lock`. By default, if the file is locked, iptables will fail with error. When that happens, the iptables rules won't be configured, and the shared mode (for which we use iptables) will not be setup properly.
Instead, pass `--wait 2`, to block.
The included patch has to be removed once we upgrade to next NetworkManager version as it is already included upstream.
--- …

networkmanager: Make iptables wait for xtables.lock

---

meta-balena-common/recipes-connectivity/networkmanager/networkmanager_1.40.4.bbappend

In v2.108.0 we did a major NetworkManager upgrade as we started using
meson as a build system. The connectivity check feature was left
disabled, which is a regression and it produces fake results.
This commit enables it back.
Fixes #2964.
--- …

Enable back connectivity check in NetworkManager

---

tests/suites/os/tests/connectivity/Dockerfile.rpi
tests/suites/os/tests/connectivity/Dockerfile.template

The connectivity test fails on the raspberrypi 0 with the following error:
```
Waiting for supervisor to be reachable before local push...
Pushing container to DUT...
[debug] new argv=[/usr/app/balena-cli/balena,/snapshot/versioned-source/bin/balena,push,127.0.0.1,--source,/data/suite/tests/connectivity,--nolive,--detached] length=8
[Debug]   Using build source directory: /data/suite/tests/connectivity
[Debug]   Pushing to local device: 127.0.0.1
[Debug]   Checking we can access device
[Debug]   Sending request to http://127.0.0.1:48484/ping
[Debug]   Checking device supervisor version: 14.4.8
[Info]    Starting build on device 127.0.0.1
[Debug]   Loading project...
[Debug]   Resolving project...
[Debug]   docker-compose.yml file found at "/data/suite/tests/connectivity"
[Debug] …
```

tests: fix connectivity test on rpi0 devices

---

meta-balena-common/recipes-bsp/u-boot/patches/env_resin.h
meta-balena-common/recipes-connectivity/redsocks/balena-files/README.ignore
meta-balena-common/recipes-connectivity/redsocks/balena-files/redsocks.conf.ignore
meta-balena-common/recipes-connectivity/redsocks/redsocks_0.5.bb
meta-balena-common/recipes-core/images/balena-image-flasher.bb
meta-balena-common/recipes-core/images/balena-image.bb

recipes-bsp/u-boot: Import extra uboot environment from scanned devices
This allows for the testbot to set resin_flasher_skip=0
in the extra_uEnv.txt file of the flasher image and
bypass the boot switch detection mechanisms used for
specific private device types.
The boot pins would otherwise prevent the flasher
from running if they were set to the eMMC position.
The flasher extra_uEnv.txt file overrides any resin_flasher_skip
value previously configured by the device integration layer.
Added this change as per the internal discussion: https://balena.zulipchat.com/#narrow/stream/360838-balena-os.2Fdevices/topic/XXX/312607356
This PR also adds sample proxy files in the boot partition, similar to the ones for …

recipes-bsp/u-boot: Import extra uboot environment from scanned devices, add sample proxy files

---

meta-balena-common/recipes-core/balena-rollback/files/rollback-health

With secure boot enabled boot and EFI partition are split apart. During rollback-health, when bind-mounting inactive root to run old hooks from, the EFI partition must be bind-mounted as well otherwise the /mnt/boot/EFI symlink is invalid and rollback fails to deploy files into that directory.
--- …

rollback-health: bind-mount EFI partition when split from boot

---

tests/suites/os/tests/config-json/index.js

there is currently an issue with persistent logging on the rpi0 https://github.com/balena-os/balena-raspberrypi/issues/927
in order to accelerate releases for this device type @alexgg suggested we could skip this test for the pi0, as its currently blocking
--- …

tests: os: skip persistent logging test for pi0

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

When refactoring secure boot setup, a logic mistake in the purpose and use of SECUREBOOT_VAR meant that devices booting the flasher with keys already enrolled would bail out with an incorrect message about secure boot not being supported in firmware.
This variable is `00` on systems with secure boot support in firmware, but not enabled and enforced, `01` on systems where secure boot is enforced, and empty when secure boot is unsupported.
Change this conditional to bail out only when the variable is empty, indicating that secure boot is unsupported.
--- …

flasher: fix secure boot setup with enrolled keys

---

meta-balena-common/classes/kernel-balena.bbclass

Newer releases of moby expect appArmor userland tools when appArmor is enabled in the kernel.
---

kernel-balena: Remove apparmor support

---

.github/renovate.json

This allows properly formatted commit messages to support nested changelogs.
---

renovate: Include to and from versions for supervisor and engine

---

docs/secure-boot.md

Document the opt-in boolean for secure boot and full-disk encryption.
---

docs: add section for sb/fde opt-in

---

tests/suites/hup/suite.js

the tx2 has exhibited a weird quirk with the hup suite. When trying to flash the DUT with the most recent prod image fetched via the SDK, the DUT fails to internally flash - it turned out that it was due to `resin-device-register` failing during `resin-init-flasher`. 
```
[ERROR] resin-device-register : Please set API_ENDPOINT and CONFIG_PATH environment variable
```
Adding the `apiEndpoint: 'https://api.balena-cloud.com',` to the DUT `config.json` fixes this issue. It is unknown why this fails only specifically for the tx2 device type - potentially there is some sort of sequencing or timing difference. 
---
- '*Approve*' if this change would be acceptable in the codebase (even if there …

tests: hup: fix flashing for tx2

---

.github/renovate.json

The engine is currently versioned in such a way that upstream semver tags are added to branches before merging to master.
We don't want to try and pin to those commits so only consider automated GitHub Releases.
[skip ci]
--- …

renovate: Only consider github releases when bumping engine

---

meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs

Block device nodes are sometimes created without attached media. These devices can neither be read from, nor written to. In this case, the flasher will attempt to install to the invalid disk and fail.  Detect this case and skip the disk to allow flashing to continue.
```
sh-5.1$ ls -la /dev/sda
brw-rw---- 1 root disk 8, 0 Feb  9 09:36 /dev/sda
sh-5.1$ lsblk /dev/sda
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
sda    8:0    1   0B  0 disk 
sh-5.1$ fdisk -l /dev/sda
fdisk: cannot open /dev/sda: No medium found
sh-5.1$ echo $?
1
```
---
- '*Request Changes*' …

os-helpers-fs: get_internal_device() skip disks w/out media

---

meta-balena-common/recipes-containers/balena/balena_git.bb

Update balena-engine from 20.10.17 to 20.10.25
Changelog-entry: Update balena-engine to v20.10.25
---

balena-engine: Update to 20.10.25

---

meta-balena-common/classes/kernel-balena.bbclass
meta-balena-common/recipes-core/images/balena-image-initramfs.bb
meta-balena-common/recipes-core/packagegroups/packagegroup-resin.bb
meta-balena-common/recipes-core/packagegroups/packagegroup-resin.inc
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars.bb
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/balena-config-vars
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
meta-balena-common/recipes-support/resin-init/resin-init-flasher.bb
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

This subset of changes from the `alexgg/installer` branch optimizes dependencies to reduce the size of the initramfs images, along with other changes required while testing the initramfs installer feature.
---

[installer] Preparation changes

---

README.md
docs/initramfs.md
meta-balena-common/recipes-core/images/balena-image-initramfs.bb
meta-balena-common/recipes-core/initrdscripts/files/finish
meta-balena-common/recipes-core/initrdscripts/files/migrate
meta-balena-common/recipes-core/initrdscripts/files/recovery
meta-balena-common/recipes-core/initrdscripts/files/rootfs
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
meta-balena-dunfell/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-thud/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-warrior/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-resin-pyro/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-resin-rocko/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-resin-sumo/recipes-core/initrdscripts/initramfs-framework_%.bbappend

This patchset introduces a migrator module to the initramfs that is capable of programming the direct boot image into internal storage from memory.
Applications for this mode include OS migration and also secure boot and disk encryption installation on non-flasher device types.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the …

Migration support

---

meta-balena-common/recipes-core/initrdscripts/files/migrate
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs

The `du` utility has the same output format for single or several files, while the `wc` utility doesn't and does not display a total for single files.
---

initrdscripts: migrate: use du instead of wc to calculate byte sizes

---

meta-balena-common/recipes-core/balena-rollback/files/rollback-tests

Previously, it was being referred to only as "balena". Being explicit that this is about balenaEngine makes it simpler to grep for Engine-related portions of balenaOS. Might also help a tad bit when looking at logs.
@klutchell Thanks for pointing me into the right files. I haven't located this because all my searches were using "engine", which is not mentioned at all in this file. I am proposing this little change to make it more discoverable. WDYT?

HUP rollback checks: refer to balenaEngine by its full name

---

meta-balena-common/recipes-support/balena-keys/balena-keys.bb

We have added DER certificates because it is the only format that QEMU/TianoCore accepts in UEFI setup. Since we made setup mode work properly, there is no need to program the QEMU keys manually and therefore there is no reason to pollute the boot partition with the DER files. If indeed necessary, they can always be extracted from the ESL, which is still shipped. Shipping the DER files is also not possible when db uses hashes instead of certificates, which we want to move towards.
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in …

balena-keys: do not ship certificates in DER format

---

meta-balena-common/classes/image-balena.bbclass

`do_resin_boot_dirgen_and_deploy` needs all the partial files deployed when it runs as it will be copying them to the actual boot partition. There is a race condition between it and `grub_conf:do_deploy`, we have seen builds fail when `grub_conf:do_deploy` does not execute in time. This patch adds an explicit dependency to avoid such situation.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you …

image-balena.bbclass: deploy grub-conf before building the boot partition

---

tests/suites/os/suite.js
tests/suites/os/tests/internet-sharing/index.js

Test for the NetworkManager patch done in https://github.com/balena-os/meta-balena/pull/2963
A racing condition between balenaEngine and NetworkManager led to some Internet connection sharing iptables rules not being applied when NM connection profile with Internet sharing was activated at boot.
This test checks whether all necessary iptables rules are added by artificially blocking iptables for 1 second and then for 3 seconds while a connection profile with Internet sharing is activated.
---
- '*Request Changes*' if this change would not be …

NetworkManager iptables rules test for Internet connection sharing

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Previously, we bailed out of the installer when the system was in user mode (keys enrolled) but the user had not opted in to secure boot, as it was ambiguous whether the user actually wanted SB/FDE.
However, some systems come with vendor keys pre-enrolled, and a user may simply turn off secure boot in the firmware setup menu without erasing the keys. This would result in the installer bailing out even though secure boot is disabled in the firmware menu.
Check that secure boot is enabled in addition to having keys enrolled before bailing out.
---
- '*Request Changes*' if this change would not be …

flasher: fix installation when in user mode w/ sb disabled

---

tests/suites/os/tests/internet-sharing/index.js

In the Internet connection sharing test one of the checks may run into a racing problem. The following command is holding the iptables lock for 3 seconds while NetworkManager activates a connection with sharing enabled:
`flock /run/xtables.lock sleep 3 & nmcli c up dummy & wait`
NetworkManager waits for 2 seconds for the lock to be released and those three seconds should be enough for one of the iptables rules to fail. However there is no guarantee that NetworkManager will start adding the iptables rules that quickly - it may start adding those after one out of those three seconds already passed, which will lead to all iptables rules to be set at the end.
This check is non-essential for the test itself, so it is removed with this commit.
---
- When submitting a review, …

Remove a bad check in Internet connection sharing test

---

meta-balena-common/recipes-core/images/balena-image-flasher.bb

This avoids device repositories having to specify it, and it can always be overwritten in append files.
This change is an extension of https://github.com/balena-os/meta-balena/commit/a3c276a1058d05e66991871bf167079fc2824843
--- …

balena-image-flasher: Default image type to balenaos-img

---

.github/renovate.json

renovate: Inherit automerge settings from org

---

tests/suites/cloud/suite.js
tests/suites/hup/suite.js
tests/suites/os/suite.js

There are 2 changes in this PR:
1. reword and re-organise the initial attempt at connecting to the DUT via the local SSH connection. Making this a "test" improves the logging slightly, and reports a cleaner message than the error that was thrown before. This will make it more obvious to newcomers what has happened, and includes this failure to connect within the test report
2. add a simple test to the cloud and OS suites at the beginning to confirm that the engine and supervisor are running. This is to immediately and clearly catch cases where either, in particular the supervisor, don't start and get into a healthy state. Without this, we would have to wait until the `container-healthcheck` tests to find out if the supervisor has started in the os suite- and even then, its not clear from …

tests: make immediate problems more clear in all suites

---

meta-balena-common/recipes-core/initrdscripts/files/migrate
meta-balena-common/recipes-core/initrdscripts/files/recovery
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

The internal target device to program is not always the device the system is booting from. Make sure the `flash-boot` partition search is done on the booting device.
---

initrdscripts: migrate: correctly identify boot device

---

meta-balena-common/classes/kernel-balena.bbclass
meta-balena-common/classes/sign-efi.bbclass
meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-bsp/efitools/efitools_git.bb
meta-balena-common/recipes-bsp/grub/grub-efi_%.bbappend
meta-balena-common/recipes-core/balena-rollback/files/rollback-health
meta-balena-common/recipes-support/balena-keys/balena-db-hashes.bb
meta-balena-common/recipes-support/balena-keys/balena-keys.bb
meta-balena-common/recipes-support/hostapp-update-hooks/files/0-signed-update
meta-balena-common/recipes-support/resin-init/resin-init-flasher.bb

This patch changes the validation of bootable images from certificate signatures to a list of allowed hashes of binaries. This only applies on db level, PK and KEK are still certificates.
The motivation is that certificates expire and we need to be sure that even devices that have been lying on a shelf for several years or whose CMOS battery has died and reset date to 1970-01-01 are still bootable. Using hashes is more aligned with this use-case and also more similar to the approach that embedded SoCs use.
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will …

Use hashes instead of certificates for secure boot image validation

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup

At this moment if the cryptsetup initrd script executes before the root device comes up (e.g. when booting off a USB disk), it assumes that encryption is not in place because it was not able to find the EFI partition.
This patch adds a wait4file loop to the script that waits for the /dev/disk/by-state directory. This is not tied to any particular partition or device but since the directory does not exist by default and is only created by a custom balenaOS udev rule, its existence implies that the rule fired and a device with balenaOS partitions is present in the system.
---
- '*Request Changes*' if this change would …

initrdscripts: give the root device a chance to come up before cryptsetup

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

This fixes corner cases discovered while testing on a variety of HW. It should make more HW work with secure boot out of box.
---

flasher: make secure boot provisioning more robust

---

tests/suites/cloud/suite.js
tests/suites/config.js
tests/suites/hup/suite.js
tests/suites/os/suite.js

At the moment we use the `networkWired` and `networkWireless` attributes in the suites config.js to determine whether or not to access the DUT via wifi or ethernet. 
We have this hard coded to be wifi in meta balena. So we are blocked when running tests on devices with ethernet only (without using a usb wifi dongle as we've done in the past). So this PR:
- sets the default config.js `networkWired` and `networkWireless` in this repo, which is used in jenkins, to false
- the test suite checks the devicetype contract to determine whether or not to use wifi or ethernet
- setting `networkWired` or `networkWireless` to true in the config.js overrides the contract - which is useful for debugging connectivity issues
- dependant on this PR: https://github.com/balena-os/leviathan-worker/pull/64 - …

tests: use deviceType contract to determine network config

---

meta-balena-common/recipes-support/os-helpers/os-helpers.bb

The purpose of testing the API calls is to detect breaking changes, not to fail builds because of temporary network or API access problems.
Printing a warning instead should be enough for developers to detect breaking changes.
--- …

os-helpers: do not fail build if API tests fail

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

When running in the initramfs, the resin-device-progress package is not installed as we cannot guarantee that the initramfs would be able to bring up all types of network interfaces.
This commit adds a check for the script to exists instead of getting a `command not found` when an API endpoint is defined.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, …

resin-init-flasher: check that commands exist before calling

---

docs/secure-boot.md

This patch extends secure boot documentation with more details about how the feature works and tries to explain why some decisions were made.
---

docs: Make secure boot docs more detailed

---

meta-balena-common/recipes-containers/balena/balena_git.bb

Update balena-engine from 20.10.26 to 20.10.35
---

Update balena-engine to v20.10.35

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

This should be the default but with no explicit argument we still end up with LUKS1 partitions. This patch adds the parameter to enforce LUKS2 formatting.
---

resin-init-flasher: Format encrypted partitions as LUKS2

---

meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-support/balena-keys/balena-keys.bb

This variable accepts the base64 encoded public key of a kernel module signing keypair and appends it to the list of trusted keys the kernel will use to validate signed modules. Multiple keys may be appended, delimited with a semicolon.
A PEM file can be used like so:
```
SIGN_KMOD_KEY_APPEND="$( sed -e '/-----BEGIN CERTIFICATE-----/d' \
-e 's/-----END CERTIFICATE-----/;/g' \
-e '$d' signing_key.pem \
| tr -d '\n' )"
balena-yocto-scripts/build/balena-build.sh \
-g "-a SIGN_KMOD_KEY_APPEND=${SIGN_KMOD_KEY_APPEND}" \
...
```
--- …

balena-keys: add SIGN_KMOD_KEY_APPEND

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

After switching to LUKS2, the header size increased from 2MB to 16MB. While HUP of older systems works, it is impossible to provision new encrypted systems.
This patch fixes the header size in flasher.
---

resin-init-flasher: Increase size of LUKS header to 16MB

---

meta-balena-common/recipes-core/initrdscripts/files/kexec

Kexec is used to boot into the decrypted kernel in the hostapp on systems with secure boot and full-disk encryption.
If kexec fails, we don't want to continue with the rest of the boot process in the first stage kernel, so bail out on failure.
--- …

bail out in kexec initramfs hook on failure

---

meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend

cryptsetup lazily depends on libgcc. With libgcc missing, certain operations, especially luksOpen will fail with
`libgcc_s.so.1 must be installed for pthread_exit to work` which panics the kernel and triggers a reboot loop indistinguishable from a "device has been tampered with" state on regular builds with no console output.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you …

initrdscripts: make initramfs-module-cryptsetup pull libgcc in

---

tests/suites/cloud/suite.js
tests/suites/hup/suite.js
tests/suites/os/suite.js

This DT is similar to the ebcrs08a2, which uses a u-boot check for the boot switch to skip provisioning.
---

Skip boot switch check for imx8mm-var-dart-plt

---

meta-balena-common/recipes-core/images/balena-image.bb

Some board BSPs may define UBOOT_MACHINE, others UBOOT_CONFIG, let's make sure we include the extra_uEnv.txt file in the non-flasher image for both cases.
---

balena-image: Install extra_uEnv for all boards that use u-boot

---

meta-balena-kirkstone/recipes-kernel/linux/kernel-devsrc.bbappend

This fix has been ported from the following upstream change: https://patchwork.yoctoproject.org/project/oe-core/patch/002c31d6add77e1002fb1ccd4050ce826a654170.1659653543.git.bruce.ashfield@gmail.com/ and fixes the following compilation error on generic-aarch64:
make[1]: *** No rule to make target 'arch/arm64/tools/gen-sysreg.awk',
needed by 'arch/arm64/include/generated/asm/sysreg-defs.h'.  Stop.
Fixes build failure for generic-aarch64 in https://github.com/balena-os/balena-generic/pull/263
--- …

linux/kernel-devsrc: Fix aarch64 kernel-headers-test build

---

meta-balena-common/classes/kernel-balena.bbclass

The kernel-balena class contains:
CONIFG_SECURITY=n
which is mispelled and not being applied. The commit where this was introduced claims it's needed to completely disable the audit logs, and also that the security framework is unused.
I disagree in that it's unused - the hostOS is not using any security framework, but applications may, so luckily the security framework was never disabled.
Removing this mispelled entry should have no functional effect. Whether the audit subsystem is disabled will depend on the final kernel configuration. Definitely we have not seen a need to disable it recently, and we have not seen the kernel log flooded with messages.
I'd argue the disabling of the audit subsystem in meta-balena serves no need but I also have no specific reason to remove it at the …

kernel-balena: remove mispelled config setting

---

.github/workflows/meta-balena-esr.yml
.github/workflows/update-backports.yml

These permissions have already been removed from flowzone-app[bot] so they cannot be requested at runtime.
---

Reduce scope of app token used for backports and ESR

---

meta-balena-common/recipes-support/resin-device-register/resin-device-register/resin-device-register
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher.service

314047e and b5c5214 made flasher block until the resin-device-register service exits and made resin-device-register give up after 6 seconds not to block infinitely when no network is available. This effectively means that if the device fails to register within first 6 seconds, it will never retry, flasher will not report status to the dashboard and the device will only register on first boot.
This patch changes the logic back to resin-device-register trying in the background in an infinite loop and moves the "give the device a chance to register" delay to flasher itself. It also extends the wait to openvpn as flasher already does that and wants VPN to run to be debuggable - in case flashing fails, it would be possible to SSH in via the VPN and look at the logs remotely. …

resin-init-flasher: Allow background device registration

---

tests/suites/os/tests/engine-healthcheck/index.js
tests/suites/os/tests/overlap_test/index.js

On at least the beaglebone black, we have a timing issue on this test - the previous test manipulates the dev/prod mode of the device and there's a chance that if that action takes too long, then this test is interfered with. 
I added a retry to the first part of this test which fixes the failure. 
--- …

tests: os: add retry to decreasing watchdog timeout to prevent timing issues in test

---

.gitmodules
tests/suites/os/tests/secureboot/index.js

Verify kernel lockdown prohibits loading of unsigned modules, and still loads modules with a signature that validates against a trusted key.
---

tests: secureboot: add test for module signing

---

meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update

The hostapp-update hooks for UEFI capsule updates
need to create and update the contents of some platform specific efi variables inside the /sys directory, and thus we need to bindmount this directory in the hostapp-update script for internal testing as well as in balenahup for api triggered updates.
Tested on AGX Orin Devkit
Connects-to: https://github.com/balena-os/balena-jetson-orin/pull/238
--- …

hostapp-update: bind-mount /sys for Jetson efivars

---

meta-balena-thud/recipes-core/initrdscripts/initramfs-framework_%.bbappend

On Thud, the util-linux recipe had still not split components into different packages.
---

meta-balena-thud: adapt migrate module dependencies

---

meta-balena-common/classes/resin-u-boot.bbclass

The env_get() function was renamed from getenv() in commit 00caae6d47645e68d6e5277aceb69592b49381a6
env: Rename getenv/_f() to env_get()
Fix the balena_check_crc32 function to build for those older u-boots too.
--- …

resin-u-boot.class: Fix for older u-boot versions

---

meta-balena-warrior/conf/distro/include/balena-os-yocto-version.inc
meta-balena-warrior/conf/layer.conf
meta-balena-warrior/recipes-connectivity/libmbim/libmbim_1.26.2.bb
meta-balena-warrior/recipes-connectivity/libqmi/libqmi_1.30.2.bb
meta-balena-warrior/recipes-connectivity/modemmanager/balena-files/77-mm-huawei-configuration.rules
meta-balena-warrior/recipes-connectivity/modemmanager/balena-files/77-mm-u-blox-modeswitch.rules
meta-balena-warrior/recipes-connectivity/modemmanager/balena-files/ModemManager.conf.systemd
meta-balena-warrior/recipes-connectivity/modemmanager/balena-files/core-switch-bash-shell-scripts-to-use-bin-sh-for-use.patch
meta-balena-warrior/recipes-connectivity/modemmanager/balena-files/mm-huawei-configuration-switch.sh
meta-balena-warrior/recipes-connectivity/modemmanager/balena-files/u-blox-switch.sh
meta-balena-warrior/recipes-connectivity/modemmanager/balena-files/u-blox-switch@.service
meta-balena-warrior/recipes-connectivity/modemmanager/modemmanager_%.bbappend
meta-balena-warrior/recipes-connectivity/modemmanager/modemmanager_1.18.4.bb

The current meta-balena libmbim is not compatible with sumo's libc version.
---

meta-balena-warrior: hold libmbim, libmbim and modemmanager versions

---

meta-resin-pyro/conf/layer.conf

The meta-balena version of modemmanager is no longer compatible with Yocto Pyro, so stop trying to apply bbappend to it from meta-balena.
---

meta-resin-pyro: do not apply further modemmanager updates

---

meta-balena-common/classes/sign-efi.bbclass
meta-balena-common/classes/sign-gpg.bbclass
meta-balena-common/classes/sign-kmod.bbclass

When the signed artifacts are big we see closed connections because of timeouts in the front caches. A retry should help.
---

classes: sign: add a retry to the signing call

---

meta-balena-common/recipes-connectivity/modemmanager/modemmanager_%.bbappend

That feature was lost when transitioning from autotools to meson.
Changelog-entry: Enable back ModemManager AT commands through D-Bus and	mmcli
---

modemmanager: Enable back AT commands through D-Bus and mmcli

---

meta-balena-common/recipes-containers/balena/balena_git.bb

Update balena-engine from 20.10.39 to 20.10.40
This version uses containerd shim runtime v2, so this PR also adjusts the balenaEngine symlinks to match what is now expected.
---

Update balena-engine to v20.10.40

---

meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update

This is so that the HUP reboot doesn't interrupt
any user service processes.

Check and get service lockfiles on HUP reboot

---

.github/workflows/meta-balena-esr.yml
.github/workflows/update-backports.yml

Flowzone App no longer has workflow:write permissions for security reasons.
This new balenaOS ESR bot has contents:write and workflows:write permissions but is only available on balenaOS repositories.
See: https://github.com/apps/balenaos-esr
--- …

workflows: Switch to balenaOS ESR [bot] for authentication

---

meta-balena-common/recipes-connectivity/balena-net-config/balena-net-config/balena-net-config

This commit fixes the following error:
```
nm-dispatcher[4209]: req:1 'hostname': find-scripts: Cannot execute '/etc/NetworkManager/dispatcher.d/50-example-script.sh': not executable by owner.
```
--- …

balena-net-config: Ensure NM dispatcher scripts are executable

---

meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs

Fix improperly returning multiple matching devices in `get_internal_device`

---

meta-balena-common/classes/kernel-balena.bbclass

This is no longer needed after the balena_os/balena-engine commit: https://github.com/balena-os/balena-engine/commit/ed8ba18e8776a7bf37b3326baeca8196b4ea76b0
released in balena-engine v20.10.39
This reverts commit 18cd233a83554b58b3540164afd768fdeda60b03.
--- …

Revert "kernel-balena: Remove apparmor support"

---

meta-balena-common/recipes-core/plymouth/plymouth_%.bbappend

This flag isn't needed on balenaOS as the splash screen remains even after plymouthd is stopped.
Having the flag in place prevents user apps from writing to tty consoles after stopping plymouth via dbus.
See: https://balena.fibery.io/Inputs/Pattern/User-apps-cannot-write-to-tty-screens-in-balenaOS-2.113.18-4471
--- …

plymouth: Remove --retain-splash flag from plymouth quit

---

tests/suites/config.js

needed to allow for more easily setting multiple worker fleets in jenkins. 
to use, in the jenkins configuration change `BALENACLOUD_APP_NAME` to a comma separated list
---

tests: allow for multiple worker fleets

---

meta-balena-common/recipes-core/balena-rollback/balena-rollback.bb
meta-balena-common/recipes-core/balena-rollback/files/rollback-board-healthcheck
meta-balena-common/recipes-core/balena-rollback/files/rollback-tests

In this PR we add a generic script which can be overridden by device integration repositories to run device-specific healthchecks in the new OS, after HUP.
This allows devices like Jetsons to check if the UEFI firmware they run after the update is in sync with the kernel version, and the rest of the BSP elements.
Connects-to PR: https://github.com/balena-os/balena-jetson-orin/pull/348 / Commit: https://github.com/balena-os/balena-jetson-orin/pull/348/commits/b47e0ff20c160544993d130039c6c26d4982229b
Added as per the internal discussion: https://balena.zulipchat.com/#narrow/stream/360838-balena-io.2Fos.2Fdevices/topic/Jetson.20AGX.20Orin.20devkit/near/400946825
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are …

balena-rollback: Run device-specific healtchecks

---

meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-logging

Detecting whether the script is running in a PID namespace by checking `/proc/1/sched` does not work for newer kernels
(see https://github.com/systemd/systemd/pull/17917).
Properly detecting this is too cumbersome for a bash logging script, see https://github.com/systemd/systemd/pull/17902, however, falling back to the last check, that is, seeing if `/.dockerenv` exists is easy enough and works for our use case.
This scritp will only be called from the hostOS, and the only case it is called from a container during in HUP and the container is always a hostOS image. So even though the interface chosen by moby, a file under /, is bad interface in general, it works fine for the specific limitations of balenaOS.
---
- '*Approve*' if …

os-helpers-logging: replace broken container check

---

meta-balena-common/recipes-core/systemd/timeinit/timesync-https.sh

We have seen cases of networks that were not able to receive a response in the current 5s.
Increasing the default to 10s should have no negative effect.
---

timesync-https: increase default connection max time to 10s

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/hostapp-update-hooks

This provides an easy switch to enable tracing on HUP hooks.
---

hostapp-update-hooks: add debug mode

---

meta-balena-common/recipes-core/initrdscripts/files/finish
meta-balena-common/recipes-core/initrdscripts/files/migrate
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend

The log files are kept in the /run partition that also houses the udev database.
By moving the /run partition to $ROOTFS_DIR/run in the migrate module, the udev database persists across reboots.
The udevcleanup module was introduced to cleanup the database so it's regenerated on the final rootfs as the rules are different between initramfs and final rootfs. By moving /run before udevcleanup ran, the cleanup was not effective.
This commit moves the relocation of the /run mount to the finish module, after udevcleanup is run, and groups it with the other relocations needed for the pivot switch.
Looking at git history, the relocation of the /run partition was initially done in the rootfs module, so when the migrate module was introduced and needed to mount the rootfs, this relocation was just …

initrdscripts: move mounting of log mounts to finish module

---

meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/balena-config-vars

There have been reports of an empty config vars cache file - probably because of a race condition when the reading of config.json happens just as the file is being replaced.
Add some checks and retries to avoid this errors from happening.
--- …

balena-config-vars: increase config.json parsing resilience

---

meta-balena-common/recipes-connectivity/networkmanager/balena-files/90shared
meta-balena-common/recipes-connectivity/networkmanager/networkmanager_1.40.4.bbappend

At this moment there is a race condition between NetworkManager and the engine when a shared interface is configured. If the interface is configured first and the engine second, the containers are allowed to access DHCP hosts behind the shared interface. If the engine comes up first and the shared interface second, access will be denied.
This patch adds a dispatcher script that always configures the firewall rules as if the engine came up last. This does not really address the underlying issue but it overcomes the race condition and makes the behavior deterministic, which is good enough at this point.
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be …

networkmanager: make FORWARD rules for shared interfaces last in chain

---

meta-balena-common/classes/balena-bootloader.bbclass
meta-balena-common/recipes-core/initrdscripts/files/kexec

Extract common bits for balena bootloader

---

meta-balena-common/recipes-core/images/balena-image-bootloader-initramfs.bb
meta-balena-common/recipes-core/initrdscripts/files/fsck

The balena bootloader initramfs contains the rootfs module and that will get the rootfs mounted but not checked first for errors. This is problematic because at first boot with network connectivity available, time will sync but the rootfs will still have the last mount time in
1970. If at that point the rootfs gets corrupted then at next boot the rootfs' initramfs module from balena-bootloader will try to mount the rootfs without checking it first and then after that the filesystem check triggered by the fsck module from the actual kernel initramfs will fail like this:
[init][INFO] Running filesystem checks on partition resin-rootA (/dev/disk/by-state/resin-rootA) resin-rootA contains a file system with errors, check forced. resin-rootA: Inodes that were part of a corrupted orphan linked …

balena-image-bootloader-initramfs.bb: Add fsck module

---

tests/suites/cloud/suite.js

This is to solve the test failures for the cloud suite when there is no existing balena cloud release - causing the app creation to fail. In this case we use a generic-arch fleet instead. 
Should reduce some of the friction for first deployment
--- …

tests: cloud: if no existing release, create generic fleet

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher.bb

Without this dependency, the call to `jq` does not happen and the check for INTERNAL_DEVICE_KERNEL is not performed.
Several devices that define internal storage but do not define INTERNAL_DEVICE_KERNEL will now fail and need to be fixed.
--- …

resin-init-flasher: add jq dependency

---

tests/suites/cloud/suite.js
tests/suites/hup/suite.js
tests/suites/os/suite.js

The revpi-connect-4 was found to have connectivity issues with the autokit wifi AP - which were resolved by configuring it to use the external antenna - even if no antenna was connected. It is thought that there was EMI or signal power issues.
--- …

tests: enable revpi-connect-4 in automated tests

---

meta-balena-common/recipes-core/os-config/os-config/os-config.service

OS-config should always run after extracting balena CA to prevent race conditions
---

Start os-config service after extracting CA

---

meta-balena-common/recipes-core/systemd/systemd/resin_update_state_probe

At this moment `resin_update_state_probe` looks for the root partition by UUID and assumes that only a single device is returned. This assumption breaks when the root is on a MD RAID1 device as not only the virtual MD device holds a filesystem with the given UUID, each member does as well.
This patch makes `resin_update_state_probe` ignore devices that are RAID members which in that case will only return the MD device as expected.
---
- …

resin_update_state_probe: ignore RAID members when looking for root

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/hostapp-update-hooks
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-sb

a203bcdfd567c0cc4b4ed9de493513142cd7463f introduced a dependency on `/usr/sbin/balena-config-defaults` to `hostapp-update-hooks`, however during HUP the script is not only executed in the "new" OS container but directly in the context of the "old" OS as well, so `/usr/sbin/balena-config-defaults` needs to exist there. The file was introduced in balenaOS v2.99.28, so trying to HUP from anything before that will fail.
This patch changes this to a soft dependency so even if the file is missing HUP will continue.
--- …

hostapp-update-hooks: Soft include balena-config-defaults

---

meta-balena-common/recipes-core/images/balena-image-initramfs.bb
meta-balena-kirkstone/classes/kernel-balena-noimage.bbclass

Remove unneeded kernel image from initramfs

---

meta-balena-common/recipes-containers/mkfs-hostapp-native/files/create.ext4

We don't need any iptables features in order to perform hostapp-update in this build recipe, and it has no impact on build output.
It does, however, improve compatbility with build environments and reduces the dependencies of the build host kernel.
--- …

mkfs-hostapp-native: Disable iptables features in yocto balena daemon

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

The v16.1.5 supervisor release has been invalidated due to problems with applying firewall rules.
---

Update balena-supervisor to v16.1.10

---

meta-balena-common/recipes-connectivity/networkmanager/balena-files/90shared

The dispatcher script that moves around FORWARD rules of shared interfaces currently calls iptables assuming it will always work but in practice two iptables commands can not run in parallel and we have occasionally seen the script fail with:
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
This patch adds the -w option to make the script wait for the lock when necessary.
It also makes the script exit with an error code if anything fails, which will log the output as WARN instead of INFO as the errors are easy to overlook at this moment.
---
- '*Request …

networkmanager: Wait for iptables lock in shared dispatcher script

---

meta-balena-common/recipes-core/packagegroups/packagegroup-resin.inc

The takeover project currently relies on the ldd script being present in the hostOS pre-migration.
While takeover can be adapted to use this script from a different location, it wouldn't hurt to have ldd in the hostOS from this point on.
Related discussion in takeover: https://github.com/balena-os/takeover/pull/66#discussion_r1526661273
--- …

packagegroup-resin: Install ldd script in balenaOS images

---

tests/suites/os/tests/connectivity/index.js
tests/suites/os/tests/modem/index.js

This change is required to migrate existing tests to run QEMU worker tests on GitHub Actions.
GitHub hosted runners can't run the `ping` command: https://github.com/actions/runner-images/issues/1519 by design. If we still intend to use `ping`, the solution would be running QEMU worker tests on self-hosted runners which allow ICMP packets
This change is intended to be backwards compatible and shouldn't affect tests running on Jenkins or for the autokit
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
--- …

Test: Unmanaged: Replace ping command in tests with curl

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/hostapp-update-hooks

Older balenaOS version (before v2.58) do not contain the logging helper in the rootfs and the new OS hooks fail to execute.
This commit checks for the file existence before using it, and defines the logging functions when not detected.
--- …

hostapp-update-hooks: check for logging helper

---

meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
meta-balena-common/recipes-support/hostapp-update-hooks/files/0-signed-update
meta-balena-common/recipes-support/hostapp-update-hooks/files/95-secureboot/2-fwd_commit_update-policy
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-sb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-tpm2

A missing semi-colon caused the firmware_measures_efibins function to
return an exit code of one, which the 0-signed-update hostapp-update
hook interpreted as "this firmware does not measure EFI binaries into
PCR 7", as opposed to zero, indicating "this firmware *does* measure EFI
binaries into PCR 7", or two, indicating "the TPM event log is
unavailable and it's impossible to tell."
Taking the wrong branch in this conditional led to an inappropriate
policy being created to seal the LUKS passphrase, which could not be
unlocked on the next boot, as in QEMU with edk2, EFI binaries *are*
measured into PCR 7.
Manual tests:
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be …

PCR 7 sealing fixes

---

README.md
docs/secure-boot-abstractions.md
meta-balena-common/classes/balena-bootloader.bbclass
meta-balena-common/classes/image-balena.bbclass
meta-balena-common/classes/kernel-balena.bbclass
meta-balena-common/classes/sign-efi.bbclass
meta-balena-common/classes/sign-rsa.bbclass
meta-balena-common/recipes-core/images/balena-image-bootloader-initramfs.bb
meta-balena-common/recipes-core/initrdscripts/files/fsuuidsinit
meta-balena-common/recipes-core/initrdscripts/files/migrate
meta-balena-common/recipes-core/initrdscripts/initramfs-module-abroot_1.0.bb
meta-balena-common/recipes-core/systemd/systemd/resin_update_state_probe
meta-balena-common/recipes-support/hostapp-update-hooks/files/1-bootfiles
meta-balena-common/recipes-support/hostapp-update-hooks/files/99-balena-bootloader
meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Depends on https://github.com/balena-os/meta-balena/pull/3408
---

CM4 secure boot

---

tests/suites/os/tests/modem/index.js
tests/suites/os/tests/modem/modems.json

The modem test was broken when changing from ping to curl as part of 071c018. Here it is fixed
---

tests: os: modem: fix curl command

---

meta-balena-common/recipes-connectivity/networkmanager/balena-files/90shared

Manipulating the firewall rules by index introduces a race condition. Both NetworkManager and balenaEngine add the rules to the top of the `FORWARD` chain instead of appending, so if we first look up a rule by number and then use the number to refer to it, we can not guarantee that the rule number has not changed (iow the rule has not been moved down) in the meantime.
This patch removes the use of rule numbers completely and makes the "shared" dispatcher script refer to the rules by definition.
--- …

NetworkManager: do not use FW rule numbers in shared dispatcher script

---

tests/suites/cloud/config.js
tests/suites/hup/config.js
tests/suites/os/config.js

To parallelize test runs on GHA, having separate test suite-specific configs available would be the way to go. 
This change is backward compatible with the current Jenkins configuration.
Reasoning: Each matrix job of Leviathan will run one test suite using this one config modification made in this PR. This will allow us only to retry a single test suite and not all 3 again. 
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

patch: Add Test Suite specific config for GHA

---

meta-balena-common/recipes-core/balena-rollback/files/rollback-health
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-tpm2

Secure boot rollback fixes

---

meta-balena-common/recipes-containers/balena/balena/balena-healthcheck

We have detected one more way in which the uuid file used by containerd can get corrupted. This time, the file is not empty, but doesn't contain a valid UUID either.
This commit thus extends the existing workaround to also handle this case.
See https://github.com/balena-os/balena-engine/issues/322
I tested this manually only. I built balenaOS for raspberrypi3-64 using my branch of meta-balena and flashed it to a device. Then I tried to manually change the contents of the `uuid` file and run the health check to see the results:
* When changing it to one of the formats accepted by containerd, the healthcheck passed and the `uuid` file remained unchanged.
* When changing it to an invalid format (including making it an empty file), or removing it altogether, the healthcheck passed and and …

Work around uuid file corruption in balenaEngine health check

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/1-bootfiles

…luding
The `os-helpers-sb` file is only included for signed builds.
---

hostapp-update-hooks: 1-bootfiles: Check for os-helpers-sb before using

---

meta-balena-common/classes/kernel-balena.bbclass

On parallel builds that share a state cache there are mismatches between a signed kernel and modules. Avoid using the cache when building signed modules to avoid this mismatch.
---

kernel-balena: do not use cache for signed kernel modules

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/0-signed-update

In 328222014146f0116e0208443f3e255d0e85ef15 we have removed the `signed-update` hook from systems that do not have `EFI` in `MACHINE_FEATURES`. This on its own makes sense, however together with it we have also removed the runtime check for whether the running system is actually booted in UEFI mode.
This effectively means it is no longer possible to update the host OS on a device type able to boot in both UEFI and BIOS modes (`intel-nuc` and `genericx86-64-ext`) when booted in BIOS mode, as the signed-update hook is executed unconditionally and fails if the device is not running UEFI.
This patch re-adds the runtime check to only execute the hook if the system is actually booted in UEFI mode.
---
- '*Approve*' if this change would be acceptable in …

hostapp-update-hooks: Re-add check for UEFI to signed-update hook

---

meta-balena-common/recipes-core/initrdscripts/files/kexec

At this moment the kexec initrd script just takes the original kernel command line, replaces root with UUID and removes bootloader args.
We have found at least one use-case (on the Pi4 and firmware GPIOs), where a different initrd script needs to pass extra arguments to the kexec'd kernel. With this patch it will append the contents of the KEXEC_EXTRA_ARGS variable to the kernel command line.
--- …

initrdscripts: Allow passing extra kernel arguments to kexec

---

meta-balena-common/recipes-core/initrdscripts/files/kexec

At this moment the kexec initrd script is skipped when `ROOTFS_DIR` is not defined or if the new rootfs is mounted, but does not contain a kernel image in the expected place. This is undesirable as we assume this is the last script executed by the balena bootloader.
This patch makes the kexec script always execute in the balena bootloader and makes it fail hard in unexpected states, which means the script is always an exit point for the balena bootloader, whether the actual kexec call succeeds or not.
--- …

initrdscripts: make the kexec script fail hard in unexpected states

---

tests/suites/os/tests/secureboot/index.js

As the secure boot feature is extended to more device types, the test needs to be easy to extend.
---

tests: secureboot: refactor to facilitate extension

---

.github/workflows/generic-amd64.yml
.github/workflows/genericx86-64.yml
.github/workflows/intel-nuc.yml
.github/workflows/raspberrypi4-64.yml

These workflows are for testing the build steps only.
---

Add GHA yocto workflows for common device types

---

meta-balena-common/classes/balena-bootloader.bbclass
meta-balena-common/classes/kernel-balena.bbclass
meta-balena-common/recipes-core/initrdscripts/files/migrate
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
tests/suites/os/tests/secureboot/index.js

Specialize secure boot tests for RPI

---

.github/workflows/genericx86-64-ext.yml
.github/workflows/genericx86-64.yml
.github/workflows/raspberrypi3-64.yml
.github/workflows/raspberrypi3.yml
.github/workflows/raspberrypi4-64.yml

For meta-balena PRs we only want to test virtual devices,
but we will do a sanity build for many types.
Depends-on: https://github.com/balena-os/balena-yocto-scripts/pull/365
Depends-on: https://github.com/balena-os/balena-yocto-scripts/pull/367
--- …

Add build-only GHA workflows for missing devices

---

meta-balena-common/recipes-connectivity/networkmanager/balena-files/90shared

Sometimes on NetworkManager restart a new rule for a shared interface is added, but the old rule is not cleaned up properly, so the rules are just piling up. This patch makes the shared dispatcher script clean up duplicates if it finds any.
--- …

NetworkManager: remove duplicate rules in shared dispatcher script

---

meta-balena-common/classes/image_types_balena.bbclass
meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-containers/mkfs-hostapp-native/mkfs-hostapp-native.bb
meta-balena-common/recipes-kernel/linux/kernel-headers-test.bb

Update docker API version in recipes to match balena API version

---

contributing-device-support.md

As reported here https://github.com/balena-io/docs/issues/2974
[skip ci]

patch: Fix broken links in CDS Docs

---

meta-balena-common/recipes-connectivity/modemmanager/balena-files/0002-quectel-disable-qmi-unsolicited-profile-manager-even.patch
meta-balena-common/recipes-connectivity/modemmanager/balena-files/0003-broadband-modem-qmi-quectel-fix-task-completion-when.patch
meta-balena-common/recipes-connectivity/modemmanager/modemmanager_%.bbappend

With the update to ModemManager version 1.22.0 we now have some Quectel modems failing to use QMI properly:
ModemManager[1178]: [modem0] power state updated: on ModemManager[1178]: [modem0] (quectel) modem reset detected, triggering reprobe ModemManager[1178]: [modem0] (quectel) modem reset detected, triggering reprobe .
.
.
ModemManager[1178]: [modem0] failed waiting for final state: Too much time waiting to get to a final state ModemManager[1178]: [modem0] failed enabling modem: Operation was cancelled ModemManager[1178]: [modem1] couldn't start initialization: Transaction timed out ModemManager[1178]: [modem1] fatal error initializing: Fatal error: modem is unusable
This has been fixed upstream with the 2 patches we backport here:
ModemManager[1139]: [modem0] power state updated: on …

modemmanager: Fix Quectel modems initialization bug

---

tests/suites/os/suite.js
tests/suites/os/tests/iptables/index.js

tests: os: add check for iptables rules

---

tests/suites/hup/suite.js
tests/suites/os/suite.js

When this config.json field has a value, the supervisor will treat the device as managed and will crash and start to boot loop.
On faster device-types we don't seem to notice and the tests pass by chance, but on Pi Zero and similar we consistently see ECONNRESET when hitting local SV endpoints.
See: https://github.com/balena-os/meta-balena/issues/3510
Added-in: https://github.com/balena-os/meta-balena/pull/2369 and https://github.com/balena-os/meta-balena/pull/3022
> [!WARNING]
> This REVERTS the changes made in https://github.com/balena-os/meta-balena/pull/3022 and we need to retest the flashing of Jetson TX2 devices.
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks …

tests:os: Avoid setting apiEndpoint for unmanaged tests

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/95-secureboot/1-fwd_commit_apply-dbx

Fix invalid return statements in apply-dbx hostapp-update hook

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup-efi-tpm

This patch adds a set of checks that make sure that the partition layout is as expected on a system with encrypted disks.
---

initrdscripts: Make cryptsetup fail hard in unexpected conditions

---

tests/suites/cloud/suite.js
tests/suites/cloud/tests/ssh-auth/index.js
tests/suites/os/tests/engine-socket/index.js

Use the existing helper function to write changes to config.json.
---

tests:os: Use writeConfigJsonProp helper function

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup-efi-tpm

`cut` is sensitive to the amount of delimiter characters when parsing output, so e.g. an additional space between two elements causes every field shift by one index.
This patch replaces the use of `cut` by `awk`, which should be more robust.
--- …

initrdscripts: replace cut by awk for parsing lsblk in cryptsetup hook

---

meta-balena-common/recipes-connectivity/modemmanager/balena-files/0004-bearer-qmi-Fix-SIM7100E-crash.patch
meta-balena-common/recipes-connectivity/modemmanager/modemmanager_%.bbappend

With the update to MM 1.22.0 we have received reports that SIM7100E is not functioning correctly.
Followed up with ModemManager devs and it was discovered the issue is related to a PCO setting:
https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/issues/884
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of …

modemmanager: Fix SIM7100E crash

---

.github/renovate.json

A commit body is provided for digest updates in the top-level config here: https://github.com/balena-os/renovate-config
So we must override the digest setting explicitly at the repo level in order to use Change-type vs Changelog-entry
See these PRs that are blocked with the wrong commit message:
- https://github.com/balena-os/meta-balena/pull/3278/commits/5ffd99f4a66453ba20e777c13d990edf9fbb6c61
- https://github.com/balena-os/meta-balena/pull/3397/commits/7c9a2054e78c5206c69c61fad1ea70bcba316e4b
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes …

Override the default commit body for digest updates

---

.github/workflows/meta-balena-esr.yml
.github/workflows/update-backports.yml

CI: Update checkout settings

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup-efi-tpm
meta-balena-common/recipes-support/hostapp-update-hooks/files/0-signed-update
meta-balena-common/recipes-support/hostapp-update-hooks/files/95-secureboot/2-fwd_commit_update-policy

The TPM is capable of storing a limited number of auth session handles. Ensure auth sessions are flushed after use, to prevent tpm2_startauthsession from failing with 'out of session handles'.
--- …

tpm2: ensure auth session contexts are flushed after use

---

tests/suites/hup/suite.js

This is to ensure we have an authenticated SDK before trying to get the last known production image - it needs to be authenticated in case the DT is private, otherwise it won't be able to fetch anything 
--- …

tests: hup: login with sdk before fetching image

---

meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-efi

Silence efi helpers

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher/balena-init-flasher-tpm

Print the PCR digest values used to create the PCR policy used to seal the LUKS passphrase during flashing. These values can be cross referenced with the logs during secure boot to diagnose policy check failures.
--- …

flasher: improve logging with secure boot

---

meta-balena-common/recipes-core/initrdscripts/files/abroot

At this moment the abroot script assumes that the boot partition is already in place when it executes. This might not be true if the rootfs sits on a device that takes a while to initialize, such as a USB drive. The script fails hard if that is the case.
This patch replicates a waiting loop from the rootfs script, which addresses the same issue for systems that do not use the balena bootloader.
--- …

initrdscripts: Wait for boot partition in the abroot script

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/99-balena-bootloader

The rollback-parse-bootloader script will give priority to resinOS_uEnv.txt so make sure there are no U-Boot leftovers when migrating to a balena-bootloader enabled system which needs to read the bootenv environment file on rollbacks.
--- …

hostapp-update-hooks: remove alternative bootloader environment files

---

tests/suites/os/suite.js
tests/suites/os/tests/power-and-cooling/assets/helpers.sh
tests/suites/os/tests/power-and-cooling/index.js

These tests are the same for all public Orin device types and validate that the power mode and the fan profile can be changed by writing directly to the config.json file in the boot partition of an un-managed OS.
Locally triggered test on AGX Orin 64GB:
```
leviathan-client-1  | [2024-10-24T09:22:40.785Z][5882da3-os]     # Subtest: Jetson Orin power mode and fan profile tests
leviathan-client-1  |         ok 1 - Fan profile test passed
leviathan-client-1  | [2024-10-24T09:22:44.149Z][5882da3-os]         ok 2 - Power mode was set
leviathan-client-1  | [2024-10-24T09:22:44.149Z][5882da3-os] Rebooting the DUT
leviathan-client-1  | [2024-10-24T09:24:08.520Z][5882da3-os] DUT has rebooted & is back online
leviathan-client-1  | [2024-10-24T09:24:11.967Z][5882da3-os]         ok …
```

tests/os: Add Jetson Orin device-specific fan and power mode smoke tests

---

tests/suites/os/package-lock.json
tests/suites/os/package.json
tests/suites/os/tests/secureboot/index.js

Ensure the signed kernel aborts the boot process when partitions or filesystems have been tampered with.
---

tests: secureboot: add test to ensure partition integrity

---

meta-balena-common/recipes-core/os-config/os-config.inc
meta-balena-common/recipes-core/os-config/os-config/0002-Add-auth.-header-to-os-v1-config-requests.patch

Add auth. header to /os/v1/config requests
Allows the API to identify devices requesting configuration and apply routing logic (e.g. switch from TCP to UDP OpenVPN configuration).
In the not-so-distant future we may chose to begin switching devices from the default TCP OpenVPN configuration, to stateless UDP config, to reduce load on the backend and increase reliability of the VPN (Cloudlink) connections. This change adds `Authorization` header to requests `{{api}}/os/v1/config` endpoint, with which the API can begin identifying devices and depending on device config vars/model returning the relevant OpenVPN (or other type of configuration).
.. also https://github.com/balena-os/os-config/pull/75
See: https://balena.fibery.io/Work/Improvement/Add-auth.-header-to-os-v1-config-requests-2176

Add auth. header to /os/v1/config requests

---

meta-balena-common/recipes-connectivity/modemmanager/balena-files/0001-increase-qmi-port-open-timeout.patch
meta-balena-common/recipes-connectivity/modemmanager/balena-files/0002-quectel-disable-qmi-unsolicited-profile-manager-even.patch
meta-balena-common/recipes-connectivity/modemmanager/balena-files/0003-broadband-modem-qmi-quectel-fix-task-completion-when.patch
meta-balena-common/recipes-connectivity/modemmanager/balena-files/0004-bearer-qmi-Fix-SIM7100E-crash.patch

We do this in preparation for the Scarthgap update because with newer Yocto versions the patches with outdated context will trigger fatal build errors.
Changelog-entry: Update outdated context for modemmanager patches
--- …

modemmanager: Update patches

---

meta-balena-common/recipes-support/os-fan-profile/os-fan-profile/os-fan-profile
meta-balena-common/recipes-support/os-power-mode/os-power-mode/os-power-mode

Supervisor PR https://github.com/balena-os/balena-supervisor/pull/2382 adds log streaming support for os-fan-profile and os-power mode.
To avoid any potential confusion for users with devices which don't support configurable power modes or fan profiles, let's not print any logs from these services unless corresponding settings have been added to config.json
---
- [] Manual test case recorded …

Don't log power mode and fan profile on unsupported devices, unless set in config.json

---

meta-balena-common/recipes-bsp/u-boot/patches/env_resin.h
meta-balena-common/recipes-core/initrdscripts/files/migrate

Right now if the flashing script errors out the initramfs just keeps running modules. This is a security risk specially for secure boot systems as at that point we have an authorized trusted OS running in an unvetted path.
This commit exits init if the flasher returns, and also attemps to crash the kernel followed by an infinite sleep for paranoic reasons.
--- …

initrdscripts: migrate: panic on installation failure

---

README.md
meta-balena-common/recipes-core/initrdscripts/files/migrate
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

This PR adds the possibility of overriding the list of target provisioning devices through config.json
This change is related to improving provisioning of Jetson Orin devices, but applies to other flasher devices as well
--- …

migrate/resin-init-flasher: Add changes for improving Jetson Orin provisioning

---

meta-balena-common/classes/kernel-balena.bbclass

Also, aufs5 and aufs6 patches are in the same git repo now.
---

classes/kernel-balena: Add aufs patches for 6.1 kernels

---

meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/balena-config-defaults
meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
meta-balena-common/recipes-support/resin-init/resin-init-flasher.bb
meta-balena-common/recipes-support/resin-init/resin-init-flasher/balena-init-flasher-efi

Fixes from the changes that introduced non-LUKS encryption support

---

tests/suites/os/tests/secureboot/index.js

tests: secureboot: add imx specialization

---

meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs

The function overwrites the first 16 MiB of each partition (the default LUKS2 header size), as well as the primary and backup GPT partition tables.
It's typically called from the cryptsetup flasher initramfs script when running on a locked device to close attack vectors that use the flasher images on locked devices, for example in https://github.com/balena-os/meta-balena-hab/pull/6/commits/e638c64c1ca24a28d827f3af33adab9a6d899d91
---
- …

os-helpers-fs: add function to erase disks

---

README.md

This commit adds detailed information for the
new power and cooling configuration options
available for Jetson Orin devices.
Connects-to: https://github.com/balena-io/docs/pull/3099
---

README: Add fan profile and power mode info to docs

---

meta-balena-common/classes/sign-digest.bbclass
meta-balena-common/recipes-core/images/balena-image-flasher.bb
meta-balena-common/recipes-core/images/balena-image.bb
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

At this moment `resin-init-flasher` just takes whatever image lies in `/opt` and dd's it to the target drive. This is fine for general use, but with secure boot enabled, we want to perform at least basic authentication of the image being written.
This patch gets the image signed at build time and makes flasher verify the signature against a key built-in the kernel trust store. At this very moment it fails hard if the signature does not match, but this may change in the future. Technically we only want to know if we are about to flash a balena-provided image or not, we might want to support both but behave slightly differently in each scenario.
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic …

resin-init-flasher: with secure boot, authenticate the inner image

---

meta-balena-common/classes/kernel-balena.bbclass

This is specially useful to prevent devices freezing at boot on errors, for example when the initramfs fail() is called allowing the device to reboot and rollback.
---

classes: kernel-balena: configure reset on oops

---

meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb

The `grub_extraenv` file is actually either installed under `/grub` for MBR systems or `/EFI/BOOT` for EFI ones.
---

hostapp-update-hooks: fix path for grub_extraenv in blacklist

---

.github/workflows/meta-balena-esr.yml

To fix errors introduced in linting changes https://github.com/balena-os/meta-balena/commit/cd2e5faba65a6598952999953fcd4eb64520ac3a#diff-4910f470eb6744625576b113b4395b6c21b015ecb85544e19d75786abf63f41fL109
--- …

workflows/meta-balena-esr: fix version array bash

---

meta-balena-common/recipes-core/images/balena-image-flasher.bb

At this moment `balena-image-flasher` depends on `do_image_sign_digest` and do_rootfs of `balena-image`, but this is not enough, as the signature symlink is only created by a postprocess script.
This patch replaces the two existing dependencies by `do_image_complete`, which should cover everything.
--- …

balena-image-flasher: depend on balena-image:do_image_complete

---

tests/suites/os/tests/secureboot/index.js

tests: imx: address issues testing with fully featured and locked device

---

.github/workflows/iot-gate-imx8.yml

With the addition of the meta-balena-hab submodule there are multiple balena layers with custom templates - specify which one to use to avoid a build error.
Changelog-entry: add custom template path to iot-gate-imx8
--- …

workflows: iot-gate-imx8: add custom template path

---

.github/workflows/iot-gate-imx8plus.yml

A custom template path has originally been added in https://github.com/balena-os/meta-balena/pull/3599 for the iot-gate-imx8. The iot-gate-imx8plus needs one as well because it's now using the meta-balena-hab submodule.
Needed for merging https://github.com/balena-os/meta-balena/pull/3602 
--- …

workflows: iot-gate-imx8plus: add custom template path

---

meta-balena-common/classes/kernel-balena.bbclass

Add aufs patches for kernel 6.6

---

tests/suites/os/tests/secureboot/index.js

`2.108.6` doesn't exist for generic-amd64. The tests used to still work, because we werent acually passing the version to kernel-module-build correctly, meaning that it would default to the one in the kernel-module-build project. That was fixed in 4484c59fc924100232cc10303a4636ed0082760a , and now we are passing the version correctly, we're looking for a nonexistant version. Changing version to match the default.
---
- …

tests: secureboot: fix reference to unavailable kernel-module-headers

---

docs/secure-boot-abstractions.md
tests/suites/cloud/suite.js
tests/suites/cloud/tests/preload/index.js

Since 1ae37ac158b93df836126030abec8c3d3f69d92b using the flasher image with secureboot and preloading doesn't work. Skipping preloading tests will unblock users not using this combination with the signed images.
--- …

tests: secureboot: remove preload test for secureboot enabled DUTs

---

tests/suites/os/tests/swap/index.js

We encountered the variance in expected and measured swap in the rpi5 to be higher than the allowed value of 10 - to make this safe and allowing of more device types, changed the allowed variation - still small enough to actually check the value is right, but should reduce false negatives
required to unblock raspberrypi5 work
https://balena.fibery.io/search/Yc6vY#Work/Project/Support-new-raspberry-Pi-CM5-device-type-949
--- …

tests: os: swap: increase wiggle room in swap check

---

meta-balena-common/recipes-kernel/linux/kernel-devsrc.bb

This is taken from Poky rev ae8fe5b896a1f6bd0740d1fa6638b9d9377a8d28 in master.
It is required for being able to compile kernel modules for 6.12+ kernels.
---

kernel-devsrc.bb: Copy from Poky for 6.12+ kernels

---

meta-balena-common/recipes-connectivity/modemmanager/balena-files/0005-Update-Cinterion-port-types.patch
meta-balena-common/recipes-connectivity/modemmanager/modemmanager_%.bbappend

- new rules file 77-mm-cinterion-port-types.rules for ModemManager
Moved here from - https://github.com/balena-os/balena-generic/pull/551
---

Add port types rules for ALAS5

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup-efi-tpm
meta-balena-common/recipes-support/hostapp-update-hooks/files/0-signed-update
meta-balena-common/recipes-support/hostapp-update-hooks/files/95-secureboot/2-fwd_commit_update-policy
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-tpm2
meta-balena-common/recipes-support/resin-init/resin-init-flasher/balena-init-flasher-efi
meta-balena-common/recipes-support/resin-init/resin-init-flasher/balena-init-flasher-tpm

Store LUKS passphrase in TPM NVRAM

---

meta-balena-common/classes/image-balena.bbclass
meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.bb
meta-balena-common/recipes-core/images/balena-image-flasher.bb
meta-balena-common/recipes-core/images/balena-image.bb

Allow for device type names and machine to differ. Until know, the device type contract had to be named `$MACHINE.json`, and then the slug in it could be something else.
The DEVICE_TYPE variable that defaults to MACHINE for backwards compatibility allows for the same MACHINE to build several device types by passing a different DEVICE_TYPE to the build.
--- …

Add DEVICE_TYPE

---

meta-balena-common/classes/kernel-balena.bbclass

CONFIG_MODULE_COMPRESS_ZSTD requires CONFIG_MODULE_COMPRESS in kernel v6.12. Enable it when necessary.
Required by: https://github.com/balena-os/balena-generic/pull/541
---

kernel-balena: enable CONFIG_MODULE_COMPRESS as needed

---

meta-balena-common/classes/kernel-balena.bbclass

From kernel v6.11 the memory controller for cgroups v1 has to be explicitely selected or its compiled out.
This is required for the engine to apply memory resource constraints.
Changelog-entry: Enable memory cgroup v1 if required
--- …

classes: kernel-balena: enable CONFIG_MEMCG_V1 when needed

---

meta-balena-common/recipes-core/initrdscripts/files/migrate

As a part of secure boot hardening, we want to avoid flasher running userspace from an external drive, and always provision from memory.
---

initrdscripts: Force migration with secure boot enabled

---

tests/suites/os/tests/modem/index.js

This is to allow for the use case of a test device having a hard wired modem, that won't work in the region the test device is hosted in - e.g NA modem soldered on but test device in the EU. In that case we can remove the SIM, and the test will skip
For https://balena.fibery.io/Work/Project/Add-Ambient's-CDS-devices-to-AutoKit-1097
Leaving as draft until tested on target device
--- …

tests: os: modem: Skip modem test if no SIM detected

---

meta-balena-common/classes/kernel-balena.bbclass

Enable multipath TCP (MPTCP) for all devices by default.
---

kernel-balena.bbclass: enable multipath TCP

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/95-secureboot/2-fwd_commit_update-policy
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-tpm2
meta-balena-common/recipes-support/resin-init/resin-init-flasher/balena-init-flasher-efi
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

A set of small fixes to make the migrator work for secure boot systems again.
---

Secure boot migrator fixes

---

meta-balena-common/recipes-support/balena-unique-key/balena-unique-key/balena-device-uuid.service

We have changed the mount units to service units a while back but forgot to update a depending service to use the new service unit instead of the older mount point unit.
---

balena-unique-key: Fix dependency on /home/root/.rnd mount point

---

tests/suites/cloud/suite.js
tests/suites/hup/suite.js
tests/suites/os/suite.js

By introducing the option to whitelist or ignore extra events in PCR2, we have changed the default behavior of the system. Instead of copying the contents of PCR2 during provisioning, we now expect no drivers to be loaded, unless there was an explicit opt-in through config.json. This is the behavior that we've seen on physical hardware, however qemu behaves differently - it loads the PXE driver for the network card unconditionally, even if secure boot is enabled and the driver has not been whitelisted.
This patch makes all the testsuites opt-in for the PCR2 whitelist, which is just a workaround to restore the previous behavior and unblock the automated testsuite.
A proper fix should either be in leviathan, or in QEMU, or implementing a proper test for the PCR2 feature, that checks all the …

tests: whitelist extra PCR2 events by default

---

meta-balena-common/recipes-core/initrdscripts/files/migrate

At this moment securityfs is not mounted in the initramfs, so when flasher is running from the migrate script, it won't find the TPM event log. This is fine for most systems, but on systems that have extra TPM events logged and measured, the expected PCR7 value will be computed incorrectly.
This patch mounts securityfs before running flasher from the migrate script.
--- …

initrdscripts: mount securityfs in migrate script

---

meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-tpm2

This should only be called during machine shutdown
---

os-helpers: tpm_nvram_store_passphrase: remove tpm2_shutdown

---

tests/suites/os/config.js
tests/suites/os/tests/secureboot/index.js

If a kernel headers file is provided, use it for the kernel module test.
---

tests: secureboot: adapt kernel modules test to private device types

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/0-signed-update
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-tpm2

At this moment migrating from passphrase encrypted in the EFI partition to passphrase stored in TPM NVRAM is a one way operation. The signed-update HUP hook will move the passphrase to TPM NVRAM and protect it with a new policy, but doesn't update the encrypted file in the EFI partition. That way, if the new OS doesn't work and triggers a rollback, the passphrase can't be decrypted when running the "old" hooks and rollback fails, leaving the system in an inconsistent state.
This patch makes the signed-update hook re-encrypt the passphrase and update it in the boot partition one last time during the migration.
* If HUP goes through, the encrypted file is removed from the boot partition and the system sticks with NVRAM only.
* If HUP fails, the system can rollback and the "old" OS version …

hostapp-update-hooks: make rollback possible when migrating to TPM NVRAM

---

meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-tpm2

At this moment tpm_nvram_store_passphrase checks whether the expected policy is currently met or not, and acts differently in each case. If the policy doesn't match, the TPM write is protected by a one-time password that is lost when the function exits.
If the policy matches, it will be used to protect the write directly. The latter seems to be broken at least in some scenarios (e.g. retrying HUP after a rollback).
This patch makes removes the special-casing and makes tpm_nvram_store_passphrase always use the password protection. While using the current PCR states directly is a nice optimization, always using the password is more universal and makes the code simpler.
---
- '*Approve*' if this change would be acceptable in the codebase (even if …

os-helpers-tpm2: Always use password protection for TPM NVRAM writes

---

tests/suites/cloud/suite.js

For the preload test, we disable DUT internet access to check the preloaded app starts without API access. For secureboot devices, we dont run the preload test as its not a supported feature yet. So don't disable the internet access for a secureboot device
--- …

tests: cloud: Don't disable DUT internet access if secureboot enabled

---

meta-balena-common/classes/kernel-balena.bbclass

On most devices this is already included but we want it everywhere, NetworkManager provides native support and it can't work without the driver.
---

kernel-balena.bbclass: Include 802.1q VLAN driver

---

meta-balena-common/recipes-core/busybox/busybox/balenaos.cfg
meta-balena-common/recipes-core/initrdscripts/files/cryptsetup-efi-tpm
meta-balena-common/recipes-core/initrdscripts/files/migrate
meta-balena-common/recipes-extended/zstd/zstd_%.bbappend
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs

Updated with a test that compares the estimated zram compression with real zram compression and fails the build if the difference is not in a 5% threshold.
**Update**: I split the zram estimation test PRs into https://github.com/balena-os/meta-balena/pull/3688 given that builder updates are required. See that PR for details.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, …

Add zram compression size estimation and other SB related changes

---

meta-balena-common/classes/kernel-balena.bbclass

This commit is a continuation of e3b7a1555542e6b1381f1a5f7131b935d1f66f22
Devices that need a driver for RTL8192 based chipsets should enable the in-tree CONFIG_RTL8192CU kernel driver which should be stable in newer kernel releases.
--- …

kernel-balena.bbclass: Remove references to disabling CONFIG_RTL8192CU

---

meta-balena-common/recipes-core/packagegroups/packagegroup-resin.bb
meta-balena-common/recipes-core/packagegroups/packagegroup-resin.inc

Packages with dinamically changed names cannot be included in allarch package groups. This package was set to allarch because it inherits packagegroup class, which sets PACKAGE_ARCH to "all" by default.
This fixes the following error:
packagegroup-resin-1.0-r1 do_package_write_ipk: An allarch packagegroup shouldn't depend on packages which are dynamically renamed (kernel-modules to kernel-modules-6.6.3-g284172f37508)
See https://github.com/openembedded/meta-openembedded/commit/112cca9f474
Change-type: Patch
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will …

recipes-core/packagegroup-resin: Set PACKAGE_ARCH

---

.github/workflows/generic-aarch64.yml
.github/workflows/generic-amd64.yml
.github/workflows/genericx86-64-ext.yml

Depends-on: https://github.com/balena-os/balena-generic/pull/635
**Remove the AX102 requirement for secure boot tests**
The latest self-hosted runners support cpu templates
so the guests will experience a consistent feature set
supported by the host.
**Require a new "qemu-os" tag for leviathan QEMU suites**
This allows us some control over which runners are available
for long-running leviathan QEMU test suites that download large
image files.
See: https://balena.fibery.io/Work/Improvement/Require-a-new-qemu-os-tag-for-leviathan-QEMU-suites-3184
See: https://balena.fibery.io/Work/Improvement/GitHub-VMs-Allow-loading-custom-guest-cpu-templates-3180
See: https://balena.fibery.io/Inputs/Pattern/QEMU-secure-boot-tests-do-not-boot-on-AMD-EPYC-chipset-self-hosted-runners-5130
See: …

Require a new "qemu-os" tag for leviathan QEMU suites

---

meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_%.bbappend

... on devices which enable firmware compression.
Connects-to: https://github.com/balena-os/balena-iot-gate-imx8/pull/916
Context: [#channel/support-help > Load module firmware from container @ 💬](https://balena.zulipchat.com/#narrow/channel/403752-channel.2Fsupport-help/topic/Load.20module.20firmware.20from.20container/near/535996624)
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. …

linux-firmware: Ensure Intel AX210 firmware can be installed
