balena-os/meta-balena

meta-resin-common/recipes-support/resin-conf/resin-conf/resin-vars

[Issue #7]
Reviewers: @pcarranzav @Page- @telphan @floion
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/8)

resin-vars: Return empty string if a certain field is not found

---

CHANGELOG.md
meta-resin-common/conf/layer.conf

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/20)

Unset rootfs size

---

meta-resin-common/README.md
meta-resin-jethro/README.md

@floion @telphan 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/21)

Minor fixes and typos

---

CHANGELOG.md
meta-resin-common/recipes-core/os-release/os-release.bbappend

Pull request for #18 
@floion @telphan @petrosagg
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/22)

os-release tweaks

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass

@telphan @floion 
#24 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/25)

Add support for hid-multitouch

---

CHANGELOG.md
meta-resin-common/recipes-core/packagegroups/packagegroup-resin-connectivity.bb

@floion @telphan 
#23 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/27)

Add CRDA to resin images

---

CHANGELOG.md
meta-resin-common/recipes-core/packagegroups/packagegroup-resin-flasher.bb
meta-resin-common/recipes-core/packagegroups/packagegroup-resin.bb
meta-resin-common/recipes-core/packagegroups/packagegroup-resin.inc
meta-resin-common/recipes-support/resin-device-progress/resin-device-progress.bb

@floion @telphan 
#11
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/28)

resin device register providers

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-supervisor/resin-supervisor-disk.bb

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/30)

Fix resin supervisor disk PV variable

---

CHANGELOG.md
meta-resin-common/conf/distro/include/resin-os.inc
meta-resin-common/recipes-devtools/rce/rce.inc
meta-resin-common/recipes-support/resin-supervisor/resin-supervisor-disk.bb
meta-resin-common/recipes-support/resinhup/resinhup.bb

@agherzan @telphan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/42)

Use docker provider

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/connman/connman/allow_more_than_MAXNS_nameserver_entries_in_the_resolv_file.patch
meta-resin-common/recipes-connectivity/connman/connman/write_dns_to_resolv.dnsmasq.patch
meta-resin-common/recipes-connectivity/connman/connman_%.bbappend
meta-resin-common/recipes-connectivity/connman/resin-connman-conf/main.conf
meta-resin-common/recipes-connectivity/dnsmasq/dnsmasq_%.bbappend
meta-resin-common/recipes-connectivity/dnsmasq/files/0001-Treat-REFUSED-not-SERVFAIL-as-an-unsuccessful-upstre.patch
meta-resin-common/recipes-connectivity/dnsmasq/files/dnsmasq.conf.systemd
meta-resin-common/recipes-connectivity/dnsmasq/files/resolv.conf
meta-resin-common/recipes-core/packagegroups/packagegroup-resin-connectivity.bb

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/40)

Use dnsmasq with connman

---

meta-resin-common/recipes-devtools/btrfs-tools/btrfs-tools/0001-btrfs-progs-utils-make-sure-set_label_mounted-uses-c.patch
meta-resin-common/recipes-devtools/btrfs-tools/btrfs-tools_%.bbappend

@petrosagg @telphan @floion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/41)

btrfs-tools: Add patch to fix labeling in BTRFS

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/connman/resin-connman-conf/main.conf

@agherzan @telphan @petrosagg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/48)

Connman ignore p2p

---

meta-resin-common/recipes-support/resin-device-progress/resin-device-progress/resin-device-progress
meta-resin-common/recipes-support/resin-supervisor/files/update-resin-supervisor

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/meta-resin/37)

Api access improvements

---

CHANGELOG.md
meta-resin-common/recipes-core/packagegroups/packagegroup-resin.inc

Install rsync

---

CHANGELOG.md
meta-resin-common/classes/image_types_resin.bbclass

@floion @telphan @petrosagg @Page-

Fix realpath issues

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Board initialization in flasher also

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-init/resin-init-flasher.bb

Add resin-init-board to RDEPENDS

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/dnsmasq/files/dnsmasq.conf.systemd
meta-resin-common/recipes-connectivity/dnsmasq/files/resolv.conf
meta-resin-common/recipes-support/resin-supervisor/files/resin-supervisor.service

dnsmasq: listen on 127.0.0.2 instead of 127.0.0.1

---

CHANGELOG.md
meta-resin-common/classes/image-resin.bbclass
meta-resin-common/recipes-core/images/resin-image-flasher.bb
meta-resin-common/recipes-core/images/resin-image.bb

* Deploy license.manifest
* In case of hddimg files fix symlink
@petrosagg @floion @telphan

Resin image bbclass

---

meta-resin-common/classes/image_types_resin.bbclass

image_types_resin.bbclass: Minor esthetics

---

meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
scripts/resinhup/run-resinhup-ssh.sh

resinhup: various improvements and default on stable tag

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Remove deprecated mmcroot

---

.gitignore
scripts/resinhup/run-resinhup-ssh.sh

@petrosagg @floion @telphan @Page- @abresas

Resinhup: Improvements on app update

---

CHANGELOG.md
meta-resin-common/recipes-core/images/resin-image-flasher.bb
meta-resin-common/recipes-support/resin-init/resin-init-flasher.bb
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Uenv expose

---

CHANGELOG.md
meta-resin-common/recipes-core/images/resin-image-flasher.bb
meta-resin-common/recipes-support/resin-init/resin-init-flasher.bb
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Revert uEnv changes

---

CHANGELOG.md
meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
scripts/resinhup/run-resinhup-ssh.sh

Add support for engine 1.10 migrator and other improvements

---

meta-resin-common/recipes-graphics/cairo/cairo_%.bbappend

cairo: Move imx specific bits to respective layers

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/connman/connman/do_not_add_routes_to_nameservers.patch
meta-resin-common/recipes-connectivity/connman/connman_%.bbappend

@agherzan @telphan @petrosagg @lifeeth

Don't allow connman to add nameserver routes in the kernel IP routing table

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/connman/resin-connman-conf/main.conf

@agherzan @telphan @petrosagg @lifeeth

resin-connman-conf: Modify PreferredTechnologies order

---

CHANGELOG.md
README.md
meta-resin-common/conf/distro/include/resin-os.inc
meta-resin-common/recipes-core/images/resin-image.bb
meta-resin-common/recipes-core/os-release/os-release.bbappend

Host OS versioning scheme

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-init/resin-init-flasher-board.bb
meta-resin-common/recipes-support/resin-init/resin-init-flasher-board/resin-init-flasher-board
meta-resin-common/recipes-support/resin-init/resin-init-flasher.bb
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Provide resin-init-flasher-board

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-init/resin-init-flasher.bb
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Remove specific board bootloader handling code from the flasher

---

README.md

Signed-off-by: Charles Chan <charleswhchan@users.noreply.github.com>

REAME.md: Remove duplicate sections under "Build Flags"

---

meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

resin-init-flasher: Remove obsolete remove_to_reprovision file

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

@floion @telphan 
Connects to #103

docker-resin-supervisor-disk: Bring back the VERSION file

---

CHANGELOG.md
meta-resin-common/classes/image-resin.bbclass
meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

@agherzan @telphan @lorenzo-stoakes

Add kernel module headers to deploy connects to #87

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Add error checking to resin-init-flasher script

---

CHANGELOG.md
meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

Ensure all build artefacts are present for kernel-modules-headers

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/openvpn/openvpn/openvpn-resin.service
meta-resin-common/recipes-connectivity/openvpn/openvpn_%.bbappend
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/resin-supervisor.service
meta-resin-common/recipes-support/resin-device-register/resin-device-register/resin-device-register
meta-resin-common/recipes-support/resin-device-register/resin-device-register/resin-device-register.service
meta-resin-common/recipes-support/resin-device-uuid/resin-device-uuid.bb
meta-resin-common/recipes-support/resin-device-uuid/resin-device-uuid/resin-device-uuid
meta-resin-common/recipes-support/resin-device-uuid/resin-device-uuid/resin-device-uuid.service

Generate uuid

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/connman/connman/remove-old-IP-and-gateway-address.patch
meta-resin-common/recipes-connectivity/connman/connman_%.bbappend

Connects to #130 
@floion @telphan @petrosagg @lifeeth

Fix connman multi IP over DHCP

---

meta-resin-common/recipes-core/os-release/os-release.bbappend

@floion @petrosagg @Page- @telphan

Fix os release quotes

---

meta-resin-common/conf/distro/include/resin-os.inc
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

@floion @telphan @petrosagg 
Connects to #137

docker-resin-supervisor-disk: Default tag to v1.11.5

---

CHANGELOG.md
meta-resin-common/classes/compress-kernel-modules.bbclass
meta-resin-common/classes/kernel-resin.bbclass
meta-resin-common/recipes-core/images/resin-image.bb

connects to resin-os/resin-beaglebone#18
@telphan @floion @petrosagg

kernel modules compress mechanism

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass
meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

@agherzan @telphan 
Connects to resin-os/resin-edison#20

Copy kernel build artifacts to deploydir

---

meta-resin-common/recipes-support/resin-info/resin-info.bb

resin-info: Fix syntax

---

meta-resin-common/recipes-support/resin-info/resin-info.bb

resin-info: Fix typo and package all files

---

meta-resin-common/recipes-containers/docker/docker/docker.service

@agherzan @floion 
Connects to #121

Delete key.json if it is empty

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/openvpn/openvpn/openvpn-resin.service
meta-resin-common/recipes-connectivity/openvpn/openvpn/prepare-openvpn.service

Fix openvpn systemd service deps

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update supervisor to version 1.11.6

---

CHANGELOG.md
meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh

@telphan @floion @petrosagg 
Connects to resin-os/resinhup#24

resinhup: When running resinhup mount /lib/modules

---

meta-resin-common/classes/image-resin.bbclass
meta-resin-common/recipes-core/images/resin-image.bb
meta-resin-common/recipes-core/systemd/systemd_%.bbappend

Connects to #191 
@telphan @floion @petrosagg

Fingerprints improvements

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update resin-supervisor to v1.12.2

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/connman/resin-connman-conf/main.conf
meta-resin-common/recipes-core/systemd/systemd_%.bbappend

@agherzan @telphan
connects to #179

Systemd define default ntp servers

---

meta-resin-common/recipes-connectivity/resin-net-config/resin-net-config/resin-net-config

resin-net-config: Fix jq invocation

---

CHANGELOG.md
meta-resin-common/recipes-core/systemd/systemd-serialgetty.bbappend
meta-resin-common/recipes-core/systemd/systemd/remove_systemd-getty-generator.patch
meta-resin-common/recipes-core/systemd/systemd_%.bbappend

Disable getty generator

---

CHANGELOG.md
meta-resin-common/recipes-core/dropbear/dropbear_%.bbappend

Connects to #210 
CC @floion @telphan @lorenzo-stoakes @petrosagg

Run dropbearkey.service at first boot

---

meta-resin-common/recipes-support/resin-info/resin-info/resin-info@.service

resin-info: Fix bash path

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/dnsmasq/dnsmasq_%.bbappend
meta-resin-common/recipes-connectivity/dnsmasq/files/dnsmasq.conf

Dnsmasq without dhcp server

---

CHANGELOG.md
meta-resin-jethro/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
meta-resin-jethro/recipes-kernel/linux-firmware/linux-firmware_git.bbappend

Connects to resin-os/resin-intel#19

Add firmware for new nuc

---

CHANGELOG.md
meta-resin-common/classes/image_types_resin.bbclass

@petrosagg @floion @telphan 
Fixes #39

Use FAT16  when creating fs as we do when creating the partitions

---

CHANGELOG.md
meta-resin-common/recipes-core/plymouth/plymouth/0001-plymouth-systemd-append.patch

connect to #231 
@agherzan @floion

Fix plymouth show

---

CHANGELOG.md
meta-resin-fido/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
meta-resin-fido/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-jethro/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
meta-resin-jethro/recipes-kernel/linux-firmware/linux-firmware_git.bbappend

fixes: https://github.com/resin-os/resin-intel/issues/20
Signed-off-by: Michal Mazurek <michal@resin.io>

iwlwifi: update firmware version: iwlwifi-7265D-10 -> iwlwifi-7265D-13

---

meta-resin-common/recipes-connectivity/connman/connman_%.bbappend
meta-resin-common/recipes-connectivity/openvpn/openvpn_%.bbappend
meta-resin-common/recipes-devtools/btrfs-tools/btrfs-tools_%.bbappend
meta-resin-daisy/recipes-bsp/u-boot/u-boot-mkimage_%.bbappend
meta-resin-daisy/recipes-connectivity/connman/connman_%.bbappend
meta-resin-daisy/recipes-connectivity/openvpn/openvpn_%.bbappend
meta-resin-daisy/recipes-devtools/binutils/binutils_2.24.bbappend
meta-resin-fido/recipes-bsp/u-boot/u-boot-mkimage_%.bbappend
meta-resin-fido/recipes-connectivity/connman/connman_%.bbappend
meta-resin-fido/recipes-connectivity/openvpn/openvpn_%.bbappend
meta-resin-fido/recipes-devtools/binutils/binutils_2.24.bbappend

Fix FILESEXTRAPATHS_append

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update supervisor to v1.14.0

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
meta-resin-common/recipes-core/systemd/systemd_%.bbappend
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher.bb
meta-resin-common/recipes-support/resin-mounts/resin-mounts.bb

Connects to #204 
@agherzan @floion

Create essential files at build time

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

@agherzan @floion @michal-mazurek @lorenzo-stoakes 
connects to #254

Provide custom logo splash for our flasher types

---

CHANGELOG.md
meta-resin-common/conf/distro/include/resin-os.inc

Release v1.9

---

meta-resin-common/recipes-core/systemd/systemd_%.bbappend

@agherzan @floion @michal-mazurek @lorenzo-stoakes

systemd: Fix bogus symlink target

---

CHANGELOG.md
meta-resin-common/conf/distro/include/resin-os.inc

Release v1.10

---

meta-resin-common/recipes-containers/docker-disk/files/entry.sh

@agherzan @floion @petrosagg @lorenzo-stoakes @michal-mazurek 
connects to #239 

Tune mkfs.btrfs command options

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker/docker/docker.service
meta-resin-common/recipes-containers/docker/docker/journal.patch
meta-resin-common/recipes-containers/docker/docker_git.bb

Connected to #156 
Signed-off-by: Michal Mazurek <michal@resin.io>

docker: enable the journald log driver

---

CHANGELOG.md
meta-resin-common/classes/host-update-resin.bbclass

Connects to #274 
@floion @michal-mazurek @telphan @petrosagg @lorenzo-stoakes

resinhup FHS directory structure for it's packages

---

meta-resin-common/recipes-core/plymouth/plymouth_0.9.2.bbappend

fixes https://github.com/resin-os/meta-resin/issues/190
Signed-off-by: Michal Mazurek <michal@resin.io>

plymouth: rdepend on bash

---

CHANGELOG.md
meta-resin-common/recipes-connectivity/openvpn/openvpn/openvpn-resin.service
meta-resin-common/recipes-connectivity/openvpn/openvpn/prepare-openvpn
meta-resin-common/recipes-connectivity/openvpn/openvpn/prepare-openvpn.service
meta-resin-common/recipes-connectivity/openvpn/openvpn_%.bbappend
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher.bb
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher/openvpn-conf.mount
meta-resin-common/recipes-support/resin-mounts/resin-mounts.bb
meta-resin-common/recipes-support/resin-mounts/resin-mounts/openvpn-conf.mount

@agherzan @floion 
Connects to #194

Make opevpn configuration read-only

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass

fixes resin-os/resin-intel#26 and resin-os/resin-intel#29

Add iptables nat ip set

---

CHANGELOG.md
meta-resin-common/recipes-core/images/resin-image-flasher.bb
meta-resin-common/recipes-core/images/resin-image.bb

Add device type json to boot

---

meta-resin-common/classes/host-update-resin.bbclass
meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh

Connects to resin-os/resinhup#28

Support resinhup using dockerhub packages

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update supervisor to v2.1.1

---

meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher.service

resin-init-flasher.service: Enter correct dependency

---

meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh

Resinhup fixes

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/resin-supervisor.service

@agherzan @floion @petrosagg @michal-mazurek @lorenzo-stoakes 
Connects to #330

resin-supervisor: Fix bind mount of the docker socket

---

CHANGELOG.md
README.md
meta-resin-common/conf/distro/include/resin-os.inc
meta-resin-common/recipes-core/dropbear/dropbear_%.bbappend
meta-resin-common/recipes-core/images/resin-image-flasher.bb
meta-resin-common/recipes-core/images/resin-image.bb
meta-resin-common/recipes-core/systemd/systemd-serialgetty.bbappend
meta-resin-common/recipes-core/systemd/systemd/remove_systemd-getty-generator.patch
meta-resin-common/recipes-core/systemd/systemd_%.bbappend
meta-resin-common/recipes-support/resin-info/resin-info.bb
meta-resin-common/recipes-support/resin-logs/resin-logs/resin-logs

@agherzan @floion @michal-mazurek 
Connects to #315

Replace DEBUG_IMAGE with DEVELOPMENT_IMAGE

---

CHANGELOG.md
meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

Kernel modules headers archive switch to gzip

---

meta-resin-common/recipes-core/dropbear/files/ssh.service

ssh.service: Add custom resin subtype

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker/docker/docker.conf.systemd
meta-resin-common/recipes-containers/docker/docker_git.bb

Docker socket over TCP on development images

---

CHANGELOG.md
meta-resin-common/recipes-core/packagegroups/packagegroup-resin.bb
meta-resin-common/recipes-support/resin-hostname/resin-hostname.bb
meta-resin-common/recipes-support/resin-hostname/resin-hostname/resin-hostname
meta-resin-common/recipes-support/resin-hostname/resin-hostname/resin-hostname.service
meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars

@agherzan @floion @petrosagg @lorenzo-stoakes @michal-mazurek 
Connects to #318

Allow hostname to be configurable

---

CHANGELOG.md
meta-resin-common/conf/distro/include/resin-os.inc
meta-resin-common/recipes-connectivity/usb-modeswitch/files/dispatcher-c-rewrite.patch
meta-resin-common/recipes-connectivity/usb-modeswitch/libpipeline_1.4.1.bb
meta-resin-common/recipes-connectivity/usb-modeswitch/usb-modeswitch-data_20151101.bb
meta-resin-common/recipes-connectivity/usb-modeswitch/usb-modeswitch_2.2.5.bb
meta-resin-common/recipes-core/packagegroups/packagegroup-resin-connectivity.bb

@telphan @floion @agherzan @lorenzo-stoakes
This seems independent from Network Manager enough to split out into a separate PR for simplicity.
Just installing this package will make it work automatically, it's tied into udev.
One of the modems I have takes 2 minutes to switch, the other is much faster, but I ran just a handful of tests.

usb-modeswitch

---

CHANGELOG.md
meta-resin-common/classes/image_types_resin.bbclass

@agherzan @floion @michal-mazurek 
Connects to #319

Generate config.json at build time

---

meta-resin-common/classes/image-resin.bbclass
meta-resin-common/classes/image_types_resin.bbclass

@agherzan @floion 
Connects to #319

image-resin: Abstract the initialization of config.json

---

meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

@telphan @floion @agherzan @lorenzo-stoakes
Connects to #264

resin-init-flasher: install NM system-connections

---

meta-resin-common/recipes-containers/docker/docker/docker.conf.systemd

docker.conf.systemd: Fix a typo in ExecStart

---

meta-resin-common/recipes-support/resin-hostname/resin-hostname/resin-hostname.service

Fix resin-hostname execution

---

meta-resin-common/recipes-connectivity/networkmanager/networkmanager_1.4.2.bb

networkmanager: Update to version 1.4.2

---

CHANGELOG.md
meta-resin-common/recipes-core/images/resin-image.bb

Increase rootfs to 300M

---

CHANGELOG.md
meta-resin-common/classes/image-resin.bbclass
meta-resin-common/recipes-core/systemd/systemd_%.bbappend
meta-resin-common/recipes-support/resin-conf-reset/resin-conf-reset/resin-conf-reset.service
meta-resin-common/recipes-support/resin-expand/resin-data-expander/resin-data-expander.service
meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand.service
meta-resin-common/recipes-support/resin-hostname/resin-hostname/resin-hostname.service
meta-resin-common/recipes-support/resin-logs/resin-logs.bb
meta-resin-common/recipes-support/resin-logs/resin-logs/resin-logs
meta-resin-common/recipes-support/resin-logs/resin-logs/resin-logs.service
meta-resin-common/recipes-support/resin-logs/resin-logs/resin-prepare-logs.service
meta-resin-common/recipes-support/resin-logs/resin-logs/systemd-journald.conf
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher/mnt-boot.mount
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher/mnt-bootorig-config.json.mount
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher/mnt-bootorig.mount
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher/temp-conf.service
meta-resin-common/recipes-support/resin-mounts/resin-mounts.bb
meta-resin-common/recipes-support/resin-mounts/resin-mounts/etc-systemd-journald.conf.d.mount
meta-resin-common/recipes-support/resin-mounts/resin-mounts/mnt-boot.mount
meta-resin-common/recipes-support/resin-mounts/resin-mounts/mnt-conf.mount
meta-resin-common/recipes-support/resin-mounts/resin-mounts/var-log-journal.mount
meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars

Resin logs

---

meta-resin-common/recipes-connectivity/avahi/avahi_%.bbappend
meta-resin-common/recipes-connectivity/avahi/files/avahi-daemon.conf

avahi_%.bbappend: Fix drop-in install

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass

CONFIG_SECCOMP

---

meta-resin-common/classes/image-resin.bbclass
meta-resin-common/recipes-connectivity/modemmanager/modemmanager_%.bbappend
meta-resin-common/recipes-connectivity/openssl/openssl_%.bbappend
meta-resin-common/recipes-containers/docker/docker/docker.conf.systemd
meta-resin-common/recipes-containers/docker/docker/docker.service
meta-resin-common/recipes-core/images/resin-image.bb
meta-resin-common/recipes-core/packagegroups/packagegroup-resin.bb
meta-resin-common/recipes-support/resin-conf-reset/resin-conf-reset/resin-conf-reset.service
meta-resin-common/recipes-support/resin-device-uuid/resin-device-uuid.bb
meta-resin-common/recipes-support/resin-device-uuid/resin-device-uuid/resin-device-uuid
meta-resin-common/recipes-support/resin-device-uuid/resin-device-uuid/resin-device-uuid.service
meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand
meta-resin-common/recipes-support/resin-logs/resin-logs/resin-logs
meta-resin-common/recipes-support/resin-mounts/resin-mounts.bb
meta-resin-common/recipes-support/resin-mounts/resin-mounts/home-root-.rnd.mount
meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars

Fixes #397 
Fixes #393 
Fixes #390 
Fixes #388 
Fixes #384

Various fixes

---

meta-resin-common/recipes-containers/docker/docker/0006-Atomically-save-libtrust-key-file.patch
meta-resin-common/recipes-containers/docker/docker/docker.service
meta-resin-common/recipes-containers/docker/docker_git.bb

docker: backport fix for atomic key.json writing

---

meta-resin-common/recipes-connectivity/openssl/openssl_%.bbappend
meta-resin-common/recipes-support/resin-device-uuid/resin-device-uuid/resin-device-uuid.service

resin-device-uuid: Don't touch openssl - use service env

---

CHANGELOG.md
contributing-device-support.md

Fixes #165 
@agherzan @telphan @lorenzo-stoakes @michal-mazurek @shaunmulligan @craig-mulligan

Add guide for new board support to Resin.io

---

CHANGELOG.md

CHANGELOG.md: Add forgotten version line for v2.0-beta.1

---

meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars
meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh

/mnt/conf -> /mnt/boot/

---

meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh

Revert "run-resinhup: Reflect new location for supervisor.conf"

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

docker-resin-supervisor-disk: Update supervisor to v2.8.1

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

[1.X] docker-resin-supervisor-disk: Update supervisor to v2.8.1

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker/docker/0007-daemon-register-container-as-late-as-possible.patch
meta-resin-common/recipes-containers/docker/docker/0008-daemon-cleanup-as-early-as-possible.patch
meta-resin-common/recipes-containers/docker/docker_git.bb

Connected to #280
Connected to resin-io/hq#401

docker: fix name conflict when creating a container

---

CHANGELOG.md
contributing-device-support.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Connects to https://github.com/resin-os/resinos/issues/102

Generate SUPERVISOR_REPOSITORY dynamically so no need to define it in `resin-<board>` anymore

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

[1.X] docker-resin-supervisor-disk: Update supervisor to v2.8.2

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

docker-resin-supervisor-disk: Update supervisor to v2.8.2

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker/docker/0006-Atomically-save-libtrust-key-file.patch
meta-resin-common/recipes-containers/docker/docker/0007-daemon-register-container-as-late-as-possible.patch
meta-resin-common/recipes-containers/docker/docker/0008-daemon-cleanup-as-early-as-possible.patch
meta-resin-common/recipes-containers/docker/docker/0009-graph-aufs-durably-write-layer-on-disk-before-return.patch
meta-resin-common/recipes-containers/docker/docker/0010-pkg-ioutils-sync-parent-directory-too.patch
meta-resin-common/recipes-containers/docker/docker/docker.service
meta-resin-common/recipes-containers/docker/docker_git.bb

Backport fixes from #402 #408 #461

Docker backports

---

CHANGELOG.md
contributing-device-support.md
meta-resin-common/recipes-support/resin-init/resin-init-flasher.bb
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Flasher support for MLO and uboot when needed

---

CHANGELOG.md
meta-resin-common/recipes-core/systemd/systemd/watchdog.conf
meta-resin-common/recipes-core/systemd/systemd_%.bbappend

@petrosagg @michal-mazurek @telphan

Enable systemd watchdog

---

CHANGELOG.md
meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

Change kernel modules headers compression type

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Add supervisor tag to conf

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Introduce SUPERVISOR_TAG

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/resin-supervisor.service

@agherzan @floion @michal-mazurek 
Connects to #487

resin-supervisor: Add missing dependency

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

@agherzan @telphan @michal-mazurek

Generate supervisor repository dynamically

---

CHANGELOG.md
meta-resin-common/recipes-core/systemd/systemd/watchdog.conf

@petrosagg @agherzan @michal-mazurek

systemd: Add missing systemd config file section name for watchdog

---

CHANGELOG.md
meta-resin-common/recipes-core/systemd/systemd/watchdog.conf

@petrosagg @telphan @michal-mazurek @agherzan

systemd: Add missing systemd config file section for watchdog

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/files/entry.sh

Add inode tuning (1 inode for 8192 bytes) in mkfs.ext4 for the resin-data partition 

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass

Connected to https://github.com/resin-os/resinos/issues/143

Deactivate nowayout on master

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass

Connected to https://github.com/resin-os/resinos/issues/143

Deactivate nowayout on 1.X

---

CHANGELOG.md
meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

Backport modules headers recipe patches

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

docker-resin-supervisor-disk: Update supervisor to v2.9.0

---

meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh

This reverts commit aa97eb23e37a2b731ecdd442899e9675a3251232.

Revert "run-resinhup.sh: support only btrfs"

---

CHANGELOG.md
meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
scripts/resinhup/run-resinhup-ssh.sh

Fixes https://github.com/resin-os/meta-resin/issues/535
Fixes https://github.com/resin-os/meta-resin/issues/534

Resinhup cache and fixes

---

meta-resin-common/recipes-containers/docker-disk/docker-utils.inc
meta-resin-morty/recipes-core/images/resin-image-flasher.bbappend
meta-resin-morty/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend

Connected to https://github.com/resin-os/meta-resin/pull/545

Morty misc for 1.X

---

CHANGELOG.md
meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh
scripts/resinhup/run-resinhup-ssh.sh

https://github.com/resin-io/hq/pull/579

Implement resinhup downgrades, logging fixes and various enhancements 

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-mounts/resin-mounts.bb
meta-resin-common/recipes-support/resin-mounts/resin-mounts/home-root-.docker.mount

Connects to resin-os/resinos#157

Make /home/root/.docker/writable

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass

Connects to resin-os/resinos#169

Compile xt_set kernel module

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass

Connects to resin-os/resinos#169

Compile xt_set kernel module (1.X branch)

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

[1.X] docker-resin-supervisor-disk: Update supervisor to v3.0.0

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

docker-resin-supervisor-disk: Update supervisor to v3.0.0

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-device-register/resin-device-register/resin-device-register.service
meta-resin-common/recipes-support/resin-init/resin-init-flasher.bb
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher.service

Connected to https://github.com/resin-os/resinos/issues/149

Add support for multiple entries in INTERNAL_DEVICE_KERNEL

---

CHANGELOG.md
meta-resin-common/classes/host-update-resin.bbclass

connects to https://github.com/resin-os/resinos/issues/113

Morty update adapt resinhup

---

CHANGELOG.md
meta-resin-common/classes/host-update-resin.bbclass

fixes https://github.com/resin-os/resinos/issues/211

Fix resinhup bundle creation directory

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

docker-resin-supervisor-disk: Update supervisor to v3.0.1

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass

Disable audit subsystem

---

CHANGELOG.md
meta-resin-common/classes/image_types_resin.bbclass
meta-resin-common/classes/resin-u-boot.bbclass
meta-resin-common/recipes-bsp/u-boot/patches/resin-specific-env-configuration.patch
meta-resin-common/recipes-bsp/u-boot/patches/resin-specific-env-integration-kconfig.patch
meta-resin-common/recipes-core/images/resin-image-flasher.bb

Connected to https://github.com/resin-io/hq/pull/521/commits

Resin uboot based on 2.0 specification

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-info/resin-info.bb

Connects to resin-os/resinos#224

[Bugfix] Do not install resin-info on our production images

---

CHANGELOG.md
meta-resin-common/classes/resin-u-boot.bbclass
meta-resin-common/recipes-bsp/u-boot/patches/resin-specific-env-configuration.patch
meta-resin-common/recipes-core/images/resin-image.bb

Connected to https://github.com/resin-io/hq/pull/521

Resin uboot scan MMC

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/resin-supervisor.service
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/update-resin-supervisor.timer

Fixes https://github.com/resin-os/resinos/issues/20

RDT promote support

---

CHANGELOG.md
meta-resin-common/recipes-core/initrdscripts/files/finish
meta-resin-common/recipes-core/initrdscripts/files/rootfs
meta-resin-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend

Add updated initramfs-framework to non-morty board

---

CHANGELOG.md
scripts/resinhup/run-resinhup-ssh.sh

run-resinhup: fixing typos in script

---

CHANGELOG.md
meta-resin-common/conf/distro/include/resin-os.inc

Release 2.0.0-rc4

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass

Fix audit disable

---

CHANGELOG.md
meta-resin-common/recipes-core/initrdscripts/files/rootfs

Fixes https://github.com/resin-os/resinos/issues/249

Get the initramfs framework use root=LABEL=

---

CHANGELOG.md
meta-resin-common/recipes-core/busybox/busybox/0001-switch_root-don-t-bail-out-when-console-doesn-t-exis.patch
meta-resin-common/recipes-core/busybox/busybox/0002-switch_root-Fix-undefined-fd-and-minor-tweak.patch
meta-resin-common/recipes-core/busybox/busybox_%.bbappend

Fixes https://github.com/resin-os/resinos/issues/230
Connected to https://github.com/resin-os/resinos/issues/244

Busybox console fix

---

CHANGELOG.md
meta-resin-common/recipes-core/plymouth/plymouth_0.9.2.bbappend

Fixes https://github.com/resin-os/resinos/issues/247

Keep splash at boot

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass
meta-resin-common/recipes-core/images/resin-image.bb
meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
meta-resin-common/recipes-go/resin-provisioner/resin-provisioner_1.0.4.bb

I've cherry-picked the patches from these PRs into a single pull request:
https://github.com/resin-os/meta-resin/pull/629
https://github.com/resin-os/meta-resin/pull/630
https://github.com/resin-os/meta-resin/pull/631
https://github.com/resin-os/meta-resin/pull/633
I'd like to look at #632 separately as it looks potentially more involved.
This should allow Jenkins to do a build of the branch (there's an issue open for fixing Jenkins to build forks properly).

A number of fixes from fboudra

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update supervisor to v4.1.2

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

[1.X] Update supervisor to v4.1.2

---

CHANGELOG.md
meta-resin-common/classes/image_types_resin.bbclass

Connects to resin-os/resinos#257

Fix compression mechanism

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand

Connects to resin-os/resinos#258
Connects to resin-os/resinos#256

Do not force fsck 

---

CHANGELOG.md
meta-resin-common/conf/distro/include/resin-os.inc

Release v1.26

---

CHANGELOG.md
meta-resin-common/classes/image-resin.bbclass

Fixes https://github.com/resin-os/meta-resin/issues/667

Don't fingerprint config.json

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-state-reset/resin-state-reset/resin-state-reset

Connects to resin-os/resinos#297

Preserve file attributes when copying

---

CHANGELOG.md
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Connects to resin-os/resinos#293

Deploy and migrate resinOS_uEnv.txt

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Fixes https://github.com/resin-os/meta-resin/issues/636

Supervisor remove image ID from PV

---

CHANGELOG.md
meta-resin-common/recipes-core/dropbear/dropbear_%.bbappend

Remove all password logins

---

CHANGELOG.md
meta-resin-common/recipes-support/resinhup/resinhup/run-resinhup.sh

Signed-off-by: Gergely Imreh <imrehg@gmail.com>

resinhup/run-resinhup.sh: update to v1.1.3

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update supervisor to v4.2.4

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Includes some bug fixes that are relevant to 1.X
Connects to #687

[1.X] Update supervisor to v4.3.1

---

meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand

resin-filesystem-expand: Reword echo message

---

CHANGELOG.md
meta-resin-common/classes/kernel-resin.bbclass

Connects to resin-os/resinos#325

Support for RT5572

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update supervisor to v5.0.0

---

meta-resin-common/recipes-containers/docker/docker/0006-container-make-sure-config-on-disk-has-a-valid-Confi.patch
meta-resin-common/recipes-containers/docker/docker_git.bb

docker: validate container config when loading from disk

---

README.md

Add some basic documentation of the keys that can be set in
config.json.
I'm not sure what all of these do so any pointers would be very helpful.

README.md: Document config.json variables

---

meta-resin-common/recipes-support/resin-mounts/resin-mounts.bb

This is just a cleanup with no functional changes.

resin-mounts: Sort list of mounts

---

meta-resin-common/README.md

README.md: Add info about oe-meta-go dependency

---

README.md
meta-resin-common/classes/kernel-resin.bbclass
meta-resin-common/classes/resin-sanity.bbclass
meta-resin-common/conf/distro/include/resin-os.inc
meta-resin-common/recipes-containers/docker-disk/docker-disk.inc
meta-resin-common/recipes-containers/docker-disk/files/Dockerfile
meta-resin-common/recipes-containers/docker-disk/files/entry.sh
meta-resin-common/recipes-containers/docker/docker/docker.conf.systemd
meta-resin-common/recipes-containers/docker/docker/docker.service
meta-resin-common/recipes-containers/docker/docker_git.bb
meta-resin-common/recipes-core/packagegroups/packagegroup-resin.bb

Fixes https://github.com/resin-os/meta-resin/issues/742

Overlayfs support

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update supervisor to v6.0.1

---

meta-resin-common/recipes-core/images/resin-image-flasher.bb
meta-resin-common/recipes-core/images/resin-image.bb

No need to have a change log entry for this as it is only refactoring.

Resin images refactor

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.1.2

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

1.X: Update supervisor to v6.1.2

---

meta-resin-common/recipes-support/resin-persistent-logs/resin-persistent-logs/resin-persistent-logs

Changelog-entry: Fix typo in resin-persistent-logs

resin-persistent-logs: Fix typo of journalctl

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.1.3

---

CHANGELOG.md
meta-resin-common/conf/distro/include/resin-os.inc

Release v2.3.0

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

1.X: Update supervisor to v6.1.3

---

CHANGELOG.md

CHANGELOG.md: Update supervisor to v6.1.3

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.2.1

---

CHANGELOG.md
versionist.conf.js

Fixes https://github.com/resin-os/meta-resin/issues/809

Changelog format - separate line for version

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.2.5

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

1.X: Update supervisor to v6.2.5

---

meta-resin-common/recipes-support/resin-mounts/resin-mounts/mnt-state.mount

Changelog-entry: Enable fsck for resin-state partition

resin-mounts: Enable fsck for resin-state partition

---

meta-resin-common/recipes-core/plymouth/plymouth/resin.plymouth
meta-resin-common/recipes-core/plymouth/plymouth/resin.script
meta-resin-common/recipes-core/plymouth/plymouth_0.9.2.bbappend

Remove unnecessary plymouth files. This saves us around 4MB.
connect https://github.com/resin-os/meta-resin/issues/218

Remove unnecessary plymouth files

---

meta-resin-common/recipes-core/packagegroups/packagegroup-resin-debugtools.bb

Add usbutils package to aid debugging.
Changelog-entry: Add usbutils package

resin-image: Add usbutils package

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.2.9

---

CHANGELOG.md
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

1.X: Update supervisor to v6.2.9

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.3.0

---

meta-resin-common/classes/kernel-resin.bbclass
meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

A couple of small changes to support the latest kernel release.

Support kernel 4.13

---

meta-resin-common/classes/image_types_resin.bbclass

Introduce new variable to define partition table type: gpt or msdos.
Introduce new function 'device_specific_configuration' allowing lower layers
to inject partition configuration before resin-boot.
Changelog-entry: GPT support

image_types_resin.bbclass: Add support for gpt

---

meta-resin-common/recipes-containers/docker/docker_git.bb

Changelog-entry: Add support for overaly2 in mobynit

docker: Add support for overlay2 in mobynit

---

meta-resin-common/recipes-containers/docker/docker_git.bb

Changelog-entry: Docker bugfix

docker: Update to bugfix

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.3.1

---

meta-resin-common/recipes-containers/docker/docker_git.bb

Changelog-Entry: docker: Improved pull progress reporting
Signed-off-by: Akis Kesoglou <akiskesoglou@gmail.com>

docker: Update for improved pull progress reporting

---

meta-resin-common/classes/image_types_resin.bbclass

image_types_resin.bbclass: Fix a small syntax error

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

This fixes an issue with applying deltas on overlay2 and images with many layers.

master: Update supervisor to v6.3.5

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/update-resin-supervisor

Tested on device, changes are from @CameronDiver

update-resin-supervisor: update API call to pine 5 version

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.3.6

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.4.2

---

meta-resin-common/recipes-connectivity/modemmanager/modemmanager_1.6.10.bb

Changelog-entry: Update ModemManager to version 1.6.10

modemmanager: Update to version 1.6.10

---

meta-resin-common/recipes-connectivity/libmbim/libmbim_1.14.2.bb

Changelog-entry: Update libmbim to version 1.14.2

libmbim: Update to version 1.14.2

---

meta-resin-common/classes/image-resin.bbclass

When we run host OS updates, we use atomic copy operations for updating the
boot partition. This requires at least free space as much as the largest file
in the partition. This check makes sure that the boot partition has enough free
space to do atomic copy operations.
Some of the work is based on:
http://git.yoctoproject.org/cgit.cgi/poky/tree/meta/classes/image-live.bbclass#n179
Changelog-entry: Check for enough space in boot partition to support atomic copy operations

image-resin.bbclass: Add sanity check for the boot partition

---

meta-resin-common/recipes-support/hostapp-update-hooks/files/0-bootfiles

Signed-off-by: Gergely Imreh <imrehg@gmail.com>

hostapp-update-hooks: fix typos in hook

---

meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

kernel-modules-headers: Include aarch64 fix

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update resin-supervisor to v6.5.0

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update resin-supervisor to v6.5.1

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Update resin-supervisor to v6.5.3

---

meta-resin-common/recipes-core/packagegroups/packagegroup-resin-debugtools.bb

Add lsof package to aid debugging.
Changelog-entry: Add lsof package

packagegroup-resin-debugtools.bb: Add lsof package

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.5.8

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.5.9

---

meta-resin-common/recipes-containers/balena/balena_git.bb

Changelog-type: patch
Changelog-entry: Update balena to include locks fix

balena: Update package to include locks fix

---

meta-resin-common/recipes-core/images/resin-image.bb
meta-resin-common/recipes-core/os-release/os-release.bbappend

Fixes https://github.com/resin-os/meta-resin/issues/906

os-release in the boot partition

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v6.6.3

---

meta-resin-rocko/README.md
meta-resin-rocko/conf/layer.conf

Prepare initial directory structure for supporting Poky Rocko
Changelog-entry: Add initial structure for supporting Poky Rocko
---

meta-resin: Add initial structure of meta-resin-rocko

---

meta-resin-common/recipes-go/resin-provisioner/resin-provisioner_1.0.4.bb

resin-provisioner_1.0.4.bb: Only package the resulted binary

---

meta-resin-pyro/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
meta-resin-pyro/recipes-kernel/linux-firmware/linux-firmware_git.bbappend

Fixes https://github.com/resin-os/meta-resin/issues/996
---

Bring back 8000c firmware

---

meta-resin-rocko/recipes-core/images/resin-image-flasher.bbappend
meta-resin-rocko/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
meta-resin-rocko/recipes-core/systemd/systemd/0001-core-Don-t-redirect-stdio-to-null-when-running-in-co.patch
meta-resin-rocko/recipes-core/systemd/systemd_%.bbappend

Connected to https://github.com/resin-os/meta-resin/issues/919
---

resin-image-flasher fixes for rocko support

---

meta-resin-common/recipes-connectivity/bluez5/bluez5_%.bbappend
meta-resin-common/recipes-connectivity/bluez5/files/run-bluetoothd-with-experimental-flag.patch

Run bluetoothd in experimental mode

---

meta-resin-common/conf/distro/include/resin-os.inc
meta-resin-common/recipes-connectivity/bind/bind_%.bbappend

Connected to https://github.com/resin-os/meta-resin/issues/919
---

Make sure rocko update doesn't add packages resinOS doesn't depend on

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v7.1.0

---

meta-resin-common/recipes-connectivity/openvpn/openvpn/openvpn.service
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/start-resin-supervisor
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/update-resin-supervisor
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/update-resin-supervisor.service

update resin supervisor posix

---

meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars

resin-vars: Assume VPN port 443 if 1723 is provided in config.json

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Changelog-Entry: Update supervisor to v7.1.3
---

docker-resin-supervisor-disk: Update to v7.1.3

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

docker-resin-supervisor-disk: Update Supervisor to v7.1.6

---

meta-resin-common/recipes-containers/balena/balena_git.bb

balena: Update package to include deadlock fix

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Changelog-Entry: Update supervisor to v7.1.11
Signed-off-by: Akis Kesoglou <akis@resin.io>
---

docker-resin-supervisor-disk: Update to v7.1.11

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Changelog-Entry: Update supervisor to v7.1.14
---

docker-resin-supervisor-disk: Update to v7.1.14

---

meta-resin-common/recipes-connectivity/networkmanager/files/NetworkManager.conf.systemd
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher/bind-path.service.in
meta-resin-common/recipes-support/resin-mounts/resin-mounts.inc

---
Fixes https://github.com/resin-os/resinos/issues/280

NM state directory persistence

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

master: Update supervisor to v7.1.18

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/start-resin-supervisor
meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars

---
---- Autogenerated Waffleboard Connection: Connects to #1044

Allow self-signed CAs to be passed to the Supervisor from `config.json`

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Brings in the following improvements since 7.4.1:
- Properly propagate delta failures
Changelog-Entry: Update supervisor to v7.4.2
Signed-off-by: Akis Kesoglou <akis@resin.io>
---

docker-resin-supervisor-disk: Update to v7.4.2

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Changelog since v7.4.2:
* On startup, only attach to logs for running containers, and remove any containers marked as dead #625 [Pablo Carranza Velez]

master: Update supervisor to v7.4.3

---

meta-resin-common/recipes-containers/docker-disk/files/entry.sh
meta-resin-common/recipes-core/initrdscripts/files/machineid
meta-resin-common/recipes-core/packagegroups/packagegroup-resin.bb
meta-resin-common/recipes-core/systemd/load-timestamp.bb
meta-resin-common/recipes-core/systemd/load-timestamp/load-timestamp.service
meta-resin-common/recipes-core/systemd/load-timestamp/load-timestamp.sh
meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
meta-resin-common/recipes-support/resin-mounts/resin-mounts.inc
meta-resin-common/recipes-support/resin-mounts/resin-mounts/resin-partition-mounter

Various date/time related fixes

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Changelog since v7.4.3
v7.5.6 - 2018-05-14
Update gitignore to ignore new test files #653 [Cameron Diver]
v7.5.5 - 2018-05-11
Update docs with multicontainer API breakages #654 [Tim Perry]
v7.5.4 - 2018-05-11
Fix handling of systemd errors when polling for log to display #612 [Cameron Diver]
v7.5.3 - 2018-05-02
Add typescript linting to supervisor tests #638 [Cameron Diver]
Convert conversions module to typescript #638 [Cameron Diver]
Move shared types to separate module #638 [Cameron Diver]
Convert blink module to typescript #638 [Cameron Diver]
Convert lib/constants module to typescript #638 [Cameron Diver]
Type parameters for validation functions better #638 [Cameron Diver]
v7.5.2 - 2018-05-01
Add some more unit tests …

Update supervisor to version 7.5.6

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Brings in the following changes since 7.5.6:
- Add support for Balena deltas
- Log delta debugging information
- Check against application source for target applications
- Add migration for source field to be added to app table
- Ignore leading and trailing whitespace when parsing env vars
- Don't generate config fields in offline mode
- Add support for changing config.txt on balena fin devices
- Change intialConfigReported value to be an api endpoint
Chengelog-entry: Update resin-supervisor to 7.5.6
Signed-off-by: Akis Kesoglou <akis@resin.io>
---
- '*Request Changes*' if this change would not be …

docker-resin-supverisor-disk: Update supervisor to version 7.9.0

---

README.md

Add pyro and rocko to the list of yocto versions supported
Fixes #1071 
---

Update Readme.md with more yocto versions

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Brings in the following changes since 7.9.0:
- Move config backend code out to classes which implement a common base
- Add support for extlinux configuration files
- Move boot config related code to config-utils module
- Add types for fs-utils module
- Update update-locking documentation
Changelog-entry: Update resin-supervisor to 7.10.0
--- …

docker-resin-supervisor-disk: Update supervisor to 7.10.0

---

meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand.bb
meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand
meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand.service

resin-filesystem-expand: fsck all partitions on error

---

meta-resin-common/recipes-connectivity/networkmanager/files/NetworkManager.conf.systemd
meta-resin-common/recipes-connectivity/networkmanager/networkmanager_%.bbappend
meta-resin-common/recipes-connectivity/openvpn/openvpn/openvpn.service
meta-resin-common/recipes-connectivity/resin-ntp-config/resin-ntp-config.bb
meta-resin-common/recipes-connectivity/resin-ntp-config/resin-ntp-config/resin-ntp-config.service
meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk/resin-supervisor.service
meta-resin-common/recipes-core/chrony/chrony_%.bbappend
meta-resin-common/recipes-core/chrony/files/chronyd.conf.systemd

Various fixes for issues introduced by the switch to chrony

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Brings in the following changes since 7.13.1:
- Fix os-config switching backends and sharing logs - Logs are now per-application and per-backend cc @agherzan
- v1 api fixes and v2 api state functions
- Various typescript conversions
Changelog-entry: Update resin-supervisor to 7.13.1
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if …

docker-resin-supervisor-disk: Update supervisor to 7.13.1

---

meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb

Brings in the following changes since 7.13.1:
* Fix typo in config method call
Change-type: aptch
Changelog-entry: Update resin-supervisor to v7.13.2
---

 docker-resin-supervisor-disk: Update supervisor to 7.13.2

---

README.md

Changelog-entry: Document supported modems
---

Document supported modems

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin supervisor to v7.16.0
---

resin-supervisor: Update to v7.16.0

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin supervisor to v7.16.4

resin-supervisor: Update to v7.16.4

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin supervisor to v7.16.6
---

resin-supervisor: Update to v7.16.6

---

meta-resin-common/recipes-connectivity/avahi/files/avahi-daemon.conf
meta-resin-common/recipes-connectivity/dnsmasq/dnsmasq-bbappend/dnsmasq.conf.systemd
meta-resin-common/recipes-connectivity/networkmanager/networkmanager_1.12.2.bb
meta-resin-common/recipes-core/chrony/files/chronyd.conf.systemd
meta-resin-common/recipes-core/os-config/os-config.inc
meta-resin-common/recipes-core/os-config/os-config/0001-Adjust-CONFIG_JSON_FLASHER_PATH-based-on-OS-changes.patch
meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher.bb
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher/mnt-boottmp.mount
meta-resin-common/recipes-support/resin-mounts/resin-mounts-flasher/temp-conf.service
meta-resin-common/recipes-support/resin-unique-key/resin-unique-key/resin-device-uuid.service
meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars

Updates and fixes

---

meta-resin-common/recipes-core/os-config/os-config.inc
meta-resin-common/recipes-core/upx/upx_3.95.bb

Update UPX to 3.95

---

meta-resin-krogoth/recipes-core/dropbear/dropbear_2016.72.bbappend
meta-resin-krogoth/recipes-core/dropbear/files/0001-Secure-configuration-options.patch
meta-resin-morty/recipes-core/dropbear/dropbear_2016.74.bbappend
meta-resin-morty/recipes-core/dropbear/files/0001-Secure-configuration-options.patch
meta-resin-pyro/recipes-core/dropbear/dropbear_2016.74.bbappend
meta-resin-pyro/recipes-core/dropbear/files/0001-Secure-configuration-options.patch
meta-resin-rocko/recipes-core/dropbear/dropbear_2017.75.bbappend
meta-resin-rocko/recipes-core/dropbear/files/0001-Secure-configuration-options.patch
meta-resin-sumo/recipes-core/dropbear/dropbear_2017.75.bbappend
meta-resin-sumo/recipes-core/dropbear/files/0001-Secure-configuration-options.patch

dropbear: Enhanced security options

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v7.19.7
---

resin-supervisor: Update to v7.19.7

---

meta-resin-common/classes/kernel-resin.bbclass

Changelog-entry: Add support for aufs 4.14.56+
---

kernel-resin.bbclass: Add support for aufs 4.14.56+

---

meta-resin-common/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-krogoth/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-morty/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-pyro/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-rocko/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-sumo/recipes-devtools/cargo/cargo_0.25.0.bbappend
meta-resin-sumo/recipes-devtools/cargo/files/Cargo.lock

Package bcm43143 separately

---

meta-resin-common/recipes-containers/balena/balena_git.bb

https://github.com/resin-os/balena/pull/101

balena: fix tty console hanging in some cases

---

meta-resin-common/classes/kernel-resin.bbclass
meta-resin-common/recipes-containers/balena/balena_git.bb
meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc
meta-resin-common/recipes-core/resin-extra-udev-rules/files/99-misc.rules
meta-resin-common/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-krogoth/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-morty/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-pyro/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-rocko/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
meta-resin-sumo/recipes-devtools/cargo/cargo_0.25.0.bbappend
meta-resin-sumo/recipes-devtools/cargo/files/Cargo.lock

Submit PRs against the development branch for inclusion in to v2.19
---

Merge development into master for v2.19

---

meta-resin-common/recipes-support/hostapp-update-hooks/files/99-resin-grub

Move grub hooks into meta resin

---

meta-resin-common/recipes-connectivity/redsocks/files/0002-Add-dnsu2t-module-to-convert-DNS-UDP-to-DNS-TCP.patch
meta-resin-common/recipes-connectivity/redsocks/files/0003-Add-OS-dependent-default-configuration-values.patch
meta-resin-common/recipes-connectivity/redsocks/files/0004-dnsu2t.c-Fix-dns-relay-when-there-is-no-TFO-cookie-c.patch
meta-resin-common/recipes-connectivity/redsocks/redsocks_0.5.bb
meta-resin-common/recipes-connectivity/resin-proxy-config/resin-proxy-config/resin-proxy-config

Fixes communication over proxy in containers
Add support for DNS over proxy
---

Proxy: fixes

---

meta-resin-common/classes/binary-compress.bbclass
meta-resin-common/conf/distro/include/resin-os.inc
meta-resin-common/recipes-core/upx/upx-git/0001-Include-lzma-sdk.patch
meta-resin-common/recipes-core/upx/upx.inc
meta-resin-common/recipes-core/upx/upx_3.94.bb
meta-resin-common/recipes-core/upx/upx_3.95.bb
meta-resin-common/recipes-core/upx/upx_git.bb

Fix UPXing ARM binaries

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v7.21.3
---

resin-supervisor: Update to v7.21.3

---

README.md
meta-resin-common/recipes-core/dropbear/dropbear_%.bbappend
meta-resin-common/recipes-core/dropbear/files/dropbear@.service
meta-resin-common/recipes-core/dropbear/files/dropbear_keys_merger
meta-resin-common/recipes-core/os-config/os-config/os-config.json
meta-resin-common/recipes-support/resin-vars/resin-vars.bb
meta-resin-common/recipes-support/resin-vars/resin-vars/os-sshkeys
meta-resin-common/recipes-support/resin-vars/resin-vars/os-sshkeys.service

Custom public SSH keys support

---

meta-resin-common/recipes-core/balena-rollback/files/rollback-health
meta-resin-common/recipes-core/balena-rollback/files/rollback-stop
meta-resin-common/recipes-support/hostapp-update-hooks/files/80-rollback

Prevent rollbacks in case the previous hooks fail

---

meta-resin-common/recipes-connectivity/resin-proxy-config/resin-proxy-config/resin-proxy-config

Fix redsocks interface when no proxy configuration available

---

meta-resin-common/recipes-core/balena-rollback/files/rollback-altboot.service
meta-resin-common/recipes-core/balena-rollback/files/rollback-health.service

Changelog-entry: Improve systemd service ordering in rollbacks
---

balena-rollback: Fix order of systemd dependencies

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc
meta-resin-common/recipes-core/balena-rollback/files/rollback-altboot.service
meta-resin-common/recipes-core/balena-rollback/files/rollback-health.service

merge development to master v2.21

---

meta-resin-common/recipes-connectivity/modemmanager/modemmanager_1.8.2.bb

Fixes #1209
Changelog-entry: Update to ModemManager v1.8.2
---

modemmanager: Update to v1.8.2

---

CONTRIBUTING.md
README.md
contributing-device-support.md
meta-resin-common/recipes-connectivity/modemmanager/modemmanager_1.8.2.bb
meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Release v2.22.0

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Release 2.23.0

---

.gitignore
package-lock.json

These files are generated by the CI when running the automatic
versioning. Since this is not a node project both can be simply ignored.
Signed-off-by: Giovanni Garufi <giovanni@resin.io>
---

.gitignore: add node_modules and package-lock files

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update resin-supervisor to v7.25.5

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v7.25.8
---

resin-supervisor: Update to v7.25.8

---

meta-resin-common/recipes-support/resin-info/resin-info/resin-info

resin-info: Small tweak for balenaCloud product

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v7.25.8
---

[2.23.x][backport] resin-supervisor: Update to v7.25.8

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v8.0.0
---

resin-supervisor: Update to v8.0.0

---

meta-resin-common/recipes-containers/balena/balena/balena.service
meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor/resin-supervisor.service

Signed-off-by: Matthew McGinn <mamcgi@gmail.com>
---

Add SyslogIdentifier= directive to healthdog processes for clarity

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v8.3.5
---

balena-supervisor: Update balena-supervisor to v8.3.5

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

This has changed from "resin" to "balena" due to the rename
Changelog-entry: Migrate the supervisor to balena repositories
---

resin-supervisor.inc: Migrate to balena repositories

---

README.md

README.md: Add info about SSH and Avahi services

---

meta-resin-common/recipes-connectivity/networkmanager/resin-files/99dhcp_ntp
meta-resin-common/recipes-core/chrony/chrony_%.bbappend
meta-resin-common/recipes-core/chrony/files/chrony.conf

Add extra config options to default chrony configuration to improve robustness
---

Improve chrony conf

---

meta-resin-common/classes/image-resin.bbclass

image-resin.bbclass: Enable localMode by default in config.json

---

meta-resin-common/classes/image-resin.bbclass

image-resin.bbclass: Fix config.json pretty format

---

meta-resin-common/recipes-connectivity/libmbim/libmbim_1.16.2.bb
meta-resin-common/recipes-connectivity/libqmi/libqmi_1.20.2.bb

Update libqmi and libmbim

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v8.6.8
---

balena-supervisor: Update to v8.6.8

---

meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

Fixes for the sanity test cases that check if the tools inside the kernel module headers are the correct arch or not.
---

Fix test cases for kernel module headers recipe

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v8.7.0
---

balena-supervisor: Update to v8.7.0

---

meta-resin-common/recipes-connectivity/networkmanager/networkmanager/0001-Do-not-include-net-ethernet.h-and-linux-if_ether.h.patch
meta-resin-common/recipes-connectivity/networkmanager/networkmanager/0001-sd-lldp.h-Remove-net-ethernet.h-seems-to-be-over-spe.patch
meta-resin-common/recipes-connectivity/networkmanager/networkmanager/0002-Fixed-configure.ac-Fix-pkgconfig-sysroot-locations.patch
meta-resin-common/recipes-connectivity/networkmanager/networkmanager/0003-Do-not-create-settings-settings-property-documentati.patch
meta-resin-common/recipes-connectivity/networkmanager/networkmanager/musl/0001-musl-basic.patch
meta-resin-common/recipes-connectivity/networkmanager/networkmanager/musl/0002-musl-dlopen-configure-ac.patch
meta-resin-common/recipes-connectivity/networkmanager/networkmanager/musl/0003-musl-network-support.patch
meta-resin-common/recipes-connectivity/networkmanager/networkmanager/musl/0004-musl-process-util.patch
meta-resin-common/recipes-connectivity/networkmanager/networkmanager/musl/0005-musl-avoid-further-conflicts-by-including-net-ethern.patch
meta-resin-common/recipes-connectivity/networkmanager/networkmanager/musl/0006-Add-a-strndupa-replacement-for-musl.patch
meta-resin-common/recipes-connectivity/networkmanager/networkmanager_%.bbappend
meta-resin-common/recipes-connectivity/networkmanager/networkmanager_1.14.4.bb

Sanity tested on the nuc vm
Wifi connect worked on a pi3.
---

Update network manager to v1.14.4

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v9.0.1
---

balena-supervisor: Update to v9.0.1

---

repo.yml

Signed-off-by: Giovanni Garufi <giovanni@balena.io>
---

VersionBot: update upstream name and url

---

meta-resin-common/classes/image_types_resin.bbclass

When BALENA_BOOT_FAT32 is 1, it will instruct the raw image generator to
create the filesystem using 32 as file allocation tables type and, as
well, create the boot partition as fat32 type.
Changelog-entry: Have boot partition type configurable as FAT32
Fixes https://github.com/balena-os/meta-balena/issues/1350
--- …

image_types_resin.bbclass: Have boot partition type configurable as FAT32

---

meta-resin-common/classes/image_types_resin.bbclass

When BALENA_BOOT_FAT32 is 1, it will instruct the raw image generator to
create the filesystem using 32 as file allocation tables type and, as
well, create the boot partition as fat32 type.
Changelog-entry: Have boot partition type configurable as FAT32
--- …

[2.29.x] image_types_resin.bbclass: Have boot partition type configurable as FAT32

---

meta-resin-common/recipes-connectivity/networkmanager/resin-files/99dhcp_ntp
meta-resin-common/recipes-containers/balena/balena_git.bb

These two commits have been merged in the development branch in https://github.com/balena-os/meta-balena/pull/1361 and https://github.com/balena-os/meta-balena/pull/1358
Backport them to v2.29.x to release v2.29.2
Changed minor to patch for https://github.com/balena-os/meta-balena/pull/1361
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context …

Backport fixes for balena-engine and chrony in v2.29.x

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v9.3.0
---

balena-supervisor: Update balena-supervisor to v9.3.0

---

meta-resin-krogoth/recipes-kernel/linux/kernel-devsrc.bbappend
meta-resin-morty/recipes-kernel/linux/kernel-devsrc.bbappend
meta-resin-pyro/recipes-kernel/linux/kernel-devsrc.bbappend
meta-resin-rocko/recipes-kernel/linux/kernel-devsrc.bbappend
meta-resin-sumo/recipes-kernel/linux/kernel-devsrc.bbappend

Fixes https://github.com/balena-os/meta-balena/issues/1354
From http://cgit.openembedded.org/openembedded-core/commit/meta/recipes-kernel/linux/kernel-devsrc.bb?id=fd74848c3c06901a77057ca03f7c01aff08ee34a
---

Fix some spurious warnings

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v9.4.2
---

balena-supervisor: Update balena-supervisor to v9.4.2

---

meta-resin-common/recipes-connectivity/dnsmasq/balena-files/balena.conf
meta-resin-common/recipes-connectivity/dnsmasq/dnsmasq_%.bbappend
meta-resin-common/recipes-containers/tini/tini_0.14.0.bb
meta-resin-common/recipes-support/resin-vars/resin-vars/resin-vars

A couple of fixes

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

balena-supervisor: Update balena-supervisor to v9.8.3

---

meta-resin-common/recipes-containers/balena/balena_git.bb

balena-engine: Bump to include runc patch

---

meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

Changelog-entry: Improve kernel-module-headers for v4.18+ kernels
---

kernel-modules-headers: Bump tool version

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v9.8.6
---

balena-supervisor: Update to v9.8.6

---

meta-resin-common/recipes-containers/balena/balena_git.bb

See: https://github.com/opencontainers/runc/issues/1766
---

balena-engine: Update to include fix for signal SIGRTMIN+3

---

meta-resin-common/recipes-core/initrdscripts/files/machineid
meta-resin-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand
meta-resin-common/recipes-support/resin-mounts/resin-mounts/resin-partition-mounter

Reduce sleep duration in the critical path in OS

---

meta-resin-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Signed-off-by: Matthew McGinn <mamcgi@gmail.com>
---

resin-init: update resin.io reference to balenaOS

---

meta-resin-common/classes/balena-linux-firmware.bbclass
meta-resin-common/classes/kernel-resin.bbclass
meta-resin-common/recipes-connectivity/modemmanager/modemmanager_%.bbappend
meta-resin-common/recipes-connectivity/networkmanager/networkmanager_%.bbappend
meta-resin-common/recipes-core/systemd/systemd_%.bbappend
meta-resin-sumo/recipes-kernel/linux/linux-firmware_git.bbappend

Disk space optimizations

---

meta-resin-common/classes/image-resin.bbclass
meta-resin-common/recipes-core/os-release/os-release.bbappend

os-release: Fix not deterministic metadata

---

README.md

Taken from fa3de69 commit message
Signed-off-by: Alexis Svinartchouk <alexis@balena.io>

README.md: Document dnsServers behaviour

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v9.9.0
---

balena-supervisor: Update to v9.9.0

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v9.11.0
---

balena-supervisor: Update to v9.11.0

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v9.11.1
---

balena-supervisor: Update to v9.11.1

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v9.11.2
---

balena-supervisor: Update to v9.11.2

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update resin-supervisor to v9.11.3
---

balena-supervisor: Update to v9.11.3

---

README.md

To be more consistent in naming.
Signed-off-by: Roman Mazur <mazur.roman@gmail.com>
---

readme: Replace resin with balena where appropriate

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

balena-supervisor: Update to v9.14.0

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v9.14.6
---

balena-supervisor: Update to v9.14.6

---

meta-resin-common/recipes-connectivity/libmbim/libmbim/clang.patch
meta-resin-common/recipes-connectivity/modemmanager/modemmanager/0001-Add-configure-check-for-canonicalize_file_name-befor.patch

Refresh modemmanager and libmbim patches

---

meta-resin-common/recipes-core/packagegroups/packagegroup-resin-connectivity.bb
meta-resin-common/recipes-support/resin-init/resin-init.bb
meta-resin-common/recipes-support/resin-init/resin-init/resin-init

Replace wireless-tools by iw

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v9.14.9
---

Upgrade balena-supervisor to v9.14.9

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v9.14.10
---

balena-supervisor: Update to v9.14.10

---

meta-resin-common/recipes-support/balena-unique-key/balena-unique-key.bb
meta-resin-common/recipes-support/balena-unique-key/balena-unique-key/balena-unique-key
meta-resin-krogoth/recipes-support/balena-unique-key/balena-unique-key.bbappend
meta-resin-morty/recipes-support/balena-unique-key/balena-unique-key.bbappend
meta-resin-pyro/recipes-support/balena-unique-key/balena-unique-key.bbappend
meta-resin-rocko/recipes-support/balena-unique-key/balena-unique-key.bbappend
meta-resin-sumo/recipes-support/balena-unique-key/balena-unique-key.bbappend

Fix openssl dependency of balena-unique-key (UUID generation)

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v9.15.0
---

balena-supervisor: Update to v9.15.0

---

meta-resin-common/classes/resin-u-boot.bbclass
meta-resin-common/recipes-bsp/u-boot/patches/env_resin.h
meta-resin-common/recipes-core/initrdscripts/files/fsck
meta-resin-common/recipes-core/initrdscripts/files/machineid
meta-resin-common/recipes-core/initrdscripts/files/resindataexpander

Fixes: https://github.com/balena-os/meta-balena/issues/1488
Fixes: https://github.com/balena-os/meta-balena/issues/1452
---

Flasher detection and cmdline in the OS

---

meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

Changelog-entry: Update kernel-module-headers to version v0.0.16
---

kernel-modules-headers: Update to version v0.0.16

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v9.15.4
---

balena-supervisor: Update to v9.15.4

---

meta-resin-common/classes/balena-linux-firmware.bbclass

Fixes https://github.com/balena-os/meta-balena/issues/1527
This adds an easier to debug logging that shows both removed and kept
firmwares. For example:
```
Cleaning iwlwifi firmware version 8000C to minimum API version 34.
Removing iwlwifi-8000C-13.ucode.
Removing iwlwifi-8000C-22.ucode.
Removing iwlwifi-8000C-21.ucode.
Removing iwlwifi-8000C-31.ucode.
Removing iwlwifi-8000C-16.ucode.
Removing iwlwifi-8000C-27.ucode.
Leaving iwlwifi-8000C-34.ucode in place.
Leaving iwlwifi-8000C-36.ucode in place.
```
Also, this commit improves the version comparison which was comparing
strings and not integers. Now we try integer comparison and fallback to
string when parse fails.
Finally, the task's vardeps expands varflags to correctly retrigger on
change.
Changelog-entry: Improve …

balena-linux-firmware: Firmware clean various improvements

---

meta-resin-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb

This update includes an arch64 fix (module.lds) and one for passing the
correct LD flags.
---

kernel-modules-headers: Update to v0.0.18

---

meta-resin-common/recipes-containers/resin-supervisor/resin-supervisor.inc

balena-supervisor: Update to v9.15.8

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

This is done because a feature (RESIN_SUPERVISOR_MIXPANEL_REPORT) needs
more work before releasing in production.
Changelog-entry: Downgrade balena-supervisor to v9.15.7
--- …

balena-supervisor: Downgrade to v9.15.7

---

meta-balena-common/recipes-core/busybox/busybox/balenaos.cfg
meta-balena-thud/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-resin-pyro/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-resin-rocko/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-resin-sumo/recipes-core/initrdscripts/initramfs-framework_%.bbappend

Busybox fix for warrior

---

meta-balena-common/classes/image-resin.bbclass

Fixes #1564
This bbclass uses the common layer path advertised by BBLAYERS to find
the paths to different resources in board repository. For example
machine json - to get the slug and advertise it in os-release. After
renaming the common layer (resin to balena) and because we support old
references to the old common layer name (by including a dummy
deprecation layer), we need to make sure this class can cope now with
both cases.
Changelog-entry: Fix image-resin.bbclass to be able to use deprecated layers
---
- '*Request Changes*' if this change would …

image-resin.bbclass: Fix to be able to use deprecated layers

---

meta-balena-common/classes/image-resin.bbclass
meta-balena-common/conf/layer.conf
meta-balena-thud/recipes-kernel/linux/kernel-devsrc.bbappend

New release

---

meta-balena-common/recipes-connectivity/resin-proxy-config/resin-proxy-config/resin-proxy-config

resin-proxy-config: fix up incorrect bash subshell command

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

balena-supervisor: Update to v9.18.8

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v10.0.3
---

balena-supervisor: Update to v10.0.3

---

meta-balena-common/recipes-containers/balena/balena/balena-healthcheck
meta-balena-common/recipes-containers/balena/balena/balena.service
meta-balena-common/recipes-containers/docker-disk/docker-disk.bb
meta-balena-common/recipes-containers/docker-disk/files/entry.sh
meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
meta-balena-common/recipes-core/packagegroups/packagegroup-resin.bb

Fix hello-world healthcheck

---

meta-balena-common/recipes-core/busybox/busybox/balenaos.cfg
meta-balena-common/recipes-core/busybox/busybox_%.bbappend

busybox: Enable OpenSSL for wget in busybox

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

balena-supervisor: Update to v10.2.2

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc
meta-balena-common/recipes-core/busybox/busybox/balenaos.cfg
meta-balena-common/recipes-core/busybox/busybox_%.bbappend
meta-balena-common/recipes-core/systemd/systemd/vacuum.conf
meta-balena-common/recipes-core/systemd/systemd_%.bbappend

v2.40 release

---

meta-balena-common/recipes-containers/balena/balena_git.bb
meta-balena-thud/recipes-core/volatile-binds/volatile-binds.bbappend
meta-balena-thud/recipes-core/volatile-binds/volatile-binds/mount-copybind
meta-balena-warrior/recipes-core/images/resin-image-initramfs.bbappend
meta-balena-warrior/recipes-core/initrdscripts/files/console_null_workaround
meta-balena-warrior/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-warrior/recipes-core/volatile-binds/volatile-binds.bbappend
meta-balena-warrior/recipes-core/volatile-binds/volatile-binds/mount-copybind

v2.41 release

---

meta-balena-common/recipes-connectivity/networkmanager/resin-files/nm-tmpfiles.conf
meta-balena-common/recipes-connectivity/openvpn/files/openvpn.service
meta-balena-common/recipes-connectivity/openvpn/openvpn/openvpn@.service
meta-balena-common/recipes-containers/balena/balena/balena-tmpfiles.conf

Fix systemd tmpfile warnings

---

meta-balena-common/classes/image-resin.bbclass
meta-balena-common/recipes-devtools/kernel-modules-headers/files/gen_mod_headers
meta-balena-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
meta-balena-common/recipes-kernel/linux/files/Dockerfile
meta-balena-common/recipes-kernel/linux/files/example_module/Makefile
meta-balena-common/recipes-kernel/linux/files/example_module/hello.c
meta-balena-common/recipes-kernel/linux/kernel-devsrc.bb
meta-balena-common/recipes-kernel/linux/kernel-headers-test.bb

Add recipe to run build time tests for kernel module headers

---

meta-balena-common/classes/image-resin.bbclass
meta-balena-common/recipes-containers/balena/balena/balena-host.service
meta-balena-common/recipes-containers/balena/balena/balena.conf.systemd
meta-balena-common/recipes-containers/balena/balena/balena.service
meta-balena-common/recipes-devtools/kernel-modules-headers/files/gen_mod_headers
meta-balena-common/recipes-devtools/kernel-modules-headers/kernel-modules-headers.bb
meta-balena-common/recipes-kernel/linux/files/Dockerfile
meta-balena-common/recipes-kernel/linux/files/example_module/Makefile
meta-balena-common/recipes-kernel/linux/files/example_module/hello.c
meta-balena-common/recipes-kernel/linux/kernel-devsrc.bb
meta-balena-common/recipes-kernel/linux/kernel-headers-test.bb
meta-balena-warrior/recipes-core/initrdscripts/files/console_null_workaround

v2.42 Release

---

meta-balena-common/recipes-connectivity/modemmanager/modemmanager_1.10.6.bb
meta-balena-common/recipes-connectivity/networkmanager/networkmanager_1.20.2.bb

Update NM and MM

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v10.3.7
---

balena-supervisor: Update to v10.3.7

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor

Depends on #1679
See also 
- https://github.com/balena-io/balena-supervisor/pull/1038
- https://github.com/balena-os/balena-engine/pull/174
- https://github.com/balena-os/balena-engine-cli/pull/8
Signed-off-by: Roman Mazur <roman@balena.io>
--- …

resin-supervisor: Expose container ID via env variable

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/resin-supervisor-healthcheck

Missed to push this change to the #1690 before merging.
---

resin-supervisor: Fix healthcheck

---

docs/hooks.md
meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
meta-balena-common/recipes-core/balena-rollback/files/rollback-health
meta-balena-common/recipes-support/hostapp-update-hooks/files/hostapp-update-hooks
meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb

Add support for Hooks 2.0

---

meta-balena-common/recipes-core/systemd/systemd/journald-balena-os.conf
meta-balena-common/recipes-core/systemd/systemd/vacuum.conf
meta-balena-common/recipes-support/resin-mounts/resin-mounts.inc

Connects-to: #1646
Changelog-entry: Increase max journal size to 32M and persist to data partition
---

persistent-logs: increase max journal size to 32M and persist to data partition

---

repo.yml

Signed-off-by: Giovanni Garufi <giovanni@balena.io>
---

Update repo.yml for ESR

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v9.15.11
---

balena-supervisor: Update to v9.15.11

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor

resin-supervisor: Fix for race condition when supervisor starts on boot

---

CONTRIBUTING.md
README.md
contributing-device-support.md
meta-balena-common/README.md
meta-balena-common/recipes-connectivity/openvpn/files/prepare-openvpn
meta-balena-common/recipes-connectivity/openvpn/openvpn/resin.conf
meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc
meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/resin-supervisor.service
meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor
meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor
meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor.service
meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor.timer
meta-balena-common/recipes-core/balena-rollback/files/rollback-check-version
meta-balena-common/recipes-core/systemd/systemd/balena-os-sysctl.conf
meta-balena-thud/README.md
meta-balena-warrior/README.md
meta-balena-warrior/recipes-core/images/resin-image-initramfs.bbappend
meta-resin-pyro/README.md
meta-resin-rocko/README.md
meta-resin-sumo/README.md

---
- [ x] `Change-type` present on at least one commit
- [x ] `Signed-off-by` is present
- [x ] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines) …

v2.46 release

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc
meta-balena-common/recipes-core/balena-rollback/files/rollback-altboot.service
meta-balena-common/recipes-core/balena-rollback/files/rollback-health.service

Update balena-supervisor to v9.15.12 and another fix from master
---

v2.38.x release

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor
meta-balena-common/recipes-core/balena-rollback/files/rollback-check-version
meta-balena-common/recipes-core/systemd/systemd/balena-os-sysctl.conf
meta-balena-warrior/recipes-core/images/resin-image-initramfs.bbappend

Cherry picked commits from master
---

Backported fixes for v2.44.x

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v10.6.13
---

balena-supervisor: Update to v10.6.13

---

meta-balena-common/recipes-containers/balena/balena/balena-healthcheck
meta-balena-common/recipes-containers/balena/balena/balena-healthcheck-image-load
meta-balena-common/recipes-containers/balena/balena/balena.service
meta-balena-common/recipes-containers/balena/balena_git.bb
meta-balena-common/recipes-containers/docker-disk/docker-disk.bb
meta-balena-common/recipes-containers/docker-disk/files/entry.sh

Namespace hello-world healthcheck image

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v10.6.17
---

balena-supervisor: Update to v10.6.17

---

meta-balena-common/recipes-connectivity/openvpn/openvpn/openvpn
meta-balena-common/recipes-connectivity/openvpn/openvpn_2.4.7.bb

Fetched from:
* https://git.openembedded.org/meta-openembedded/commit/meta-networking/recipes-support/openvpn/openvpn_2.4.7.bb?id=c1c8895609ae70a1b735e8625c19046c25184ee4
* https://git.openembedded.org/meta-openembedded/commit/meta-networking/recipes-support/openvpn/openvpn/openvpn?id=910891d722085c56c474ac72788898b94c5ed193
Connects-to: #1740
Changelog-entry: Update openvpn to v2.4.7
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance …

openvpn: Update to v2.4.7

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor to v10.6.27
---

balena-supervisor: Update to v10.6.27

---

meta-balena-common/classes/kernel-resin.bbclass

Add uinput user level driver support directly from meta-balena
as this will benefit all our customers.
Changelog-entry: Add uinput kernel module
---

kernel-resin.bbclass: Add uinput module

---

README.md

Americanize the README.md

---

README.md

This PR builds extends this https://github.com/balena-io/docs/pull/1249 where config.json docs were merged into the docs https://www.balena.io/docs/reference/OS/configuration/. As these valid fields are shared content I'd like to pull this directly from this repo to maintain a single source.
Discussion for any substantive content change (e.g. `dnsServers` can be found in the discussions of the linked PR)  
--- …

README.md: Update config.json documentation

---

meta-balena-common/recipes-connectivity/bluez5/bluez5_%.bbappend

Enable sixaxis in bluez

---

README.md

Update readme usb dongle

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Fixes #1828
Changelog-entry: Use a weak default assignment in a recipe for customer trying to override a variable in his layer
---

resin-supervisor: Use weak assignment

---

README.md

Changelog-entry: Update config.json documentation for disabling NM connectivity checks
Signed-off-by: Gareth Davies gareth@balena.io
---

README.md: Update config.json docs for disabling NM connectivity checks

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from  to v10.8.0
Changelog-entry: Update balena-supervisor from  to v10.8.0
---

balena-supervisor: Update to v10.8.0

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v10.8.0 to v10.11.0
Changelog-entry: Update balena-supervisor from v10.8.0 to v10.11.0
---

balena-supervisor: Update to v10.11.0

---

docs/os-internals.md
meta-balena-common/classes/kernel-resin.bbclass
meta-balena-common/classes/resin-u-boot.bbclass
meta-balena-common/recipes-bsp/u-boot/patches/env_resin.h
meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
meta-balena-common/recipes-core/images/resin-image-initramfs.bb
meta-balena-common/recipes-core/initrdscripts/files/fsck
meta-balena-common/recipes-core/initrdscripts/files/fsuuidsinit
meta-balena-common/recipes-core/initrdscripts/files/machineid
meta-balena-common/recipes-core/initrdscripts/files/prepare
meta-balena-common/recipes-core/initrdscripts/files/resindataexpander
meta-balena-common/recipes-core/initrdscripts/files/rootfs
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-common/recipes-core/systemd/systemd/60-resin-update-state.rules
meta-balena-common/recipes-core/systemd/systemd/resin_update_state_probe
meta-balena-common/recipes-core/systemd/systemd_%.bbappend
meta-balena-common/recipes-devtools/mtools/mtools_%.bbappend
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-logging
meta-balena-common/recipes-support/resin-expand/resin-filesystem-expand.bb
meta-balena-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand
meta-balena-common/recipes-support/resin-mounts/resin-mounts.bb
meta-balena-common/recipes-support/resin-mounts/resin-mounts/resin-partition-mounter

---
This commit is related to https://github.com/balena-os/balena-intel/pull/289

Boot using udev by-state symlinks instead of labels

---

meta-balena-common/recipes-containers/balena/balena/balena-host.service

Fix hostapp update offline

---

meta-balena-common/recipes-connectivity/modemmanager/modemmanager_1.12.8.bb

Fixes #1859
Changelog-entry: Update ModemManager to v1.12.8
---

modemmanager: Update to v1.12.8

---

meta-balena-common/recipes-containers/balena/balena_git.bb

Fixes the bug in mobynit caused by the recent work on the graphdriver
system
---

Bump balena-engine to 18.09.17

---

docs/os-internals.md
meta-balena-common/classes/kernel-resin.bbclass
meta-balena-common/classes/resin-u-boot.bbclass
meta-balena-common/recipes-bsp/u-boot/patches/env_resin.h
meta-balena-common/recipes-connectivity/modemmanager/modemmanager_1.12.8.bb
meta-balena-common/recipes-connectivity/networkmanager/resin-files/NetworkManager.conf.systemd
meta-balena-common/recipes-containers/balena/balena/balena-host.service
meta-balena-common/recipes-containers/balena/balena_git.bb
meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc
meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor
meta-balena-common/recipes-core/images/resin-image-initramfs.bb
meta-balena-common/recipes-core/initrdscripts/files/fsck
meta-balena-common/recipes-core/initrdscripts/files/fsuuidsinit
meta-balena-common/recipes-core/initrdscripts/files/machineid
meta-balena-common/recipes-core/initrdscripts/files/prepare
meta-balena-common/recipes-core/initrdscripts/files/resindataexpander
meta-balena-common/recipes-core/initrdscripts/files/rootfs
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-common/recipes-core/systemd/systemd/60-resin-update-state.rules
meta-balena-common/recipes-core/systemd/systemd/resin_update_state_probe
meta-balena-common/recipes-core/systemd/systemd_%.bbappend
meta-balena-common/recipes-devtools/mtools/mtools_%.bbappend
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-logging
meta-balena-common/recipes-support/resin-expand/resin-filesystem-expand.bb
meta-balena-common/recipes-support/resin-expand/resin-filesystem-expand/resin-filesystem-expand
meta-balena-common/recipes-support/resin-mounts/resin-mounts.bb
meta-balena-common/recipes-support/resin-mounts/resin-mounts/resin-partition-mounter

2.49.0 release

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v10.11.0 to v11.3.0
Changelog-entry: Update balena-supervisor from v10.11.0 to v11.3.0
---

balena-supervisor: Update to v11.3.0

---

meta-balena-common/recipes-connectivity/libqmi/libqmi_1.24.10.bb

Changelog-entry: Update to libqmi v1.24.10
---

libqmi: update to v1.24.10

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v10.8.0 to v10.8.1
Changelog-entry: Update balena-supervisor from v10.8.0 to v10.8.1
---

balena-supervisor: Update to v10.8.1

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v11.3.0 to v11.4.1
Changelog-entry: Update balena-supervisor from v11.3.0 to v11.4.1
---

balena-supervisor: Update to v11.4.1

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v11.4.1 to v11.4.10
Changelog-entry: Update balena-supervisor from v11.4.1 to v11.4.10
---

balena-supervisor: Update to v11.4.10

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v11.4.10 to v11.4.14
Changelog-entry: Update balena-supervisor from v11.4.10 to v11.4.14
---

balena-supervisor: Update to v11.4.14

---

meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs

Fallback to legacy root device detection to support devices with closed source bootloaders

---

meta-balena-common/recipes-containers/balena/balena_git.bb
meta-balena-common/recipes-support/bindmount/bindmount_0.0.1.bb

Use renamed repos

---

repo.yml

Generate nested changelogs for balena-engine

---

meta-balena-common/classes/resin-u-boot.bbclass
meta-balena-common/recipes-bsp/u-boot/patches/env_resin.h
meta-balena-common/recipes-core/images/resin-image.bb

Allow setting cmdline args and custom fdt from supervisor

---

meta-balena-common/classes/kernel-resin.bbclass
meta-balena-common/recipes-core/packagegroups/packagegroup-resin.bb
meta-balena-common/recipes-core/systemd/systemd/10-zram.rules
meta-balena-common/recipes-core/systemd/systemd/dev-zram0.swap
meta-balena-common/recipes-core/systemd/systemd/zram-swap-init
meta-balena-common/recipes-core/systemd/systemd_%.bbappend

Enable compressed memory swap

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v11.9.2 to v11.9.3
Changelog-entry: Update balena-supervisor from v11.9.2 to v11.9.3
---

balena-supervisor: Update to v11.9.3

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/update-resin-supervisor
meta-balena-common/recipes-support/resin-device-progress/resin-device-progress/resin-device-progress
meta-balena-common/recipes-support/resin-device-register/resin-device-register/resin-device-register

Update to use api v6 and fix a quoting bug

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v11.9.3 to v11.9.4
Changelog-entry: Update balena-supervisor from v11.9.3 to v11.9.4
Signed-off-by: Rich Bayliss <rich@balena.io>

balena-supervisor: Update to v11.9.4

---

repo.yml

Add next, current and sunset ESR versions for backporting fixes via
commit logs.
---

repo: Update backports branches

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from 11.9.6 to 11.9.8
Backport-to: next
---

balena-supervisor: Update to v11.9.8

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from 11.9.8 to 11.9.9
Signed-off-by: Rich Bayliss <rich@balena.io>
---

balena-supervisor: Update to v11.9.9

---

meta-balena-common/recipes-support/resin-device-progress/resin-device-progress/resin-device-progress
meta-balena-common/recipes-support/resin-device-register/resin-device-register/resin-device-register

Use a named key when querying for device by uuid

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v11.9.9 to v11.12.2
Changelog-entry: Update balena-supervisor from v11.9.9 to v11.12.2
---

balena-supervisor: Update to v11.12.2

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v11.12.2 to v11.12.4
Backport-to: next
---

balena-supervisor: Update to v11.12.4

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v11.12.4 to v11.13.0
Changelog-entry: Update balena-supervisor from v11.12.4 to v11.13.0
---

balena-supervisor: Update to v11.13.0

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v11.13.0 to v11.14.0
Changelog-entry: Update balena-supervisor from v11.13.0 to v11.14.0
---

balena-supervisor: Update to v11.14.0

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/0-bootfiles

hooks: fix up improperly named variable

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/0-bootfiles

bootfiles: blacklist proper grub configuration backend

---

README.md

readme: DCHP -> DHCP

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from v12.1.1 to v12.1.1
Changelog-entry: Update balena-supervisor from v12.1.1 to v12.1.1
---

balena-supervisor: Update to v12.1.1

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/start-resin-supervisor

supervisor: remove old/unnecessary balenaRootCA references

---

meta-balena-common/classes/kernel-resin.bbclass

Links to: https://github.com/balena-os/meta-balena/issues/2066
---

Kernel task accounting

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor from v12.1.1 to v12.2.11

balena-supervisor: Update to 12.2.11

---

README.md

The file rename happened in v2.51 but the README has not been updated
accordingly.
---

README: Rename resin-logo to balena-logo.

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor from v12.2.11 to v12.3.0
Signed-off-by: Felipe Lalanne <felipe@balena.io>
---

balena-supervisor: Update to 12.3.0

---

README.md

Connects-to: https://github.com/balena-os/meta-balena/issues/2011
---

docs: mention balenaRootCA as a config.json parameter

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor from v12.3.0 to v12.3.5
---

balena-supervisor: Update to 12.3.5

---

tests/suites/os/conf.js
tests/suites/os/suite.js

Update OS test suites

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor from v12.3.5 to v12.4.6
Signed-off-by: Felipe Lalanne <felipe@balena.io>
---

balena-supervisor: update to 12.4.6

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor from v12.4.6 to v12.5.6
Signed-off-by: Christina Wang <christina@balena.io>
---

balena-supervisor: Update to 12.5.6

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Changelog-entry: Update balena-supervisor from v12.5.6 to v12.5.10
Signed-off-by: Christina Wang <christina@balena.io>
---

balena-supervisor: Update to 12.5.10

---

tests/suites/os/suite.js
tests/suites/os/tests/config-json/index.js

Reactivate Persistent Logging test

---

tests/suites/os/tests/healthcheck/index.js

This change makes a fix to the container healthcheck test by adding a retry, based on the failed test here: https://jenkins.dev.resin.io/job/leviathan-raspberry-pi/563/console 
--- …

add retries to status check

---

meta-balena-common/recipes-connectivity/modemmanager/balena-files/77-mm-u-blox-modeswitch.rules
meta-balena-common/recipes-connectivity/modemmanager/balena-files/u-blox-switch.sh
meta-balena-common/recipes-connectivity/modemmanager/balena-files/u-blox-switch@.service

Rework the u-blox modem switch to ECM mode

---

meta-balena-common/recipes-bsp/grub/grub-efi_%.bbappend

Signed-off-by: Joseph Kogut <joseph.kogut@gmail.com>
---

grub: grub-efi: buildin gzio for gz compressed kernels

---

meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor.inc

Update balena-supervisor from 12.5.10 to 12.7.0
Connects-to: https://github.com/balena-os/meta-balena/pull/2171
Changelog-entry: Update balena-supservisor from v12.5.10 to v12.7.0
--- …

balena-supervisor: Update to 12.7.0

---

README.md

Add the warrior and dunfell versions to the list of tested releases.
---

README: Update supported Yocto versions

---

meta-balena-common/recipes-connectivity/bluez5/bluez5_%.bbappend
meta-balena-common/recipes-connectivity/bluez5/files/bluetooth.conf.systemd
meta-balena-common/recipes-connectivity/bluez5/files/main.conf

bluez: Set AutoEnable and fix bluetooth service

---

meta-balena-common/recipes-connectivity/resin-net-config/resin-net-config/resin-net-config
meta-balena-common/recipes-support/ca-certificates/ca-certificates/extract-balena-ca
meta-balena-common/recipes-support/hostapp-update-hooks/files/75-supervisor-db/75-forward_supervisor-db

Sync file modifications to disk to protect against power losses

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

Update balena-supervisor from 12.7.0 to 12.8.7
Changelog-entry: Update balena-supervisor from v12.7.0 to v12.8.7
---

balena-supervisor: Update to 12.8.7

---

tests/suites/os/tests/boot-splash/index.js

As noted by the OS team the automated HDMI test sometimes fails. There are 2 variations of this failure:
- no frames captured (this is exclusive to Rpi0 so far)
- occasionally the path name of a captured frame is corrupt when it is being read - I have added a change to catch that error and not immediately fail the test
--- …

Make HDMI test more consistant

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

Update balena-supervisor from 12.8.7 to 12.8.8
Changelog-entry: Update balena-supervisor from v12.8.7 to v12.8.8
---

balena-supervisor: Update to 12.8.8

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/75-supervisor-db/75-forward_supervisor-db
meta-balena-common/recipes-support/hostapp-update-hooks/files/75-supervisor-db/75-fwd_commit_supervisor-db
meta-balena-common/recipes-support/hostapp-update-hooks/files/76-supervisor-db/76-forward_supervisor-db
meta-balena-common/recipes-support/hostapp-update-hooks/files/76-supervisor-db/76-fwd_commit_supervisor-db
meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb

When we renamed the resin-supervisor to balena-supervisor some migrations were missed.
This PR should handle the database unless the user is already running v2.80.0 or newer. The only downside of a missed migration seems to be a message that images are downloading again before they are actually found on disk.
Copied the tested flow from this previous PR: https://github.com/balena-os/meta-balena/pull/2071
Resolves: https://github.com/balena-os/meta-balena/issues/2222
**Manual test case**
1. Provision a Balena Fin (CM3) to `2.77.0+rev1` in balena cloud
2. Record the output of the following
```bash
ls -al /mnt/data/resin-data/
```
3. Download `balena-image.docker` from a Jenkins build of this PR
4. Load, tag, and push the image to a personal docker registry
```bash
MACHINE=fincm3 …
```

Migrate supervisor database after supervisior rename

---

tests/suites/os/suite.js

This patch fetches the journal logs from the DUT at the end of the OS test suite, and makes them available to view as an artifact in jenkins
---

get journal logs at the end of test suite

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

Update balena-supervisor from 12.8.8 to 12.9.3
Changelog-entry: Update balena-supervisor from v12.8.8 to v12.9.3
---

balena-supervisor: update to 12.9.3

---

meta-balena-common/classes/image-balena.bbclass
meta-balena-common/classes/image_types_balena.bbclass
meta-balena-common/recipes-core/images/balena-image.bb

Fail build if hostOS update file won't fit rootfs partition

---

tests/suites/os/tests/config-json/index.js

We no longer require reboots when changing dnsServers in config.json and the service should restart on it's own.
Test for all the supported values as per https://www.balena.io/docs/reference/OS/configuration/#dnsservers
Resolves: https://github.com/balena-os/meta-balena/issues/2252
Connects-to: https://github.com/balena-os/meta-balena/pull/2250
---
1. Apply custom servers via `config.json`
2. Confirm `dnsmasq` has restarted and is active with new servers
```bash
jq '.dnsServers = "1.2.3.4"' /mnt/boot/config.json > /mnt/data/config.json && mv /mnt/data/config.json /mnt/boot/config.json
systemctl status dnsmasq.service config-json.*
jq '.dnsServers = "null"' /mnt/boot/config.json > /mnt/data/config.json && mv …
```

Remove reboot requirement from dnsmasq tests

---

meta-balena-common/recipes-core/balena-rollback/files/rollback-altboot
tests/suites/hup/suite.js
tests/suites/hup/tests/rollback-altboot.js
tests/suites/hup/tests/rollback-health.js
tests/suites/hup/tests/smoke.js

https://github.com/balena-os/meta-balena/blob/master/docs/rollbacks.md

Add HUP rollback tests

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/balena-supervisor.service
meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/start-balena-supervisor
meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor

Avoid removing supervisor containers in 3 different places
and consolidate the steps into `start-balena-supervisor`.
**Manual test case**
1. Provision a Pi4 to `2.75.0+rev1` in staging cloud
2. Record the output of the following
```bash
cat /etc/os-release
cat /etc/*-supervisor/supervisor.conf
cat /tmp/update-supervisor.conf
balena images
balena ps -a
```
3. Download `balena-image.docker` from a Jenkins build of this PR
4. Load, tag, and push the image to a personal docker registry
```bash
MACHINE=raspberrypi4-64
SHA256=$(docker load -q -i ~/Downloads/balena-image.docker | awk '{print $4}')
docker tag $SHA256 klutchell/balenaos:$MACHINE
docker push klutchell/balenaos:$MACHINE
```
5. Run hostapp-update on device to …

Consolidate supervisor container removal

---

meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_20210511.bb

Add recipe from poky hardknott, revision 74dbb08
---

linux-firmware: upgrade 20190815 -> 20210511

---

meta-balena-common/recipes-containers/balena/balena_git.bb

Update balena-engine from 19.03.23 to 19.03.24
Changelog-entry: Update balena-engine to v19.03.24
---

balena-engine: Update to 19.03.24

---

meta-balena-common/classes/balena-linux-firmware.bbclass
meta-balena-common/classes/kernel-balena.bbclass
meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_20210511.bb

Add firmware compression support

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

Update balena-supervisor from 12.9.3 to 12.10.3
---

balena-supervisor: Update balena-supervisor to v12.10.3

---

tests/suites/hup/suite.js
tests/suites/os/suite.js
tests/suites/os/tests/boot-splash/index.js

The changes are as follows:
1. Delete custom logic in tests for archiving logs
2. Make use of the new archiveLogs helper
3. Make use of the new implementation of the Archiver module
--- …

tests: Use new Archiver implementation & helpers

---

contributing-device-support.md

contributing-device-support.md: Updates to board support instructions

---

tests/suites/os/tests/connectivity/index.js

tests: Remove reboots from redsocks test cases

---

meta-balena-common/recipes-core/systemd/systemd-serialgetty.bbappend
meta-balena-common/recipes-core/systemd/systemd-serialgetty/development-features.conf
meta-balena-common/recipes-core/systemd/systemd/balena-os-sysctl.conf
meta-balena-common/recipes-core/systemd/systemd/getty-service-development-features.conf
meta-balena-common/recipes-core/systemd/systemd/getty-target-development-features.conf
meta-balena-common/recipes-core/systemd/systemd_%.bbappend
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/os-sshkeys.service

Performing unit modifications in drop-in files in better practise.
---

systemd: Use drop-in to modify unit files instead of sed

---

README.md

See: https://github.com/balena-io/docs/issues/2116
---

patch: Fix URL to yocto project dependencies

---

meta-balena-common/recipes-tpm2/tpm2-abrmd/files/tpm2-abrmd-init.sh
meta-balena-common/recipes-tpm2/tpm2-abrmd/files/tpm2-abrmd.default
meta-balena-common/recipes-tpm2/tpm2-abrmd/tpm2-abrmd_2.4.0.bb
meta-balena-common/recipes-tpm2/tpm2-tools/tpm2-tools_5.0.bb
meta-balena-common/recipes-tpm2/tpm2-tss/tpm2-tss/0001-configure.ac-fix-compatibility-with-autoconf-2.70.patch
meta-balena-common/recipes-tpm2/tpm2-tss/tpm2-tss/ax_pthread.m4
meta-balena-common/recipes-tpm2/tpm2-tss/tpm2-tss/fix_musl_select_include.patch
meta-balena-common/recipes-tpm2/tpm2-tss/tpm2-tss_3.0.3.bb

Taken as is from http://git.yoctoproject.org/cgit/cgit.cgi/meta-security/tree/meta-tpm/recipes-tpm2
Only add the recipes, let DTs pull it as necessary.
---

Add recipes for TPM2 tools

---

meta-balena-common/recipes-kernel/peak/peak_8.12.0.bb

Only add the recipe, let DTs pull it as necessary
---

Add out-of-tree peak CAN driver

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend

initrdscripts: add a script for unlocking LUKS volumes

---

meta-balena-common/recipes-support/resin-mounts/resin-mounts.bb
meta-balena-common/recipes-support/resin-mounts/resin-mounts/balena-efi.service
meta-balena-common/recipes-support/resin-mounts/resin-mounts/resin-partition-mounter

resin-mounts: mount EFI partition if it is split from boot

---

meta-balena-common/classes/sign-efi.bbclass
meta-balena-common/classes/sign-kmod.bbclass
meta-balena-common/classes/sign.bbclass

Add signing classes

---

meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend

initramfs-module-cryptsetup: add TPM dependencies

---

meta-balena-common/recipes-bsp/grub/grub-conf.bb
meta-balena-common/recipes-bsp/grub/grub-conf/grub.cfg_internal_luks_template
meta-balena-common/recipes-bsp/grub/grub-efi/pass-secure-boot.patch
meta-balena-common/recipes-bsp/grub/grub-efi_%.bbappend
meta-balena-common/recipes-core/initrdscripts/files/kexec
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-resin-pyro/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-resin-sumo/recipes-core/initrdscripts/initramfs-framework_%.bbappend

Refactor mtoman/kexec-stage2

---

meta-balena-common/classes/kernel-balena.bbclass
meta-resin-pyro/recipes-support/gnupg/gnupg_%.bbappend
meta-resin-pyro/recipes-support/libksba/libksba_%.bbappend
meta-resin-pyro/recipes-support/npth/npth_%.bbappend
meta-resin-pyro/recipes-support/pinentry/pinentry_%.bbappend
meta-resin-rocko/recipes-support/gnupg/gnupg_%.bbappend
meta-resin-rocko/recipes-support/libksba/libksba_%.bbappend
meta-resin-rocko/recipes-support/npth/npth_%.bbappend
meta-resin-rocko/recipes-support/pinentry/pinentry_%.bbappend

kernel-balena.class: Add support for FDE and sign for secure boot

---

meta-balena-common/recipes-kernel/peak/peak_8.12.0.bb

peak: Modify kernel driver to use signing class

---

meta-balena-common/recipes-bsp/efitools/efitools-native_git.bb
meta-balena-common/recipes-bsp/efitools/efitools.inc
meta-balena-common/recipes-bsp/efitools/efitools/0001-console.c-Fix-compilation-against-latest-usr-include.patch
meta-balena-common/recipes-bsp/efitools/efitools/Add-static-keyword-for-IsValidVariableHeader.patch
meta-balena-common/recipes-bsp/efitools/efitools/Allow-to-override-tools-for-target-build.patch
meta-balena-common/recipes-bsp/efitools/efitools/Build-DBX-by-default.patch
meta-balena-common/recipes-bsp/efitools/efitools/Don-t-build-PreLoader.efi.patch
meta-balena-common/recipes-bsp/efitools/efitools/Dynamically-load-openssl.cnf-for-openssl-1.0.x-1.1.x.patch
meta-balena-common/recipes-bsp/efitools/efitools/Fix-for-the-cross-compilation.patch
meta-balena-common/recipes-bsp/efitools/efitools/Fix-help2man-error.patch
meta-balena-common/recipes-bsp/efitools/efitools/Fix-help2man-failure.patch
meta-balena-common/recipes-bsp/efitools/efitools/Fix-the-wrong-dependency-for-blacklist.esl.patch
meta-balena-common/recipes-bsp/efitools/efitools/Kill-all-the-build-warning-caused-by-implicit-declar.patch
meta-balena-common/recipes-bsp/efitools/efitools/LockDown-disable-the-entrance-into-BIOS-setup-to-re-.patch
meta-balena-common/recipes-bsp/efitools/efitools/LockDown-enable-the-enrollment-for-DBX.patch
meta-balena-common/recipes-bsp/efitools/efitools/LockDown-run-system-warm-reset-after-the-key-provisi.patch
meta-balena-common/recipes-bsp/efitools/efitools/LockDown-show-the-error-message-with-3-sec-timeout.patch
meta-balena-common/recipes-bsp/efitools/efitools/Makefile-do-not-build-signed-efi-image.patch
meta-balena-common/recipes-bsp/efitools/efitools/Reuse-xxdi.pl.patch
meta-balena-common/recipes-bsp/efitools/efitools_git.bb
meta-balena-common/recipes-devtools/sbsigntool/sbsigntool/0001-Fix-openssl-3.0-issue-involving-ASN1-xxx_it.patch
meta-balena-common/recipes-devtools/sbsigntool/sbsigntool/0001-Makefile.am-do-not-use-Werror.patch
meta-balena-common/recipes-devtools/sbsigntool/sbsigntool/0001-configure-Dont-t-check-for-gnu-efi.patch
meta-balena-common/recipes-devtools/sbsigntool/sbsigntool/0001-fileio.c-initialize-local-variables-before-use-in-fu.patch
meta-balena-common/recipes-devtools/sbsigntool/sbsigntool/0001-src-Makefile.am-Add-read_write_all.c-to-common_SOURC.patch
meta-balena-common/recipes-devtools/sbsigntool/sbsigntool/0002-docs-Don-t-build-man-pages.patch
meta-balena-common/recipes-devtools/sbsigntool/sbsigntool/0003-sbsign-add-x-option-to-avoid-overwrite-existing-sign.patch
meta-balena-common/recipes-devtools/sbsigntool/sbsigntool_git.bb

Add efitools

---

meta-balena-common/recipes-core/base-files/base-files/mdns.allow
meta-balena-common/recipes-core/base-files/base-files/nsswitch.conf
meta-balena-common/recipes-core/base-files/base-files_%.bbappend

common: enable multi-label mDNS resolution and IPv6

---

tests/suites/os/tests/config-json/index.js

One of the test was making sure we were NOT using the default 8.8.8.8
server even though that may be a valid upstream server provided by DHCP/PPP.
---

tests: Fix dnsmasq tests in cases where 8.8.8.8 is assigned via DHCP

---

meta-balena-common/recipes-core/initrdscripts/files/fsck
tests/suites/os/suite.js
tests/suites/os/tests/fsck/index.js

Related to: https://github.com/balena-os/meta-balena/issues/2156
---

Fsck resin data w/ test

---

meta-balena-common/classes/image-balena.bbclass

common: image-balena: enable developmentMode when OS_DEVELOPMENT=1

---

tests/suites/os/suite.js
tests/suites/os/tests/device-specific-tests/revpi-core-3/index.js

Test output:
```
[2021-11-26T13:14:05.856Z][192-os] Powering on DUT
[2021-11-26T13:14:14.161Z][192-os] DUT powered on
[2021-11-26T13:14:14.161Z][192-os] Waiting for device to be reachable
[2021-11-26T13:14:44.692Z][192-os] # Subtest: Unmanaged BalenaOS release suite
[2021-11-26T13:14:45.598Z][192-os] Rebooting the DUT
[2021-11-26T13:15:38.026Z][192-os] DUT has rebooted & is back online
[2021-11-26T13:15:41.834Z][192-os]     # Subtest: RevPi Core 3 DIO module test
[2021-11-26T13:15:41.835Z][192-os]         ok 1 - Test binary should return: Bit value: 1
[2021-11-26T13:16:03.643Z][192-os]         ok 2 - Test binary should return: Bit value: 0
[2021-11-26T13:16:03.650Z][192-os]         1..2 …
```

tests: Add RevPi Core 3 DIO module test

---

meta-balena-common/recipes-core/systemd/systemd/60-resin-update-state.rules
meta-balena-common/recipes-core/systemd/systemd/resin_update_state_probe

Update udev rules for LUKS

---

tests/suites/os/suite.js
tests/suites/os/tests/device-specific-tests/beaglebone-black/index.js

tests: Add BeagleBone Black u-boot overlay test

---

repo.yml

This should be done automatically on the ESR creation script.
---

repo.yml: Correct ESR backports metadata

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/60-data-breadcrumb
meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb
tests/suites/hup/tests/smoke.js

Resolves: https://github.com/balena-os/meta-balena/issues/2429
---

hostapp-update-hooks: Ensure data breadcrumb is present before HUP

---

docs/rollbacks.md

Resolves: https://github.com/balena-os/meta-balena/issues/2427
---

docs: Fix links in Rollback documentation

---

meta-balena-common/recipes-connectivity/networkmanager/balena-files/balena-client-id.patch
meta-balena-common/recipes-connectivity/networkmanager/balena-files/remove-https-warning.patch
meta-balena-common/recipes-connectivity/networkmanager/networkmanager_1.32.12.bb

Changelog-entry: Update NetworkManager to 1.32.12
---

networkmanager: Update to 1.32.12

---

meta-balena-common/conf/distro/include/balena-os.inc

Now that we have the aufs to overlay2 migrator in place, let's switch
all our boards to overlay2.
---

balena-os.inc: Switch balena backend storage to overlay2

---

tests/suites/os/tests/fsck/index.js

Chain operations using Promise.then(), and run commands in parallel
using Promise.map(). This reduces the time taken for fsck tests to about
half.
- ok 1 - fsck.ext4 tests # time=152304.735ms
+ ok 1 - fsck.ext4 tests # time=75104.016ms
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand …

os: tests: optimize fsck tests

---

tests/suites/hup/suite.js
tests/suites/os/suite.js

Resolves: https://github.com/balena-os/meta-balena/issues/2471
---

Enable UART before flash in HUP and OS suites

---

meta-balena-common/classes/kernel-balena.bbclass

The aufs patches are used by the devices
that transition from aufs to overlay2.
---

classes/kernel-balena: Update aufs patches for kernel 5.10.82

---

README.md

explain balenaRootCA better

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

Includes improvements when writing to `config.json` to reduce the chances of corruption.
---

balena-supervisor: Update balena-supervisor to v12.11.32

---

meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
meta-balena-common/recipes-support/resin-init/resin-init-flasher.bb
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
meta-balena-common/recipes-support/resin-mounts/resin-mounts.bb
meta-balena-common/recipes-support/resin-mounts/resin-mounts/resin-partition-mounter

Update flasher for LUKS encryption

---

tests/suites/os/tests/device-tree/index.js

Upstream kernel added a new fkms overlay for
the Pi4 and CM4 and switched to using it
from overlay-map, however, we were not aware
of this.
Let's add a vcdbg testcase to warn in case the RPi
firmware fails to load any overlay or dtb, and set
gpu_mem to 64 so that vcdbg can run.
Connects-to: https://github.com/balena-os/balena-raspberrypi/pull/792
---
- '*Comment*' if …

suites/os: Add testcase for RPi device-tree

---

meta-balena-common/recipes-support/resin-device-register/resin-device-register/resin-device-register
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher.service

* Fix VPN connection after registration
* Run flashing once registration happens so the reports can be sent to the cloud
---

Improve provisioning

---

tests/suites/cloud/suite.js

Avoid additional wait and API call when we already have the device ID.
This might also resolve a race condition that has been difficult to
track down.
--- …

tests/cloud: Use deviceID returned from pre-registration

---

meta-balena-common/recipes-connectivity/openvpn/openvpn_%.bbappend
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/unit-conf.json

Context https://www.flowdock.com/app/rulemotion/r-resinos/threads/fw7iXa2AYhpyma6ic-P6IOKrYli
---

Make `prepare-openvpn` restart on `apiKey` change

---

tests/suites/os/tests/device-specific-tests/beaglebone-black/index.js

tests/os: fix bracket in bbb overlay test

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor

balena-supervisor: Fix supervisor tagging command

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-common/recipes-core/systemd/systemd/60-resin-update-state.rules
meta-balena-common/recipes-core/systemd/systemd/resin_update_state_probe
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-tpm2
meta-balena-common/recipes-support/resin-init/resin-init-flasher.bb
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
meta-balena-common/recipes-support/resin-mounts/resin-mounts/balena-efi.service

Add PCR protection to LUKS/TPM manipulation

---

tests/suites/os/suite.js
tests/suites/os/tests/modem/index.js
tests/suites/os/tests/modem/modems.json

Signed-off-by: Alex Bucknall <alexbucknall@balena.io>
---

Adds modem test suite

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

Ensure preloaded applications are ran when no internet is available on
first run
Signed-off-by: 20k-ultra <3946250+20k-ultra@users.noreply.github.com>
---

balena-supervisor: Update balena-supervisor to v12.11.38

---

meta-balena-common/classes/image_types_balena.bbclass
meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-core/images/balena-image-initramfs.bb
meta-balena-common/recipes-core/initrdscripts/files/resindataexpander
meta-balena-common/recipes-devtools/gptfdisk/gptfdisk_%.bbappend

---
Add as per https://github.com/balena-os/balena-jetson/pull/272

Add gpt check

---

tests/suites/hup/suite.js

test/hup: fix unmounting error

---

tests/suites/os/tests/modem/README.md
tests/suites/os/tests/modem/index.js
tests/suites/os/tests/modem/modems.json

Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>
---

Updates SIM info for soracom and provides docs.

---

meta-balena-common/recipes-containers/mobynit/mobynit_git.bb

mobynit: Update to v0.2.0

---

.github/renovate.yml
repo.yml

Add renovate configuration

---

tests/suites/cloud/tests/ssh-auth/index.js

Cloud suite / ssh test didn't work on the testbot worker because the ssh keys were not being transferred to the testbot.
---

tests/cloud: fix ssh test for testbot workers

---

tests/suites/os/suite.js
tests/suites/os/tests/swap/index.js

Closes https://github.com/balena-os/meta-balena/issues/2603
---

tests: os: create swap test

---

tests/suites/hup/suite.js
tests/suites/hup/tests/smoke.js

Add "HUP from this release" test to ensure hostapp-update is functional

---

tests/suites/os/tests/connectivity/index.js

No meaningful performance difference here, just a cleanup.
---

os: tests: optimize connectivity tests

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

Update balena-supervisor from 12.11.38 to 13.1.4
---

supervisor: Update balena-supervisor to v13.1.4

---

.github/renovate.json

renovate: Override default package rules to enable leviathan

---

tests/suites/os/tests/connectivity/docker-compose.yml
tests/suites/os/tests/connectivity/index.js

Fixes: https://github.com/balena-os/meta-balena/issues/2612
See: https://github.com/balena-os/meta-balena/issues/2408
---

tests/connectivity: Force proxy tests to use IPv4

---

contributing-device-support.md

contributing-device-support.md: Enhance device contribution guide

---

meta-balena-common/recipes-core/os-config/os-config/os-config.timer
tests/suites/cloud/suite.js
tests/suites/cloud/tests/os-config/index.js

Randomize os-config timer service

---

tests/suites/cloud/tests/os-config/index.js

test: os-config: Use common code to wait for service state

---

contributing-device-support.md

- Fix grammatical issues and improve sentence structure 
- Remove horizontal lines 
- Fixed heading tags and removed some 
Syncing these docs to balenaCloud docs with PR https://github.com/balena-io/docs/pull/2277

patch: Get CDS doc ready for docs sync

---

tests/suites/os/tests/config-json/index.js

Fix config json race

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

Relates-to: https://github.com/balena-os/balena-supervisor/pull/1944
Signed-off-by: Felipe Lalanne <felipe@balena.io>
---

supervisor: Update balena-supervisor to v13.1.11

---

tests/suites/os/tests/udev/index.js

Cleanup udev tests

---

tests/suites/os/suite.js

utils.waitUntil expects rejectionFail before _times and _delay, include
this argument to ensure the later arguments have the intended effect
---

os: waitForServiceState: fix missing rejectionFail

---

contributing-device-support.md

Also cleaned up markdown
Signed-off-by: Ryan Hampton (@rhampt) <rhampt@balena.io>
---

Added all device support options

---

tests/suites/os/tests/chrony/index.js

Reduce chrony timeouts

---

tests/suites/os/tests/chrony/index.js

This reduces the time taken for chrony tests by approximately 20s (total time with changes is appx. 90s)
---

tests: os: chrony: reduce retry interval

---

tests/suites/config.js
tests/suites/os/tests/chrony/index.js
tests/suites/os/tests/config-json/index.js

Resolves: https://github.com/balena-os/meta-balena/issues/2688
Resolves: https://github.com/balena-os/balena-raspberrypi/issues/853
Resolves: https://github.com/balena-os/balena-beaglebone/issues/352
Resolves: https://github.com/balena-os/meta-balena/issues/2680
Resolves: https://github.com/balena-os/balena-beaglebone/issues/334
--- …

Fix race conditions in os-config and chrony tests

---

meta-balena-common/recipes-support/hostapp-update-hooks/files/1-bootfiles
meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb

We may have cases when for some boards we do not want
to have all these files blacklisted. See for example
https://github.com/balena-os/balena-rockpi/commit/b5eadcfb3a296eea2554dc0cbdd16002d51c5169
In conclusion, we rework how the blacklist is constructed
so that users of meta-balena can alter this list as they see fit.
--- …

hostapp-update-hooks: Rework bootfiles blacklist

---

repo.yml

Update backport for current being 2.88.x

---

tests/suites/os/tests/config-json/index.js

Readlink can fail when the path is non-existent, raising an error and
making the udevRules test fail. Test that the link exists before
attempting to use readlink.
--- …

tests: os: config-json: fix race in udevRules test

---

meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/os-config-json

On occassions, this fails with a broken pipe error.
---

balena-config-vars: Do not use systemctl to list unit files

---

tests/suites/cloud/tests/ssh-auth/index.js

This test was broken previously, and would fail with "All configured
authentication methods failed" after a long delay caused by excessive
retries.
Optionally depends on: https://github.com/balena-os/leviathan/pull/805 (speeds up testing)
Fixes: #2719
--- …

tests: cloud: fix production mode ssh test

---

tests/suites/hup/suite.js
tests/suites/hup/tests/rollback-altboot.js
tests/suites/hup/tests/rollback-health.js
tests/suites/hup/tests/smoke.js

Resolves: https://github.com/balena-os/balena-beaglebone/issues/336
---

tests: hup: Clear inactive storage partition before HUP

---

tests/suites/os/suite.js
tests/suites/os/tests/chrony/index.js
tests/suites/os/tests/config-json/index.js

Resolves: https://github.com/balena-os/meta-balena/issues/2742
Resolves: https://github.com/balena-os/meta-balena/issues/2738
---

tests: os: Use helpers for chrony and config.json tests

---

.github/renovate.json

renovate: Fix nested changelogs and change-type for SV updates

---

.github/renovate.json

Renovate: Fix package rules for balena supervisor

---

.gitignore
tests/suites/cloud/package-lock.json
tests/suites/hup/package-lock.json
tests/suites/os/package-lock.json
tests/suites/package.json

patch: Add package-lock.json files for tests

---

tests/suites/os/tests/boot-splash/index.js

tests: os: only do hdmi test if testbot has capture device

---

contributing-device-support.md

contributing-device-support.md: Clarify repo set-up in balenaOS org

---

meta-balena-rust/recipes-devtools/rust/rust-common.inc

meta-balena-rust: Fix ABI for arm

---

meta-balena-common/classes/kernel-balena.bbclass

The task that applies the aufs patches is still required to support hostOS updates between aufs and overlay2 balenaOS versions.
This commit adds support for 5.15 kernels and improves the branch selection logic to cover some corner cases.
It also adds a test task so that we can test regressions.
--- …

classes: kernel-balena: improve aufs branch selection

---

contributing-device-support.md

Updated the link in the docs to the device-type listings (on hub as SOT)
Signed-off-by: Ryan Hampton (@rhampt) <rhampt@balena.io>
---

Update Docs Link

---

tests/suites/hup/suite.js
tests/suites/hup/tests/rollbacks.js

Disclaimer: I dislike how this turned out. 
Problem: issue #2816
Solution:
1. Check for available HostOS releases for deviceType
2. If found, then continue as usual
3. If not found, then skip all test suites in the HUP suite and end the test with a PASS
We do that by adding all the following suites into the unstable tests debug object: https://balena-os.github.io/leviathan/pages/Getting-Started/debugging.html
Problems
1. The only way to skip tests with a PASS in levaithan is to mark tests as unstable during runtime. A escape hatch I built for only development usecases to run test suites with unstable tests.
2. Tests suites can't be dynamically picked and I had to hard code names for test suites (check out my comments in suite.js at the end of the file) This will break if someone changes …

Skip HUP suite if no balenaOS releases found

---

tests/suites/os/tests/udev/index.js

These links are required for HUP, ensure they're created by udev
---

tests: os: ensure by-state links are created

---

.github/workflows/meta-balena-esr.yml

This workflow will create an ESR branch when a minor or major version is tagged.
The ESR branch will start on the latest patch of the latest minor version before the tag event.
--- …

Add meta-balena-esr workflow

---

docs/raid.md

docs: add RAID setup info

---

tests/suites/cloud/suite.js
tests/suites/cloud/tests/ssh-auth/index.js

Fix ssh-auth tests for testbot/non-direct connection devices

---

meta-balena-common/recipes-bsp/grub/grub-conf/grub.cfg_internal_luks_template
meta-balena-common/recipes-core/balena-rollback/files/rollback-clear-bootcount
meta-balena-common/recipes-core/balena-rollback/files/rollback-parse-bootloader
meta-balena-common/recipes-core/balena-rollback/files/rollback-stop
meta-balena-common/recipes-support/hostapp-update-hooks/files/1-bootfiles
meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

HUP support for LUKS encrypted partitions

---

tests/README.md
tests/suites/cloud/README.md
tests/suites/hup/README.md
tests/suites/os/README.md

add os testing docs

---

tests/suites/os/tests/purge-data/index.js

Clean up some duplicated code and avoid test comments that to not write to logs when called but instead await the next test command.
Also change the supervisor ping test to run on the DUT, rather than the core container since we are only checking for supervisor liveness and don't want to be thrown off by networking or firewall issues.
Resolves: https://github.com/balena-os/meta-balena/issues/2891
--- …

Refactor and clean up the purge data tests

---

tests/suites/cloud/tests/device-specific-tests/hostapd/index.js
tests/suites/cloud/tests/multicontainer/index.js
tests/suites/cloud/tests/supervisor/index.js

Also reduce the interval to 1s.
---

tests/cloud: Increase the wait time for services to start

---

meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher.service

Improve debugging experience of flasher service by outputting logs to serial console.
---

flasher: output logs to serial console

---

tests/suites/hup/tests/smoke.js

This has since been fixed in the engine but since it impacts the HUP from version we need to handle it in the test suite.
Resolves: https://github.com/balena-os/balena-raspberrypi/issues/929
--- …

tests/hup: Avoid an old engine bug when pulling multiarch images on rpi

---

tests/suites/os/tests/chrony/index.js

The previous method of disabling NTP by stopping the nameserver (dnsmasq) relied on the dnsmasq unit not being reactivated before the test completed.
Instead, disable NTP by blocking ntp.org in the local dnsmasq instance using a dbus method call. NTP is re-enabled as before, by restarting dnsmasq.
---
- '*Comment*' if you don't feel you have enough information to decide either …

tests: os: chrony: disable NTP w/ dnsmasq dbus API

---

.github/workflows/meta-balena-esr.yml

Correct the calculation of the version to include in the yml file.
---

workflows: meta-balena-esr: Fix version calculation

---

.github/workflows/meta-balena-esr.yml

workflows: esr: use semver compatible versions

---

meta-balena-common/classes/sign-efi.bbclass
meta-balena-common/classes/sign-gpg.bbclass
meta-balena-common/classes/sign-kmod.bbclass
meta-balena-common/recipes-support/balena-keys/balena-keys.bb

Re-sign artifacts if keys change

---

tests/suites/os/suite.js
tests/suites/os/tests/secureboot/index.js

Check for secureboot and full-disk encryption, and logs the results.
---

tests: os: add basic SB/FDE tests

---

balena-docs/README.md

Update balenaOS docs title
Resolves: #2979
[skip ci]
---

patch: Update balenaOS docs title

---

meta-balena-common/recipes-bsp/efitools/efitools_git.bb

There are ARM systems that use UEFI, and for example the `efivar` package can also be built for ARM architectures.
---

efitools: Allow builds for ARM architecture

---

tests/suites/os/tests/config-json/index.js

tests: os: skip persistent logging test for pi0

---

.github/renovate.json
meta-balena-common/recipes-containers/balena/balena_git.bb

renovate: Add regex manager for balena-engine

---

tests/suites/os/tests/connectivity/Dockerfile.rpi
tests/suites/os/tests/connectivity/Dockerfile.template

tests: os: fix tests that use glider on rpi0

---

meta-balena-common/recipes-bsp/efitools/efitools.inc
meta-balena-common/recipes-bsp/efitools/efitools/0001-console-Fix-a-typo-in-the-EFI-warning-list-in-gnu-ef.patch
meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb
meta-balena-common/recipes-support/resin-init/resin-init-flasher.bb

Only include EFI tools if the machine feature is defined

---

docs/initramfs.md
meta-balena-common/recipes-core/initrdscripts/files/prepare
meta-balena-common/recipes-core/initrdscripts/files/resindataexpander
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-config
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-logging
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-time
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-tpm2
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
tests/suites/os/tests/os-release/index.js
tests/suites/os/tests/swap/index.js
tests/suites/os/tests/variables/index.js

Installer - general changes

---

.github/workflows/update-backports.yml

This workflow will update the backports entry in repo.yml after a new ESR release is created.
---

workflows: add update-backports

---

.github/workflows/update-backports.yml

Use the correct syntax for no ci.
[no ci]
---

workflows: update-backports: remove skipping tests

---

tests/suites/hup/suite.js

tests: hup: fix flashing for tx2

---

tests/suites/os/tests/secureboot/index.js

Secure boot is now opt-in, even in the case where the image is signed, and it's supported in firmware. Skip the secure boot tests when it's not enabled at runtime.
--- …

tests: os: secureboot: skip if system is not locked down

---

meta-balena-common/recipes-core/images/balena-image.bb

... before trying to include them in the boot partition, otherwise the yocto build may fail sporadically.
---

recipes-core/images: Ensure redsocks sample files are deployed

---

meta-balena-common/conf/distro/include/balena-os.inc

conf: distro: balena-os: use lower case for signing key names

---

docs/debugging-balenaos.md

Moving balenaOS debugging docs from masterclass to meta-balena 
[skip ci]
---

patch: Add balenaOS debugging docs

---

meta-balena-common/recipes-kernel/peak/peak_8.12.0.bb

peak: Ship signed module when signing is enabled

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.bb
meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-api

Add os-helpers-api

---

balena-docs/supported-boards.md
contributing-device-support.md

Removed links to hub

---

tests/suites/cloud/suite.js
tests/suites/hup/suite.js
tests/suites/os/suite.js
tests/suites/os/tests/secureboot/index.js

Requires: https://github.com/balena-os/leviathan/pull/972
---

Secureboot integrity tests

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.bb
meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-api

Backport API helper into 2.107 ESR branch

---

meta-balena-common/classes/kernel-balena.bbclass

As per internal discussion thread
https://balena.zulipchat.com/#narrow/stream/345882-_help/topic/.E2.9C.94.20nfs.20.283.20or.204.29.20on.20jetson.20nano/near/342072698
---

kernel-balena: Include NFS V2, V3 and V4 client and server modules

---

README.md

README: modify migration documentation to match module

---

meta-balena-common/recipes-bsp/grub/grub-efi_%.bbappend
meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Ship separate GRUB images for secure boot

---

tests/suites/config.js
tests/suites/os/suite.js
tests/suites/os/tests/migrate/index.js

Relates-to: https://github.com/balena-os/leviathan-worker/pull/60
---

test: installer's migration

---

meta-balena-common/classes/kernel-balena.bbclass
meta-balena-common/classes/sign-efi.bbclass
meta-balena-common/classes/sign-gpg.bbclass
meta-balena-common/classes/sign-kmod.bbclass
meta-balena-common/recipes-support/balena-keys/balena-db-hashes.bb
meta-balena-common/recipes-support/balena-keys/balena-keys.bb

Resign kernel and modules if keys change

---

tests/suites/cloud/suite.js
tests/suites/hup/suite.js
tests/suites/os/suite.js

Improves developer experience when reviewing test logs and helps in figuring which user has been used while testing.
---

patch: Add additional logs when logging in using balenaSDK

---

tests/suites/cloud/suite.js
tests/suites/config.js
tests/suites/hup/suite.js
tests/suites/os/suite.js

test: fix clashes between secure boot and migration configuration

---

contributing-device-support.md

Updated CDS link to the balena.io subdomain one
Signed-off-by: Ryan Hampton (@rhampt) <rhampt@balena.io>
---

Updated the CDS link

---

meta-balena-common/recipes-core/initrdscripts/files/recovery
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
tests/suites/cloud/suite.js
tests/suites/config.js
tests/suites/hup/suite.js
tests/suites/os/suite.js
tests/suites/os/tests/migrate/index.js

Depends on https://github.com/balena-os/leviathan/pull/993
---

Miscellaneous SB fixes

---

tests/suites/cloud/suite.js
tests/suites/hup/suite.js
tests/suites/os/suite.js

allows for the tests to use `resin_flasher_skip=0` (https://github.com/balena-os/meta-balena/pull/2953) to make the DUT skip boot-switch selection. Simplifies flashing for devices that have these switches
---

enable skipping boot switch

---

README.md

with informaton on how u-boot, grub, cboot and
UEFI L4TLauncher are used in balenaOS.
---

README: Add bootloader section

---

meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-api

This is used to test the os-helpers-api package.
---

os-helpers: Add curl as a native dependency

---

meta-balena-kirkstone/recipes-kernel/linux/kernel-devsrc.bbappend

Fix kernel headers for 6.1+ kernels in kirkstone

---

.github/workflows/meta-balena-esr.yml
.github/workflows/update-backports.yml

Replace GitHub PAT with ephemeral app tokens 

---

tests/suites/cloud/suite.js
tests/suites/cloud/tests/os-config/index.js
tests/suites/cloud/tests/preload/index.js
tests/suites/cloud/tests/supervisor/index.js
tests/suites/config.js
tests/suites/hup/suite.js
tests/suites/os/suite.js

Changes to test suite to enable the use of another balena environment (e.g staging or a balena machine instance)
Depends on https://github.com/balena-os/leviathan/pull/1011 and https://github.com/balena-os/leviathan/pull/1008
--- …

tests: allow for configurable BC env

---

meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_20210511.bb
meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_20230404.bb
meta-balena-dunfell/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
meta-balena-honister/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
meta-balena-kirkstone/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
meta-balena-thud/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
meta-balena-warrior/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
meta-resin-pyro/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
meta-resin-rocko/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
meta-resin-sumo/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend

linux-firmware-20230404

---

meta-balena-common/recipes-connectivity/balena-net-config/balena-net-config/balena-net-config
meta-balena-common/recipes-connectivity/balena-net-config/balena-net-config/balena-net-config.service
meta-balena-common/recipes-connectivity/networkmanager/networkmanager_1.40.4.bbappend
meta-balena-common/recipes-support/resin-init/resin-init-flasher.bb
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
meta-balena-common/recipes-support/resin-mounts/resin-mounts-flasher.bb
meta-balena-common/recipes-support/resin-mounts/resin-mounts.inc

Support for dispatch user scripts for NetworkManager

---

tests/suites/hup/suite.js

We have no retries in place when sending the hostapp to the DUT in the HUP suite. We are using `rsync` to do so, and if something flakes then the suite fails. Added a simple retry mechanism as this is a pretty common failure point for tests.
This is a bandaid. Ideally I thought that perhaps we can get the DUT to pull the hostapp image but currently its not being hosted anywhere except on jenkins. Perhaps we could do something funky like in the test setup, create a block/app and push the hostapp (`balena.docker`) to it so its in a registry - then just pull from that registry URL with `hostapp-update`, mocking what we do with hostapp releases in production if I understand it correctly. What do you guys think of that idea @klutchell @alexgg @vipulgupta2048 
---
- When …

tests: hup: retry sending image if fails

---

meta-balena-thud/conf/distro/include/balena-os-yocto-version.inc
meta-balena-thud/conf/layer.conf
meta-balena-thud/recipes-connectivity/libmbim/libmbim_1.24.2.bb
meta-balena-thud/recipes-connectivity/libqmi/libqmi_1.26.0.bb
meta-balena-thud/recipes-connectivity/modemmanager/modemmanager_1.14.2.bb

meta-balena-thud: hold libqmi and libmbim

---

tests/suites/cloud/tests/supervisor/index.js

Change the test order to make things more consistent.
---

tests: cloud: lockfile: change test order

---

.github/renovate.json

renovate updates patch only

---

meta-balena-common/recipes-core/balena-rollback/files/rollback-altboot
meta-balena-common/recipes-core/balena-rollback/files/rollback-health
meta-balena-common/recipes-core/balena-rollback/files/rollback-parse-bootloader
meta-balena-common/recipes-core/balena-rollback/files/rollback-stop
meta-balena-common/recipes-core/images/balena-image-bootloader-initramfs.bb
meta-balena-common/recipes-core/initrdscripts/files/abroot
meta-balena-common/recipes-core/initrdscripts/files/kexec
meta-balena-common/recipes-core/initrdscripts/files/rootfs
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-common/recipes-core/initrdscripts/initramfs-module-abroot_1.0.bb
meta-balena-common/recipes-support/hostapp-update-hooks/files/99-balena-bootloader
meta-balena-common/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bb

Add common bits for balena second stage bootloader

---

.github/workflows/meta-balena-esr.yml

flowzone: meta-balena-esr: add weekly run to keep workflow enabled

---

tests/suites/os/tests/engine-healthcheck/index.js

This is required for the RPI0 automation tests to pass.
---

tests: os: retry healthcheck disable

---

meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
meta-balena-common/recipes-containers/hostapp-update/hostapp-update.bb
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-logging
meta-balena-common/recipes-support/os-helpers/os-helpers/safe_reboot
tests/suites/os/suite.js
tests/suites/os/tests/safe-reboot/index.js

Add safe reboot script

---

meta-balena-common/recipes-core/initrdscripts/files/cryptsetup
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-common/recipes-support/os-helpers/os-helpers.bb
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-secureboot
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Check for user mode in cryptsetup hook

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor
meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor/update-balena-supervisor.service
meta-balena-common/recipes-containers/hostapp-update/files/hostapp-update
meta-balena-common/recipes-support/hostapp-update-hooks/files/1-bootfiles
meta-balena-common/recipes-support/hostapp-update-hooks/files/70-sshd_migrate_keys
meta-balena-common/recipes-support/hostapp-update-hooks/files/75-supervisor-db/75-forward_supervisor-db
meta-balena-common/recipes-support/hostapp-update-hooks/files/75-supervisor-db/75-fwd_commit_supervisor-db
meta-balena-common/recipes-support/hostapp-update-hooks/files/76-supervisor-db/76-forward_supervisor-db
meta-balena-common/recipes-support/hostapp-update-hooks/files/76-supervisor-db/76-fwd_commit_supervisor-db
meta-balena-common/recipes-support/hostapp-update-hooks/files/80-rollback
meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-uboot
meta-balena-common/recipes-support/hostapp-update-hooks/files/hostapp-update-hooks
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-logging

Surface hup logs to journal

---

meta-balena-common/recipes-core/os-config/os-config/os-config.service

Start extract-balena-ca before os-config update

---

meta-balena-common/classes/kernel-balena.bbclass

This helps debugging watchdog related issues.
Changelog-entry: expose watchdog details in sysfs
---

expose watchdog in sysfs

---

tests/suites/config.js

tests: allow for multiple worker fleets

---

tests/suites/cloud/suite.js

As part of the cloud suite we disable DUT internet access by disabling ipv4 port forwarding on the worker. We were disabling it before provisioning the DUT. This caused problems on the jetson orin devices, where we may have to build a jetson-flash docker container during provision time - the build container would have no internet access and fail to build.
So I moved it to after the DUT is provisioned, but just before we power it on. I also added to the teardowns to re-enable it - in case we end up with a test failure in between disabling and re-enabling it - as this would cause it to be disabled for subsequent tests, and the DUT would not have internet access.
In a separate leviathan worker PR - I have integrated enabling port forwarding in the network set up, to avoid accidents like this …

tests: cloud: disable dut internet after flashing

---

tests/suites/hup/tests/rollbacks.js

Wait for fallback services to complete before testing breadcrumbs

---

meta-balena-common/classes/kernel-balena.bbclass

Fix kernel configuration checks warnings

---

contributing-device-support.md

Info on the ascii art for consoles was missing, so we add that in this PR.
---

Update contributing-device-support with balena-info documentation

---

meta-balena-common/classes/sign-rsa.bbclass

Change-type: Add RSA signing class
---

classes: sign-rsa: add class for RSA artifact signing

---

tests/suites/os/tests/internet-sharing/index.js

For some device types it's been noted that it takes longer than the time it takes do do one check of the iptables rules for the intended rules to appear, leading to a failure. This aims to make the check more consistent by checking 5 times before failing.
--- …

tests: os: address race in internet con. sharing tests

---

contributing-device-support.md

docs: Elaborate automated testing requirement in board support guide

---

meta-balena-common/recipes-kernel/peak/peak_8.17.0.bb

This is needed to have it compiled against kernel version 6.6.23, which we will include in balena-generic.
---

peak: Update to version 8.17.0

---

tests/suites/os/tests/safe-reboot/index.js

tests: os: safe-reboot: fetch and modify local/target-state instead of pushing new one

---

.github/workflows/meta-balena-esr.yml
.github/workflows/update-backports.yml

workflows: fix linter errors

---

.github/workflows/meta-balena-esr.yml
.github/workflows/update-backports.yml

2024.7: workflows: fix linter errors

---

meta-balena-kirkstone/recipes-connectivity/openssh/files/CVE-2024-6387.patch
meta-balena-kirkstone/recipes-connectivity/openssh/openssh_%.bbappend

2024.4: openssh: CVE-2024-6387

---

meta-balena-kirkstone/recipes-connectivity/openssh/files/CVE-2024-6387.patch
meta-balena-kirkstone/recipes-connectivity/openssh/openssh_%.bbappend

2024.7: openssh: CVE-2024-6387

---

meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

Update balena-supervisor from 16.1.10 to 16.4.1
---

Update balena-supervisor to v16.4.1

---

meta-balena-common/recipes-connectivity/networkmanager/balena-files/90shared
meta-balena-common/recipes-containers/balena-supervisor/balena-supervisor.inc

[5.2.x][2024.7] Update SV to 16.4.1 and update NM rules to remove duplicates

---

tests/suites/cloud/config.js
tests/suites/hup/config.js
tests/suites/os/config.js

See: https://github.com/balena-os/meta-balena/pull/3117
---

tests: config: restore both network options to false

---

meta-balena-common/recipes-containers/mkfs-hostapp-native/files/Dockerfile
meta-balena-rust/recipes-devtools/rust/rust-llvm.inc
meta-balena-rust/recipes-devtools/rust/rust-llvm/0003-Support-Add-missing-cstdint-header-to-Signals.h.patch

Fix builds for host distributions that use glibc-2.39 and gcc 13 - like Ubuntu 24.04

---

meta-balena-common/recipes-kernel/linux/files/Dockerfile

kernel-headers-test: update dockerfile to bullseye

---

tests/suites/cloud/suite.js

Using to check if this works for now so draft (not reproducible locally)
---

tests: cloud: prevent hanging in cloud suite teardown

---

.github/workflows/meta-balena-esr.yml

workflows/meta-balena-esr: fix version creation bash

---

meta-balena-common/classes/kernel-balena.bbclass
meta-balena-common/conf/distro/include/balena-os.inc
meta-balena-common/recipes-bsp/efitools/efitools.inc
meta-balena-common/recipes-core/balena-rollback/files/rollback-parse-bootloader
meta-balena-common/recipes-core/initrdscripts/files/resindataexpander
meta-balena-common/recipes-core/systemd/systemd/resin_update_state_probe
meta-balena-common/recipes-core/systemd/systemd_%.bbappend
meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-grub
meta-balena-common/recipes-support/hostapp-update-hooks/files/99-resin-uboot
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-fs
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher
meta-balena-common/recipes-support/resin-mounts/resin-mounts.bb
meta-balena-common/recipes-support/resin-mounts/resin-mounts/balena-nonencboot.service

Add support for dm-crypt encrypted partitions

---

meta-balena-common/recipes-kernel/linux-firmware/linux-firmware_%.bbappend

This was requested for the AGX Orin 64GB devkit image, and will be included from the device repository.
---

recipes-kernel/linux-firmware: Package Intel AX210 firmware

---

meta-balena-common/classes/kernel-balena.bbclass
meta-balena-common/recipes-core/images/balena-image-initramfs.bb
meta-balena-common/recipes-core/initrdscripts/files/zram
meta-balena-common/recipes-core/initrdscripts/initramfs-framework_%.bbappend
meta-balena-common/recipes-support/resin-init/resin-init-flasher/resin-init-flasher

Mount /tmp as zram in initramfs

---

meta-balena-common/recipes-kernel/peak/peak_8.19.0.bb

This is needed to have it compiled against kernel version 6.12.3, which we will include in balena-generic.
---

peak: Update to version 8.19.0

---

meta-balena-common/recipes-core/initrdscripts/files/migrate
meta-balena-common/recipes-support/resin-init/resin-init-flasher.bb

Fix image authentication in migration path

---

meta-balena-common/recipes-support/resin-mounts/resin-mounts.bb

Only mount enc partition when disk is available

---

meta-balena-common/classes/kernel-balena.bbclass

kernel-balena.bbclass: Add aufs patches for 6.12 kernels

---

meta-balena-common/classes/kernel-balena.bbclass
tests/suites/os/tests/device-tree/getValue.sh
tests/suites/os/tests/device-tree/index.js

Rework dtoverlay test

---

tests/suites/os/tests/secureboot/index.js

Fix imx tests for i.MX8MP

---

meta-balena-common/recipes-bsp/efitools/efitools.inc
meta-balena-common/recipes-bsp/efitools/efitools/0001-hash-to-efi-sig-list.c-Allow-raw-hashes-as-arguments.patch
meta-balena-common/recipes-bsp/efitools/efitools_git.bb
meta-balena-common/recipes-support/hostapp-update-hooks/files/0-signed-update
meta-balena-common/recipes-support/hostapp-update-hooks/files/95-secureboot/2-fwd_commit_update-policy
meta-balena-common/recipes-support/os-helpers/os-helpers/os-helpers-tpm2
meta-balena-common/recipes-support/resin-init/resin-init-flasher/balena-init-flasher-efi
meta-balena-common/recipes-support/resin-init/resin-init-flasher/balena-init-flasher-tpm

Support devices using 3rd party UEFI drivers

---

meta-balena-common/classes/kernel-balena.bbclass

We will continue to update to the stable head of v6.6 until v6.12 is officially deployed.
---

kernel-balena: add aufs commit for v6.6.84

---

.github/workflows/generic-aarch64.yml
.github/workflows/generic-amd64.yml

This includes adding secure boot tests to the generic-amd64 test matrix.
See: https://balena.fibery.io/Work/Project/Add-workflow_call-trigger-to-device-repo-workflows-for-meta-balena-1057
See: https://balena.fibery.io/Work/Project/Add-secureboot-tests-to-meta-balena-1261
Depends-on: https://github.com/balena-os/balena-generic/pull/589
Depends-on: https://github.com/balena-os/.github/pull/549
--- …

Use workflow_call for balena-generic device type tests

---

tests/suites/cloud/package-lock.json
tests/suites/cloud/package.json
tests/suites/cloud/suite.js
tests/suites/hup/package-lock.json
tests/suites/hup/package.json
tests/suites/hup/suite.js
tests/suites/os/package-lock.json
tests/suites/os/package.json
tests/suites/os/suite.js

requires https://github.com/balena-os/leviathan/pull/1288
Currently being tested with all suites (pi 0 2w DT):
OS: passed
Cloud: passed
HUP: passed
---

tests: update for node 22

---

.github/workflows/meta-balena-esr.yml

If an esr branch for a previous minor already exists, then fall back to the current minor
---

meta-balena-esr: fall back to current minor

---

meta-balena-common/recipes-connectivity/libnss-ato/libnss-ato/libnss-ato.conf
meta-balena-common/recipes-connectivity/libnss-ato/libnss-ato_git.bb
meta-balena-common/recipes-connectivity/openssh/balena-files/ssh_keys_merger
meta-balena-common/recipes-connectivity/openssh/openssh_%.bbappend
meta-balena-common/recipes-containers/balena/balena/balena.service
meta-balena-common/recipes-containers/balena/balena_git.bb
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars.bb
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/os-sshkeys
meta-balena-common/recipes-support/balena-config-vars/balena-config-vars/os-sshkeys.service
meta-balena-common/recipes-support/balena-unique-key/balena-unique-key.bb
meta-balena-common/recipes-support/balena-unique-key/balena-unique-key/balena-device-uuid.service
meta-balena-common/recipes-support/resin-mounts/resin-mounts-flasher.bb
meta-balena-common/recipes-support/resin-mounts/resin-mounts.bb
meta-balena-common/recipes-support/resin-mounts/resin-mounts.inc

Do not hardcode root home
